engine/src/main/java/org/camunda/bpm/engine/ProcessEngineConfiguration.java
Based on Romans explanation in
https://groups.google.com/forum/#!topic/camunda-bpm-users/6P0NzH0rDg8,
let's extend the java-doc wherever possible.
=> add java-doc for hintJobExecutor

examples/invoice/src/main/java/org/camunda/bpm/example/invoice/DemoDataGenerator.java
Now you can add your own filters and put them in between the existing
=> realistic filter priorities

engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.history.sql
=> fix(db/scripts): remove column DATA_FORMAT_ID_ from oracle sql create scripts

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TimerEntity.java
repeat was printed as repeatPT10S instead of repeat=PT10S
=> add missing '=' to toString()

parent/pom.xml
=> Update WildFly used for wildfly distro from 8.2.0 to 8.2.1.

.gitignore, engine/src/main/java/org/camunda/bpm/application/AbstractProcessApplication.java, engine/src/main/java/org/camunda/bpm/application/ProcessApplication.java, engine/src/main/java/org/camunda/bpm/container/impl/RuntimeContainerDelegateImpl.java, engine/src/main/java/org/camunda/bpm/container/impl/deployment/ParseProcessesXmlStep.java, engine/src/main/java/org/camunda/bpm/container/impl/spi/DeploymentOperation.java
see https://app.camunda.com/jira/browse/CAM-6937
I need to change deploymentSteps for spring boot. Having the steps in extra methods makes it easier to overwrite the steps without changing the implementation
=> Cam 6937 plugable deployment steps

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/CompositeProcessEnginePlugin.java, engine/src/test/java/org/camunda/bpm/engine/impl/cfg/CompositeProcessEnginePluginTest.java
see https://app.camunda.com/jira/browse/CAM-6957
allows collecting plugins in a composite before adding it to the engine configuration
=> CAM-6957 composite engine plugin

engine/src/main/java/org/camunda/bpm/engine/impl/form/type/DateFormType.java
fixes https://app.camunda.com/jira/browse/CAM-5903
=> [CAM-5903] form field with type "date" should return null for empty inputs

examples/invoice/README.md
Added `clean` in mvn command for invoice example to avoid `ProcessEngineException` per discussion in [CAM-7864](https://app.camunda.com/jira/browse/CAM-7864).
=> [CAM-7864] add clean in mvn command for invoice example.

engine-spring/src/main/java/org/camunda/bpm/engine/spring/application/SpringProcessApplication.java, engine-spring/src/test/java/org/camunda/bpm/engine/spring/test/application/PostDeployWithNestedContext.java, engine-spring/src/test/java/org/camunda/bpm/engine/spring/test/application/SpringProcessApplicationTest.java, engine-spring/src/test/resources/org/camunda/bpm/engine/spring/test/application/PostDeployWithNestedContext-context.xml
=> fix(spring): add child context check for trigger auto-deploy

engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandInvocationContext.java, engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/LegacyBehavior.java
* drop dead code
* correct javadoc
=> Style fixes

qa/integration-tests-webapps/src/test/java/org/camunda/bpm/CsrfPreventionIT.java
https://app.camunda.com/jira/browse/CAM-10467
related to CAM-10467
=> [CAM-10467] add csrf prevention integration test

NOTICE, bom/pom.xml, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/aop/ActivitiStateAnnotationBeanPostProcessor.java, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/aop/ProcessStartAnnotationBeanPostProcessor.java, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/aop/ProcessStartingMethodInterceptor.java, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/aop/ProcessStartingPointcutAdvisor.java, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/aop/util/MetaAnnotationMatchingPointcut.java, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/aop/util/MetaAnnotationMethodMatcher.java, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/aop/util/Scopifier.java, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/config/xml/ActivitiAnnotationDrivenBeanDefinitionParser.java, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/config/xml/ActivitiNamespaceHandler.java, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/config/xml/StateHandlerAnnotationBeanFactoryPostProcessor.java, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/jobexecutor/SpringJobExecutor.java, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/registry/ActivitiStateHandlerRegistration.java, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/registry/ActivitiStateHandlerRegistry.java, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/scope/ProcessScope.java, engine/src/main/java/org/camunda/bpm/engine/impl/digest/_apacheCommonsCodec/Base64.java, engine/src/main/java/org/camunda/bpm/engine/impl/digest/_apacheCommonsCodec/StringUtils.java, pom.xml, qa/test-db-instance-migration/test-fixture-73/src/main/resources/org/camunda/bpm/qa/upgrade/alldb_engine_delete_global_auth.sql, qa/test-db-upgrade/clear.authorization.table.sql, qa/test-old-engine/clear.authorization.table.sql
* update to release parent 3.4
* revert apache commons code license headers
* mention Apache fondation in NOTICE file due to above
* fix spring license headers
* add licens header to test related sql scripts
Related to CAM-10473
=> fix(license-check): adjust wrong header licenses

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstanceQuery.java, engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/ProcessInstanceQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/runtime/ProcessInstanceQuery.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Execution.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceQueryTest.java, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java
related to [CAM-10309](https://app.camunda.com/jira/browse/CAM-10309)
=> Add #processDefinitionKeyIn() and #processDefinitionKeyNotIn() in HistoricProcessInstanceQuery and ProcessInstanceQuery

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDetail.xml, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricDetailQueryTest.java
related to [CAM-10343](https://app.camunda.com/jira/browse/CAM-10343)
=> Add missing "and" operator in historic detail query

engine/src/main/java/org/camunda/bpm/engine/delegate/DelegateTask.java, engine/src/test/java/org/camunda/bpm/engine/test/api/task/DelegateTaskTest.java
related to [CAM-3862](https://app.camunda.com/jira/browse/CAM-3862)
=> Expose DelegateTask#getFollowUpDate() and DelegateTask#setFollowUpDate()

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml
Related to [CAM-9837](https://app.camunda.com/jira/browse/CAM-9837)
=> [CAM-9837] remove inner select * from job acquisition query

engine/pom.xml
- this enables us to override the value via command line
related to CAM-10568
=> CAM-10568: configure test fork count via property

bom/pom.xml, pom.xml
Related to [CAM-10528](https://app.camunda.com/jira/browse/CAM-10528)
=> CAM-10528: switch to camunda-bpm-release-parent

distro/wildfly/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/util/FixedObjectTypeAttributeDefinition.java, distro/wildfly8/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/util/FixedObjectTypeAttributeDefinition.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ConfigurationLogger.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
=> [CAM-9897] log messages instead of stack traces

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/behavior/ErrorEndEventActivityBehavior.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/Error.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/error/ErrorEndEventTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/error/ErrorEndEventTest.testError.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/error/ErrorEndEventTest.testErrorMessage.bpmn20.xml
Introduce errorMessages on error definitions in bpmn xml files
=> [CAM-9994] Add support for error messages on BPMN Error events

engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/DefaultDmnEngineConfiguration.java, engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/evaluation/ExpressionEvaluationHandler.java, engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/transform/DmnExpressionTransformHelper.java, engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/api/EvaluateDecisionTest.java, engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/api/ParseDecisionTest.java, engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/el/FeelIntegrationTest.java, engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/api/dmn12/NoInput.dmn, engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/el/dmn12/FeelIntegrationTest.dmn, engine/src/test/java/org/camunda/bpm/engine/test/dmn/businessruletask/DmnBusinessRuleTaskTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/dmn/businessruletask/dmn12/DmnBusinessRuleTaskTest.testDecisionOkay.dmn
- with feature set restricted to what is already implemented, i.e. no new DMN 1.2 features
=> CAM-10587: Deploy and evaluate decisions in dmn 12 namespace

examples/invoice/pom.xml, qa/integration-tests-webapps/pom.xml, qa/integration-tests-webapps/src/test/java/org/camunda/bpm/AbstractWebIntegrationTest.java, qa/integration-tests-webapps/src/test/java/org/camunda/bpm/AbstractWebappUiIntegrationTest.java, qa/integration-tests-webapps/src/test/java/org/camunda/bpm/CsrfPreventionIT.java, qa/integration-tests-webapps/src/test/java/org/camunda/bpm/HttpHeaderSecurityIT.java, qa/integration-tests-webapps/src/test/java/org/camunda/bpm/SessionCookieSecurityIT.java, qa/integration-tests-webapps/src/test/java/org/camunda/bpm/cockpit/DashboardIT.java, qa/integration-tests-webapps/src/test/java/org/camunda/bpm/rest/RestIT.java, qa/integration-tests-webapps/src/test/java/org/camunda/bpm/rest/RestJaxRs2IT.java, qa/integration-tests-webapps/src/test/java/org/camunda/bpm/tasklist/TasklistIT.java, qa/integration-tests-webapps/src/test/resources/testconfig.properties
* this allows to change the context path dynamically in other projects
* a classes artifact of the invoice example needs to be build
related to [CAM-10605](https://app.camunda.com/jira/browse/CAM-10605)
=> [CAM-10605] context path can be changed via properties file

distro/jbossas7/webapp/src/main/webapp/WEB-INF/web.xml, distro/tomcat/webapp/src/main/webapp/WEB-INF/web.xml, qa/integration-tests-webapps/src/test/java/org/camunda/bpm/ErrorPageIT.java
* add error page to web.xml of ce distros
* add an integration test
Related to [CAM-10557](https://app.camunda.com/jira/browse/CAM-10557)
=> CAM-10557: add error page to web xml of ce distros

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/behavior/ErrorEndEventActivityBehavior.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/Error.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/error/ErrorEndEventTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/error/ErrorEndEventTest.testErrorMessageExpression.bpmn20.xml
=> [CAM-10573] Add support for expressions in BPMN error messages

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/optimize/OptimizeHistoricVariableUpdateQueryCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java, engine/src/main/java/org/camunda/bpm/engine/impl/optimize/OptimizeManager.java, engine/src/main/java/org/camunda/bpm/engine/impl/util/CollectionUtil.java, engine/src/test/java/org/camunda/bpm/engine/test/api/optimize/GetHistoricVariableUpdatesForOptimizeTest.java
related to https://app.camunda.com/jira/browse/CAM-10513
=> CAM-10513: optimize variable fetching with large numbers

engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AcquirableJobEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobEntity.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsByDueDateNotPriorityTest.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsByPriorityTest.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsByTypeTest.java
[CAM-10557](https://app.camunda.com/jira/browse/CAM-10557)
=> CAM-9838: job acquisition query

engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/task/TaskQuery.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java
Related to [CAM-10624](https://app.camunda.com/jira/browse/CAM-10624)
Main ticket: [CAM-4670](https://app.camunda.com/jira/browse/CAM-4670)
=> CAM-10624: feat(engine): add task query filter by assignees

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/task/TaskQuery.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java
Please review PR #404 first.
Related to: https://app.camunda.com/jira/browse/CAM-10625
Main ticket: https://app.camunda.com/jira/browse/CAM-4670
=> CAM-10625:  feat(rest-api): task rest service filter by assignees

engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrencyTestCase.java
https://app.camunda.com/jira/browse/CAM-10631
=> CAM-10631: avoid race condition in concurrency tests

engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobHelper.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorExceptionLoggingHandlerTest.java
https://app.camunda.com/jira/browse/CAM-10620
Related to CAM-10620
=> [CAM-10620] Allow override of logging behavior

engine/src/main/java/org/camunda/bpm/engine/ProcessEngineConfiguration.java, javaee/ejb-service/src/main/java/org/camunda/bpm/container/impl/ejb/JobExecutionHandlerMDB.java, javaee/jobexecutor-ra/src/main/java/org/camunda/bpm/container/impl/threading/ra/inflow/JcaInflowExecuteJobsRunnable.java, javaee/jobexecutor-ra/src/main/java/org/camunda/bpm/container/impl/threading/ra/inflow/JobExecutionHandler.java
Please review #410 before
https://app.camunda.com/jira/browse/CAM-10601
Related to CAM-10601
=> [CAM-10601] Respect logging configuration on WLS

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.testInvalidSubProcessWithoutStartEvent.bpmn
https://app.camunda.com/jira/browse/CAM-10274
Related to CAM-10274
=> [CAM-10274]: Add error when parsing subProcess without start event

engine/src/main/java/org/camunda/bpm/engine/impl/calendar/DurationHelper.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/calendar/DurationHelperTest.java
https://app.camunda.com/jira/browse/CAM-10321
Related to CAM-10321
=> [CAM-10321]: Add support for "PnW" duration patterns on timer events

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceQueryDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricVariableInstanceQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricTaskInstanceRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricVariableInstanceRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/history/HistoricTaskInstanceQuery.java, engine/src/main/java/org/camunda/bpm/engine/history/HistoricVariableInstanceQuery.java, engine/src/main/java/org/camunda/bpm/engine/impl/HistoricTaskInstanceQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/HistoricVariableInstanceQueryImpl.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricVariableInstance.xml, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricVariableInstanceTest.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/HistoricTaskInstanceQueryTest.java, engine/src/test/resources/logback-test.xml
https://app.camunda.com/jira/browse/CAM-10669
Related to CAM-10669
=> [CAM-10669] Add case-insensitive queries for HistoricTaskInstanceQuery and HistoricVariableInstanceQuery

engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/impl/FetchAndLockRestServiceInteractionTest.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/ExternalTaskDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/FetchExternalTasksDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/externaltask/ExternalTask.java, engine/src/main/java/org/camunda/bpm/engine/externaltask/ExternalTaskQueryTopicBuilder.java, engine/src/main/java/org/camunda/bpm/engine/externaltask/LockedExternalTask.java, engine/src/main/java/org/camunda/bpm/engine/impl/externaltask/ExternalTaskQueryTopicBuilderImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/externaltask/LockedExternalTaskImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/externaltask/TopicFetchInstruction.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExternalTaskEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExternalTaskManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/ExternalTask.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.testFetchAndLockByProcessDefinitionVersionTag.bpmn20.xml
https://app.camunda.com/jira/browse/CAM-10393
Related to CAM-10393
=> [CAM-10393] Add support for fetch and lock external tasks by version tag of process definition

bom/pom.xml
=> [CAM-10696, CAM-10695] Bump mybatis dependency to 3.4.6

bom/pom.xml
=> [CAM-10699, CAM-10695 Bump java-uuid-generator dependency to 3.2.0

bom/pom.xml, qa/test-old-engine/pom.xml
=> [CAM-10696, CAM-10695] Bump mybatis dependency

engine-dmn/bom/pom.xml
https://app.camunda.com/jira/browse/CAM-10722
=> CAM-10722: switch to bpm-release-parent

distro/jbossas7/modules/pom.xml, distro/wildfly/modules/pom.xml, distro/wildfly8/modules/pom.xml, engine-rest/engine-rest/pom.xml
=> [CAM-10702, CAM-10695] Bump slf4j-api dependency to 1.7.26

bom/pom.xml, distro/jbossas7/modules/src/main/modules/org/apache/httpcomponents/httpclient/main/module.xml, distro/wildfly/modules/src/main/modules/org/apache/httpcomponents/httpclient/main/module.xml, distro/wildfly8/modules/src/main/modules/org/apache/httpcomponents/httpclient/main/module.xml, qa/integration-tests-webapps/pom.xml
=> [CAM-10711, CAM-10695] Bump httpclient dependency to 4.5.9

engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java, qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/classloading/jobexecution/ClassloadingDuringJobExecutionTest.java
Related to https://app.camunda.com/jira/browse/CAM-10379
=> fix(engine): perform context classloader switch before running a job

engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java, javaee/jobexecutor-ra/src/main/java/org/camunda/bpm/container/impl/threading/ra/inflow/JcaInflowExecuteJobsRunnable.java
=> CAM-10379: fix classloading for weblogic server

engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java, javaee/jobexecutor-ra/src/main/java/org/camunda/bpm/container/impl/threading/ra/inflow/JcaInflowExecuteJobsRunnable.java
Related to [CAM-10760](https://app.camunda.com/jira/browse/CAM-10760)
=> CAM-10760: improve docs for classloader switch during job execution

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/ExternalTaskBpmnError.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskBpmnErrorDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/TaskResource.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/impl/TaskResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/TaskService.java, engine/src/main/java/org/camunda/bpm/engine/impl/TaskServiceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/behavior/ExternalTaskActivityBehavior.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/HandleTaskBpmnErrorCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExternalTaskEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/TaskAuthorizationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/task/HandleTaskBpmnErrorAuthorizationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskServiceTest.java
Related to [CAM-10398](https://app.camunda.com/jira/browse/CAM-10398)
=> CAM-10398 Handle bpmn error in user task

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskEscalationDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/TaskResource.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/impl/TaskResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/TaskService.java, engine/src/main/java/org/camunda/bpm/engine/impl/TaskServiceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/behavior/BpmnBehaviorLogger.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/behavior/ThrowEscalationEventActivityBehavior.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/helper/EscalationEventDefinitionFinder.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/helper/EscalationHandler.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CommandLogger.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/HandleTaskEscalationCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/task/HandleTaskAuthorizationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskServiceTest.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/escalation/EscalationEventParseInvalidProcessTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/task/TaskServiceTest.handleUserTaskEscalation.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/escalation/EscalationEventParseInvalidProcessTest.invalidAttachement.bpmn20.xml
* adjust exsisting tests
related to [CAM-10397](https://app.camunda.com/jira/browse/CAM-10397)
=> CAM-10397: escalation event can be handled in user task

engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/helper/MockExternalTaskBuilder.java, engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/LockedExternalTaskDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockExternalTaskBuilder.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
=> [CAM-10693]: expose versionTag to fetched external tasks

qa/integration-tests-webapps/integration-tests/src/test/java/org/camunda/bpm/CsrfPreventionIT.java
related to [CAM-10791](https://app.camunda.com/jira/browse/CAM-10791)
=> [CAM-10791] Fix default value of same site flag for CSRF

parent/pom.xml
Related to [CAM-10745](https://app.camunda.com/jira/browse/CAM-10745)
=> CAM-10745: chore(deps): bump tomcat to 9.0.24

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ProcessDefinitionRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricCaseDefinitionRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricDecisionStatisticsRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricProcessDefinitionRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/repository/impl/ProcessDefinitionResourceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/FilterResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessEngineRestServiceTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/StatisticsRestTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricActivityStatisticsRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricCaseActivityStatisticsRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricDecisionStatisticsRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/FilterService.java, engine/src/main/java/org/camunda/bpm/engine/externaltask/UpdateExternalTaskRetriesBuilder.java, engine/src/main/java/org/camunda/bpm/engine/impl/AbstractQuery.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ExecuteFilterListPageCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/util/QueryMaxResultsLimitUtil.java, engine/src/main/java/org/camunda/bpm/engine/migration/MigrationPlanExecutionBuilder.java, engine/src/main/java/org/camunda/bpm/engine/query/Query.java, engine/src/main/java/org/camunda/bpm/engine/runtime/ModificationBuilder.java, engine/src/main/java/org/camunda/bpm/engine/runtime/RestartProcessInstanceBuilder.java, engine/src/main/java/org/camunda/bpm/engine/runtime/UpdateProcessInstanceSuspensionStateBuilder.java, engine/src/test/java/org/camunda/bpm/engine/test/api/queries/BoundedNumberOfMaxResultsDelegate.java, engine/src/test/java/org/camunda/bpm/engine/test/api/queries/BoundedNumberOfMaxResultsTest.java
Add config flag to set a max results limit for queries.
related to [CAM-10497](https://app.camunda.com/jira/browse/CAM-10497)
=> [CAM-10497] Query Max Results Limit

qa/integration-tests-webapps/integration-tests/src/test/java/org/camunda/bpm/AbstractWebIntegrationTest.java
No label assigned because we don't have CI for webapps ITs 😢  
related to [CAM-10839](https://app.camunda.com/jira/browse/CAM-10839)
=> [CAM-10839] increase waiting time of webapps ITs to avoid race conditions

qa/integration-tests-webapps/shared-engine/pom.xml, qa/integration-tests-webapps/standalone-engine/pom.xml
Related to [CAM-10881](https://app.camunda.com/jira/browse/CAM-10881)
=> CAM-10881: fix(webapps-it): enable preferIPv4Stack for jboss/wildfly

distro/wildfly/assembly/src/wildfly/standalone-full.xml, distro/wildfly/assembly/src/wildfly/standalone.xml, parent/pom.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml, qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
* bump WildFly versions in parent POM
* adjust standalone, domain, host XMLs
related to CAM-10808
=> CAM-10808: add support for WildFly 18

engine/src/main/java/org/camunda/bpm/engine/impl/el/VariableScopeElResolver.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/el/ExpressionManagerTest.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/el/ValueIncreasingListener.java, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/el/ExpressionManagerTest.testSetVariableByExpressionFromListener.bpmn20.xml
related to [CAM-10871](https://app.camunda.com/jira/browse/CAM-10871)
=> CAM-10871: mark variable expression context as resolved

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/ModificationDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/modification/ProcessInstanceModificationDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ModificationRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/ProcessInstanceResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ModificationRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/impl/ModificationBuilderImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/ProcessInstanceModificationBuilderImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractModificationCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ModifyProcessInstanceAsyncCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ModifyProcessInstanceCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ProcessInstanceModificationBatchCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ProcessInstanceModificationCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/StartProcessInstanceAtActivitiesCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java, engine/src/main/java/org/camunda/bpm/engine/impl/oplog/UserOperationLogContextEntry.java, engine/src/main/java/org/camunda/bpm/engine/impl/oplog/UserOperationLogContextEntryBuilder.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/UserOperationLogManager.java, engine/src/main/java/org/camunda/bpm/engine/runtime/ModificationBuilder.java, engine/src/main/java/org/camunda/bpm/engine/runtime/ProcessInstanceModificationBuilder.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ModificationUserOperationLogTest.java
Related to [CAM-10865](https://app.camunda.com/jira/browse/CAM-10865)
=> CAM-10865 add annotation during process instance modification

engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ContextLogger.java
Related to [CAM-10627](https://app.camunda.com/jira/browse/CAM-10627)
=> CAM-10627: chore(engine): log bpmn stack trace on level DEBUG

javaee/jobexecutor-ra/src/main/java/org/camunda/bpm/container/impl/threading/ra/inflow/JobExecutionHandlerActivationSpec.java
Related to [CAM-9811](https://app.camunda.com/jira/browse/CAM-9811)
=> CAM-9811: chore(jobexecutor-ra): add dummy property to prevent NPE in WAS

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/history/HistoricProcessDefinitionRestService.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricActivityStatisticsQueryDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricProcessDefinitionRestServiceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricActivityStatisticsRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/history/HistoricActivityStatisticsQuery.java, engine/src/main/java/org/camunda/bpm/engine/impl/HistoricActivityStatisticsQueryImpl.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricStatistics.xml, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricActivityStatisticsQueryTest.java
https://app.camunda.com/jira/browse/CAM-10887
=> CAM-10887: Historic activity instance statistics selection by process instance id

distro/jbossas7/modules/src/main/modules/net/minidev/json-smart/main/module.xml, distro/wildfly/modules/src/main/modules/net/minidev/json-smart/main/module.xml, distro/wildfly8/modules/src/main/modules/net/minidev/json-smart/main/module.xml, qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/spin/SpinJsonPathTest.java, qa/integration-tests-engine/src/test/resources/org/camunda/bpm/integrationtest/jsonpath-process.bpmn
related to [CAM-10879](https://app.camunda.com/jira/browse/CAM-10879)
=> [CAM-10879] fix module.xml descriptors of json-smart

engine/src/main/java/org/camunda/bpm/engine/impl/form/engine/HtmlFormEngine.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/form/HtmlFormEngineTest.testRenderDateField.html, engine/src/test/resources/org/camunda/bpm/engine/test/api/form/HtmlFormEngineTest.testRenderDateFieldWithPattern.html
related to [CAM-10829](https://app.camunda.com/jira/browse/CAM-10829)
=> [CAM-10829] fix prefix of angular bootstrap ui directive in form engine

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SaveUserCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/UserEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/api/identity/CustomPasswordPolicyTest.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/identity/DefaultPasswordPolicyTest.java
Related to [CAM-10802](https://app.camunda.com/jira/browse/CAM-10802)
=> CAM-10802: fix(engine): fix update user when password policy is enabled

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/CaseExecution.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Commons.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Execution.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricCaseInstance.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/VariableInstanceAuthorizationTest.java
Related to [CAM-10864](https://app.camunda.com/jira/browse/CAM-10864)
=> CAM-10864 adjust variable ignore case queries

bom/pom.xml, engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ProcessDataLoggingContext.java
* removes direct dependency on SLF4J from engine
related to [CAM-10907](https://app.camunda.com/jira/browse/CAM-10907)
=> fix(engine): replace MDC usage by commons facade

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/usertask/TaskCandidateTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/usertask/groupTest.bpmn
https://app.camunda.com/jira/browse/CAM-10903
=> CAM-10903: task or query with involved user

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/GroupRestService.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/identity/GroupQueryDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/GroupRestServiceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/GroupRestServiceQueryTest.java
https://app.camunda.com/jira/browse/CAM-10910
=> CAM-10910: idIn parameter for group query

engine/src/main/java/org/camunda/bpm/engine/impl/cmmn/model/CaseDefinitionBuilder.java, engine/src/main/java/org/camunda/bpm/engine/impl/context/Context.java, engine/src/main/java/org/camunda/bpm/engine/impl/form/engine/HtmlDocumentBuilder.java, engine/src/main/java/org/camunda/bpm/engine/impl/pvm/ProcessDefinitionBuilder.java, engine/src/main/java/org/camunda/bpm/engine/impl/util/xml/ParseHandler.java
* use `Deque` instead of `Stack` where synchronization is not needed
related to [CAM-9653](https://app.camunda.com/jira/browse/CAM-9653)
=> CAM-9653: remove unnecessary synchronization

engine-dmn/pom.xml, parent/pom.xml
https://app.camunda.com/jira/browse/CAM-10918
=> CAM-10918: bump surefire to 2.22.2

bom/pom.xml
Related to [CAM-9972](https://app.camunda.com/jira/browse/CAM-9972)
=> CAM-9972: chore(engine): update spin version after release

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractVariableCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AddCommentCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CreateAttachmentCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteAttachmentCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SaveAttachmentCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetTaskVariablesCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/tasklistener/TaskListenerTest.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/tasklistener/util/RecorderTaskListener.java
https://app.camunda.com/jira/browse/CAM-10889
=> CAM-10889: task UPDATE event for attachment, comment, variables

qa/test-db-upgrade/pom.xml
Related to [CAM-10923](https://app.camunda.com/jira/browse/CAM-10923)
=> CAM-10923: chore(qa): add commons testing

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentQueryDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/IncidentQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/IncidentRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIncidentRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/history/HistoricIncidentQuery.java, engine/src/main/java/org/camunda/bpm/engine/impl/HistoricIncidentQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/IncidentQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/runtime/IncidentQuery.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Incident.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/IncidentQueryTest.java, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricIncidentQueryTest.java
https://app.camunda.com/jira/browse/CAM-10939
=> CAM-10939: query incidents by process definition key

engine/src/main/java/org/camunda/bpm/engine/authorization/OptimizePermissions.java, engine/src/main/java/org/camunda/bpm/engine/authorization/Resources.java
https://app.camunda.com/jira/browse/CAM-10929
=> CAM-10929: deprecate Optimize permissions

engine/src/main/java/org/camunda/bpm/engine/ManagementService.java, engine/src/main/java/org/camunda/bpm/engine/impl/ManagementServiceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteLicenseKeyCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/GetLicenseKeyCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/LicenseCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/PurgeDatabaseAndCacheCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetLicenseKeyCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/management/DatabasePurgeReport.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ResourceManager.java, engine/src/main/java/org/camunda/bpm/engine/impl/test/TestHelper.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Resource.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/LicenseUserOperationLogTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceTableCountTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/license/LicenseKeyAuthTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/license/LicenseKeyDirtyDbTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/license/LicenseKeyTest.java, engine/src/test/java/org/camunda/bpm/engine/test/concurrency/CompetingLicenseKeyAccessTest.java
=> Add support for new license format

qa/test-db-rolling-update/README.md, qa/test-db-upgrade/README.md
Related to [CAM-10928](https://app.camunda.com/jira/browse/CAM-10928)
=> chore(qa): update qa maven commands

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/FilterResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java
https://app.camunda.com/jira/browse/CAM-10955
=> CAM-10955: fetch hal variables without pagination limit

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteLicenseKeyCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/PurgeDatabaseAndCacheCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ResourceEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ResourceManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Resource.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/LicenseUserOperationLogTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/license/LicenseKeyDirtyDbTest.java
=> CAM-10667 Refactor License Key Deletion

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricActivityStatisticsDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricActivityStatisticsRestServiceQueryTest.java
Related to [CAM-10991](https://app.camunda.com/jira/browse/CAM-10991)
=> CAM-10991: fix(rest): expose closedIncidents to hist act statistics response

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ProcessDataLoggingContext.java, engine/src/test/java/org/camunda/bpm/engine/test/logging/ProcessDataLoggingContextTest.java
[![CAM-11003](https://badgen.net/badge/JIRA/CAM-11003/0052CC)](https://app.camunda.com/jira/browse/CAM-11003)
related to CAM-11003
=> [CAM-11003] fix(engine): correct logging context properties' names

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/ActivityInstanceDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/TransitionInstanceDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/AbstractRestServiceTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/GetActivityInstanceCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ActivityInstanceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ProcessElementInstanceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TransitionInstanceImpl.java, engine/src/main/java/org/camunda/bpm/engine/runtime/ActivityInstance.java, engine/src/main/java/org/camunda/bpm/engine/runtime/TransitionInstance.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceTest.java, engine/src/test/java/org/camunda/bpm/engine/test/util/ActivityInstanceAssert.java
Related to [CAM-10906](https://app.camunda.com/jira/browse/CAM-10906)
=> CAM-10906: chore(engine): add incident ids in get activities instances

distro/jbossas7/webapp/pom.xml, qa/integration-tests-webapps/integration-tests/src/test/java/org/camunda/bpm/ExceptionLoggerIT.java, qa/integration-tests-webapps/pom.xml
[![CAM-10805](https://badgen.net/badge/JIRA/CAM-10805/0052CC)](https://app.camunda.com/jira/browse/CAM-10805)
Related to CAM-10805
=> CAM-10805: fix(engine): add logging module dependency to webapps rest

distro/wildfly/assembly/src/wildfly/standalone.xml
[![CAM-10964](https://badgen.net/badge/JIRA/CAM-10964/0052CC)](https://app.camunda.com/jira/browse/CAM-10964)
related to CAM-10964
=> [CAM-10964] chore(wildfly): activate MDC by default in log

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricActivityStatisticsDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricActivityStatisticsQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricActivityStatisticsRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/history/HistoricActivityStatistics.java, engine/src/main/java/org/camunda/bpm/engine/history/HistoricActivityStatisticsQuery.java, engine/src/main/java/org/camunda/bpm/engine/impl/HistoricActivityStatisticsQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricActivityStatisticsImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricStatisticsManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricStatistics.xml, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricActivityStatisticsQueryTest.java
[![CAM-11037](https://badgen.net/badge/JIRA/CAM-11037/0052CC)](https://app.camunda.com/jira/browse/CAM-11037)
=> CAM-11037: expose open/resolved/closed incidents count to historic activity instance statistics

engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/BatchDbSqlSession.java
[![CAM-10990](https://badgen.net/badge/JIRA/CAM-10990/0052CC)](https://app.camunda.com/jira/browse/CAM-10990)
- some databases (postgres with rewriteBatchedInserts option) do not
return the number of rows when processing a batch of inserts
- the process engine doesn't need this number for INSERTs, so we do
not have to validate it
related to CAM-10990
=> CAM-10990: do not validate affected rows of INSERTs

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/repository/DecisionDefinitionQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/DecisionDefinitionRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/impl/dmn/entity/repository/DecisionDefinitionQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/dmn/entity/repository/DecisionDefinitionQueryProperty.java, engine/src/main/java/org/camunda/bpm/engine/repository/DecisionDefinitionQuery.java, engine/src/test/java/org/camunda/bpm/engine/test/api/repository/DecisionDefinitionQueryTest.java
https://app.camunda.com/jira/browse/CAM-10992
=> CAM-10992: order decision definitions by requirements key

distro/license-book/src/main/resources/license-book.txt
[![CAM-11101](https://badgen.net/badge/JIRA/CAM-11101/0052CC)](https://app.camunda.com/jira/browse/CAM-11101)
=> CAM-11101: update third party license book

database/pom.xml, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.12_to_7.13.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.12_to_7.13.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.12_to_7.13.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.12_to_7.13.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.12_to_7.13.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.12_to_7.13.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.12_to_7.13.sql, qa/test-db-instance-migration/pom.xml, qa/test-db-instance-migration/test-fixture-712/pom.xml, qa/test-db-instance-migration/test-fixture-713/pom.xml, qa/test-db-instance-migration/test-fixture-713/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java, qa/test-db-instance-migration/test-fixture-713/src/main/resources/camunda.cfg.xml, qa/test-db-rolling-update/create-old-engine/pom.xml, qa/test-db-rolling-update/rolling-update-util/pom.xml, qa/test-db-rolling-update/test-old-engine/pom.xml, qa/test-db-upgrade/pom.xml, qa/test-old-engine/pom.xml, typed-values/pom.xml
[![CAM-11032](https://badgen.net/badge/JIRA/CAM-11032/0052CC)](https://app.camunda.com/jira/browse/CAM-11032)
related to CAM-11032
=> [CAM-11032] chore(release): update old version

database/pom.xml, engine/pom.xml
[![CAM-11104](https://badgen.net/badge/JIRA/CAM-11104/0052CC)](https://app.camunda.com/jira/browse/CAM-11104)
Related to CAM-11104
=> CAM-11104: chore(engine): remove oracle 10 code

qa/test-old-engine/pom.xml
[![CAM-11032](https://badgen.net/badge/JIRA/CAM-11032/0052CC)](https://app.camunda.com/jira/browse/CAM-11032)
related to CAM-11032
=> [CAM-11032] chore(old-engine): use explicit version numbers

engine/src/main/java/org/camunda/bpm/engine/impl/ProcessInstanceModificationBuilderImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractDeleteProcessInstanceCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractInstanceCancellationCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractInstantiationCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractProcessInstanceModificationCommand.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ModifyProcessInstanceCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/operation/PvmAtomicOperationDeleteCascade.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceTerminationCascadeStateTest.java
[![CAM-10832](https://badgen.net/badge/JIRA/CAM-10832/0052CC)](https://app.camunda.com/jira/browse/CAM-10832)
=> correct state for externally canceled subprocess

distro/tomcat/assembly/src/conf/server.xml, qa/tomcat-runtime/src/main/conf/server.xml
[![CAM-10577](https://badgen.net/badge/JIRA/CAM-10577/0052CC)](https://app.camunda.com/jira/browse/CAM-10577)
=> Adjust renamed tomcat property maxActive to maxTotal

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ProcessDefinitionRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricCaseDefinitionRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricDecisionStatisticsRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricProcessDefinitionRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/repository/impl/ProcessDefinitionResourceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/FilterResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/StatisticsRestTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricActivityStatisticsRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricCaseActivityStatisticsRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricDecisionStatisticsRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/impl/AbstractQuery.java, engine/src/main/java/org/camunda/bpm/engine/query/Query.java, engine/src/test/java/org/camunda/bpm/engine/test/api/queries/BoundedNumberOfMaxResultsTest.java
[![CAM-11149](https://badgen.net/badge/JIRA/CAM-11149/0052CC)](https://app.camunda.com/jira/browse/CAM-11149)
related to CAM-11149
=> CAM-11149 feat(engine/rest): make unlimited queries public api

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/ProcessInstanceResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/impl/ProcessInstanceModificationBuilderImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractDeleteProcessInstanceCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java, engine/src/main/java/org/camunda/bpm/engine/runtime/ProcessInstanceModificationBuilder.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceTerminationCascadeStateTest.java
[![CAM-11131](https://badgen.net/badge/JIRA/CAM-11131/0052CC)](https://app.camunda.com/jira/browse/CAM-11131)
Related to CAM-11131
=> CAM-11131: Improve cancellation API

database/pom.xml
[![CAM-11108](https://badgen.net/badge/JIRA/CAM-11108/0052CC)](https://app.camunda.com/jira/browse/CAM-11108)
related to CAM-11108
=> CAM-11108 chore(database): remove jdbc drivers for db2 9.7 & 10.1

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ProcessInstanceRestServiceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/ManagementService.java, engine/src/main/java/org/camunda/bpm/engine/RuntimeService.java, engine/src/main/java/org/camunda/bpm/engine/impl/ManagementServiceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/RuntimeServiceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/SetJobsRetriesByProcessBatchCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/batch/DeleteProcessInstanceBatchCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceAsyncOperationsTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceAsyncOperationsTest.java
[![CAM-11118](https://badgen.net/badge/JIRA/CAM-11118/0052CC)](https://app.camunda.com/jira/browse/CAM-11118)
related to CAM-11118
=> CAM-11118 fix(engine/rest): remove query limit for historic query based operations

engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.12_patch_7.12.0_to_7.12.1.sql
[![CAM-11117](https://badgen.net/badge/JIRA/CAM-11117/0052CC)](https://app.camunda.com/jira/browse/CAM-11117)
Related to CAM-11117
=> fix(db): adjust drop index statement for mysql

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DefaultJobRetryCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/async/FoxJobRetryCmdTest.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/parse/RetryIntervalsConfigurationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentJobExecutorTest.java, qa/test-db-instance-migration/test-fixture-712/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java, qa/test-db-instance-migration/test-fixture-712/src/main/java/org/camunda/bpm/qa/upgrade/customretries/FailingIntermediateBoundaryTimerJobScenario.java, qa/test-db-instance-migration/test-fixture-712/src/main/resources/org/camunda/bpm/qa/upgrade/customretries/failingTimerJob.bpmn20.xml, qa/test-db-instance-migration/test-migration/src/test/java/org/camunda/bpm/qa/upgrade/scenarios7130/customretries/FailingIntermediateBoundaryTimerJobTest.java
[![CAM-9571](https://badgen.net/badge/JIRA/CAM-9571/0052CC)](https://app.camunda.com/jira/browse/CAM-9571)
=> CAM-9571: fix(engine): unlock job with custom retries when fails

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/EverLivingJobEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentHistoryCleanupReconfigureTest.java
[![CAM-11147](https://badgen.net/badge/JIRA/CAM-11147/0052CC)](https://app.camunda.com/jira/browse/CAM-11147)
related to CAM-11147
=> CAM-11147 chore(engine): avoid NPE while reconfiguring the cleanup job

engine/src/test/resources/camunda.cfg.prefix.xml
[![CAM-11167](https://badgen.net/badge/JIRA/CAM-11167/0052CC)](https://app.camunda.com/jira/browse/CAM-11167)
Related to CAM-11167
=> chore(tests): add database hint in prefix configuration file

engine/src/test/java/org/camunda/bpm/engine/test/bpmn/callactivity/CallActivityTest.java
[![CAM-11191](https://badgen.net/badge/JIRA/CAM-11191/0052CC)](https://app.camunda.com/jira/browse/CAM-11191)
Test cases as a followup of CAM-9932.
related to CAM-11191
=> CAM-11191: transient flag is preserved in call activity mapping

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/ActivityInstanceDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/ActivityInstanceIncidentDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/TransitionInstanceDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/AbstractRestServiceTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/GetActivityInstanceCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ActivityInstanceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TransitionInstanceImpl.java, engine/src/main/java/org/camunda/bpm/engine/runtime/ActivityInstance.java, engine/src/main/java/org/camunda/bpm/engine/runtime/TransitionInstance.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceTest.java
[![CAM-11190](https://badgen.net/badge/JIRA/CAM-11190/0052CC)](https://app.camunda.com/jira/browse/CAM-11190)
related to CAM-11190
=> CAM-11190 fix(engine/rest): add incident -> activity id mapping in instance tree

examples/invoice/src/main/resources/META-INF/processes.xml, qa/integration-tests-webapps/integration-tests/src/test/java/org/camunda/bpm/rest/RestIT.java
[![CAM-10682](https://badgen.net/badge/JIRA/CAM-10682/0052CC)](https://app.camunda.com/jira/browse/CAM-10682)
=> Adjust integration test that relied on invoice example

model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/Bpmn.java, model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/BpmnModelConstants.java, model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/instance/CategoryImpl.java, model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/instance/GroupImpl.java, model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/instance/Category.java, model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/instance/Group.java, model-api/bpmn-model/src/test/java/org/camunda/bpm/model/bpmn/instance/CategoryTest.java, model-api/bpmn-model/src/test/java/org/camunda/bpm/model/bpmn/instance/GroupTest.java
[![CAM-10905](https://badgen.net/badge/JIRA/CAM-10905/0052CC)](https://app.camunda.com/jira/browse/CAM-10905)
See https://github.com/zeebe-io/zeebe/commit/16e57b8a6435037feb7952fb192484de69518296
=> Allow group and category elements

examples/invoice/src/main/resources/META-INF/processes.xml, examples/invoice/src/main/resources/reviewInvoice.bpmn, qa/integration-tests-webapps/integration-tests/src/test/java/org/camunda/bpm/rest/RestIT.java
[![CAM-10682](https://badgen.net/badge/JIRA/CAM-10682/0052CC)](https://app.camunda.com/jira/browse/CAM-10682)
=> Do not assume order of response items in RestIT

model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/builder/AbstractBaseElementBuilder.java, model-api/bpmn-model/src/test/java/org/camunda/bpm/model/bpmn/builder/ProcessBuilderTest.java
[![CAM-11230](https://badgen.net/badge/JIRA/CAM-11230/0052CC)](https://app.camunda.com/jira/browse/CAM-11230)
Add a builder method to add Documentation elements to any BaseElement and set the text content.
=> CAM-11230: feat(model): add Documentation to BaseElements with fluent builder API

database/pom.xml, settings/maven/nexus-settings.xml
[![CAM-10628](https://badgen.net/badge/JIRA/CAM-10628/0052CC)](https://app.camunda.com/jira/browse/CAM-10628)
related to CAM-10628
=> [CAM-10628] feat(database): add profiles for Oracle 19

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceQueryTest.java
[![CAM-11233](https://badgen.net/badge/JIRA/CAM-11233/0052CC)](https://app.camunda.com/jira/browse/CAM-11233)
Please only consider commit 12c71af for this review. The rest of the commits are reviewed under PR #610.
=> CAM-11233: feat(rest): add historic job log hostname parameter

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
[![CAM-11179](https://badgen.net/badge/JIRA/CAM-11179/0052CC)](https://app.camunda.com/jira/browse/CAM-11179)
=> CAM-11179 Improve bad performing sql query for task query

engine/pom.xml, engine/src/main/java/org/camunda/bpm/engine/impl/batch/builder/BatchBuilder.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ConfigurationLogger.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/test/java/org/camunda/bpm/engine/impl/batch/BatchInvocationsPerJobByBatchTypeConfigTest.java, engine/src/test/java/org/camunda/bpm/engine/impl/batch/BatchInvocationsPerJobByBatchTypeTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/SetExternalTasksRetriesTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/BatchHistoricDecisionInstanceDeletionTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/HistoryServiceAsyncOperationsTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceAsyncOperationsTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ModificationExecutionAsyncTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RestartProcessInstanceAsyncTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceAsyncOperationsTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/SingleProcessInstanceModificationAsyncTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/UpdateProcessInstancesSuspendStateAsyncTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/migration/batch/BatchMigrationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/HistoryCleanupBatchTest.java, engine/src/test/resources/camunda.cfg.invocationsPerJobByBatchType.xml
[![CAM-11182](https://badgen.net/badge/JIRA/CAM-11182/0052CC)](https://app.camunda.com/jira/browse/CAM-11182)
=> CAM-11182 I can configure the invocations per batch job by batch type

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/json/JsonTaskQueryConverter.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskManager.java, engine/src/main/java/org/camunda/bpm/engine/task/TaskQuery.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterTaskQueryTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryOrTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java
[![CAM-10952](https://badgen.net/badge/JIRA/CAM-10952/0052CC)](https://app.camunda.com/jira/browse/CAM-10952)
=> CAM-10952: chore(engine/rest): add processInstanceIdIn to the task query

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/IncidentDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/JobDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/IncidentRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockJobBuilder.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIncidentRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceQueryTest.java
[![CAM-10378](https://badgen.net/badge/JIRA/CAM-10378/0052CC)](https://app.camunda.com/jira/browse/CAM-10378)
* significant commit for this PR is https://github.com/camunda/camunda-bpm-platform/pull/619/commits/98e7e767db8bcc5293ddb09819adcdb4d3fbfdb8
* only merge **after** https://github.com/camunda/camunda-bpm-platform/pull/617
* I will rebase this PR after https://github.com/camunda/camunda-bpm-platform/pull/617 is merged
related to CAM-10378
=> [CAM-10378] feat(rest): add id of failed activity

distro/tomcat/distro/pom.xml, distro/tomcat/webapp/pom.xml
[![CAM-10977](https://badgen.net/badge/JIRA/CAM-10977/0052CC)](https://app.camunda.com/jira/browse/CAM-10977)
=> CAM-10977: use Resteasy 3 instead of 2 on Tomcat

distro/wildfly/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-dmn/main/module.xml
[![](https://badgen.net/badge/JIRA//0052CC)](https://app.camunda.com/jira/browse/)
=> feel ❤️ JBoss EAP

distro/jbossas7/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-dmn/main/module.xml, distro/wildfly/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-dmn/main/module.xml, engine-dmn/engine/pom.xml
[![](https://badgen.net/badge/JIRA//0052CC)](https://app.camunda.com/jira/browse/)
=> WIP exclude slf4j from shading [feel]

distro/tomcat/webapp/pom.xml, engine-rest/assembly/assembly-war-jbossas7.xml, engine-rest/assembly/assembly-war-tomcat.xml, engine-rest/assembly/pom.xml, engine-rest/engine-rest-jaxrs2/pom.xml, engine-rest/engine-rest/pom.xml, parent/pom.xml
[![CAM-11285](https://badgen.net/badge/JIRA/CAM-11285/0052CC)](https://app.camunda.com/jira/browse/CAM-11285)
=> CAM-11285: Resteasy 3 update

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogQueryDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/JobQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/history/HistoricJobLogQuery.java, engine/src/main/java/org/camunda/bpm/engine/impl/HistoricJobLogQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/JobQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/runtime/JobQuery.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricJobLog.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/JobQueryTest.java, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricJobLogQueryTest.java
[![CAM-11273](https://badgen.net/badge/JIRA/CAM-11273/0052CC)](https://app.camunda.com/jira/browse/CAM-11273)
related to CAM-11273
=> [CAM-11273] feat(engine+rest): add job query filter for failed activity

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentQueryDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/IncidentQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/IncidentRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIncidentRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/history/HistoricIncidentQuery.java, engine/src/main/java/org/camunda/bpm/engine/impl/HistoricIncidentQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/IncidentQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/runtime/IncidentQuery.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Incident.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/IncidentQueryTest.java, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricIncidentQueryTest.java
[![CAM-11274](https://badgen.net/badge/JIRA/CAM-11274/0052CC)](https://app.camunda.com/jira/browse/CAM-11274)
related to CAM-11274
=> [CAM-11274] feat(engine+rest): add query filter for failed activity id

engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/NewScalaFeelBehaviorTest.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/CamundaFeelEngine.java
[![CAM-11347](https://badgen.net/badge/JIRA/CAM-11347/0052CC)](https://app.camunda.com/jira/browse/CAM-11347)
=> CAM-11347 add constructor instead of init block

engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/type/DmnDataTypeTransformerTest.java
[![CAM-11314](https://badgen.net/badge/JIRA/CAM-11314/0052CC)](https://app.camunda.com/jira/browse/CAM-11314)
=> chore(dmn): make zoneddatetime instance more robust

bom/pom.xml, database/pom.xml, engine-rest/engine-rest/pom.xml, parent/pom.xml, pom.xml, qa/integration-tests-engine/pom.xml, qa/test-db-instance-migration/test-fixture-710/pom.xml, qa/test-db-instance-migration/test-fixture-711/pom.xml, qa/test-db-instance-migration/test-fixture-712/pom.xml, qa/test-db-instance-migration/test-fixture-713/pom.xml, qa/test-db-instance-migration/test-fixture-72/pom.xml, qa/test-db-instance-migration/test-fixture-73/pom.xml, qa/test-db-instance-migration/test-fixture-74/pom.xml, qa/test-db-instance-migration/test-fixture-75/pom.xml, qa/test-db-instance-migration/test-fixture-76/pom.xml, qa/test-db-instance-migration/test-fixture-77/pom.xml, qa/test-db-instance-migration/test-fixture-78/pom.xml, qa/test-db-instance-migration/test-fixture-79/pom.xml, qa/test-db-instance-migration/test-migration/pom.xml, qa/test-db-rolling-update/create-old-engine/pom.xml, qa/test-db-rolling-update/rolling-update-util/pom.xml, qa/test-db-rolling-update/test-old-engine/pom.xml, qa/test-db-util/pom.xml, qa/test-old-engine/pom.xml
[![CAM-11345](https://badgen.net/badge/JIRA/CAM-11345/0052CC)](https://app.camunda.com/jira/browse/CAM-11345)
=> CAM-11345: remove BOM from pom hierarchy

engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/util/container/TomcatServerBootstrap.java
[![CAM-11345](https://badgen.net/badge/JIRA/CAM-11345/0052CC)](https://app.camunda.com/jira/browse/CAM-11345)
related to CAM-11345
=> fix(engine-rest): enable remote fetching in shrinkwrap test

parent/pom.xml, qa/large-data-tests/README.md, qa/large-data-tests/pom.xml, qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/OptimizeApiPageSizeTest.java, qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/util/DmnHelper.java, qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/util/EngineDataGenerator.java, qa/large-data-tests/src/test/resources/camunda.cfg.xml, qa/large-data-tests/src/test/resources/logback-test.xml, qa/pom.xml
[![CAM-11371](https://badgen.net/badge/JIRA/CAM-11371/0052CC)](https://app.camunda.com/jira/browse/CAM-11371)
Copy of https://github.com/camunda/camunda-bpm-platform/pull/642 with some additional changes and to run CI.
related to #CAM-11371
=> chore(optimize): add tests to ensure databases can cope with page size

qa/integration-tests-webapps/integration-tests/src/test/java/org/camunda/bpm/AbstractWebIntegrationTest.java, qa/integration-tests-webapps/integration-tests/src/test/java/org/camunda/bpm/CsrfPreventionIT.java
[![CAM-10911](https://badgen.net/badge/JIRA/CAM-10911/0052CC)](https://app.camunda.com/jira/browse/CAM-10911)
* Add test coverage to assert that the a correct Error response is received by an HTTP Client when a CSRF token isn't provided.
Related to CAM-10911
=> fix(webapps): ensure correct response on missing csrf token

spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/CsrfPreventionIT.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/util/HeaderRule.java
[![CAM-10911](https://badgen.net/badge/JIRA/CAM-10911/0052CC)](https://app.camunda.com/jira/browse/CAM-10911)
Before merging this PR, please notify me, so that I can rebase it on master. It should only be merged after #655 is merged.
=> CAM-10911: fix(webapps): on missing csrf token, correct error is provided

engine-rest/engine-rest-openapi-generator/pom.xml, engine-rest/engine-rest-openapi-generator/src/main/java/org/camunda/bpm/engine/rest/openapi/generator/impl/SchemaValidator.java, engine-rest/engine-rest-openapi-generator/src/main/java/org/camunda/bpm/engine/rest/openapi/generator/impl/TemplateParser.java, engine-rest/engine-rest-openapi/pom.xml, engine-rest/engine-rest-openapi/src/main/openapi/schema.json
[![CAM-11353](https://badgen.net/badge/JIRA/CAM-11353/0052CC)](https://app.camunda.com/jira/browse/CAM-11353)
* add schema.json to the project
* add validation step during the build of the OpenAPI docs
=> chore(openapi): add json schema validation

engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/DefaultDmnEngineConfiguration.java, engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/BreakingScalaFeelBehaviorTest.java, engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/CustomFunctionConfigTest.java, engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/helper/CustomFunctionProvider.java, engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/helper/TestPojo.java, engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/feel/custom_function.dmn, engine-dmn/feel-scala/pom.xml, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/CamundaFeelEngine.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/CamundaFeelEngineFactory.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/CustomFunction.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/CustomFunctionTransformer.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/FeelCustomFunctionProvider.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/builder/CustomFunctionBuilder.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/builder/CustomFunctionBuilderImpl.java, engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/CustomFunctionSpiTest.java, engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/CustomFunctionTest.java, engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/helper/MyPojo.java, engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/helper/NonSpiFunctionProvider.java, engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/helper/SpiFunctionProvider.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/dmn/configuration/DmnEngineConfigurationBuilder.java, engine/src/test/java/org/camunda/bpm/engine/test/dmn/feel/FeelCustomFunctionConfigTest.java, engine/src/test/java/org/camunda/bpm/engine/test/dmn/feel/helper/CustomFunctionProvider.java, engine/src/test/resources/org/camunda/bpm/engine/test/dmn/feel/custom_function.dmn
[![CAM-11271](https://badgen.net/badge/JIRA/CAM-11271/0052CC)](https://app.camunda.com/jira/browse/CAM-11271)
=> CAM-11271 add java native custom function mechanism for Scala-based FEEL Engine

engine-rest/engine-rest/pom.xml, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/util/container/TomcatServerBootstrap.java
[![CAM-11345](https://badgen.net/badge/JIRA/CAM-11345/0052CC)](https://app.camunda.com/jira/browse/CAM-11345)
related to CAM-11345
=> fix(engine-rest): forward Maven settings from build to shrinkwrap

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/history/HistoryServiceTest.java
[![CAM-11395](https://badgen.net/badge/JIRA/CAM-11395/0052CC)](https://app.camunda.com/jira/browse/CAM-11395)
=> CAM-11395: rewrite variable condition to join

engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/CamundaFeelEngine.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ContextVariableWrapper.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/CustomFunctionTransformer.java, engine-dmn/feel-scala/src/main/resources/META-INF/services/org.camunda.feel.impl.spi.CustomValueMapper, engine-dmn/feel-scala/src/main/resources/META-INF/services/org.camunda.feel.valuemapper.CustomValueMapper, engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/CustomFunctionSpiTest.java, engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/helper/NonSpiFunctionProvider.java, engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/helper/SpiFunctionProvider.java
[![CAM-11393](https://badgen.net/badge/JIRA/CAM-11393/0052CC)](https://app.camunda.com/jira/browse/CAM-11393)
=> CAM-11393 Adjust package structure according to feel-scala

engine-rest/engine-rest-openapi-generator/src/main/java/org/camunda/bpm/engine/rest/openapi/generator/impl/TemplateParser.java, engine-rest/engine-rest-openapi/pom.xml
[![CAM-11391](https://badgen.net/badge/JIRA/CAM-11391/0052CC)](https://app.camunda.com/jira/browse/CAM-11391)
=> CAM-11391: Debug option of OpenAPI doc

distro/jbossas7/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-dmn/main/module.xml, distro/jbossas7/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-feel-scala/main/module.xml, distro/wildfly/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-dmn/main/module.xml, distro/wildfly/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-feel-scala/main/module.xml, engine-dmn/engine/pom.xml, engine-dmn/feel-scala/pom.xml
[![CAM-11262](https://badgen.net/badge/JIRA/CAM-11262/0052CC)](https://app.camunda.com/jira/browse/CAM-11262)
=> CAM-11262 separate engine-dmn & feel-scala artifact

engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/DefaultDmnEngineConfiguration.java
[![CAM-11398](https://badgen.net/badge/JIRA/CAM-11398/0052CC)](https://app.camunda.com/jira/browse/CAM-11398)
Related to CAM-11398
=> CAM-11398: chore(dmn): update feel custom providers setters

distro/run/pom.xml, distro/run/qa/pom.xml, distro/run/qa/src/test/java/org/camunda/bpm/run/qa/ComponentAvailabilityTest.java, distro/run/qa/src/test/java/org/camunda/bpm/run/qa/util/SpringBootManagedContainer.java, distro/run/qa/src/test/java/org/camunda/bpm/run/qa/webapps/AbstractWebIntegrationTest.java, distro/run/qa/src/test/java/org/camunda/bpm/run/qa/webapps/AbstractWebappUiIntegrationTest.java, distro/run/qa/src/test/java/org/camunda/bpm/run/qa/webapps/LoginITTest.java, distro/run/qa/src/test/resources/logback-test.xml, distro/run/qa/src/test/resources/logging.properties, distro/run/qa/src/test/resources/testconfig.properties
[![CAM-11291](https://badgen.net/badge/JIRA/CAM-11291/0052CC)](https://app.camunda.com/jira/browse/CAM-11291)
* introduce qa module
* create SpringBootManagedContainer to handle Spring Boot lifecycle
* create parameterized test for REST & Webapps availability
* copy LoginIT temporarily from platform qa for basic Webapp test
until CAM-11379 is realized
related to CAM-11291
**Hint**:
you can run the integration tests locally with 
```
mvn clean install -Pdistro,distro-ce,integration-test-camunda-run
```
at `<repo>/distro/run`. They expect a local Chrome of version 78.x (which we have CI environments for on Jenkins). If you have a Chrome with a different version, provide `-Dversion.chromedriver=<your-version>` with `<your-version>` being chosen from …
=> [CAM-11291] chore(project): add integration tests

distro/run/distro/pom.xml, distro/run/distro/src/main/java/org/camunda/bpm/run/CamundaBpmRunSecurityConfiguration.java, distro/run/distro/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunLdapProperties.java, distro/run/distro/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunProperties.java, distro/run/distro/src/test/java/org/camunda/bpm/run/test/config/identity/DemoUserConfigurationTest.java, distro/run/distro/src/test/java/org/camunda/bpm/run/test/config/identity/LdapConfigurationTest.java, distro/run/distro/src/test/java/org/camunda/bpm/run/test/config/ldap/LdapConfigurationTest.java, distro/run/distro/src/test/resources/application-test-demo-user.yml, distro/run/distro/src/test/resources/application-test-ldap-enabled.yml
[![CAM-11293](https://badgen.net/badge/JIRA/CAM-11293/0052CC)](https://app.camunda.com/jira/browse/CAM-11293)
=> [CAM-11293] Enable support for authentication via LDAP

engine-rest/engine-rest-openapi-generator/pom.xml, engine-rest/engine-rest-openapi/pom.xml, engine-rest/engine-rest-openapi/src/test/java/org/camunda/bpm/engine/rest/openapi/client/DeploymentTest.java, engine-rest/engine-rest-openapi/src/test/java/org/camunda/bpm/engine/rest/openapi/client/ProcessInstanceTest.java
[![CAM-11354](https://badgen.net/badge/JIRA/CAM-11354/0052CC)](https://app.camunda.com/jira/browse/CAM-11354)
=> CAM-11354: smoke tests for rest OpenAPI doc

engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelEngine.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelLogger.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/CustomFunctionTransformer.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/builder/CustomFunctionBuilderImpl.java
[![CAM-11464](https://badgen.net/badge/JIRA/CAM-11464/0052CC)](https://app.camunda.com/jira/browse/CAM-11464)
=> CAM-11464 Consolidate all FEEL Exceptions to logger class

engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelLogger.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/CustomFunction.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/CustomFunctionTransformer.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/builder/CustomFunctionBuilder.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/builder/CustomFunctionBuilderImpl.java, engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/CustomFunctionTest.java
[![CAM-11405](https://badgen.net/badge/JIRA/CAM-11405/0052CC)](https://app.camunda.com/jira/browse/CAM-11405)
=> CAM-11405 In scala-feel, add varargs flag for custom functions

engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/FeelBehavior.java, engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/feel/context_function.dmn
[![CAM-11470](https://badgen.net/badge/JIRA/CAM-11470/0052CC)](https://app.camunda.com/jira/browse/CAM-11470)
=> CAM-11470 For FEEL, ensure context functions are not available

engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/DefaultDmnEngineConfiguration.java, engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/evaluation/ExpressionEvaluationHandler.java, engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/transform/DmnExpressionTransformHelper.java, engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/api/EvaluateDecisionTest.java, engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/api/ParseDecisionTest.java, engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/el/FeelIntegrationTest.java, engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/api/dmn13/NoInput.dmn, engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/el/dmn13/FeelIntegrationTest.dmn, engine/src/test/java/org/camunda/bpm/engine/test/dmn/businessruletask/DmnBusinessRuleTaskTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/dmn/businessruletask/dmn13/DmnBusinessRuleTaskTest.testDecisionOkay.dmn, model-api/dmn-model/src/main/java/org/camunda/bpm/model/dmn/Dmn.java, model-api/dmn-model/src/main/java/org/camunda/bpm/model/dmn/impl/DmnModelConstants.java, model-api/dmn-model/src/main/java/org/camunda/bpm/model/dmn/impl/DmnParser.java, model-api/dmn-model/src/main/resources/DMN13.xsd, model-api/dmn-model/src/main/resources/DMNDI13.xsd, model-api/dmn-model/src/test/java/org/camunda/bpm/model/dmn/ExampleCompatibilityTest.java, model-api/dmn-model/src/test/resources/org/camunda/bpm/model/dmn/Example-DMN-1.3.dmn
[![CAM-11187](https://badgen.net/badge/JIRA/CAM-11187/0052CC)](https://app.camunda.com/jira/browse/CAM-11187)
=> CAM-11187: Support DMN 1.3 namespace

engine-rest/engine-rest-openapi/README.md, engine-rest/engine-rest-openapi/pom.xml, engine-rest/engine-rest-openapi/src/test/java/org/camunda/bpm/engine/rest/openapi/client/DeploymentTest.java
[![CAM-11407](https://badgen.net/badge/JIRA/CAM-11407/0052CC)](https://app.camunda.com/jira/browse/CAM-11407)
=> fix(rest-openapi): fix the dateLibrary in the client generator config

engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelLogger.java, engine-plugins/spin-plugin/pom.xml, engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/impl/feel/integration/SpinValueMapperTest.java
[![CAM-11473](https://badgen.net/badge/JIRA/CAM-11473/0052CC)](https://app.camunda.com/jira/browse/CAM-11473)
* Update the Scala FEEL logger category to be consistent with the existing FEEL Engine category;
* Add a test case to assert that the correct logs are logged at the correct levels.
Related to CAM-11473
=> CAM-11473: chore(feel/spin): update scala feel logger category

engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelLogger.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/builder/CustomFunctionBuilder.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/builder/CustomFunctionBuilderImpl.java, engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/CustomFunctionTest.java
[![CAM-11490](https://badgen.net/badge/JIRA/CAM-11490/0052CC)](https://app.camunda.com/jira/browse/CAM-11490)
=> CAM-11490 In FEEL Scala, allow using varargs and explicit params together

distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunConfiguration.java
[![CAM-11510](https://badgen.net/badge/JIRA/CAM-11510/0052CC)](https://app.camunda.com/jira/browse/CAM-11510)
=> CAM-11510: Rename configuration class

distro/run/assembly/resources/start.bat, distro/run/assembly/resources/start.sh, distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunConfiguration.java, distro/run/distro/assembly.xml
[![CAM-11505](https://badgen.net/badge/JIRA/CAM-11505/0052CC)](https://app.camunda.com/jira/browse/CAM-11505)
=> CAM-11505: rename database dir to userlib

engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/VariableQueryParameterDto.ftl
[![CAM-11377](https://badgen.net/badge/JIRA/CAM-11377/0052CC)](https://app.camunda.com/jira/browse/CAM-11377)
=> chore(rest-openapi): extract text formatting function

distro/run/assembly/assembly.xml, distro/run/assembly/resources/default.yml, distro/run/assembly/resources/production.yml, distro/run/assembly/resources/start.bat, distro/run/assembly/resources/start.sh, distro/run/qa/pom.xml, distro/run/qa/src/test/java/org/camunda/bpm/run/qa/ProductionConfigurationIntegrationTest.java, distro/run/qa/src/test/java/org/camunda/bpm/run/qa/util/SpringBootManagedContainer.java, distro/run/qa/src/test/resources/ProductionConfigurationIntegrationTest_production.yml
[![CAM-11302](https://badgen.net/badge/JIRA/CAM-11302/0052CC)](https://app.camunda.com/jira/browse/CAM-11302)
=> CAM-11302: add support for two configuration yml files

distro/run/distro/assembly.xml, distro/run/distro/pom.xml, distro/run/qa/src/test/java/org/camunda/bpm/run/qa/SqlAvailabilityIntegrationTest.java
[![CAM-11481](https://badgen.net/badge/JIRA/CAM-11481/0052CC)](https://app.camunda.com/jira/browse/CAM-11481)
=> CAM-11481: include DDL SQL scripts in distro

distro/run/assembly/assembly.xml, distro/run/assembly/pom.xml
[![CAM-11449](https://badgen.net/badge/JIRA/CAM-11449/0052CC)](https://app.camunda.com/jira/browse/CAM-11449)
=> CAM-11449: include license and notice files in run distro

distro/run/assembly/resources/default.yml, distro/run/assembly/resources/production.yml, distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunAuthenticationProperties.java
[![CAM-11298](https://badgen.net/badge/JIRA/CAM-11298/0052CC)](https://app.camunda.com/jira/browse/CAM-11298)
=> CAM-11298: add default configuration for both configuration files in Camunda BPM Run

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractSetJobDefinitionStateCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractSetStateCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ProcessDefinitionManager.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ActivateJobDefinitionTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/SuspendJobDefinitionTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/suspensionstate/MultiTenancyJobDefinitionSuspensionStateTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/suspensionstate/MultiTenancyProcessDefinitionSuspensionStateTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/repository/ProcessDefinitionSuspensionTest.java
[![CAM-11183](https://badgen.net/badge/JIRA/CAM-11183/0052CC)](https://app.camunda.com/jira/browse/CAM-11183)
* add a `deploymentId` to the created timer jobs in order to let deployment-aware job executors only execute the associated jobs
related to CAM-11183
=> [CAM-11183] feat(engine): make scheduled state updates deployment-aware

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/MultiFormDeploymentDto.ftl
[![CAM-11654](https://badgen.net/badge/JIRA/CAM-11654/0052CC)](https://app.camunda.com/jira/browse/CAM-11654)
it's not about activity id. I copied the text from the docs at https://docs.camunda.org/manual/7.12/reference/rest/deployment/post-deployment/
=> CAM-11654: correct description for tenant-id

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/sort-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/commons/sort-props.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SchemaLogEntryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SchemaLogQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/schema/log/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/schema/log/post.ftl
[![CAM-11537](https://badgen.net/badge/JIRA/CAM-11537/0052CC)](https://app.camunda.com/jira/browse/CAM-11537)
Related to CAM-11537
=> CAM-11537: feat(open-api): add schema log endpoints

engine-rest/engine-rest-openapi/README.md
[![](https://badgen.net/badge/JIRA//0052CC)](https://app.camunda.com/jira/browse/)
=> chore(rest-openapi): add review hints to the read me

engine-rest/engine-rest-openapi/README.md
[![](https://badgen.net/badge/JIRA//0052CC)](https://app.camunda.com/jira/browse/)
=> chore(rest-openapi): add markdown formatting options

engine/src/main/java/org/camunda/bpm/engine/EntityTypes.java, engine/src/main/java/org/camunda/bpm/engine/authorization/HistoricTaskPermissions.java, engine/src/main/java/org/camunda/bpm/engine/authorization/Resources.java, engine/src/main/java/org/camunda/bpm/engine/impl/util/ResourceTypeUtil.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
[![CAM-11614](https://badgen.net/badge/JIRA/CAM-11614/0052CC)](https://app.camunda.com/jira/browse/CAM-11614)
related to CAM-11614
=> feat(engine): introduce historic task permissions

engine/src/main/java/org/camunda/bpm/engine/AuthorizationService.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AuthorizationCheckCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/EnableHistoricInstancePermissionsTest.java
[![CAM-11623](https://badgen.net/badge/JIRA/CAM-11623/0052CC)](https://app.camunda.com/jira/browse/CAM-11623)
related to CAM-11623
=> feat(engine): add config flag to enable historic instance permissions

engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SignalDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/signal/post.ftl
[![CAM-11530](https://badgen.net/badge/JIRA/CAM-11530/0052CC)](https://app.camunda.com/jira/browse/CAM-11530)
=> CAM-11530: add documentation for signal endpoint 

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/linkable-dto-props.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/LinkableDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/DeploymentDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/TriggerVariableValueDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/CommentDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/create/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/{commentId}/get.ftl
[![CAM-11550](https://badgen.net/badge/JIRA/CAM-11550/0052CC)](https://app.camunda.com/jira/browse/CAM-11550)
Related to CAM-11550
=> CAM-11550: feat(open-api): add task comment endpoints

distro/tomcat/assembly/src/conf/server.xml, parent/pom.xml, pom.xml, qa/tomcat-runtime/src/main/conf/server.xml
[![CAM-11578](https://badgen.net/badge/JIRA/CAM-11578/0052CC)](https://app.camunda.com/jira/browse/CAM-11578)
* Use tomcat 9.0.33 for tomcat distro
* Update server.xml to 9.0.33
* disable AJP connector for distro builds
* disable AJP secret for QA builds
* Use tomcat 9.0.31 for spring-boot-starter
=> CAM-11578: Bump tomcat version to > 9.0.30

engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/IdentityLinkDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/identity-links/delete/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/identity-links/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/identity-links/post.ftl
[![CAM-11552](https://badgen.net/badge/JIRA/CAM-11552/0052CC)](https://app.camunda.com/jira/browse/CAM-11552)
Related to CAM-11552
=> CAM-11552: feat(open-api): add task id-link endpoints

engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java, javaee/jobexecutor-ra/src/main/java/org/camunda/bpm/container/impl/threading/ra/inflow/JcaInflowExecuteJobsRunnable.java
[![CAM-11679](https://badgen.net/badge/JIRA/CAM-11679/0052CC)](https://app.camunda.com/jira/browse/CAM-11679)
=> CAM-11679: re-integrate hook method for job execution

engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelEngine.java, engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/CustomFunctionTest.java, engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/ExternalFunctionTest.java, engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/helper/FeelRule.java, pom.xml
[![CAM-11516](https://badgen.net/badge/JIRA/CAM-11516/0052CC)](https://app.camunda.com/jira/browse/CAM-11516)
related to CAM-11516
=> [CAM-11516] chore(deps): bump feel scala engine to 1.11.0

engine-rest/engine-rest-openapi/README.md, engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/LinkableDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/metrics/MetricsIntervalResultDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/metrics/MetricsResultDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/metrics/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/metrics/{metrics-name}/sum/get.ftl
[![CAM-11532](https://badgen.net/badge/JIRA/CAM-11532/0052CC)](https://app.camunda.com/jira/browse/CAM-11532)
=> CAM-11532: add documentation for metric endpoints

engine/src/main/java/org/camunda/bpm/engine/HistoryService.java, engine/src/main/java/org/camunda/bpm/engine/authorization/Permissions.java, engine/src/main/java/org/camunda/bpm/engine/authorization/TaskPermissions.java, engine/src/main/java/org/camunda/bpm/engine/impl/HistoricTaskInstanceReportImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/CommandChecker.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/auth/AuthorizationCommandChecker.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/multitenancy/TenantCommandChecker.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskReportManager.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
[![CAM-11624](https://badgen.net/badge/JIRA/CAM-11624/0052CC)](https://app.camunda.com/jira/browse/CAM-11624)
related to CAM-11624
=> fix(engine): remove redundant task instance report authorization checks

engine/src/main/java/org/camunda/bpm/engine/impl/db/AuthorizationCheck.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
[![CAM-11619](https://badgen.net/badge/JIRA/CAM-11619/0052CC)](https://app.camunda.com/jira/browse/CAM-11619)
⚠️ Needs to be rebased onto master after CAM-11614 & CAM-11623 was merged.
related to CAM-11619
=> feat(engine): historic task authorization is enforced for task query

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricVariableInstance.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricVariableInstanceAuthorizationTest.java
[![CAM-11620](https://badgen.net/badge/JIRA/CAM-11620/0052CC)](https://app.camunda.com/jira/browse/CAM-11620)
⚠️ Needs to be rebased onto master after CAM-11614, CAM-11623 & CAM-11619 was merged.
related to CAM-11620
=> feat(engine): historic task authorization is enforced for variable query

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDetail.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricDetailAuthorizationTest.java
[![CAM-11621](https://badgen.net/badge/JIRA/CAM-11621/0052CC)](https://app.camunda.com/jira/browse/CAM-11621)
⚠️ Needs to be rebased onto master after CAM-11614, CAM-11623 & CAM-11619 was merged.
related to CAM-11621
=> feat(engine): historic task authorization is enforced for detail query

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/auth/DefaultAuthorizationProvider.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
[![CAM-11615](https://badgen.net/badge/JIRA/CAM-11615/0052CC)](https://app.camunda.com/jira/browse/CAM-11615)
⚠️ Needs to be rebased once CAM-11614, CAM-11623 & CAM-11619 is on master.
related to CAM-11615
=> feat(engine): add granting of hist task read permission

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIdentityLinkLog.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricIdentityLinkLogAuthorizationTest.java
[![CAM-11627](https://badgen.net/badge/JIRA/CAM-11627/0052CC)](https://app.camunda.com/jira/browse/CAM-11627)
related to CAM-11627
=> feat(engine): historic task authorization is enforced for ident.link log

engine/src/main/java/org/camunda/bpm/engine/ProcessEngineConfiguration.java, engine/src/main/java/org/camunda/bpm/engine/authorization/HistoricTaskPermissions.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/auth/DefaultAuthorizationProvider.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/util/AuthManagerUtil.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/TaskReadVariablePermissionAuthorizationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricDetailAuthorizationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricVariableInstanceAuthorizationTest.java
[![CAM-11626](https://badgen.net/badge/JIRA/CAM-11626/0052CC)](https://app.camunda.com/jira/browse/CAM-11626)
related to CAM-11626
=> feat(engine): introduce READ_VARIABLE permission for historic tasks

engine/src/main/java/org/camunda/bpm/engine/HistoryService.java
[![CAM-11676](https://badgen.net/badge/JIRA/CAM-11676/0052CC)](https://app.camunda.com/jira/browse/CAM-11676)
related to CAM-11676
=> chore(engine): add javadocs to queries about hist. instance permissions

engine/src/main/java/org/camunda/bpm/engine/authorization/Authorization.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/auth/DefaultAuthorizationProvider.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricProcessInstanceManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/AbstractRemovalTimeTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/HistoricRootProcessInstanceTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyEndTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyStartTest.java
[![CAM-11646](https://badgen.net/badge/JIRA/CAM-11646/0052CC)](https://app.camunda.com/jira/browse/CAM-11646)
related to CAM-11646
=> feat(engine): set removal time to auth when identity link is added

engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricProcessInstanceManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupRemovalTimeTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerAuthorizationsTest.java
[![CAM-11661](https://badgen.net/badge/JIRA/CAM-11661/0052CC)](https://app.camunda.com/jira/browse/CAM-11661)
⚠️ Needs to be rebased onto master before merge.
related to CAM-11661
=> feat(engine): include deletion of authorizations in history cleanup

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SaveAuthorizationCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationEntity.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyEndTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyStartTest.java
[![CAM-11617](https://badgen.net/badge/JIRA/CAM-11617/0052CC)](https://app.camunda.com/jira/browse/CAM-11617)
⚠️ Needs to be rebased onto master before merge.
related to CAM-11617
=> feat(engine): set removal time to authorization on creation

engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/{varName}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/{varName}/data/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/{varName}/data/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/{varName}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/{varName}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/{varName}/put.ftl
[![CAM-11553](https://badgen.net/badge/JIRA/CAM-11553/0052CC)](https://app.camunda.com/jira/browse/CAM-11553)
Related to CAM-11553
=> CAM-11553: feat(rest): add openapi task variables endpoints

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricProcessInstanceManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeHierarchicalTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeNonHierarchicalTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/helper/BatchSetRemovalTimeRule.java
[![CAM-11618](https://badgen.net/badge/JIRA/CAM-11618/0052CC)](https://app.camunda.com/jira/browse/CAM-11618)
⚠️ Needs to be rebased onto master before merge.
related to CAM-11618
=> feat(engine): include authorization in set removal time batch operation

engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/{varName}/data/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/{varName}/data/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/{varName}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/{varName}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/{varName}/put.ftl
[![CAM-11554](https://badgen.net/badge/JIRA/CAM-11554/0052CC)](https://app.camunda.com/jira/browse/CAM-11554)
Related to CAM-11554
=> CAM-11554: feat(rest): add openapi task local variables endpoints

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/authorization/AuthorizationDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/AuthorizationRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/AuthorizationRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
[![CAM-11660](https://badgen.net/badge/JIRA/CAM-11660/0052CC)](https://app.camunda.com/jira/browse/CAM-11660)
related to CAM-11660
=> feat(rest): expose removal time & root process instance id for auth

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricTaskInstanceManager.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
[![CAM-11701](https://badgen.net/badge/JIRA/CAM-11701/0052CC)](https://app.camunda.com/jira/browse/CAM-11701)
related to CAM-11701
=> feat(engine): historic auth is removed when deleting hist task

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/deployment-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/DeploymentDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/DeploymentResourceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/DeploymentWithDefinitionsDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/RedeploymentDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/create/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/{id}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/{id}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/{id}/redeploy/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/{id}/resources/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/{id}/resources/{resourceId}/data/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/{id}/resources/{resourceId}/get.ftl, engine-rest/engine-rest-openapi/src/test/java/org/camunda/bpm/engine/rest/openapi/client/DeploymentTest.java
[![CAM-11535](https://badgen.net/badge/JIRA/CAM-11535/0052CC)](https://app.camunda.com/jira/browse/CAM-11535)
Related to CAM-11535
=> CAM-11535: feat(openapi): add deployment endpoints

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/JobQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
related to CAM-11713, CAM-11714
=> [CAM-11714] chore(rest): expose processInstanceIds for job query

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/repository/ProcessDefinitionQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessDefinitionRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/impl/ProcessDefinitionQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/ProcessDefinitionQueryProperty.java, engine/src/main/java/org/camunda/bpm/engine/impl/QueryOrderingProperty.java, engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java, engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DeploymentTableMapping.java, engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/MybatisJoinHelper.java, engine/src/main/java/org/camunda/bpm/engine/repository/ProcessDefinitionQuery.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/ProcessDefinition.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/repository/AbstractDefinitionQueryTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/repository/CaseDefinitionQueryTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/repository/ProcessDefinitionQueryTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/TestOrderingUtil.java
[![CAM-11689](https://badgen.net/badge/JIRA/CAM-11689/0052CC)](https://app.camunda.com/jira/browse/CAM-11689)
=> CAM-11689: Add filter and sort by deployment time options to ProcessDefinitionQuery

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/external-task-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExternalTaskQueryDto.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/ExternalTaskQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
=> [CAM-11712] feat(rest): expose externalTaskIdIn for external task query

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/repository/DecisionDefinitionQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/DecisionDefinitionRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/impl/dmn/entity/repository/DecisionDefinitionQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/dmn/entity/repository/DecisionDefinitionQueryProperty.java, engine/src/main/java/org/camunda/bpm/engine/repository/DecisionDefinitionQuery.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/DecisionDefinition.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/repository/DecisionDefinitionQueryTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/TestOrderingUtil.java
[![CAM-11690](https://badgen.net/badge/JIRA/CAM-11690/0052CC)](https://app.camunda.com/jira/browse/CAM-11690)
=> CAM-11690: Add filter and sort by deployment time options to DecisionDefinitionQuery

engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/retries-async/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/count/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/delete-historic-query-based/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/delete/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/job-retries-historic-query-based/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/job-retries/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/suspended-async/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/suspended/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/activity-instances/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/modification-async/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/modification/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/suspended/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/{varName}/data/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/{varName}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/{varName}/put.ftl
* fix BatchDto examples as well
Related to CAM-11597
=> chore(rest-openapi): add process instance examples

distro/wildfly/assembly/src/wildfly/standalone-full.xml, distro/wildfly/assembly/src/wildfly/standalone.xml, distro/wildfly/modules/src/main/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml, parent/pom.xml, qa/integration-tests-engine/pom.xml, qa/wildfly-runtime/src/main/common/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml, qa/wildfly-runtime/src/main/common/standalone/deployments/h2-ds.xml, qa/wildfly-runtime/src/main/common/standalone/deployments/h2-xa-ds.xml, qa/wildfly-runtime/src/main/common/standalone/deployments/postgresql-ds.xml, qa/wildfly-runtime/src/main/common/standalone/deployments/postgresql-xa-ds.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml, qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
Related to CAM-11456
:information_source: Note for the reviewer: In case the commits are squashed, please make sure to add a co-author label for @langfr .
=> CAM-11456: chore(distro): support wildfly 19

engine-rest/engine-rest-openapi/README.md
=> chore(openapi): update readme with changes

engine-rest/engine-rest-openapi/README.md, engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/CountResultDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SchemaLogEntryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SuspensionStateDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/metrics/MetricsIntervalResultDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/metrics/MetricsResultDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/CaseDefinitionDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/DecisionDefinitionDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/DecisionRequirementsDefinitionDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/DeploymentDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/ProcessDefinitionDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ExecutionDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/batch/BatchDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExtendLockOnExternalTaskDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExternalTaskFailureDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/modification/ProcessInstanceModificationInstructionDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/AttachmentDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/CommentDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskDto.ftl
to resolve issues in C# clients
Related to CAM-11767
=> improve(rest-openapi): add nullable field to int/long properties

engine/src/main/java/org/camunda/bpm/engine/impl/util/StringUtil.java, engine/src/test/java/org/camunda/bpm/engine/impl/util/StringUtilTest.java
=> fix(engine): convert null byte array to empty string and not throw NPE

distro/run/assembly/resources/production.yml
=> CAM-11738: consistently use dash styled properties for run config

spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/configuration/impl/DefaultJobConfiguration.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/configuration/impl/DefaultJobConfigurationTest.java
=> fix(spring-boot): use non-blocking rejected jobs handler

engine-rest/engine-rest-openapi-generator/src/main/java/org/camunda/bpm/engine/rest/openapi/generator/impl/TemplateParser.java
=> make available properties with null values in the examples
Related to CAM-11801
=> fix(openapi-generator): add null values serialization in gson formatting

distro/run/assembly/resources/README.txt, distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunRestConfiguration.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationEnabledAllowedOriginConfiguredTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationEnabledWildcardTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsWithChangedContextPathTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/https/HttpsConfigurationEnabledTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/identity/AuthenticationWithChangedContextPathTest.java, distro/run/core/src/test/resources/application-test-auth-enabled.yml, distro/run/core/src/test/resources/application-test-changed-rest-context-path.yml, distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/AutoDeploymentIT.java, distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/ComponentAvailabilityIT.java, distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/ProductionConfigurationIT.java, spring-boot-starter/starter-qa/integration-test-webapp/runtime/pom.xml, spring-boot-starter/starter-rest/src/main/java/org/camunda/bpm/spring/boot/starter/rest/CamundaJerseyResourceConfig.java, spring-boot-starter/starter-rest/src/test/java/my/own/custom/spring/boot/project/JerseyConfig.java, spring-boot-starter/starter-rest/src/test/java/org/camunda/bpm/spring/boot/starter/rest/CamundaBpmRestConfigurationIT.java, spring-boot-starter/starter-rest/src/test/java/org/camunda/bpm/spring/boot/starter/rest/SampleCamundaRestApplicationIT.java
=> chore(spring-boot/run): change context path of rest api

engine/src/main/java/org/camunda/bpm/engine/HistoryService.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/UserOperationLogEntry.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/UserOperationLogAuthorizationTest.java
=> Enforce Historic Task Authorizations for User Operation Log Query

engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/condition/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/topic-names/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/message/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/metrics/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/signal/post.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/ExternalTaskRestService.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ExternalTaskRestServiceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskTopicNamesRestServiceTest.java
I ran into an issue with squashing commits, and had to close the old pull request. I have since discovered the issue and it won't happen again.
=> CAM-11492 : topic-names-rest-api

engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/delegate/DmnDecisionEvaluationEvent.java, engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/DefaultDmnDecisionContext.java, engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/delegate/DmnDecisionEvaluationEventImpl.java, engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/metrics/DefaultEngineMetricCollector.java, engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/metrics/DmnEngineMetricCollectorWrapper.java, engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/spi/DmnEngineMetricCollector.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/metrics/dmn/MetricsDecisionEvaluationListener.java, engine/src/main/java/org/camunda/bpm/engine/impl/metrics/parser/MetricsBpmnParseListener.java, engine/src/main/java/org/camunda/bpm/engine/impl/metrics/parser/MetricsExecutionListener.java, engine/src/main/java/org/camunda/bpm/engine/management/Metrics.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/metrics/AbstractMetricsTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/metrics/ActivityInstanceCountMetricsTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/metrics/DecisionMetricsTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/metrics/JobExecutorMetricsTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/metrics/MetricsDisabledTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/metrics/MetricsTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/metrics/RootProcessInstanceMetricsTest.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/db/entitymanager/PurgeDatabaseTest.java
Related to CAM-11186
:information_source: The separate commits have been added for review purposes. They should be squashed before merging.
=> CAM-11186: add new pricing model metrics

settings/eclipse/formatter.xml
=> chore(settings): update line limit to 120

engine/pom.xml, engine/src/test/java/org/camunda/bpm/engine/test/standalone/jpa/BigIntegerIdJPAEntity.java, engine/src/test/resources/META-INF/persistence.xml, parent/pom.xml
=> CAM-11669: use latest OpenJPA 2.x patch level

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeployCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/api/repository/ProcessApplicationDeploymentTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/repository/RedeploymentTest.java, engine/src/test/java/org/camunda/bpm/engine/test/util/ProcessEngineTestRule.java
=> CAM-11750: fix existing deployments registration bug

engine-dmn/engine/pom.xml, engine-dmn/feel-scala/pom.xml, engine/pom.xml, parent/pom.xml
- gson in camunda-engine
- feel-scala and scala in camunda-engine-feel-scala
related to CAM-11323
=> CAM-11323: do not expose shaded libraries

engine/src/test/java/org/camunda/bpm/engine/test/api/repository/ProcessApplicationDeploymentTest.java
* Introduce a delay between Deployments in the new test so that their DEPLOY_TIME_ timestamps can be ordered properly in MySQL.
Related to CAM-11750
=> CAM-11750: fix(engine): ensure distinct deploy time timestamps

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/behavior/BpmnActivityBehavior.java
=> CAM-11778: chore(engine): fix typo in method argument

distro/tomcat/assembly/src/tomcat/setenv.bat, distro/tomcat/assembly/src/tomcat/setenv.sh
the property has been removed from Java 8
Related to CAM-11896
=> chore(distro): remove PermSize property

distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/ComponentAvailabilityIT.java, distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/webapps/AbstractWebIT.java, distro/run/qa/runtime/src/test/resources/testconfig.properties, spring-boot-starter/starter-qa/integration-test-webapp/runtime/pom.xml, spring-boot-starter/starter-webapp-core/pom.xml, spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappAutoConfiguration.java, spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappInitializer.java, spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/filter/ResourceLoadingSecurityFilter.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/apppath/ChangedAppPathTest.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/apppath/containerbasedauth/ChangedAppPathContainerBasedAuthTest.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/apppath/containerbasedauth/ContainerBasedAuthFilterRegistration.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/apppath/containerbasedauth/TestApplication.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/CsrfPreventionIT.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/CookieNameIT.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteCustomValueIT.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteDisabledIT.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteEnabledIT.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteOptionLaxIT.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteOptionStrictIT.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SecureDisabledIT.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SecureEnabledIT.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/util/HeaderRule.java, spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/property/WebappProperty.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/property/webapppath/WebAppPathPropertyDefaultTest.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/property/webapppath/WebAppPathPropertyEmptyTest.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/property/webapppath/WebAppPathPropertySanitizeTest.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/property/webapppath/WebAppPathPropertyTest.java
=> chore(spring-boot/webapp): change default application path to /camunda

engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.13_to_7.14.sql
=> chore(release): add 7.14 upgrade scripts

qa/test-db-instance-migration/pom.xml, qa/test-db-instance-migration/test-fixture-714/pom.xml, qa/test-db-instance-migration/test-fixture-714/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java, qa/test-db-instance-migration/test-fixture-714/src/main/resources/camunda.cfg.xml
=> chore(release): add camunda-qa-upgrade-test-fixture-714

database/pom.xml, qa/test-db-rolling-update/create-new-engine/pom.xml, qa/test-db-rolling-update/create-old-engine/pom.xml, qa/test-db-rolling-update/rolling-update-util/pom.xml, qa/test-db-rolling-update/test-old-engine/pom.xml, qa/test-db-upgrade/pom.xml, qa/test-old-engine/pom.xml
=> chore(release): update camunda.version.old prop

examples/invoice/src/main/resources/invoiceBusinessDecisions.dmn
=> CAM-11915: update invoice example DMN to 1.3 standard

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
=> chore(sql): add hint to consider auth checks in webapps as well

parent/pom.xml
=> chore(deps): update tomcat to 9.0.36

pom.xml
=> chore(deps): update spring boot to 2.2.8

engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/type/DateDataTypeTransformer.java
can we review and apply the PR?
=> CAM-11897 DMN date conversion issue in multithreading mode

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricActivityInstance.xml, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricActivityInstanceTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/history/calledProcessWaiting.bpmn20.xml
=> CAM-12030: update calledProcessInstanceID for historic activity instance

distro/jbossas7/webapp/src/main/webapp/WEB-INF/web.xml, distro/run/assembly/resources/production.yml, distro/tomcat/webapp/src/main/webapp/WEB-INF/web.xml, qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/HttpHeaderSecurityIT.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/headersec/it/HstsIT.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/headersec/it/properties/HttpHeaderSecurityAbsenceIT.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/headersec/it/properties/HttpHeaderSecurityPresenceIT.java, spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/property/HeaderSecurityProperties.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/property/headersec/HstsPropertiesTest.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/property/headersec/HttpHeaderSecurityDisabledTest.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/property/headersec/HttpHeaderSecurityEnabledTest.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/property/headersec/HttpHeaderSecurityValueTest.java
related to CAM-11602
**Note to reviewer**
* Due to the Webapp dependency, it doesn't make sense to assign PR based CI labels
* I run the following tests successfully on my local machine:
* Webapp Unit Tests
* Spring Boot CE & EE Unit & Integration Tests
* Camunda Run CE & EE Integration Tests
=> Spring Boot/Run/Webapp: Add support for HSTS header

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-activity-instance.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricActivityInstanceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricActivityInstanceQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/ProcessDefinitionSuspensionStateDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/activity-instance/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/activity-instance/count/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/activity-instance/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/activity-instance/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/activity-instance/{id}/get.ftl
=> feat(rest/open-api): add historic activity instance endpoints

engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/NewScalaFeelBehaviorTest.java
* Add test coverage for the bug fix in the feel-scala#90 issue.
Related to CAM-11382
:information_source: The branch is based on #851 and will need to be rebased after that one is merged (or merged directly into that branch)
=> CAM-11382: chore(dmn): add test coverage for feel-scala bugfix

engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/BreakingScalaFeelBehaviorTest.java, engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/NewScalaFeelBehaviorTest.java, pom.xml
* Add test coverage for the bug fix in the https://github.com/camunda/feel-scala/issues/110 issue.
Related to CAM-11304
=> CAM-11304: chore(dmn): bump feel scala and add test coverage

parent/pom.xml
=> chore(parent-pom): remove xercesImpl

engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/TelemetryConfigurationDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/telemetry/configuration/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/telemetry/post.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/TelemetryRestService.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/TelemetryConfigurationDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/AbstractProcessEngineRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/DefaultProcessEngineRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/NamedProcessEngineRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/TelemetryRestServiceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TelemetryRestServiceTest.java, engine/src/main/java/org/camunda/bpm/engine/ManagementService.java, engine/src/main/java/org/camunda/bpm/engine/impl/ManagementServiceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/TelemetryConfigureCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/ManagementAuthorizationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceTest.java
=> CAM-12024: configure telemetry via Java and Rest API

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java
=> feat(engine): add telemetry endpoint configuration property

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
=> chore(engine): update telemetry endpoint to production

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/security/auth/AuthenticationProvider.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/security/auth/AuthenticationResult.java
=> chore(docs): improve javadocs of AuthenticationProvider

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/incident-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/IncidentDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/incident/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/incident/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/incident/{id}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/incident/{id}/get.ftl
=> chore(openapi): add OpenAPI doc for /incident

engine/src/main/java/org/camunda/bpm/engine/ProcessEngineConfiguration.java, engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java, engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java, engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/PropertyManager.java, engine/src/main/java/org/camunda/bpm/engine/impl/test/TestHelper.java, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Property.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/cfg/InstallationCfgTest.java, engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentInstallationIdInitializationTest.java
=> feat(engine): add installation id on engine start

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/TelemetryRestServiceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TelemetryRestServiceTest.java, engine/src/main/java/org/camunda/bpm/engine/ManagementService.java, engine/src/main/java/org/camunda/bpm/engine/impl/ManagementServiceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/IsTelemetryEnabledCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryLogger.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/ManagementAuthorizationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentTelemetryConfigurationTest.java
* add API to fetch the configuration from the db
* switch to `toggleTelemetry` name for setting the config
Related to CAM-12078
=> feat(engine): expand telemetry API in management service

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/FetchExternalTaskTopicDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/fetchAndLock/post.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/FetchExternalTasksDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/LockedExternalTaskDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/externaltask/ExternalTask.java, engine/src/main/java/org/camunda/bpm/engine/externaltask/ExternalTaskQueryTopicBuilder.java, engine/src/main/java/org/camunda/bpm/engine/externaltask/LockedExternalTask.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/helper/BpmnProperties.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParseUtil.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/FetchExternalTasksCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/externaltask/ExternalTaskQueryTopicBuilderImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/externaltask/LockedExternalTaskImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/externaltask/TopicFetchInstruction.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExternalTaskEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/external/ExternalTaskParseTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.testFetchAndLockWithExtensionProperties.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.testFetchAndLockWithoutExtensionProperties.bpmn20.xml
=> Add support for custom extension properties in external tasks

engine/pom.xml
=> fix(engine): fix httpclient shading

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/IdentityRestService.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/identity/PasswordPolicyRequestDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/IdentityRestServiceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/PasswordPolicyServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/IdentityService.java, engine/src/main/java/org/camunda/bpm/engine/identity/PasswordPolicyRule.java, engine/src/main/java/org/camunda/bpm/engine/impl/IdentityServiceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CreateGroupCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CreateTenantCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CreateUserCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SaveUserCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/identity/DefaultPasswordPolicyImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/identity/PasswordPolicyUserDataRuleImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/UserEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/api/identity/CustomPasswordPolicyTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/identity/IdentityServiceTenantTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/identity/IdentityServiceTest.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/identity/DefaultPasswordPolicyTest.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/identity/PasswordPolicyUserDataTest.java
=> Engine: Add user data rule to password policy 

engine/src/main/java/org/camunda/bpm/engine/impl/util/xml/Parse.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.java
=> chore(engine): configure model parser more strict regarding xxe

engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml
=> fix(mysql): improve update removal time query for MySQL

engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/get.ftl
=> fix(openapi): add missing process instance endpoint

pom.xml, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/CsrfPreventionIT.java
=> [CAM-11919] chore(platform): bump SpringBoot to 2.3

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricProcessInstanceManager.java, qa/large-data-tests/pom.xml, qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/DeleteDeploymentCascadeTest.java, qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/OptimizeApiPageSizeTest.java, qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/util/DmnHelper.java, qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/util/EngineDataGenerator.java
=> chore(fix): partition delete historicProcessInstances when > 2000

engine/src/main/java/org/camunda/bpm/engine/impl/optimize/OptimizeManager.java
=> chore(fix): partition historicProcessInstances input/output lookup

engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentHistoryCleanupUpdateOfFailingJobTest.java
=> chore(test): make sure t2 finishes after t1

engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/type/DmnDataTypeTransformerTest.java, engine-dmn/pom.xml
Related to https://jira.camunda.com/browse/CAM-12139
=> chore(engine-dmn/test): Fix test DmnDataTypeTransformerTest.shouldTransformZonedDateTime.

database/pom.xml
=> chore(pom): bump dependency of SQL Server to 8.2.2

qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/LoginIT.java, qa/integration-tests-webapps/pom.xml
=> fix(qa/webapps): download chrome driver version on-the-fly

qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/DeleteDeploymentCascadeTest.java, qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/OptimizeApiPageSizeTest.java, qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/util/EngineDataGenerator.java
=> fix(large-data): only cleanup DeleteDeploymentCascadeTest data

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/util/ParseUtil.java, engine/src/main/java/org/camunda/bpm/engine/impl/util/ProcessEngineDetails.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/ProcessEngineDetailsTest.java
=> fix(engine): fix telemetry data to respect enterprise aplha versions

spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/util/SpringBootProcessEngineLogger.java
=> fix(spring-boot): change enterLicenseKey logger to take string argument

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
Issue: https://jira.camunda.com/browse/CAM-12179
=> [CAM-12179] fix(engine): add access to bpmnParseFactory in engine configuration

CONTRIBUTING.md, README.md, TESTING.md
- in preparation for hacktoberfest
related to CAM-12288
=> CAM-12288: revamp our contribution guidelines

engine/src/main/java/org/camunda/bpm/engine/RuntimeService.java, engine/src/main/java/org/camunda/bpm/engine/authorization/BatchPermissions.java, engine/src/main/java/org/camunda/bpm/engine/batch/Batch.java, engine/src/main/java/org/camunda/bpm/engine/history/UserOperationLogEntry.java, engine/src/main/java/org/camunda/bpm/engine/impl/RuntimeServiceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/batch/AbstractBatchJobHandler.java, engine/src/main/java/org/camunda/bpm/engine/impl/batch/BatchConfiguration.java, engine/src/main/java/org/camunda/bpm/engine/impl/batch/BatchEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/batch/variables/BatchSetVariablesHandler.java, engine/src/main/java/org/camunda/bpm/engine/impl/batch/variables/SetVariablesJsonConverter.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CommandLogger.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/batch/variables/SetVariablesToProcessInstancesBatchCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/core/variable/VariableUtil.java, engine/src/main/java/org/camunda/bpm/engine/impl/core/variable/scope/AbstractVariableScope.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/VariableInstanceEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/VariableInstanceManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/batch/creation/SetVariablesBatchAuthorizationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/helper/BatchSetRemovalTimeRule.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/SetVariablesBatchTest.java, engine/src/test/java/org/camunda/bpm/engine/test/dmn/businessruletask/TestPojo.java, engine/src/test/java/org/camunda/bpm/engine/test/util/BatchRule.java
=> feat(engine): add batch operation to set variables

engine/src/main/java/org/camunda/bpm/engine/history/UserOperationLogEntry.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/batch/variables/SetVariablesToProcessInstancesBatchCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/SetVariablesBatchTest.java
=> fix(engine): correct log of set variables operation

NOTICE, distro/license/NOTICE
=> CAM-12026: include quartz in notice file

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/batch/SetVariablesAsyncDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/variables-async/post.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/ProcessInstanceRestService.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/batch/SetVariablesAsyncDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ProcessInstanceRestServiceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java
=> feat(rest): add batch operation to set variables

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/JtaProcessEngineConfiguration.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/StandaloneProcessEngineConfiguration.java, engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandCounterInterceptor.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/CommandCounter.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Command.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryDataTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryRegistryCounterTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
=> chore(engine): add command counter

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ConfigurationLogger.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/history/DefaultHistoryRemovalTimeProvider.java, engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java, engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupRemovalTimeTest.java
=> feat(engine): add configurable cleanup of historyCleanupJob logs

distro/wildfly/assembly/src/wildfly/standalone-full.xml, distro/wildfly/assembly/src/wildfly/standalone.xml, distro/wildfly/subsystem/pom.xml, parent/pom.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml, qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
=> [CAM-11457] feat(env): add support for WildFly 20

engine-rest/engine-rest-openapi/src/main/templates/paths/telemetry/configuration/get.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/TelemetryRestService.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/TelemetryConfigurationDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/TelemetryRestServiceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TelemetryRestServiceTest.java
=> chore(engine-rest): expose telemetry configuration fetch

engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/TelemetryConfigureCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Metric.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/telemetry/TelemetryTaskWorkerMetricsTest.java, engine/src/test/resources/logback-test.xml
=> chore(engine): expand telemetry data with metrics

engine/pom.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
* exclude in memory test from table prefix profile
Related to CAM-12378
=> fix(test): fix setting time in telemetry metric tests

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/optimize/OptimizeRestService.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/optimize/OptimizeCompletedHistoricIncidentRestServiceTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/optimize/OptimizeOpenHistoricIncidentRestServiceTest.java, engine/src/main/java/org/camunda/bpm/engine/impl/OptimizeService.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/optimize/OptimizeCompletedHistoricIncidentsQueryCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/optimize/OptimizeOpenHistoricIncidentsQueryCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/optimize/OptimizeManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/optimize/OptimizeServiceAuthorizationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/optimize/GetCompletedHistoricIncidentsForOptimizeTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/optimize/GetCompletedHistoricProcessInstancesForOptimizeTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/optimize/GetOpenHistoricIncidentsForOptimizeTest.java
=> [CAM-12382] chore(optimize): add new historic incident endpoint

engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringTransactionsProcessEngineConfiguration.java
to collect command counts for telemetry
Related to CAM-12413
=> chore(spring): add command counter interceptor to spring setup

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/TelemetryConfigureCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
by setting the property via set property command
Related to CAM-12089
=> chore(engine): add user operation log when configuring telemetry

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricTaskInstanceManager.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
=> chore(engine): improve unique task worker count calculation

engine/src/main/java/org/camunda/bpm/engine/impl/batch/variables/BatchSetVariablesHandler.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/VariableInstanceEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/util/TypedValueField.java
=> fix(engine): skip variable update listeners for batch operation

engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/telemetry/TelemetryTaskWorkerMetricsTest.java
=> fix(tests): remove incorrect response body from telemetry stubs

engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/telemetry/TelemetryTaskWorkerMetricsTest.java
=> chore(engine): make telemetry metric fields consistent to database

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Jdk.java, engine/src/main/java/org/camunda/bpm/engine/impl/util/ParseUtil.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
=> chore(engine): extend telemetry data with jdk info

engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/db/AuthorizationCheck.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Statistics.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml, engine/src/test/java/org/camunda/bpm/engine/test/cmmn/CmmnDisabledTest.java, engine/src/test/java/org/camunda/bpm/engine/test/util/ProcessEngineTestRule.java
=> CAM-12408: avoid cmmn complexity in task query

distro/run/assembly/resources/production.yml
=> chore(distro/run): add csp to production.yaml

engine/src/main/java/org/camunda/bpm/engine/impl/TablePageQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java, engine/src/main/java/org/camunda/bpm/engine/impl/db/entitymanager/DbEntityManager.java, engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/BatchDbSqlSession.java, engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSession.java, engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/SimpleDbSqlSession.java, engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandInvocationContext.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/IdentityInfoManager.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TableDataManager.java, engine/src/main/java/org/camunda/bpm/engine/impl/util/ExceptionUtil.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/IdentityInfo.xml, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/TableData.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/cfg/PersistenceExceptionTest.java, engine/src/test/java/org/camunda/bpm/engine/test/persistence/SuppressSqlExceptionsTest.java
=> fix(engine): suppress sql exceptions

internal-dependencies/pom.xml, qa/integration-tests-engine/pom.xml, qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/telemetry/TelemetryConnectPluginTest.java, qa/integration-tests-engine/src/test/resources-tomcat/org/camunda/bpm/integrationtest/telemetry/processes-connectPlugin.xml, qa/integration-tests-engine/src/test/resources-wildfly/org/camunda/bpm/integrationtest/telemetry/processes-connectPlugin.xml
when connect plugin is included
Related to CAM-12285
=> test(telemetry): add telemetry IT to ensure reporting works

engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
=> CAM-12471: chore(telemetry): ensure EDE and EDI metrics are passed in telemetry

distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/webapps/LoginIT.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/LoginIT.java
=> test(webapp-it): close telemetry modal dialog

engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/feel/context_function.dmn, pom.xml
=> CAM-12469: chore(dmn): bump feel scala engine version

engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandContext.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/AuthorizationLoggingTest.java
=> fix(engine): log authorization exceptions on detail log level

engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
=> CAM-12492: fix(telemetry): resolve static camunda integration in telemetry data

qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/telemetry/TelemetryConnectPluginTest.java
=> fix(qa): fix tear down in telemetry IT

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.11_patch_7.11.18_to_7.11.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.12_patch_7.12.11_to_7.12.12.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.13_patch_7.13.5_to_7.13.6.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.11_patch_7.11.18_to_7.11.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.12_patch_7.12.11_to_7.12.12.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.13_patch_7.13.5_to_7.13.6.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.11_patch_7.11.18_to_7.11.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.12_patch_7.12.11_to_7.12.12.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.13_patch_7.13.5_to_7.13.6.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.11_patch_7.11.18_to_7.11.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.12_patch_7.12.11_to_7.12.12.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.13_patch_7.13.5_to_7.13.6.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.11_patch_7.11.18_to_7.11.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.12_patch_7.12.11_to_7.12.12.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.13_patch_7.13.5_to_7.13.6.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.11_patch_7.11.18_to_7.11.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.12_patch_7.12.11_to_7.12.12.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.13_patch_7.13.5_to_7.13.6.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.13_to_7.14.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.11_patch_7.11.18_to_7.11.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.12_patch_7.12.11_to_7.12.12.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.13_patch_7.13.5_to_7.13.6.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.13_to_7.14.sql
=> CAM-12049: chore(db): prepare db upgrade scripts for backport

distro/license-book/src/main/resources/license-book.txt
=> CAM-12451: update license book for 7.14.0

engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/CamundaIntegration.java
=> CAM-12522: fix(engine): fix typo in integration fields for telemetry

database/pom.xml, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.cockroachdb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/cockroachdb_engine_7.14_to_7.15.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.14_to_7.15.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.14_to_7.15.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.14_to_7.15.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.14_to_7.15.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.14_to_7.15.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.14_to_7.15.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.14_to_7.15.sql, qa/test-db-instance-migration/pom.xml, qa/test-db-instance-migration/test-fixture-715/pom.xml, qa/test-db-instance-migration/test-fixture-715/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java, qa/test-db-instance-migration/test-fixture-715/src/main/resources/camunda.cfg.xml, qa/test-db-rolling-update/create-new-engine/pom.xml, qa/test-db-rolling-update/create-old-engine/pom.xml, qa/test-db-rolling-update/rolling-update-util/pom.xml, qa/test-db-rolling-update/test-old-engine/pom.xml, qa/test-db-upgrade/pom.xml, qa/test-old-engine/config/camunda.cfg.xml, qa/test-old-engine/pom.xml
=> Prepare 7.15

engine-plugins/identity-ldap/src/test/java/org/camunda/bpm/identity/impl/ldap/ProcessDefinitionQueryWithCustomIdentityProviderTest.java, engine-plugins/identity-ldap/src/test/resources/org/camunda/bpm/identity/impl/ldap/ProcessDefinitionQueryWithCustomIdentityProviderTest.bpmn20.xml, engine/src/main/java/org/camunda/bpm/engine/impl/ProcessDefinitionQueryImpl.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/ProcessDefinition.xml
=> fix(engine): resolve candidate groups outside of SQL

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/json/JsonTaskQueryConverter.java, engine/src/main/java/org/camunda/bpm/engine/task/TaskQuery.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/MultiTenancyFilterServiceTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/MultiTenancySignalReceiveTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/query/MultiTenancyTaskQueryTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyMessageCorrelationCmdTenantCheckTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyMessageEventReceivedCmdTenantCheckTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancySignalReceiveCmdTenantCheckTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryOrTest.java
=> CAM-12559: fix(engine): enable or queries for tenant id filtering

engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryMultipleEnginesTest.java
=> CAM-12576: chore(tests): improve telemetry test to be process engine configuration

README.md
for accessing the repos license and forum at the first glance
just click the badge and get to the camunda forum or repository licence
=> chore: added badges for quick naigation

distro/run/core/src/test/resources/application.yml, distro/run/qa/integration-tests/src/test/resources/base-test-application.yml, spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-all/src/test/resources/application.properties, spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-json-jackson/src/test/resources/application.properties, spring-boot-starter/starter-qa/integration-test-simple/src/test/resources/application.properties, spring-boot-starter/starter-qa/integration-test-webapp/invoice-example/src/main/resources/application.yaml, spring-boot-starter/starter-qa/integration-test-webapp/runtime/src/test/resources/application.properties, spring-boot-starter/starter-rest/src/test/resources/application.properties, spring-boot-starter/starter-webapp-core/src/test/resources/application.properties, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/TelemetryNonPaIT.java, spring-boot-starter/starter/src/test/resources/application.properties
=> CAM-12512: chore(starter): disable telemetry reporter

spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/configuration/impl/DefaultDatasourceConfiguration.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/configuration/impl/DefaultDatasourceConfigurationTest.java
=> [CAM-11923] feat(engine): use dedicated camundaBpmTransactionManager bean if declared

README.md
Added Project licence info in Readme to get information about the projects licence at first glance
related to CAM-12579
=> [CAM-12579] chore: add repo licence link 

engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java
=> CAM-12601: chore(engine): adjust duplicated code in persistence logger

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java
=> [CAM-12583] fix(rest): return 'assigned' attribute of task filter

distro/jbossas7/modules/pom.xml, distro/jbossas7/modules/src/main/modules/org/camunda/bpm/camunda-engine-plugin-spin/main/module.xml, distro/jbossas7/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-feel-scala/main/module.xml, distro/jbossas7/modules/src/main/modules/org/camunda/feel/feel-engine/main/module.xml, distro/tomcat/assembly/assembly.xml, distro/wildfly/modules/pom.xml, distro/wildfly/modules/src/main/modules/org/camunda/bpm/camunda-engine-plugin-spin/main/module.xml, distro/wildfly/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-feel-scala/main/module.xml, distro/wildfly/modules/src/main/modules/org/camunda/feel/feel-engine/main/module.xml, engine-dmn/engine/pom.xml, engine-dmn/feel-scala/pom.xml, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ContextVariableWrapper.java, engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelEngine.java, engine-dmn/pom.xml, engine/pom.xml, pom.xml
=> fix(dmn): add shaded feel engine dependency

engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/get.ftl
=> CAM-12391: fix(rest-openapi): fix variables query parameter

engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSession.java
=> CAM-12131: fix(engine): pg jdbc api change adjustments

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/converter/DateConverter.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/converter/DateConverterTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/dto/converter/DateConverterTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricTaskInstanceRestServiceQueryTest.java
=> fix(engine-rest): return invalid request for double quoted date value

internal-dependencies/pom.xml
=> CAM-12503: chore(rest): bump commons-fileupload version

qa/test-db-upgrade/config/org/camunda/bpm/engine/test/concurrency/historycleanup.camunda.cfg.xml, qa/test-db-upgrade/pom.xml, qa/test-old-engine/config/org/camunda/bpm/engine/test/concurrency/historycleanup.camunda.cfg.xml, qa/test-old-engine/pom.xml
=> CAM-12612: fix qa for CockroachDB

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/util/WebApplicationUtil.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
=> chore(telemetry): add webapps to telemetry data

qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/telemetry/TelemetryConnectPluginTest.java
=> test(telemetry): add webapp data to telemetry test

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/batch.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SuspensionStateDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/batch/BatchDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/batch/BatchStatisticsDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceSuspensionStateAsyncDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceSuspensionStateDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/batch/BatchDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/batch/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/batch/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/batch/statistics/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/batch/statistics/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/batch/{id}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/batch/{id}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/batch/{id}/suspended/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/get.ftl
=> CAM-11528: feat(openapi): add OpenAPI doc for batch endpoints

distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/webapps/LoginIT.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/LoginIT.java
=> test(qa/run/webapps): make LoginIT more robust

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/ExternalTask.xml
=> fix(engine): replace like with equal operator in fetch and lock query

engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/bpmnError/post.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/impl/TaskResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/TaskService.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/HandleTaskBpmnErrorCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskServiceTest.java
=> fix(engine): meaningful error message for missing errorCode

qa/test-db-instance-migration/pom.xml, qa/test-db-instance-migration/test-fixture-710/pom.xml, qa/test-db-instance-migration/test-fixture-711/pom.xml, qa/test-db-instance-migration/test-fixture-712/pom.xml, qa/test-db-instance-migration/test-fixture-713/pom.xml, qa/test-db-instance-migration/test-fixture-714/pom.xml, qa/test-db-instance-migration/test-fixture-714/src/main/resources/camunda.cfg.xml, qa/test-db-instance-migration/test-fixture-715/pom.xml, qa/test-db-instance-migration/test-fixture-72/pom.xml, qa/test-db-instance-migration/test-fixture-73/pom.xml, qa/test-db-instance-migration/test-fixture-74/pom.xml, qa/test-db-instance-migration/test-fixture-75/pom.xml, qa/test-db-instance-migration/test-fixture-76/pom.xml, qa/test-db-instance-migration/test-fixture-77/pom.xml, qa/test-db-instance-migration/test-fixture-78/pom.xml, qa/test-db-instance-migration/test-fixture-79/pom.xml, qa/test-db-instance-migration/test-migration/pom.xml, qa/test-db-instance-migration/test-migration/src/test/java/org/camunda/bpm/qa/upgrade/authorization/AuthorizationTest.java
=> CAM-12644: fix(qa): adjust instance-migration tests for crdb

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/decision-definition.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/dmn/EvaluateDecisionDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/DecisionDefinitionDiagramDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/key/{key}/diagram/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/key/{key}/evaluate/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/key/{key}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/key/{key}/history-time-to-live/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/key/{key}/tenant-id/{tenant-id}/diagram/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/key/{key}/tenant-id/{tenant-id}/evaluate/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/key/{key}/tenant-id/{tenant-id}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/key/{key}/tenant-id/{tenant-id}/history-time-to-live/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/key/{key}/tenant-id/{tenant-id}/xml/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/key/{key}/xml/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/{id}/diagram/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/{id}/evaluate/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/{id}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/{id}/history-time-to-live/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/{id}/xml/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/key/{key}/form-variables/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/key/{key}/tenant-id/{tenant-id}/form-variables/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/{id}/form-variables/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/complete/post.ftl
=> CAM-11533: feat(openapi): add doc for decision definitions

CONTRIBUTING.md, webapps/README.md
=> chore(CONTRIBUTING): add paragraph about how to skip building the webapps

pom.xml
=> chore(pom): bump mybatis from 3.5.3 to 3.5.6

webapps/pom.xml
=> fix(webapps): skip deploy zip frontend sources to maven central

webapps/ui/cockpit/src/App.js, webapps/ui/cockpit/src/components/ProcessInstance/HOC/withProcessInstance.js, webapps/ui/cockpit/src/modules/components/processInstance/CancelProcessInstance/CancelProcessInstance.js, webapps/ui/cockpit/src/plugins/cockpit.processInstance.runtime.action/CancelProcessInstance.js
=> chore(cockpit): add process instance provider

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/TenantIdProviderTest.java
=> fix(engine): make form properties available to custom TenantIdProvider

engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstantiationAtActivitiesHistoryTest.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.shouldEvaluateExpressionStartTimerEventInEventSubprocess.bpmn20.xml
=> fix(engine): initialize variables before starting process

engine-rest/engine-rest/pom.xml, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricDecisionInstanceRestServiceInteractionTest.java, internal-dependencies/pom.xml
=> chore(dependency): bump commons-io to 2.8

webapps/ui/welcome/client/scripts/directives/user-profile.js
=> fix(welcome): use userId in count request

webapps/ui/admin/client/scripts/pages/groupEdit.html, webapps/ui/admin/client/scripts/pages/groupEdit.js, webapps/ui/admin/client/scripts/pages/tenantEdit.html, webapps/ui/admin/client/scripts/pages/tenantEdit.js
=> fix(groups): fix user table when using LDAP

Jenkinsfile
=> chore(ci): fix maven local repo config

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ExecuteJobsCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/context/Context.java, engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ProcessDataContext.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobHelper.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/JobEntityTest.java, engine/src/test/java/org/camunda/bpm/engine/test/logging/ProcessDataLoggingContextTest.java
=> CAM-12772: Restore activity id MDC after nested command returns

Jenkinsfile
=> chore(ce-pipeline): adjust archiveArtifacts for ee pipe

.ci/daily/Jenkinsfile, Jenkinsfile
* Trigger the Daily pipeline from the CE pipeline;
* Transfer CE-built artifacts to the Daily pipeline (when triggered by CE);
* Stash CE-built artifacts and use only those in the Daily pipeline stages (when triggered by CE).
Related to CAM-12798
=> CAM-12798: Trigger Daily pipeline from CE and transfer artifacts

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/group-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/GroupDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/GroupQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/count/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/create/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/{id}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/{id}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/{id}/members/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/{id}/members/{userId}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/{id}/members/{userId}/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/{id}/members/{userId}/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/{id}/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/group/{id}/put.ftl
=> feat(open-api): add group endpoints

.ci/daily/Jenkinsfile, Jenkinsfile
* introduce EE_BRANCH_NAME param
* disable maven artifact upload
* switch to $WORSPACE instead of $pwd
* rename stash-distro to stash-archives
* use -f pom instead of changing dir
CAM-12788
=> CAM-12788: chore(ce-pipeline): trigger correct branch in ee

.ci/daily/Jenkinsfile, Jenkinsfile
* Add stages for Engine/Engine Authorizations DB Unit tests;
* Add stages for Webapp/Webapp Authorizations DB Unit tests;
* Add missing stages in the second parallelization block;
Related to CAM-12752
=> CAM-12752: add DB matrix stages

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/tenant-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/TenantDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/create/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/group-members/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/group-members/{groupId}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/group-members/{groupId}/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/user-members/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/user-members/{userId}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/user-members/{userId}/put.ftl
=> feat(openapi):  add tenant endpoints

.ci/daily/Jenkinsfile, Jenkinsfile
* execute when condition before agent
* add 'no-build' label logic
* pass PR_LABELS param to dowstream builds as json string
* trigger daily only when specific pr labels are applied
* add publish step for master
Related to CAM-12793
=> CAM-12793: chore(pipelines): resolve pr labels

.ci/daily/Jenkinsfile, Jenkinsfile
Related to CAM-12712, CAM-12751
=> CAM-12751: handle pipeline stage errors

.ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-12819: feat(side-pipe): add slow pipeline with crdb

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-12850: Pipeline default branch lib

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> chore(ci): extract publishTestResult in shared library

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
Related to CAM-12713, CAM-12867
=> CAM-12867: feat(ci): extract db methods to shared lib

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricActivityInstanceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceDto.ftl
=> fix(openapi): int32 durationInMills too small

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-12713: chore(ci): update pipeline names

.ci/daily/Jenkinsfile, Jenkinsfile
=> CAM-12865: extract error handling methods

distro/run/assembly/resources/production.yml
logging.file has been renamed to logging.file.name -> https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes
=> CAM-12679: fix Camunda BPM Run logging properties

model-api/xml-model/src/main/java/org/camunda/bpm/model/xml/impl/type/attribute/DoubleAttributeBuilder.java
In this commit we just remove extra parentheses from code.
=> style(DoubleAttributeBuilder): remove unnecessary parentheses

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-12851: extract agent methods

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-12866: extract mvn methods to shared lib

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-12855: chore(ci): extract withLabels

engine/src/main/java/org/camunda/bpm/engine/impl/JobQueryImpl.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/JobQueryTest.java
=> fix(engine): correct excluding condition in job query

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParseUtil.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.testParseEmptyExtensionProperty.bpmn
=> fix(parse): parse empty extension properties

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-12862: chore(ci): extract stash/unstash methods

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-12863: Pipeline extract artifact logic

webapps/ui/cockpit/src/legacy/client/scripts/pages/processes.less
=> fix(audit-log): widen timestamp cells

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
Related to CAM-12713, CAM-12861
=> CAM-12861: extract runMaven method

Jenkinsfile
=> CAM-12892: extract ee update

Jenkinsfile
=> CAM-12864: chore(ci): use cambpmRunMaven method in Assembly

model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/instance/dc/FontImpl.java, model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/instance/dc/Font.java
Reverts camunda/camunda-bpm-platform#1196
=> Revert "refactor(Font): rename method in camelCase style"

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile
* Ensure the correct stages are executed depending on the type of the pipeline build: STANDALONE (DAILY), DOWNSTREAM-MASTER, or DOWNSTREAM-PR.
Related to CAM-12713, CAM-12877
=> CAM-12877: feat(ci): adjust sidetrack pipeline

Jenkinsfile
Related to CAM-12778, CAM-12905
=> CAM-12905: chore(ci): add all rest stages

Jenkinsfile
Related to CAM-12778, CAM-12906
=> CAM-12906: chore(ci): add all webapp-it stages

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
Related to CAM-12713, CAM-12896
=> CAM-12896: reduce pipeline size

engine/src/main/java/org/camunda/bpm/engine/impl/calendar/DurationHelper.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/calendar/DurationHelperTest.java
=> fix(engine): fix parsing of weeks >3 of ISO8601 durations

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-12899: Pipeline imp mvn

webapps/ui/tasklist/client/scripts/filter/modals/cam-tasklist-filter-modal.html, webapps/ui/tasklist/client/scripts/filter/modals/cam-tasklist-filter-modal.js, webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task-meta.html, webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task-meta.js, webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task-meta.less, webapps/ui/tasklist/plugins/standaloneTask/app/navbar/action/modals/cam-tasklist-create-task-modal.html, webapps/ui/tasklist/plugins/standaloneTask/app/navbar/action/modals/cam-tasklist-create-task-modal.js
=> feat(buttons): disable buttons when submit is pending

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/deserialize-values-parameter.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/commons/variable-instance-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/VariableInstanceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/VariableInstanceQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/count/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/{id}/data/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/{id}/get.ftl
=> feat(openapi): add variable instance endpoint

distro/jbossas7/modules/src/main/modules/commons-codec/commons-codec/main/module.xml, distro/jbossas7/modules/src/main/modules/org/apache/httpcomponents/httpclient/main/module.xml, distro/jbossas7/modules/src/main/modules/org/apache/httpcomponents/httpcore/main/module.xml, distro/wildfly/modules/src/main/modules/commons-codec/commons-codec/main/module.xml, distro/wildfly/modules/src/main/modules/org/apache/httpcomponents/httpclient/main/module.xml, distro/wildfly/modules/src/main/modules/org/apache/httpcomponents/httpcore/main/module.xml, pom.xml
=> CAM-12956: bump connect to 1.5.2

Jenkinsfile
=> chore(ci): add history level jobs

engine/src/main/java/org/camunda/bpm/engine/impl/incident/IncidentHandler.java, engine/src/main/java/org/camunda/bpm/engine/impl/incident/IncidentHandling.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExternalTaskEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/IncidentEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/CreateAndResolveIncidentTest.java
- also fixes that the incident handler is called for custom incident
types
related to CAM-12744
=> CAM-12744: call incident handler on deletion of non-job incidents

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-12757: chore(ci): add custom retry to steps

engine-dmn/engine/pom.xml, engine-dmn/feel-api/pom.xml, engine-dmn/feel-juel/pom.xml, engine-dmn/feel-scala/pom.xml, engine-dmn/pom.xml, engine/pom.xml, model-api/bpmn-model/pom.xml, model-api/cmmn-model/pom.xml, model-api/dmn-model/pom.xml, model-api/xml-model/pom.xml, parent/pom.xml, typed-values/pom.xml
* Define proper camunda artifact name in sub module
Related to CAM-12911
=> [CAM-12911] chore(model-api): fix OSGi metadata

webapps/camunda-commons-ui/lib/pages/index.js, webapps/camunda-commons-ui/lib/widgets/header/cam-widget-header.js, webapps/ui/admin/client/scripts/config.js, webapps/ui/admin/client/scripts/index.html, webapps/ui/cockpit/client/scripts/config.js, webapps/ui/cockpit/client/scripts/index.html, webapps/ui/tasklist/client/index.html, webapps/ui/welcome/client/scripts/index.html
=> feat(webapps): allow modification of App Name

Jenkinsfile
=> revert(ci): revert no-build label name

Jenkinsfile
=> CAM-12983: feat(ci): add e2e pr label support

webapps/ui/common/styles/directives/notifications-panel.less
=> feat(deployment): line-breaks in notifications

Jenkinsfile
=> chore(ci): adjust path to downstream

spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/event/PublishDelegateParseListener.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/CamundaEventingIT.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/configuration/impl/DefaultDeploymentConfigurationTest.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/test/nonpa/BoundaryEventServiceTask.java, spring-boot-starter/starter/src/test/resources/bpmn/eventingWithBoundary.bpmn, spring-boot-starter/starter/src/test/resources/bpmn/eventingWithIntermediateCatch.bpmn
=> CAM-12844: fix(spring-boot-starter): Remove duplicate execution listeners 

.ci/config/stage-types.yaml
=> CAM-12987: chore(ci): add default-build label to webapp-unit matrix

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-12986: detect downstream prs

spring-boot-starter/starter/src/test/resources/bpmn/eventingWithIntermediateCatch.bpmn
=> test(starter): adjust timer date

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExternalTaskFailureDto.ftl
=> chore(docs): Add openAPI documentation for added extension element

webapps/camunda-bpm-sdk-js/lib/utils.js, webapps/ui/admin/client/scripts/pages/execution-metrics.js, webapps/ui/admin/client/scripts/pages/groups.js, webapps/ui/admin/client/scripts/pages/tenants.js, webapps/ui/admin/client/scripts/pages/users.js, webapps/ui/cockpit/client/scripts/directives/incidentsTab.js, webapps/ui/cockpit/client/scripts/repository/deployments/directives/cam-cockpit-deployments.js, webapps/ui/cockpit/plugins/base/app/views/processDefinition/processInstanceTable.js, webapps/ui/cockpit/plugins/decisionList/app/views/decisionDefinition/decisionInstanceTable.js, webapps/ui/cockpit/plugins/external-tasks-process-instance-runtime-tab/controllers/process-instance-runtime-external-tasks-controller.js, webapps/ui/cockpit/plugins/external-tasks-process-instance-runtime-tab/services/external-tasks.js
=> fix(searches): show only latest result

database/pom.xml, settings/maven/nexus-settings.xml
=> chore(deps): bump mysql-connector/j to 8.0.22

parent/pom.xml
=> CAM-12776: update resteasy3 version to 3.14.0.Final

.ci/config/stage-types.yaml, .ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-12989: fix(ci): adjust db stages run conditions

.ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-12986: chore(ci): adjust nexus deployment eval

.ci/daily/Jenkinsfile, Jenkinsfile
=> CAM-12991: chore(ci): reduce yaml file reads

.ci/sidetrack/Jenkinsfile, Jenkinsfile
=> fix(ci): create crdb node before when stage evaluation

database/pom.xml
=> chore(deps): bump mysql-connector-java from 8.0.22 to 8.0.23

webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form-generic-variables.html, webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form-generic-variables.js, webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form-generic.js, webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form-generic.less
=> feat(generic form): allow complex data types

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> chore(ci): pass project and build id to downstream to copy artifacts

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> fix(ci): fix compilation errors

parent/pom.xml
* bumps Tomcat to 9.0.41 for engine modules
* bumps Spring Boot to 2.4.2 to bump Tomcat to 9.0.41
related to CAM-12957
=> chore(*): bump Tomcat version

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml, engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/HistoricTaskInstanceQueryOrTest.java
=> fix(engine): respect or query for historicTaskInstanceQueries

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/execution-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/CreateIncidentDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/VariableValueDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ExecutionQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ExecutionTriggerDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/count/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/create-incident/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/{varName}/data/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/{varName}/data/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/{varName}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/{varName}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/{varName}/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/messageSubscriptions/{messageName}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/messageSubscriptions/{messageName}/trigger/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/signal/post.ftl
=> feat(openapi): add execution endpoints

engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/HistoricTaskInstanceQueryOrTest.java
=> chore(test): specify correct history level for historic task query tests

webapps/camunda-commons-ui/lib/widgets/search/cam-widget-search.js, webapps/ui/common/scripts/util/search-widget-utils.js
* Add `With Incidents` filter criterion
* Add `State` filter criterion with operators `equals` and `in`
* Expose `Canceled internally` & `Canceled externally` state
related to CAM-13020
=> feat(cockpit): add filter criteria to proc inst runtime tab

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> chore(ci): use new syntax of cambpmConditionalRetry

engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricDecisionInstanceManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml
- avoids deadlocks on DB2 when executing the dmn removal time batch
related to CAM-12904
=> fix(engine): split up UPDATE query in separate queries

engine-rest/engine-rest/pom.xml
=> chore(rest): bump commons-codec to 1.15 in tests

distro/wildfly/assembly/src/wildfly/standalone-full.xml, distro/wildfly/assembly/src/wildfly/standalone.xml, parent/pom.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml, qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
=> feat(env): add support for WildFly 21

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/optimize/OptimizeRestService.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/optimize/OptimizeVariableUpdateRestServiceTest.java, engine/src/main/java/org/camunda/bpm/engine/impl/OptimizeService.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/optimize/OptimizeHistoricVariableUpdateQueryCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/optimize/OptimizeServiceAuthorizationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/optimize/GetHistoricVariableUpdatesForOptimizeTest.java, qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/OptimizeApiPageSizeTest.java
=> feat(engine-rest): Optimize variable update API object value parameter

webapps/ui/cockpit/client/scripts/camunda-cockpit-bootstrap.js, webapps/ui/cockpit/client/scripts/config.js
=> chore(plugins): add compatibility for legacy plugins

engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
to avoid differences in the exception message among JDKs
Related to CAM-12947
=> improve(engine): improve telemetry test assertion

webapps/src/main/java/org/camunda/bpm/cockpit/impl/plugin/base/dto/query/AbstractProcessInstanceQueryDto.java, webapps/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/processInstance.xml, webapps/src/test/java/org/camunda/bpm/cockpit/plugin/base/ProcessInstanceRestServiceTest.java
* adds a `withIncident` option to process instance queries
related to CAM-13107
=> feat(webapps): add withIncident filter to process instance

engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceReportImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/HistoricTaskInstanceReportImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/ManagementServiceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/TaskReportImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandCounterInterceptor.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/FailedJobListener.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupHandler.java, engine/src/main/java/org/camunda/bpm/engine/impl/metrics/MetricsQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/metrics/reporter/DbMetricsReporter.java, engine/src/main/java/org/camunda/bpm/engine/impl/metrics/reporter/MetricsCollectionTask.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/deploy/DeleteDeploymentFailListener.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/deploy/DeploymentFailListener.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryDynamicDataTest.java, webapps/src/main/java/org/camunda/bpm/cockpit/impl/db/QueryServiceImpl.java, webapps/src/main/java/org/camunda/bpm/cockpit/impl/plugin/base/sub/resources/ProcessDefinitionResource.java, webapps/src/main/java/org/camunda/bpm/cockpit/impl/plugin/resources/ProcessInstanceRestService.java
=> CAM-12992: telemetry doesn't report lambda/anonymous commands

webapps/ui/common/scripts/services/plugins/addPlugins.js
=> fix(plugins): hide breadcrumbs on custom route

webapps/ui/cockpit/client/scripts/config.js, webapps/ui/cockpit/client/scripts/repository/resource/controllers/cam-cockpit-resource-details-ctrl.js, webapps/ui/cockpit/client/scripts/repository/resource/directives/cam-cockpit-html-source.html, webapps/ui/cockpit/client/scripts/repository/resource/directives/cam-cockpit-html-source.js, webapps/ui/cockpit/client/scripts/repository/resource/directives/cam-cockpit-resource-content.html, webapps/ui/cockpit/client/scripts/repository/resource/directives/cam-cockpit-resource-content.js, webapps/ui/cockpit/client/scripts/repository/resource/main.js, webapps/ui/cockpit/client/styles/pages/repository.less, webapps/ui/common/scripts/services/cam-configuration.js
=> feat(repository): display preview of HTML files

distro/wildfly/assembly/src/wildfly/standalone-full.xml, distro/wildfly/assembly/src/wildfly/standalone.xml, parent/pom.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml, qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
=> CAM-12944: feat(dist): add wildfly 22 support

engine-rest/engine-rest-openapi/src/main/templates/paths/batch/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/batch/statistics/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/create/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/{id}/get.ftl
=> fix(openapi): fix deployment and batch responses

.gitignore, distro/run/modules/swaggerui/pom.xml, distro/run/modules/swaggerui/ui/package-lock.json, distro/run/modules/swaggerui/ui/package.json, distro/run/modules/swaggerui/ui/tasks/license.js, distro/run/modules/swaggerui/ui/webpack.config.js
=> feat(run): add license book generation for swagger-ui

webapps/ui/common/scripts/module/index.js
=> feat(custom batch): pass api object to onSubmit

webapps/camunda-commons-ui/lib/widgets/bpmn-viewer/cam-widget-bpmn-viewer.js, webapps/ui/cockpit/client/scripts/camunda-cockpit-bootstrap.js, webapps/ui/cockpit/client/scripts/config.js
=> fix(bpmn-js): allow loading of additional modules

webapps/ui/tasklist/client/scripts/filter/directives/cam-tasklist-filter-modal-criteria.js, webapps/ui/tasklist/client/scripts/filter/directives/cam-tasklist-filter-modal-form-criteria.js, webapps/ui/tasklist/client/scripts/tasklist/plugins/cam-tasklist-search-plugin-config.json
=> feat(task): add filter for tasks without due date

engine-rest/engine-rest/pom.xml, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/util/container/TomcatServerBootstrap.java
=> chore(engine-rest): remove Jackson 1 test dependency

engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/BreakingScalaFeelBehaviorTest.java, pom.xml
=> chore(engine-dmn): bump feel scala engine to 1.13.1

webapps/package-lock.json, webapps/package.json, webapps/ui/common/styles/cam-webapps-common.less, webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form-camunda.js, webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form.html, webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form.js, webapps/ui/tasklist/client/scripts/form/index.js, webapps/ui/tasklist/client/scripts/process/plugins/action/modals/cam-tasklist-process-start-modal.js, webapps/ui/tasklist/client/scripts/task/plugins/detail/cam-tasklist-task-detail-form-plugin.js
=> feat(forms): add support for form-js

webapps/ui/cockpit/client/scripts/repository/resource/directives/cam-cockpit-resource-wrapper.html, webapps/ui/cockpit/client/scripts/repository/resource/directives/cam-cockpit-resource-wrapper.js, webapps/ui/cockpit/client/scripts/repository/resource/plugins/details/definitions/cam-cockpit-definitions-plugin.html, webapps/ui/cockpit/client/scripts/repository/resource/plugins/details/definitions/cam-cockpit-definitions-plugin.js, webapps/ui/cockpit/client/styles/pages/repository.less
=> chore(deployment): only show "Definitions" on process resources

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
* reduce parameters and complexity of when clause
Related to CAM-13270
=> chore(ci): rename `standalone` label to `upstream`

.ci/config/stage-types.yaml
=> chore(ci): add npm to jdk stages

webapps/ui/common/scripts/util/search-widget-utils.js, webapps/ui/tasklist/client/scripts/tasklist/plugins/cam-tasklist-search-plugin-config.json, webapps/ui/tasklist/client/scripts/tasklist/plugins/cam-tasklist-search-plugin.js
=> feat(task): allow process variable 'notLike' search

parent/pom.xml
* Bump Spring Boot to 2.4.3 (contains Tomcat 9.0.43)
* Bump Tomcat to 9.0.43
related to CAM-13185
=> chore(project): bump tomcat to latest version

engine-rest/engine-rest-openapi/src/main/templates/paths/user/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/user/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/user/{id}/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/user/{id}/profile/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/user/{id}/profile/put.ftl
=> fix(openapi): fix incorrect user example

spring-boot-starter/starter-client/spring-boot/src/test/java/org/camunda/bpm/client/spring/boot/starter/MockHelper.java, spring-boot-starter/starter-client/spring-boot/src/test/java/org/camunda/bpm/client/spring/boot/starter/client/BasicAuthAndInterceptorConfigurationTest.java, spring-boot-starter/starter-client/spring-boot/src/test/java/org/camunda/bpm/client/spring/boot/starter/client/BasicAuthConfigurationTest.java
=> test(xtac-starter): skip mocked tests on ibm jdk 8 

spring-boot-starter/starter-client/spring-boot/src/main/java/org/camunda/bpm/client/spring/boot/starter/impl/ClientAutoConfiguration.java, spring-boot-starter/starter-client/spring/src/main/java/org/camunda/bpm/client/spring/impl/PostProcessorConfiguration.java, spring-boot-starter/starter-client/spring/src/test/java/org/camunda/bpm/client/spring/client/configuration/PropertyPlaceholderConfiguration.java
=> fix(xtac-starter): add static modifier to bfpp returning bean methods

spring-boot-starter/starter-client/spring/src/main/java/org/camunda/bpm/client/spring/impl/subscription/SpringTopicSubscriptionImpl.java, spring-boot-starter/starter-client/spring/src/test/java/org/camunda/bpm/client/spring/subscription/AutoOpenFalseTest.java
=> fix(xtac-starter): fix open state when closing a subscription

webapps/grunt/config/less.js, webapps/package-lock.json, webapps/package.json, webapps/ui/cockpit/client/scripts/repository/resource/directives/cam-cockpit-form.html, webapps/ui/cockpit/client/scripts/repository/resource/directives/cam-cockpit-form.js, webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form-camunda.js
=> chore(form-js): handle schema errors

engine-rest/engine-rest-openapi/src/main/templates/paths/group/{id}/members/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/group-members/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/user-members/options.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/identity/impl/GroupMembersResourceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/identity/impl/TenantGroupMembersResourceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/identity/impl/TenantUserMembersResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/GroupRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TenantRestServiceInteractionTest.java
=> fix(rest): remove incorrect GET method in options response

engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/bpmnEscalation/post.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/impl/TaskResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/TaskService.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/HandleTaskEscalationCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskServiceTest.java
=> fix(rest+engine): wrong error message when submitting null or empty escalationCode

Jenkinsfile
=> fix(ci): fix maven snapshot deploy in main ce pipeline

webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task-meta.js
=> fix(tasklist): disable claim button until user loaded

distro/license-book/assembly.xml, distro/license-book/pom.xml, distro/license-book/src/main/resources/license-book.txt
=> CAM-13235: update license book for 7.15

webapps/ui/common/scripts/services/plugins/loadPlugins.js
* Add error handling for non-existing files
related to CAM-13352
=> fix(pluigns): correctly load new plugins from JAR

database/pom.xml, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.cockroachdb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/cockroachdb_engine_7.15_to_7.16.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.15_to_7.16.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.15_to_7.16.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.15_to_7.16.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.15_to_7.16.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.15_to_7.16.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.15_to_7.16.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.15_to_7.16.sql, qa/test-db-instance-migration/pom.xml, qa/test-db-instance-migration/test-fixture-716/pom.xml, qa/test-db-instance-migration/test-fixture-716/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java, qa/test-db-instance-migration/test-fixture-716/src/main/resources/camunda.cfg.xml, qa/test-db-rolling-update/create-new-engine/pom.xml, qa/test-db-rolling-update/create-old-engine/pom.xml, qa/test-db-rolling-update/rolling-update-util/pom.xml, qa/test-db-rolling-update/test-old-engine/pom.xml, qa/test-db-upgrade/pom.xml, qa/test-old-engine/config/camunda.cfg.xml, qa/test-old-engine/config/org/camunda/bpm/engine/test/concurrency/historycleanup.camunda.cfg.xml, qa/test-old-engine/pom.xml, webapps/README.md
=> chore(release): prepare codebase for 7.16 development

CONTRIBUTING.md
=> chore(contribution-guide): show how to exclude swagger-ui module

Jenkinsfile
=> fix(ci): remove post action for engine-api-compatibility

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> chore(ci): disable parallel builds

Jenkinsfile
* adjust assembly condition evaluation
Related to CAM-13397
=> chore(ci): use default branch var instead of hard-coded value

engine-spring/compatibility-test-spring4/pom.xml, parent/pom.xml
* Bump Spring 5 to 5.2.13.RELEASE;
* Bump Spring 4 to 4.3.30.RELEASE;
Related to CAM-13279
=> CAM-13279: chore(spring): bump spring versions

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile
=> chore(ci): rename UPSTREAM_PR to UPSTREAM

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/filter-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/filter/CreateFilterDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/filter/FilterDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/create/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/count/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/list/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/list/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/options.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/singleResult/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/singleResult/post.ftl
=> feat(openapi): add filter endpoints

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-cleanable-decision-definition-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/CleanableHistoricDecisionInstanceReportResultDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/decision-definition/cleanable-decision-instance-report/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/decision-definition/cleanable-decision-instance-report/get.ftl
=> feat(openapi): add historic decision definition endpoints

engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricDecisionInstanceStatisticsDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/decision-requirements-definition/{id}/statistics/get.ftl
=> feat(openapi): add historic drd endpoint

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-task-instance-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/DurationReportResultDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceReportResultDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/task/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/task/count/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/task/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/task/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/task/report/get.ftl
=> CAM-11568: feat(openapi): add historic task endpoints

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/historic-decision-instance-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/commons/historic-decision-instance-single-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/DeleteHistoricDecisionInstancesDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricDecisionInputInstanceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricDecisionInstanceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricDecisionInstanceQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricDecisionOutputInstanceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/SetRemovalTimeToHistoricDecisionInstancesDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/decision-instance/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/decision-instance/delete/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/decision-instance/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/decision-instance/set-removal-time/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/decision-instance/{id}/get.ftl
=> feat(openapi): add historic decision instance endpoints

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/job-definition-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SuspensionStateDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDefinitionDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDefinitionPriorityDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDefinitionQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDefinitionSuspensionStateDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDefinitionsSuspensionStateDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job-definition/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job-definition/count/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job-definition/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job-definition/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job-definition/suspended/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job-definition/{id}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job-definition/{id}/jobPriority/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job-definition/{id}/retries/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job-definition/{id}/suspended/put.ftl
=> feat(openapi): add job definition endpoints

engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoryCleanupConfigurationDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/cleanup/configuration/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/cleanup/job/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/cleanup/jobs/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/cleanup/post.ftl, engine/src/main/java/org/camunda/bpm/engine/HistoryService.java
=> CAM-11564: feat(openapi): add history cleanup endpoints

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/decision-requirements-definition.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/dmn/DecisionRequirementsDefinitionDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/dmn/DecisionRequirementsDefinitionXmlDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/key/{key}/diagram/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/key/{key}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/key/{key}/tenant-id/{tenant-id}/diagram/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/key/{key}/tenant-id/{tenant-id}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/key/{key}/tenant-id/{tenant-id}/xml/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/key/{key}/xml/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/{id}/diagram/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/{id}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/{id}/xml/get.ftl
* adds all DRD endpoints
* adds a `binary` option for media type responses which is
needed for image responses for DRD diagram endpoints
related to CAM-11534
=> feat(openapi): add DRD endpoints

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-definition-activity-statistics.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-definition-process-instance-report.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/CleanableHistoricProcessInstanceReportResultDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricActivityStatisticsDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-definition/cleanable-process-instance-report/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-definition/cleanable-process-instance-report/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-definition/{id}/statistics/get.ftl
=> feat(openapi): add historic process definition endpoints

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/historic-external-task-log-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricExternalTaskLogDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricExternalTaskLogQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/external-task-log/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/external-task-log/count/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/external-task-log/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/external-task-log/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/external-task-log/{id}/error-details/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/external-task-log/{id}/get.ftl
=> feat(openapi): add historic external task log

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-detail-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricDetailDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricDetailQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/detail/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/detail/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/detail/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/detail/{id}/data/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/detail/{id}/get.ftl
=> CAM-11560: feat(openapi): add historic detail endpoints

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/historic-decision-instance-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/commons/historic-incident-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-identity-link.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/commons/incident-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricDecisionInputInstanceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricDecisionInstanceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricDecisionOutputInstanceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricIdentityLinkLogDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/identity-link-log/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/identity-link-log/get.ftl
* adds all historic identity link logs endpoints
* adds default date format link where missing for other endpoints
related to CAM-11561
=> feat(openapi): add historic identity link endpoints

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/historic-batch-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/batch/CleanableHistoricBatchReportResultDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/batch/HistoricBatchDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/batch/HistoricBatchQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/batch/removaltime/SetRemovalTimeToHistoricBatchesDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/batch/cleanable-batch-report/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/batch/cleanable-batch-report/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/batch/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/batch/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/batch/set-removal-time/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/batch/{id}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/batch/{id}/get.ftl
=> feat(openapi): add historic batch endpoints

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/user-operation-log-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/UserOperationLogEntryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/user-operation/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/user-operation/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/user-operation/{operationId}/clear-annotation/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/user-operation/{operationId}/set-annotation/put.ftl
=> CAM-11569: feat(openapi): add user operation log endpoints

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/VariableValueDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/migration/MigrationInstructionValidationReportDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/migration/MigrationPlanDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/migration/MigrationPlanGenerationDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/migration/MigrationPlanReportDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/migration/MigrationVariableValidationReportDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/migration/execute/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/migration/executeAsync/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/migration/generate/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/migration/validate/post.ftl
=> feat(openapi): set variables on process instance migration

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/historic-variable-instance-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/main.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricVariableInstanceDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricVariableInstanceQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/detail/{id}/data/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/variable-instance/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/variable-instance/count/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/variable-instance/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/variable-instance/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/variable-instance/{id}/data/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/variable-instance/{id}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/variable-instance/{id}/get.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricVariableInstanceQueryDto.java
=> feat(openapi): add OpenAPI docs for Historic Variable Instance endpoint

.ci/config/matrices.yaml
=> CAM-13476: remove retired environments ci

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
* publish tests only on stage failure
* adjust webapp-UNIT-database-table-prefix stage execution 
* adjust daily trigger to 0-3 UTC 
Related to CAM-13467
=> chore(ci): reduce test results publishing 

.ci/config/matrices.yaml, .ci/config/stage-types.yaml, Jenkinsfile
=> chore(ci): merge engine and webapp unit stage

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-task-instance-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/task/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/task/get.ftl
=> CAM-13482: add orQueries parameter to historic task instance query

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/impl/TaskResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/cmmn/oneTaskCaseWithFormKey.cmmn
=> fix(rest): fix forms not being fetched for cmmn tasks

webapps/package-lock.json, webapps/package.json
=> chore(deps): bump lodash to version 4.17.21

spring-boot-starter/starter/pom.xml, spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/CamundaBpmPluginConfiguration.java, spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/plugin/ApplicationContextClassloaderSwitchPlugin.java
=> chore(spring-boot): add application context classloader switch option

engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobExecutor.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorStartTest.java
=> chore(engine): allow setting custom AcquireJobsCommandFactory before starting job executor

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ActivityInstanceIncidentDto.ftl
=> fix(open-api): correct ActivityInstanceIncidentDto properties

qa/test-old-engine/pom.xml
Related to CAM-13576
Context: https://jira.camunda.com/browse/CAM-12976?focusedCommentId=191644&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-191644
=> chore(qa): disable tests on galera setup in old-engine

Jenkinsfile
=> fix(ci): add missing leading slash to downstream project path

Jenkinsfile
switch from pipeline-master to master as default branch
Related to CAM-13409
=> chore(ci): enable artifacts deployment for master

webapps/camunda-bpm-sdk-js/lib/api-client/resources/task.js, webapps/ui/common/scripts/services/cam-configuration.js, webapps/ui/tasklist/client/scripts/config/config.js, webapps/ui/tasklist/client/scripts/task/plugins/action/modals/cam-tasklist-comment-form.js
=> fix(tasklist): make adding procInstId to task comment configurable 

webapps/camunda-commons-ui/lib/widgets/variables-table/cam-widget-variables-table.less, webapps/package-lock.json, webapps/package.json
=> chore(deps): bump form-js

webapps/camunda-commons-ui/grunt/tasks/ensureLibs.js
=> fix(webapps): fix frontend license book

Jenkinsfile
=> chore(ci): add repo maven param

parent/pom.xml, spring-boot-starter/starter/pom.xml
=> feat(spring-boot): bump spring-boot to 2.5

webapps/.stylelintrc.json, webapps/camunda-commons-ui/lib/services/HttpClient.js
reverts https://github.com/camunda/camunda-bpm-platform/commit/66002d73e41ff747f2914a3a486be748395e2b3e#diff-57e25c8be31a569afb4f1fd4454861be36d405b8f193a4dd844b2edc21d8379dL20-L22
related to CAM-13492
=> fix(build): use global cam-SDK

.ci/config/matrices.yaml, .ci/config/stage-types.yaml, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/FetchExternalTasksCmd.java
* mitigates illegal reflective access to `HashMap.Values#size` method
* adds JDK 15 CI stages
related to CAM-13557
=> chore(engine): support Java 15 execution

distro/run/assembly/resources/start.bat, distro/run/assembly/resources/start.sh
* adds support for JVM options being passed on to Run's
application start via JAVA_OPTS variable
related to CAM-13532
=> feat(run): support external JVM options via JAVA_OPTS

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/MultiFormDeploymentDto.ftl, engine-rest/engine-rest-openapi/src/test/java/org/camunda/bpm/engine/rest/openapi/client/DeploymentTest.java
=> docs(rest-openapi): document deployment-activation-time in deploy

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/DeploymentRestServiceImpl.java
=> fix(engine-rest): add empty check for deployment activation time

distro/jbossas7/modules/pom.xml, distro/jbossas7/modules/src/main/modules/com/jayway/jsonpath/json-path/main/module.xml, distro/jbossas7/modules/src/main/modules/net/minidev/accessors-smart/main/module.xml, distro/jbossas7/modules/src/main/modules/net/minidev/json-smart/main/module.xml, distro/wildfly/modules/pom.xml, distro/wildfly/modules/src/main/modules/com/jayway/jsonpath/json-path/main/module.xml, distro/wildfly/modules/src/main/modules/net/minidev/accessors-smart/main/module.xml, distro/wildfly/modules/src/main/modules/net/minidev/json-smart/main/module.xml
* adds placeholders for version of json-path and its dependencies
related to CAM-13684
=> chore(distro): update json-path modules

distro/jbossas7/webapp-standalone/pom.xml, distro/jbossas7/webapp-standalone/src/main/webapp/WEB-INF/applicationContext.xml, distro/tomcat/webapp-standalone/pom.xml, distro/tomcat/webapp-standalone/src/main/webapp/WEB-INF/applicationContext.xml, engine-spring/compatibility-test-spring4/pom.xml, engine-spring/core/pom.xml, engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/jpa/JPASpringTest-context.xml, engine/pom.xml, internal-dependencies/pom.xml, parent/pom.xml
* removes commons-dbcp from engine-spring tests
* replaces commons-dbcp with Hikari in standalone webapps
related to CAM-13519
=> chore(*): remove commons-dbcp

.ci/daily/Jenkinsfile, Jenkinsfile, distro/wildfly/assembly/src/wildfly/standalone-full.xml, distro/wildfly/assembly/src/wildfly/standalone.xml, parent/pom.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml, qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
=> CAM-13328: feat(engine): add wildfly 23 support

webapps/ui/tasklist/client/scripts/task/controller/cam-tasklist-task-groups-ctrl.js, webapps/ui/tasklist/client/scripts/task/modals/cam-tasklist-groups-modal.html
=> fix(tasklist): don't allow double group assignment

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/main/java/org/camunda/bpm/engine/impl/form/handler/DefaultFormHandler.java, engine/src/main/java/org/camunda/bpm/engine/impl/form/handler/DefaultStartFormHandler.java, engine/src/main/java/org/camunda/bpm/engine/impl/form/handler/DefaultTaskFormHandler.java, engine/src/main/java/org/camunda/bpm/engine/impl/task/TaskDefinition.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/start/StartEventCamundaFormDefinitionParseTest.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/usertask/UserTaskCamundaFormDefinitionParseTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/start/StartEventCamundaFormDefinitionParseTest.shouldNotParseCamundaFormDefinitionAndFormKey.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/start/StartEventCamundaFormDefinitionParseTest.shouldNotParseCamundaFormDefinitionUnsupportedBinding.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/start/StartEventCamundaFormDefinitionParseTest.shouldParseCamundaFormDefinitionDeploymentBinding.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/start/StartEventCamundaFormDefinitionParseTest.shouldParseCamundaFormDefinitionLatestBinding.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/start/StartEventCamundaFormDefinitionParseTest.shouldParseCamundaFormDefinitionMultipleStartEvents.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/start/StartEventCamundaFormDefinitionParseTest.shouldParseCamundaFormDefinitionVersionBinding.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/usertask/UserTaskCamundaFormDefinitionParseTest.shouldNotParseCamundaFormDefinitionAndFormKey.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/usertask/UserTaskCamundaFormDefinitionParseTest.shouldNotParseCamundaFormDefinitionUnsupportedBinding.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/usertask/UserTaskCamundaFormDefinitionParseTest.shouldParseCamundaFormDefinitionDeploymentBinding.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/usertask/UserTaskCamundaFormDefinitionParseTest.shouldParseCamundaFormDefinitionLatestBinding.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/usertask/UserTaskCamundaFormDefinitionParseTest.shouldParseCamundaFormDefinitionVersionBinding.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/usertask/UserTaskCamundaFormDefinitionParseTest.shouldParseTwoUserTasksWithCamundaFormDefinition.bpmn20.xml
=> feat(form): parse camunda form definition on user tasks

model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/builder/AbstractStartEventBuilder.java, model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/builder/AbstractUserTaskBuilder.java, model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/BpmnModelConstants.java, model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/instance/StartEventImpl.java, model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/instance/UserTaskImpl.java, model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/instance/StartEvent.java, model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/instance/UserTask.java, model-api/bpmn-model/src/test/java/org/camunda/bpm/model/bpmn/BpmnTestConstants.java, model-api/bpmn-model/src/test/java/org/camunda/bpm/model/bpmn/builder/ProcessBuilderTest.java, model-api/bpmn-model/src/test/java/org/camunda/bpm/model/bpmn/instance/StartEventTest.java, model-api/bpmn-model/src/test/java/org/camunda/bpm/model/bpmn/instance/UserTaskTest.java
=> feat(form): extend UserTask/StartEvent model API with new form bindings

distro/jbossas7/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/service/ProcessApplicationDeploymentService.java, distro/wildfly/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/service/ProcessApplicationDeploymentService.java, engine/src/main/java/org/camunda/bpm/application/AbstractProcessApplication.java, qa/integration-tests-engine/pom.xml, qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/deployment/spring/timer/ApplicationContext.java, qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/deployment/spring/timer/MyBean.java, qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/deployment/spring/timer/SpringServletPATimerStartEventExpressionTest.java, qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/cdi/CdiBeanResolutionOnDeploymentTest.java, qa/integration-tests-engine/src/test/resources/META-INF/scan_for_definitions_processes.xml, qa/integration-tests-engine/src/test/resources/org/camunda/bpm/integrationtest/deployment/spring/timer/start-event-expression-web.xml, qa/integration-tests-engine/src/test/resources/org/camunda/bpm/integrationtest/deployment/spring/timer/timer-start-event-process.bpmn
=> Switch into context of process application before deployment 
