engine/src/main/java/org/camunda/bpm/engine/test/ProcessEngineRule.java

Please check this one, the processEngineRule was not supplying all available services since 7.2.
We started working on assertions for case plans and noticed that there are no getters (or setters) for the services in the TestRule. I made the rule implement ProcessEngineServices (so next time, this raises an error) and fixed the missing methods. Also, the setter for historyService was named setHistoricDataService ... I did not want to break the api, but it would be a good idea to make the old on deprecated ...

Add getter for AuthorizationService and CaseService in ProcessEngineRule

---

engine-plugins/identity-ldap/src/test/java/org/camunda/bpm/identity/impl/ldap/LdapUserQueryTest.java

This looks like it was originally a copy and paste error.  The change is in the `testFilterByLastname` method.

Fix minor error in ldap plugin test.

---

engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java

- HistoricJobLogEvent uses ClockUtil now.
related to 4875

chore(engine) change paramater to use ClockUtil.getDate()

---

engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceTest.java

Related to CAM-5130.
Column names retrieved from the database schema are given in lower case letters for Informix as well as for Postgres obviously.
With this change, the column is searched first by the uppercase name, and, in case of not found, again with the lowercase name. There is no need anymore then to ask for the database type name.

ManagementServiceTest: search column with uppercase and lowercase name.

---

engine/src/main/java/org/camunda/bpm/engine/impl/ProcessEngineImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/ProcessEngineLogger.java

To track the application lifecycle it would be nice if the engine clearly logs when it is closed. So I added a Logger method and the statement to engine.close()

add logInfo when process engine is finally closed

---

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/mapper/MultipartPayloadProvider.java

Final qualifier messes with resteasy-cdi features deploying a custom JAX-RS application to Wildfly.
Fixes #CAM-5155.

Remove final qualifier from MultipartPayloadProvider

---

engine/src/main/java/org/camunda/bpm/engine/impl/ProcessEngineImpl.java

To avoid confusion, I added the override annotations to the methods declared in processEngine and processEngineServices

add override annotation

---

engine/src/main/java/org/camunda/bpm/engine/impl/test/TestHelper.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/testing/ProcessEngineRuleParentClassDeployment.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/testing/ProcessEngineRuleParentClassDeploymentTest.java
engine/src/test/resources/org/camunda/bpm/engine/test/standalone/testing/ProcessEngineRuleParentClassDeployment.bpmn

We figured out that when using test class hierarchies (for example with the Enclosed-Runner) the Deployment annotation on parent classes is not recognized right now.
This PR is a simple enhancement iterating up to Object.class while looking for the deployment annotation, allowing annotating a class higher up in the hierarchy.

enhance deployment annotation scan on parent class

---

qa/integration-tests-engine/pom.xml
qa/integration-tests-webapps/pom.xml

as it just hangs without any error message when it is started with JDK 8 during engine-it/webapps-it
related to #CAM-6410

chore(qa): enforce JDK 6/7 for JBoss AS

---

examples/invoice/src/main/java/org/camunda/bpm/example/invoice/InvoiceProcessApplication.java

To avoid the flood of process instances with the same variables after each engine start, supress the start if there are still some instances running.

Don't start new instances if there are some running

---

engine-spring/src/main/java/org/camunda/bpm/engine/spring/application/SpringProcessApplication.java

so it can be accessed from classes extending it

make beanName protected

---

engine-spring/src/main/java/org/camunda/bpm/engine/spring/ProcessEngineFactoryBean.java

so far multiple calls to getObject tried to create a new instance although isSingleton and destroy() clearly suggest otherwise.

enforce singleton behavior

---

examples/invoice/src/main/resources/invoice.v1.bpmn
examples/invoice/src/main/resources/invoice.v2.bpmn

Add the history-time-to-live to the example processes: version 1 will be kept for 30 days, version 2 for 45 days.
Also use the version tag of the process definition.

History time to live

---

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java

Added whitespace after bpmnElement variable for better readability when showing parse errors.

Added whitespace in BPMNParse messages.

---

engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobHelper.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorExceptionLoggingHandlerTest.java

fix problem that user cannot override logging of job executor exceptions
related to CAM-9214

fix(jobexecutor): customize error log

---

engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerBatchesTest.java

When you are using other databases as H2 , there is noch order guaranty
, on DB2 zOS you will get (sometimes) your Monitor-Process and then the
test will fail

CAM-9951 Specialize JUnit Test for HistoryCleanupSchedulerBatchesTest

---

engine/src/main/java/org/camunda/bpm/engine/impl/form/handler/FormFieldHandler.java

See https://app.camunda.com/jira/browse/CAM-10385
With the released version of Camunda, I get an exception like this:
01-Jun-2019 10:49:05.607 WARNING [http-nio-8080-exec-225] org.camunda.bpm.engine.rest.exception.ExceptionHandler.toResponse java.lang.NumberFormatException: For input string: "
"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Long.parseLong(Long.java:601)
at java.lang.Long.<init>(Long.java:965)
at org.camunda.bpm.engine.impl.form.type.LongFormType.convertValue(LongFormType.java:46)
at org.camunda.bpm.engine.impl.form.type.SimpleFormFieldType.convertToFormValue(SimpleFormFieldType.java:29)
at org.camunda.bpm.engine.impl.form.handler.FormFieldHandler.createFormField(FormFieldHandler.java:86)
at …

CAM-10385 make exception include the name of the variable if FormFieldHandler.createFormField throws

---

engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobExecutorLogger.java

OptimisticLockingExceptions should only be logged fully on logging level DEBUG. On logging levels lower than DEBUG only the occurrence of the exception should be logged.
https://app.camunda.com/jira/browse/CAM-9938
Related to CAM-9938

[CAM-9938] Only log stacktrace of OptimisticLockingException on DEBUG

---

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryOrTest.java

* use left joins if OR clauses are contained in the query,
use inner joins otherwise
* degrades the performance of all OR queries
related to CAM-9114

[CAM-9114] fix(engine): correct results for or queries with multiple joins

---

engine/src/main/java/org/camunda/bpm/engine/ProcessEngineConfiguration.java
engine/src/main/java/org/camunda/bpm/engine/impl/ProcessEngineLogger.java
engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandContext.java
engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobHelper.java
engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/CmdExceptionLoggingTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExceptionLoggingTest.java

* enable reduced job logging -> only exceptions in jobs with no retries
will be logged
* enable reduced cmd logging -> only exceptions in commands that are not
handled by the engine are logged
Related to CAM-10067

[CAM-10067] configuration for exception logging during cmd/job execution

---

engine/src/main/java/org/camunda/bpm/engine/impl/ManagementServiceImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/AbstractPersistenceSession.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/FlushResult.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/PersistenceSession.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/entitymanager/DbEntityManager.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/entitymanager/operation/DbBulkOperation.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/entitymanager/operation/DbEntityOperation.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/entitymanager/operation/DbOperation.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/BatchDbSqlSession.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSession.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/SimpleDbSqlSession.java
engine/src/main/java/org/camunda/bpm/engine/impl/test/AbstractProcessEngineTestCase.java
engine/src/main/java/org/camunda/bpm/engine/impl/test/RequiredDatabase.java
engine/src/main/java/org/camunda/bpm/engine/impl/test/TestHelper.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/CollectionUtil.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/EnsureUtil.java
engine/src/main/java/org/camunda/bpm/engine/test/ProcessEngineRule.java
engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrencyTestCase.java
engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ThrowOleWhenDeletingExceptionStacktraceTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/SequentialJobAcquisitionTest.java
engine/src/test/java/org/camunda/bpm/engine/test/persistence/DatabaseFlushTest.java

- fixes the problem that a db operation could fail and
we would incorrectly assume that this was ok and not rollback the
transaction
- example:
- we flush an insert into ACT_RU_VARIABLE which fails, because
it violates the uniqueness constraint on NAME_ and SCOPE_
- db entity manager catches the exception and identifies it as a case
of concurrent modification
- db entity manager (wrongfully) matched the failure to a history
operation in the same flush
- with the setting that we do not raise optimistic locking exception
in case of history entities, the failed insert does not trigger
transaction rollback and the flush continues; this leads to
inconsistencies in the runtime tables
- the core fix is that we must handle the exception raised by mybatis
differently in case flushing fails; in …

Cam 10409 flush bug

---

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceQueryDto.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceQueryTest.java
engine/src/main/java/org/camunda/bpm/engine/impl/ProcessInstanceQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/runtime/ProcessInstanceQuery.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Execution.xml
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceQueryOrTest.java

OR queries extension for ProcessInstanceQuery based on the already existing OR queries for tasks from tag 7.10.0. Also added a JUnit test for it and extended the query DTO for the REST API.
See also CAM-9676 in Jira

[CAM-9676] feat(engine): Implemented OR queries for ProcessInstanceQuery

---

qa/test-db-instance-migration/test-fixture-710/pom.xml
qa/test-db-instance-migration/test-fixture-711/pom.xml
qa/test-db-instance-migration/test-fixture-74/pom.xml
qa/test-db-instance-migration/test-fixture-75/pom.xml
qa/test-db-instance-migration/test-fixture-76/pom.xml
qa/test-db-instance-migration/test-fixture-77/pom.xml
qa/test-db-instance-migration/test-fixture-78/pom.xml
qa/test-db-instance-migration/test-fixture-79/pom.xml

* The recent move of the DMN Engine and Typed Values directly into the platform resulted in them becoming transitive dependencies, whose versions have to be explicitly declared in the test fixtures of the instance migration test suite.
Related to CAM-10589 (https://app.camunda.com/jira/browse/CAM-10589)

CAM-10589: fix(qa): add transitive dependency versions to poms

---

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AcquireJobsCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/entitymanager/cache/DbEntityCache.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/entitymanager/cache/DbEntityCacheKeyMapping.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AcquirableJobEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobManager.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/async/FoxJobRetryCmdTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/AbstractJobExecutorAcquireJobsTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/AcquirableJobCacheTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/AcquireJobCmdUnitTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/DeploymentAwareJobExecutorForOracleTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/DeploymentAwareJobExecutorTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsByDueDateNotPriorityTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsByDueDateTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsByPriorityAndDueDateTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsByPriorityTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsByTypeAndDueDateTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsByTypeTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsDefaultTest.java

* by reducing the select of all column but rather only the needed
* update the job lock details accordingly
* introduce AcquirableJobEntity
-- to contains the selected job data
-- to update the job lock details
Related to [CAM-9838](https://app.camunda.com/jira/browse/CAM-9838)

CAM-9838: improve job acquisition query

---

engine-spring/compatibility-test-spring4/pom.xml
engine-spring/compatibility-test-spring5/pom.xml
engine-spring/core/pom.xml
engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/transaction/inner/rollback/InnerProcessService.java
engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/transaction/inner/rollback/InnerProcessServiceImpl.java
engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/transaction/inner/rollback/SpringInnerTransactionRollbackTest.java
engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/transaction/inner/rollback/TransactionTestDelegate.java
engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/transaction/SpringInnerTransactionRollbackTest-applicationContext.xml
engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/transaction/SpringInnerTransactionRollbackTest.shouldRollbackProcessData-inner.bpmn20.xml
engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/transaction/SpringInnerTransactionRollbackTest.shouldRollbackProcessData-outer.bpmn20.xml
engine/src/main/java/org/camunda/bpm/engine/context/ProcessEngineContext.java
engine/src/main/java/org/camunda/bpm/engine/impl/context/ProcessEngineContextImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandContextInterceptor.java
engine/src/test/java/org/camunda/bpm/engine/test/api/context/ProcessEngineContextTest.java

* Provide static methods to declare a new CommandContext creation;
* Provide a test case for inner transactions (REQUIRES_NEW) in the Spring integration.
Related to CAM-10002 (https://app.camunda.com/jira/browse/CAM-10002)

[CAM-10002] fix(engine-spring): enable inner transactions with spring

---

engine-rest/engine-rest-jaxrs2/src/main/java/org/camunda/bpm/engine/rest/impl/CamundaRestResources.java
engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/impl/FetchAndLockRestServiceInteractionTest.java
engine-rest/engine-rest/pom.xml
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/CamundaRestResources.java
engine-rest/engine-rest/src/test/java-resteasy/org/camunda/bpm/engine/rest/ResteasyTaskRestServiceInteractionTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/SignalRestServiceTest.java

* by registering the ExceptionHandler for the REST API
* add test cases for rest and rest jaxrs2 by throwing IllegalArgumentException
Related to [CAM-10592](https://app.camunda.com/jira/browse/CAM-10592)

CAM-10592: prevent showing stack traces in REST API

---

engine/src/main/java/org/camunda/bpm/engine/impl/util/EngineUtilLogger.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/xml/Parse.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.java
engine/src/test/java/org/camunda/bpm/engine/test/util/SystemPropertiesRule.java

- configuration is respected via the jaxp system property
related to CAM-10640

CAM-10640: allow access to all external schemas by default

---

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java

The `assigneeIn` property wasn't included in the `fromQuery` method of the TaskQueryDto, so it couldn't be used with the Filter Rest service.
I also cleaned up the class to use diamond operators.
Related to CAM-10639 (https://app.camunda.com/jira/browse/CAM-10639)
Main ticket: https://app.camunda.com/jira/browse/CAM-4670

CAM-10639: chore(rest): make assigneeIn filter work with tasklist filters

---

bom/pom.xml

[CAM-10699, CAM-10695] Bump java-uuid-generator dependency to 3.2.0

---

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeployCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/DeploymentEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/repository/CandidateDeploymentImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/repository/DefaultDeploymentHandler.java
engine/src/main/java/org/camunda/bpm/engine/impl/repository/DefaultDeploymentHandlerFactory.java
engine/src/main/java/org/camunda/bpm/engine/repository/CandidateDeployment.java
engine/src/main/java/org/camunda/bpm/engine/repository/DeploymentHandler.java
engine/src/main/java/org/camunda/bpm/engine/repository/DeploymentHandlerFactory.java
engine/src/test/java/org/camunda/bpm/engine/test/api/cfg/DatabaseTablePrefixTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/repository/ProcessApplicationDeploymentTest.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/deployment/BpmnDeploymentTest.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/deployment/VersionedDeploymentHandler.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/deployment/VersionedDeploymentHandlerFactory.java

Decisions:
- The `Handler` interface was extended to include separate resume methods for resuming by Process Definition Keys and Deployment Name.
- The `Handler` interface now also provides a method to determine a `Duplicate` deployment  (old implementation calls it an `existingDeployment`.
- A Factory interface is provided to instantiate DeploymentHandlers in the DeployCmd class.
Related to https://app.camunda.com/jira/browse/CAM-10258

CAM-10258: feat(engine): add customizable resource deployments

---

engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java
engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterTaskQueryTest.java

Related to [CAM-10730](https://app.camunda.com/jira/browse/CAM-10730)
The ticket implements the `assigneeIn` task query filter when the query is extended. This is used when executing the query on Tasklist Filters.

CAM-10730: fix(engine): task query assignee in filter can be extended

---

engine-spring/compatibility-test-spring4/pom.xml
engine-spring/compatibility-test-spring5/pom.xml
engine-spring/core/pom.xml
engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringBeansResolverFactory.java
engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringProcessEngineConfiguration.java
engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/ScriptTaskTest.java
engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/Testbean.java
engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/scripttask/ScriptTaskTest-applicationContext.xml

Allow to execute bean (i.e. Spring beans) methods from a script task  (for example JavaScript or Groovy).
Makes available all beans managed by the Spring container by implementing the `org.camunda.bpm.engine.impl.scripting.engine.Resolver` and `org.camunda.bpm.engine.impl.scripting.engine.ResolverFactory` interfaces.
This solution was suggested by Thorben Lindhauer on the Camuda Forum:
[Inability to Access Spring Beans in Input/Output Mapping Script](https://forum.camunda.org/t/inability-to-access-spring-beans-in-input-output-mapping-script/3310).
It will solve the JIRAissue CAM-4222.
Now it is configured to register in the `org.camunda.bpm.engine.spring.SpringProcessEngineConfiguration` class, method `initScripting()`.
It could be perhaps implemented as a community extension, imolemented …

CAM-10853: feat(engine): allow to call Spring bean methods from script tasks

---

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/context/Context.java
engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/AtomicOperationInvocation.java
engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandContextInterceptor.java
engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandInvocationContext.java
engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ProcessDataLoggingContext.java
engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobHelper.java
engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/test/TestHelper.java
engine/src/test/java/org/camunda/bpm/engine/test/logging/ProcessDataLoggingContextTest.java
engine/src/test/java/org/camunda/bpm/engine/test/logging/TestApplicationReusingExistingEngine.java
engine/src/test/java/org/camunda/bpm/engine/test/util/ProcessEngineLoggingRule.java
engine/src/test/resources/org/camunda/bpm/engine/test/logging/ProcessDataLoggingContextTest.shouldLogFailureFromEventSubprocessInSubprocessTaskContext.bpmn20.xml
engine/src/test/resources/org/camunda/bpm/engine/test/logging/deployment-reusing-existing-engine.xml

* log activityId, applicationName, businessKey, processInstanceId,
definitionId, and tenantId for process-related executions
* preserve context for logging in JobExecutor in exception case
* make context properties configurable (all but businessKey enabled by default)
related to [CAM-10798](https://app.camunda.com/jira/browse/CAM-10798)

CAM-10798: provide process data context for logging

---

distro/tomcat/webapp-standalone/pom.xml

* module `java.xml.bind` removed from Java 9+
* add dependency on JAXB to webapp-standalone so it is provided
for the application on Tomcat
related to [CAM-10374](https://app.camunda.com/jira/browse/CAM-10374)

CAM-10374: add JAXB to webapp-standalone

---

engine-rest/engine-rest/pom.xml
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/ExceptionHandler.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/ExceptionHandlerHelper.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/ExceptionLogger.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/JsonMappingExceptionHandler.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/JsonParseExceptionHandler.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/ProcessEngineExceptionHandler.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/RestExceptionHandler.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/UserRestServiceInteractionTest.java

* Add a Camunda Commons `BaseLogger` based Exception logger for the engine Rest API;
* Refactor and cleanup rest exception logging;
* Add a dependency to camunda-commons-testing in the engine-rest project;
* Add logging rule test coverage in engine-rest.
* Remove old `slf4j` and `logback` versions. They are not needed since the `httpclient` was bumped to a newer version (reason for having them).
Related to [CAM-10805](https://app.camunda.com/jira/browse/CAM-10805)

CAM-10805: chore(rest): ensure correct rest exception log levels

---

engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java

* Document the steps to add a TaskQuery filter that supports Tasklist filtering.
Related to [CAM-10732](https://app.camunda.com/jira/browse/CAM-10732)

CAM-10732: chore(engine): add javadoc for task query properties

---

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricActivityInstanceQueryDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricCaseActivityInstanceQueryDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricDecisionInstanceQueryDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricDetailQueryDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricExternalTaskLogQueryDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIdentityLinkLogQueryDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentQueryDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogQueryDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceQueryDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricVariableInstanceQueryDto.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricActivityInstanceRestServiceQueryTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricCaseActivityInstanceRestServiceQueryTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricDecisionInstanceRestServiceQueryTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricDetailRestServiceQueryTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricExternalTaskLogRestServiceQueryTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIdentityLinkLogRestServiceQueryTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIncidentRestServiceQueryTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceQueryTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricTaskInstanceRestServiceQueryTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricVariableInstanceRestServiceQueryTest.java

Related to [CAM-6554](https://app.camunda.com/jira/browse/CAM-6554)

CAM-6554: feat(rest): query historic queries without tenant id

---

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AssignTaskCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ClaimTaskCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CompleteTaskCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DelegateTaskCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteTaskCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ResolveTaskCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SaveTaskCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetTaskOwnerCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetTaskPriorityCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SubmitTaskFormCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmmn/cmd/CompleteCaseExecutionCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskManager.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ModificationUserOperationLogTest.java
engine/src/test/java/org/camunda/bpm/engine/test/history/useroperationlog/UserOperationLogTaskServiceAndBeanTest.java
engine/src/test/java/org/camunda/bpm/engine/test/history/useroperationlog/UserOperationLogTaskTest.java

[![CAM-10962](https://badgen.net/badge/JIRA/CAM-10962/0052CC)](https://app.camunda.com/jira/browse/CAM-10962)
Fixes the problem that task deletion would always generate an op log entry, regardless by which user command it is triggered. There should only be a dedicated task delete op log entry if the triggering command is the task deletion command. If a task gets deleted "indirectly", e.g. via instance modification, then only the op log of the triggering command should be written.

CAM-10962: prevent task op log on instance modification

---

engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/script/SpinScriptTaskSupportTest.java
engine/src/main/java/org/camunda/bpm/engine/impl/scripting/SourceExecutableScript.java

[![CAM-11090](https://badgen.net/badge/JIRA/CAM-11090/0052CC)](https://app.camunda.com/jira/browse/CAM-11090)
- reverts 8e99804534cc6d51d03d13f6b678d12bce4ae8b7
- Javascript compilation needs to be implemented more carefully; it looks
like a compiled script is tied to its scripting engine and running
multiple compiled scripts in succession (as we do to define the S function)
only works when scripts have been compiled with the same engine
related tO CAM-11090, CAM-10506

CAM-11090: disable javascript compilation

---

engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/script/SpinJRubyScriptTaskTest.java
engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/script/SpinScriptTaskSupportTest.java
engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/script/SpinScriptTaskSupportWithAutoStoreScriptVariablesTest.java

[![CAM-11090](https://badgen.net/badge/JIRA/CAM-11090/0052CC)](https://app.camunda.com/jira/browse/CAM-11090)
- JRuby tests are not isolated because they leak process variables between
process instances and definitions
- the problem is documented in CAM-11114
- this commit relaxes a test assertion to avoid test failure because
of this
related to CAM-11090, CAM-11114

CAM-11090: relax test assertion

---

typed-values/pom.xml

[![CAM-10583](https://badgen.net/badge/JIRA/CAM-10583/0052CC)](https://app.camunda.com/jira/browse/CAM-10583)
typed values moved to platform in 7.12.0 version
so the version changed from 1.x.y/commons to 7.z/platform
Keep in mind that during the creation of the PR, the `camunda.version.old` is still `7.11.0` ([CAM-11032](https://jira.camunda.com/browse/CAM-11032)) so the check finishes with a warning since 7.11.0 version doesn't exist for `typed-values`. This will be resolved when the version is adjusted to `7.12.0`
```
---- current
[INFO] --- clirr-maven-plugin:2.8:check-no-fork (all) @ camunda-commons-typed-values ---
[INFO] Comparing to version: 7.11.0
Downloading: https://app.camunda.com/nexus/content/groups/internal/org/camunda/commons/camunda-commons-typed-values/7.11.0/camunda-commo …
```

CAM-10583: chore(typed-values): adjust old version for clirr comparison check

---

qa/test-old-engine/pom.xml

[![CAM-11032](https://badgen.net/badge/JIRA/CAM-11032/0052CC)](https://app.camunda.com/jira/browse/CAM-11032)
* add commons-testing (new in 7.12)
* fix 7.12.0 versions for transitive dependencies
(DMN and typed values)
* use `camunda.old.engine.version` property
related to CAM-11032

[CAM-11032] chore(qa): adjust old-engine dependencies

---

engine-plugins/spin-plugin/src/main/java/org/camunda/spin/plugin/impl/JsonValueSerializer.java
engine-plugins/spin-plugin/src/main/java/org/camunda/spin/plugin/impl/XmlValueSerializer.java
engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/variables/JsonDelegate.java
engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/variables/JsonValueTest.java
engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/variables/XmlValueTest.java
engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricDecisionInputInstanceEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricDecisionOutputInstanceEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricDetailVariableInstanceUpdateEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricVariableInstanceEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/VariableInstanceEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/util/TypedValueField.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/AbstractObjectValueSerializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/AbstractSerializableValueSerializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/BooleanValueSerializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/ByteArrayValueSerializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/DateValueSerializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/DoubleValueSerializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/FileValueSerializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/IntegerValueSerializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/LongValueSerlializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/NullValueSerializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/PrimitiveValueSerializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/ShortValueSerializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/StringValueSerializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/TypedValueSerializer.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/jpa/JPAVariableSerializer.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/TransientVariableTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/variables/FileValueSerializerTest.java

[![CAM-9932](https://badgen.net/badge/JIRA/CAM-9932/0052CC)](https://app.camunda.com/jira/browse/CAM-9932)
- when accessing a the deserialized value of a serialized, transient
variable, the returned typed value was non-transient
related to CAM-9932

CAM-9932: fix transient flag for serialized typed values

---

database/pom.xml

[![CAM-11100](https://badgen.net/badge/JIRA/CAM-11100/0052CC)](https://app.camunda.com/jira/browse/CAM-11100)
I adjusted the following:
1. Bumped the `com.microsoft.sqlserver:sqljdbc4` dependency, to version 4.2. 
2. Removed the `net.sourceforge.jtds:jdts` dependency. According to their official page, JDTS supports Microsoft SqlServer versions up to 2012 (http://jtds.sourceforge.net/)
Related to CAM-11100

CAM-11100: chore(database): adjust mssql jdbc driver versions

---

bom/pom.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Attachment.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Comment.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/ExternalTask.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Filter.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDetail.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricVariableInstance.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml

[![CAM-10779](https://badgen.net/badge/JIRA/CAM-10779/0052CC)](https://app.camunda.com/jira/browse/CAM-10779)
This pull request includes changes to the MyBatis Mapper XML files for a number of entities to use ".size" to retrieve the size for array lists instead of ".size()".
This prevents the "Illegal reflective access by org.apache.ibatis.ognl.OgnlRuntime java.util.Arrays exception" under JDK 13.
Updated the version of the MyBatis dependency to 3.5.3 resolve the following error under JDK 13.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ibatis.reflection.Reflector (file:/Users/marcus/.m2/repository/org/mybatis/mybatis/3.4.4/mybatis-3.4.4.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to …

CAM-10779: Fixed Illegal reflective access exception for MyBatis 

---

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/history/handler/CompositeHistoryEventHandler.java
engine/src/test/java/org/camunda/bpm/engine/test/history/AbstractCompositeHistoryEventHandlerTest.java
engine/src/test/java/org/camunda/bpm/engine/test/history/CompositeDbHistoryEventHandlerTest.java
engine/src/test/java/org/camunda/bpm/engine/test/history/CompositeHistoryEventHandlerTest.java
engine/src/test/java/org/camunda/bpm/engine/test/history/DefaultHistoryEventHandlerTest.java

[![CAM-10650](https://badgen.net/badge/JIRA/CAM-10650/0052CC)](https://app.camunda.com/jira/browse/CAM-10650)
* Use an instance of `CompositeHistoryEventHandler` as the default `HistoryEventHandler`;
* Provide a list property for adding custom HistoryEventHandlers;
* Provide a flag property to enable/disable the `DbHistoryEventHandler`;
Related to [CAM-11217](https://jira.camunda.com/browse/CAM-11217)
Note: I originally implemented this in the scope of the main ticket (CAM-10650). However, separating it makes more sense.

CAM-11217: feat(engine): set default composite history event handler 

---

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/repository/ProcessDefinitionQueryDto.java

[![CAM-11231](https://badgen.net/badge/JIRA/CAM-11231/0052CC)](https://app.camunda.com/jira/browse/CAM-11231)
- Allow for extensibility similar to org.camunda.bpm.engine.rest.dto.runtime.modification.ProcessInstanceModificationInstructionDto, org.camunda.bpm.engine.rest.dto.runtime.StartProcessInstanceDto and many others.
- Some uses are builders extending the class to either allow full configuration or setting user selected defaults, facades, factories or integrations with search engines that need to create custom queries programmatically.

CAM-11231: Set ProcessDefinitionQueryDto.java attributes as protected.

---

engine/src/main/java/org/camunda/bpm/engine/impl/migration/instance/MigratingActivityInstance.java
engine/src/test/java/org/camunda/bpm/engine/test/history/CustomHistoryEventHandlerTest.java
engine/src/test/java/org/camunda/bpm/engine/test/util/ProcessEngineConfigurator.java

[![CAM-11250](https://badgen.net/badge/JIRA/CAM-11250/0052CC)](https://app.camunda.com/jira/browse/CAM-11250)
- fixes that a migrate event is fired for the history of a process
instance (instead of an update event)
- adds tests for all migrate events
related to CAM-11250

CAM-11250: correct history event on instance migration

---

parent/pom.xml

[![CAM-11387](https://badgen.net/badge/JIRA/CAM-11387/0052CC)](https://app.camunda.com/jira/browse/CAM-11387)
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-i …

CAM-11387: [SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/migration/history/MigrationHistoricProcessInstanceTest.java

[![CAM-11380](https://badgen.net/badge/JIRA/CAM-11380/0052CC)](https://app.camunda.com/jira/browse/CAM-11380)
Related to CAM-11380

fix(engine): populate historic process instance state during migration

---

engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/type/DateDataTypeTransformer.java
engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/type/DmnDataTypeTransformerTest.java

[![CAM-11412](https://badgen.net/badge/JIRA/CAM-11412/0052CC)](https://app.camunda.com/jira/browse/CAM-11412)
An exception is thrown when there is an attempt to convert a (Scala FEEL) `ZonedTime` data type to `java.util.DateTime`.
Related to CAM-11412

CAM-11412: chore(dmn): add limitation on date transformer

---

engine-dmn/pom.xml
pom.xml

[![CAM-11471](https://badgen.net/badge/JIRA/CAM-11471/0052CC)](https://app.camunda.com/jira/browse/CAM-11471)
* Move the `feel-scala` version property to the root pom of the platform project, so that it is grouped together with other Camunda-maintained side-projects;
* Remove unused `scalatest-maven-plugin` in the DMN root pom's plugin management section.
Related to CAM-11471

CAM-11471: chore(feel): move feel-scala version property

---

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobManager.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/BoundaryTimerNonInterruptingEventTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobAcquisitionBackoffIdleTest.java

[![CAM-8724](https://badgen.net/badge/JIRA/CAM-8724/0052CC)](https://app.camunda.com/jira/browse/CAM-8724)
* Fix bug that executes Timer jobs whose DueDate is earlier than the sum of the Current Time and the JobExecutor wait time.
Related to CAM-8724

CAM-8724: fix(engine): timer jobs are executed on time

---

engine-rest/engine-rest-openapi/src/main/templates/main.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/AttachmentDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/MultiFormAttachmentDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/attachment/create/post.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/attachment/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/attachment/{attachmentId}/data/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/attachment/{attachmentId}/delete.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/attachment/{attachmentId}/get.ftl

[![CAM-11551](https://badgen.net/badge/JIRA/CAM-11551/0052CC)](https://app.camunda.com/jira/browse/CAM-11551)
Related to CAM-11551
**Note**: 
1. The GET `/task/attachment/get-task-attachment-data/` produces a `byte stream`. Some feedback, if things were done correctly, would be great.
2. The POST `/task/{id}/attachment/create` endpoint should accept a `binary` parameter called `content`. This is not the case in the docs. It would be good if we can discuss what is the correct approach here.

CAM-11551: feat(open-api): add task attachment endpoints

---

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/PriorityDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/RetriesDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/CompleteExternalTaskDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExtendLockOnExternalTaskDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExternalTaskBpmnError.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExternalTaskFailureDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/FetchExternalTaskTopicDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/FetchExternalTasksDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/LockedExternalTaskDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/SetRetriesForExternalTasksDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/fetchAndLock/post.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/retries-async/post.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/retries/put.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/bpmnError/post.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/complete/post.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/errorDetails/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/extendLock/post.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/failure/post.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/priority/put.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/retries/put.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/unlock/post.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/{varName}/get.ftl

* Add OpenAPI documentation for operations on External Task (excluding
querying and counting);
* Add missing Jackson links.
Related to CAM-11540, CAM-11709

CAM-11709: feat(rest): add external task operation openapi endpoints

---

distro/run/assembly/resources/start.sh
distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunConfiguration.java
distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunRestConfiguration.java
distro/run/pom.xml
distro/run/qa/integration-tests/pom.xml
distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/AutoDeploymentIT.java
distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/ComponentAvailabilityIT.java
distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/ProductionConfigurationIT.java
distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/SqlAvailabilityIT.java
distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/util/SpringBootManagedContainer.java
distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/webapps/LoginIT.java
distro/run/qa/runtime/pom.xml

[![CAM-11665](https://badgen.net/badge/JIRA/CAM-11665/0052CC)](https://app.camunda.com/jira/browse/CAM-11665)
- avoids copying the unpacked run distribution into the test classpath
via the maven resources plugin
- copying lost the file permissions for the startup scripts,
so the integration tests failed
related to CAM-11665

CAM-11665: make integration tests run on Unix systems

---

distro/wildfly/modules/src/main/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml

[![CAM-11456](https://badgen.net/badge/JIRA/CAM-11456/0052CC)](https://app.camunda.com/jira/browse/CAM-11456)
Use sub-modules org.jboss.metadata.common and org.jboss.metadata.web instead of former existing org.jboss.metadata.

CAM-11456: Adjust module reference for WildFly 19.x

---

engine-rest/engine-rest-openapi-generator/src/main/java/org/camunda/bpm/engine/rest/openapi/generator/impl/TemplateParser.java

7.X(.0-alphaY) version doesn't exist in the manual docs during
development of a new version =>
the docs links are built with `latest` version
Related to CAM-11715

fix(rest-openapi): fix docsVersion for alpha releases

---

engine-rest/engine-rest-openapi/README.md
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/retries-async/post.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/delete/post.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/suspended-async/post.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/modification-async/post.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/delegate/post.ftl

* rename async operations to prevent collisions with generated C# clients
* rename delegate operation as `delegate` is reserved word in C# clients
Related to CAM-11749

CAM-11749: adjust async operation ids

---

engine/src/main/java/org/camunda/bpm/engine/HistoryService.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricExternalTaskLog.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricJobLog.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/UserOperationLogEntry.xml
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricActivityInstanceAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricDetailAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricExternalTaskLogAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricIdentityLinkLogAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricIncidentAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricJobLogAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricProcessInstanceAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricVariableInstanceAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/UserOperationLogAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyEndTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyStartTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeHierarchicalTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeNonHierarchicalTest.java
qa/test-db-instance-migration/test-fixture-72/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java
qa/test-db-instance-migration/test-fixture-72/src/main/java/org/camunda/bpm/qa/upgrade/scenarios/histperms/HistoricInstancePermissionsWithoutProcDefKeyScenario.java
qa/test-db-instance-migration/test-migration/pom.xml
qa/test-db-instance-migration/test-migration/src/test/java/org/camunda/bpm/qa/upgrade/scenarios7130/histperms/HistoricInstancePermissionsAuthorizationTest.java

Enforces Historic Process Instance Authorizations for the following queries:
* Historic Incident
* Job Log
* External Task Log
* User Operation Log
Parent Ticket: CAM-11189

Enforce Historic Process Instance Authorizations for more queries

---

distro/run/core/pom.xml

- the version (5.0.4) pulled in via json-smart overrid the version
(7.1) pulled in via jersey and created an inconsistency in
dependency versions
related to CAM-11803

chore(run): exclude asm dependency from test scope

---

engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.decision.history.sql
engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql

* Set NVARCHAR as the data type for the ROOT_PROCESS_INSTANCE_ID_ columns in ACT_GE_BYTEARRAY, ACT_HI_DEC_IN and ACT_HI_DEC_OUT.
Related to CAM-11116

CAM-11116: fix(db): set correct oracle db column type

---

engine-dmn/bom/pom.xml
qa/test-db-instance-migration/test-fixture-710/pom.xml
qa/test-db-instance-migration/test-fixture-711/pom.xml
qa/test-db-instance-migration/test-fixture-712/pom.xml
qa/test-db-instance-migration/test-fixture-713/pom.xml
qa/test-db-instance-migration/test-fixture-73/pom.xml
qa/test-db-instance-migration/test-fixture-74/pom.xml
qa/test-db-instance-migration/test-fixture-75/pom.xml
qa/test-db-instance-migration/test-fixture-76/pom.xml
qa/test-db-instance-migration/test-fixture-77/pom.xml
qa/test-db-instance-migration/test-fixture-78/pom.xml
qa/test-db-instance-migration/test-fixture-79/pom.xml

- this triggers the execution as soon as the plugin is configured
anywhere in the POM hierarchy
- this was the case when we added the dependency plugin to the release
parent
related to CAM-10419

CAM-10419: do not configure execution in plugin mgmt

---

qa/test-old-engine/pom.xml

- this suite uses the tests at tag 7.12.0 which are not adapted
to OpenJPA 2 yet
- this change can be reverted as soon as we move the old engine version
to 7.13.0
related to CAM-11669

CAM-11669: use OpenJPA 1 for old-engine tests

---

qa/test-db-instance-migration/test-migration/pom.xml
qa/test-db-rolling-update/create-new-engine/pom.xml
qa/test-db-rolling-update/test-old-engine/pom.xml

- avoids that these executions are accidentally triggered as soon
as the dependency plugin is activated in the build in any way (e.g.
via command line or via another pom in the hierarchy)
related to CAM-10419

CAM-10419: remove dependency plugin execution from mgmt sections

---

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/FilterEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/JsonUtil.java
engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterPropertiesTest.java

Ensure that a Tasklist Filter with no properties defined is stored correctly.
Related to CAM-11109

CAM-11109: fix empty properties filter

---

distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunRestConfiguration.java
distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunCorsProperty.java
distro/run/core/src/test/java/org/camunda/bpm/run/test/AbstractRestTest.java
distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsAccessControlHeadersTest.java
distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsAuthenticationTest.java
distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationDisabledTest.java
distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationEnabledAllowedOriginConfiguredTest.java
distro/run/core/src/test/java/org/camunda/bpm/run/test/config/https/HttpsConfigurationEnabledTest.java

* execute CORS filter before authentication filter
* do not forward CORS preflight request to succeding filter
* allow all HTTP methods that are used by Camunda REST API
Related to CAM-11840, CAM-11885

fix(run): fix CORS with authentication behavior

---

qa/large-data-tests/pom.xml
qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/util/EngineDataGenerator.java

- since optimize changed the type of op logs it exports, the test setup
must be adapted accordingly
- doubles the heap size; in a local H2 setup I could observe the max heap
size being approached and the garbage collector becoming very busy
related to CAM-11899

CAM-11899: fix large data tests

---

distro/license-book/src/main/resources/license-book.txt

Why the big diff?
* Run introduced quite a number of new Java dependencies
* The frontend part is now fully generated
* In many cases, it contains the text of the license for every dependency
* It currently includes both production and dev dependencies
related to CAM-11764

CAM-11764: update for 7.13

---

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExternalTaskManager.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/ExternalTask.xml
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/FetchExternalTaskAuthorizationTest.java

- leads to bad query plans as the database cannot push the pagination
much into the query plan when distinct is present
- must be applied with caution: distinct can only be omitted when we do not
join another table
related to CAM-11887

CAM-11887: remove distinct from fetch and lock on postgres

---

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/deployment-query-params.ftl
engine-rest/engine-rest-openapi/src/main/templates/lib/commons/external-task-query-params.ftl
engine-rest/engine-rest-openapi/src/main/templates/lib/commons/process-definition-query-params.ftl
engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.ftl

* OpenAPI supports `array` type in query parameters and
resolves them to idIn=val1&idIn=val2
* the REST API expects a comma-separated lists idIn=val1,val2
Related to CAM-11934

fix(rest-openapi): fix string arrays definitions in query parameters

---

pom.xml
spring-boot-starter/pom.xml
spring-boot-starter/starter-qa/pom.xml

- modules with webapp dependencies should not be built as part of the
distro profile, because that profile is run in the platform-ASSEMBLY
build, at which point the webapps have not been built yet
- See the Run and Tomcat distro builds for the same pattern, e.g.
distro/tomcat/pom.xml builds the Tomcat webapp only in the distro-ce
profile
related to CAM-11950

CAM-11950: separate Spring boot build into assembly and distro

---

distro/jbossas7/pom.xml

* Revert the merging of the JBoss distro module 'distro' and 'distro-ce' profiles since it
creates a cycle in the Maven modules build hierarchy by requiring the
Webapps during the ASSEMBLY phase (uses the 'distro' profile), which breaks the build.
Related to CAM-11950

CAM-11950: fix(jboss): revert distro and distro-ce profile merge

---

engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java
engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/ManagementAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentTelemetryConfigurationTest.java

* renamed to `telemetryInitialized`
* considered only for the initial value of the telemetryEnabled db property
Related to CAM-12023

chore(engine): adjust telemetry configuration property

---

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/VariableQueryParameterDto.ftl

The property designated for the name of the variable had the wrong (duplicate) property name, causing the generated class to miss the property for the name of the variable.
related to CAM-12098

[CAM-12098] fix(openapi-template): corrected VariableQueryParameterDto property for the name of the variable

---

engine-dmn/feel-scala/pom.xml
engine-dmn/feel-scala/src/test/resources/logback-test.xml
engine-dmn/pom.xml

- we already use logback as our slf4j implementation in other modules
(e.g. engine)
- that way, we only maintain a single logging dependency
related to CAM-12120

CAM-12120: replace log4j with logback

---

engine/src/main/java/org/camunda/bpm/engine/impl/el/ExpressionManager.java

- fixes concurrency issues with lazy initialization in #getCachedElResolver,
due to which it was possible that the resolver object could
be created but not yet initialized when being accessed by another thread
- see https://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html
related to CAM-12106

CAM-12106: make el resolver volatile

---

distro/run/core/pom.xml

- with the update to Spring Boot 2.3.1, Spring Boot no longer always
brings the JAXB API; only some profiles in the jersey dependencies
that are activated with Java 11+ include those APIs. Since we build
Run with Java 8 and intend to operate with any Java version, this
will create issues when operating it with Java 11+
- the fix adds a direct JAXB dependency so that we always include
it in the Run distro regardless which Java version is used to build it
- This commit uses the Jakarta artifact of the JAXB API. This is
a different artifact than the one we e.g. use with Spin. I did this,
because the Jakarta artifacts are newer and Spring Boot uses the Jakarta
artifacts itself. E.g. the jaxb-api version is now managed via the
Spring Boot BOM. This should avoid some cases in which the JAXB API …

CAM-12187: add direct JAXB-API dependency

---

engine/src/main/java/org/camunda/bpm/engine/impl/repository/DefaultDeploymentHandler.java
engine/src/test/java/org/camunda/bpm/engine/test/api/repository/ProcessApplicationDeploymentTest.java

* using the `ProcessDefinitionQuery` to fetch definitions results in
parsing the model and caching the result in the `DeploymentCache`;
thus we should avoid using it on engine/application startup to
prevent previous versions of models being parsed and in the cache
related to CAM-11956

fix(engine): prevent caching of procDefs on app resume

---

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/IncidentDto.ftl

Fix error on java client IncidentDtodesirialization:
```
Cannot deserialize value of type `java.time.OffsetDateTime` from String "262e7d86-d650-11ea-bae9-0242ac170007": Failed to deserialize java.time.OffsetDateTime:
through reference chain: java.util.ArrayList[0]->com.example.model.IncidentDto["rootCauseIncidentId"]
```

[CAM-12269] fix(openapi) correct format of IncidentDto.rootCauseIncidentId 

---

CONTRIBUTING.md

small error fixed in the url
related to CAM-12268

[CAM-12268] fix(docs): the easypick tasks url has been corrected in docs.

---

engine-dmn/feel-juel/pom.xml
parent/pom.xml
pom.xml
qa/performance-tests-engine/pom.xml

- consumes updated maven-shade-plugin configuration so that third-party
NOTICE files are concatenated
related to CAM-12182

CAM-12182: bump release parent 2.2.0

---

engine-dmn/feel-juel/pom.xml
parent/pom.xml
pom.xml
qa/performance-tests-engine/pom.xml

- fixes that maven-shade-plugin is not executed for every module
related to CAM-12182

CAM-12182: bump release parent 2.2.1

---

engine/src/main/java/org/camunda/bpm/engine/impl/core/variable/scope/AbstractVariableScope.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/DecisionEvaluationUtil.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/MessageCorrelationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/TransientVariableTest.java

- on any API that accepts local variables (e.g. message correlation,
DelegateExecution)
- removes redundant code in abstract variable scope; the distinction between
transient and non-transient can be made in a single place
(#setVariableLocal) to which all variable-setting APIs delegate
related to CAM-10520

CAM-10520: do not persist transient local variables

---

engine/src/main/java/org/camunda/bpm/engine/ManagementService.java
engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java
engine/src/main/java/org/camunda/bpm/engine/impl/ManagementServiceImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/IsTelemetryEnabledCmd.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentTelemetryConfigurationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/telemetry/TelemetryDefaultConfigTest.java

* enabling to fetch null whether the telemetry is already configured or
not
* extend tests
Related to CAM-12377

chore(engine): adjust initilizeTelemetry config to null by default

---

engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceTest.java

I am not sure why this test was left out, I would assume that it wasn't on purpose as nobody touch it for more than 7 years.

chore(engine): adjust RuntimeServiceTest case

---

engine/src/test/java/org/camunda/bpm/engine/test/standalone/telemetry/TelemetryTaskWorkerMetricsTest.java

when history level differs from default
Related to CAM-12401

fix(test): ensure database schema creation before test

---

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java

as wrapper Boolean is not supported when parsing xml process engine
configuration
Related to CAM-12406

fix(engine): change property setter to primitive

---

engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java
engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/CommandCounter.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryLogger.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Data.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Product.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetryReporter.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/telemetry/TelemetryTaskWorkerMetricsTest.java

- implements retries for sending the telemetry
- retries are configurable in the engine configuration
- lets the toggling of the telemetry fail if the timer for reporting cannot be scheduled
- makes the reporting period configurable via engine configuration and makes the first telemetry request after five minutes
related to CAM-12115

CAM-12115: refactor telemetry reporting

---

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/util/WebApplicationUtil.java
engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java
engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteLicenseKeyCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetLicenseKeyCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/LicenseKeyData.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/LicenseKeyUtil.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/license/LicenseKeyTelemetryTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/ProcessEngineDetailsTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryRegistryCounterTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterSuiteElement.java

* adds utility function in REST API to add license key data to telemetry
* adds license key data object in telemetry
* handles setting and deleting license keys via ManagementService with
regards to telemetry data
related to CAM-12379

chore(engine+rest): add license key to telemetry

---

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetryReporter.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/ConnectUtil.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/telemetry/TelemetryTaskWorkerMetricsTest.java
pom.xml
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/telemetry/TelemetryConnectPluginTest.java

* introduce a process engine configuration property
* default value 15 seconds
* apply the configuration on the telemetry request
Related to CAM-12421

CAM-12421: chore(engine): add telemetry request timeout configuration

---

engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/TelemetryConfigureCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandCounterInterceptor.java
engine/src/main/java/org/camunda/bpm/engine/impl/metrics/MetricsRegistry.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/TelemetryUtil.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryDynamicDataTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryMultipleEnginesTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryStaticDataTest.java

* introduce collecting telemetry data flag in telemetry and metrics
registry for (commands and metrics data)
* update flags on start up, telemetry toggle and report
* add null check for metrics registry in telemetry
Related to CAM-12432

CAM-12432М chore(engine): collect dynamic data only when telemetry is enabled

---

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/TaskAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/task/StandaloneTasksAndCmmnDisabledTest.java

- the proc def table is used for checking authorizations and for
applying definition-related filters to the task query. When both are
used, a single join is sufficient
- Which join type to use
- cmmn and standalone tasks disabled: inner join
- else
- or query: left join
- and query
- authorization enabled: left join
- authorization disabled: inner join
related to CAM-11277, CAM-12410

CAM-12410: use a single proc def join in task query

---

engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/TelemetryConfigureCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryLogger.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetryReporter.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryDynamicDataTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryMultipleEnginesTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
engine/src/test/java/org/camunda/bpm/engine/test/util/NoInitMessageBootstrapEngineCommand.java
engine/src/test/java/org/camunda/bpm/engine/test/util/NoInitMessageInMemProcessEngineConfiguration.java
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/telemetry/TelemetryConnectPluginTest.java

* schedules an initial message to ET containing the status of
telemetry (enabled, disabled, undefined) if the reporter
is active and the message has not been sent yet once
* chooses an initial message delay based on the flag being `null` (3 hours)
or set (5 minutes) to get feedback soon when changed from `null` to
anything else and to make test data more unlikely (3 hours)
* reschedules the reporter task either when flag was null or changes
from `false` to `true`
related to CAM-12459

chore(telemetry): send initial message to ET

---

engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetryReporter.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java

CAM-12557: fix(telemetry): skip sending initial report during engine close

---

engine-rest/engine-rest-jaxrs2/src/main/java/org/camunda/bpm/engine/rest/impl/FetchAndLockHandlerImpl.java

- Loggers in FetchAndLockHandlerImpl triggered **critical** sonar issue `printf-style format strings should not lead to unexpected behavior at runtime` because of ambiguous argument.
- Fixed other Sonar issues/code styles in FetchAndLockHandlerImpl class

Fix critical sonar issues in FetchAndLockHandlerImpl

---

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/util/WebApplicationUtil.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/PlatformTelemetryRegistry.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java
engine/src/main/java/org/camunda/bpm/engine/test/ProcessEngineRule.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java

* pushes the app server info from servlet contexts to a
container-wide telemetry registry
* fetches the app server info from the container-wide registry
until it is provided (if ever)
related to CAM-12499

fix(telemetry): reliably fetch app server info

---

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/CompleteExternalTaskDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExtendLockOnExternalTaskDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExternalTaskFailureDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/HandleExternalTaskDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/LockExternalTaskDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/lock/post.ftl
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/CompleteExternalTaskDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/ExternalTaskFailureDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/HandleExternalTaskDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/LockExternalTaskDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/externaltask/ExternalTaskResource.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/externaltask/impl/ExternalTaskResourceImpl.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskRestServiceInteractionTest.java

* Allow for an External Task to be locked without a fetch operation through the Rest API.
* Document the new External Task Lock Rest API endpoint in the OpenAPI documentation.
* Deprecate the `ExtendLockOnExternalTaskDto` methods `#getNewDuration()` and `#setNewDuration(long)` in favor of the new `lockDuration` property.
Related to CAM-12652, CAM-7170
:information_source: Note: this PR is currently based on #1089 since it relies on the code contributed by that PR.

CAM-12652: feat(rest): lock external task without fetch

---

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/CompleteExternalTaskDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExtendLockOnExternalTaskDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExternalTaskFailureDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/HandleExternalTaskDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/LockExternalTaskDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/lock/post.ftl
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/CompleteExternalTaskDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/ExternalTaskFailureDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/HandleExternalTaskDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/LockExternalTaskDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/externaltask/ExternalTaskResource.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/externaltask/impl/ExternalTaskResourceImpl.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskRestServiceInteractionTest.java
engine/src/main/java/org/camunda/bpm/engine/ExternalTaskService.java
engine/src/main/java/org/camunda/bpm/engine/impl/ExternalTaskServiceImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/HandleExternalTaskCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/LockExternalTaskCmd.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/CompleteExternalTaskAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/ExtendLockOnExternalTaskAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/GetErrorDetailsAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/HandleExternalTaskAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/HandleExternalTaskBpmnErrorAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/HandleExternalTaskFailureAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/HandleLockedExternalTaskAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/LockExternalTaskAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/SetExternalTaskRetriesAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/UnlockExternalTaskAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
engine/src/test/java/org/camunda/bpm/engine/test/concurrency/CompetingExternalTaskLockingTest.java
engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrencyTestCase.java

* Allow for an External Task to be locked without a fetch operation.
Related to CAM-12651, CAM-7170

CAM-12651: feat(engine): lock external task without fetch

---

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/LockExternalTaskDto.ftl
engine/src/main/java/org/camunda/bpm/engine/ExternalTaskService.java
engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java

* An already locked task, can be locked again by the same worker. In
this case, the Lock API behaves like the Extend Lock API.
Related to CAM-12651, CAM-7170

CAM-12651: fix(engine): clarify lock external task api behavior

---

engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringTransactionInterceptor.java
engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringTransactionsProcessEngineConfiguration.java
engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/transaction/crdb/CrdbTxRetryOnCommitDelegate.java
engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/transaction/crdb/CrdbTxRetryOnCommitTest.java
engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/transaction/CrdbTransactionIntegrationTest.crdbFailureProcess.bpmn20.xml
engine/src/main/java/org/camunda/bpm/engine/impl/cfg/JtaProcessEngineConfiguration.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSession.java
engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/JtaTransactionInterceptor.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/DatabaseUtil.java
engine/src/test/java/org/camunda/bpm/engine/impl/cfg/JtaTransactionInterceptorTest.java

* When CockroachDB is used, a CRDB concurrency error may occur on transaction commit.
To ensure that these errors are still detected as OLEs, we must catch them and wrap
them in a CrdbTransactionRetryException
Related to CAM-12524

CAM-12524: fix(engine): detect crdb errors on tx commit

---

distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/util/SpringBootManagedContainer.java
parent/pom.xml
spring-boot-starter/starter-test/pom.xml
spring-boot-starter/starter/pom.xml

* keeps JUnit 4 legacy support in `starter-test`
* removes optional Spring Security dependency from `starter`
to not enable auto-configuration of web security for web-based
integration tests (newly enabled by Spring Boot 2.4's
`ManagementWebSecurityAutoConfiguration`)
* makes Run ITs more robust in case of REST-only startup since
no default `DispatcherServlet` is registered anymore listening
for requests on "/" in this scenario
related to CAM-12148

chore(spring-boot-starter): bump to Spring Boot 2.4

---

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DefaultJobRetryCmd.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/IncidentTest.java

- when retry configuration is R0/..., the incident message was not
populated because the incident was already created before the
exception message was set in the job entity
related to CAM-12769

CAM-12769: populate incident message when job has 0 retries

---

.ci/daily/Jenkinsfile
.ci/scripts/check-sql-scripts.sh
Jenkinsfile

* Add trigger for pipeline - once a day on SCM change;
* Add check-sql-scripts stage;
* Add shell script for check-sql-scripts stage;
* Add H2 QA stages;
* Define matrix stages;
* Define structure of DB matrix stages;
* Define JDK matrix stages;
* [TMP] Disable `when` block, so that stages are always executed;
* [TMP] Disable non-H2 DB stages, so we get a successfull view of the pipeline;
* [TMP] Disable stashing/unstashing of artifacts, we want to obtain a successful execution first.
Related to CAM-12712, CAM-12763

CAM-12763: feat(qa): add daily pipeline scaffold

---

engine/src/main/java/org/camunda/bpm/engine/impl/AbstractQueryVariableValueCondition.java
engine/src/main/java/org/camunda/bpm/engine/impl/AbstractVariableQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/CompositeQueryVariableValueCondition.java
engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/HistoricTaskInstanceQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/HistoricVariableInstanceQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/ProcessInstanceQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/QueryVariableValue.java
engine/src/main/java/org/camunda/bpm/engine/impl/SingleQueryVariableValueCondition.java
engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/externaltask/TopicFetchInstruction.java
engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/StringValueSerializer.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Commons.xml
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/VariableInstanceQueryTest.java
engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricVariableInstanceTest.java
qa/test-db-instance-migration/test-fixture-714/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java
qa/test-db-instance-migration/test-fixture-714/src/main/java/org/camunda/bpm/qa/upgrade/variable/EmptyStringVariableScenario.java
qa/test-db-instance-migration/test-fixture-714/src/main/resources/org/camunda/bpm/qa/upgrade/variable/oneTaskProcess.bpmn20.xml
qa/test-db-instance-migration/test-migration/src/test/java/org/camunda/bpm/qa/upgrade/scenarios7150/variable/EmptyStringVariableTest.java
qa/test-db-rolling-update/rolling-update-util/src/main/java/org/camunda/bpm/qa/rolling/update/TestFixture.java
qa/test-db-rolling-update/rolling-update-util/src/main/java/org/camunda/bpm/qa/rolling/update/scenarios/variable/EmptyStringVariableScenario.java
qa/test-db-rolling-update/test-old-engine/src/test/java/org/camunda/bpm/qa/rolling/update/variable/EmptyStringVariableTest.java
webapps/src/main/java/org/camunda/bpm/cockpit/impl/plugin/base/dto/query/AbstractProcessInstanceQueryDto.java
webapps/src/main/java/org/camunda/bpm/cockpit/impl/plugin/base/dto/query/ProcessDefinitionQueryDto.java
webapps/src/main/java/org/camunda/bpm/cockpit/impl/plugin/base/sub/resources/ProcessDefinitionResource.java
webapps/src/main/java/org/camunda/bpm/cockpit/impl/plugin/resources/ProcessInstanceRestService.java

* allows to differentiate empty string variable values
from null values on Oracle DBs (empty strings are persisted
as NULL there) by using the TEXT2_ column
related to CAM-12592

chore(engine): enable empty string variable value on Oracle

---

parent/pom.xml

* resolves several security issues with Tomcat version <9.0.38
related to CAM-12775

chore(dependencies): bump Tomcat to 9.0.40

---

model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/instance/dc/FontImpl.java
model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/instance/dc/Font.java

In this commit we change method name from `SetUnderline` to `setUnderline` in both interface and implementation

refactor(Font): rename method in camelCase style

---

engine-cdi/pom.xml
engine-cdi/src/test/java/org/camunda/bpm/engine/cdi/test/dmn/DmnJuelTest.java
engine-cdi/src/test/resources/org/camunda/bpm/engine/cdi/test/dmn/JuelTest.dmn
engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/dmn/DmnJuelTest.java
engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/dmn/Testbean.java
engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/dmn/DmnJuelTest-applicationContext.xml
engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/dmn/JuelTest.dmn

Test cases show that CDI & Spring beans can be resolved in the DMN Engine using JUEL.

test(spring/cdi): add dmn juel context tests

---

.ci/daily/Jenkinsfile

* Add wildfly subsystem unit test stage
* Fix runMaven method calls for instance migration and large data stages
Related to CAM-12778, CAM-12908

CAM-12908: feat(ci): add wildfly subsystem unit test stage

---

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/AnnotationDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/IncidentDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/incident/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/incident/{id}/annotation/delete.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/incident/{id}/annotation/put.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/incident/{id}/get.ftl
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/IncidentDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/repository/impl/IncidentResourceImpl.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/IncidentResource.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/IncidentRestServiceInteractionTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/IncidentRestServiceQueryTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIncidentRestServiceQueryTest.java

* adds set and clear annotation methods to incident REST endpoint
* adds OpenAPI description of the new methods
related to CAM-13061

chore(engine-rest): add annotation methods to incident

---

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobManager.java
qa/large-data-tests/pom.xml
qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/SetJobRetriesAsyncTest.java
qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/util/BatchModificationJobHelper.java
qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/util/EngineDataGenerator.java

* Ensure that more than 2100 jobs can be queried on MS SqlServer;
* Add a large-data-set test.
Related to CAM-12852

CAM-12852: fix(engine): set retries to more than 2100 jobs

---

engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/{id}/deployed-start-form/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/deployed-form/get.ftl
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/repository/impl/ProcessDefinitionResourceImpl.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/impl/TaskResourceImpl.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/util/ContentTypeUtil.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessDefinitionRestServiceInteractionTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractGetDeployedFormCmd.java
engine/src/test/java/org/camunda/bpm/engine/test/api/form/FormServiceTest.java
engine/src/test/resources/org/camunda/bpm/engine/test/api/form/DeployedCamundaFormsProcess.bpmn20.xml
engine/src/test/resources/org/camunda/bpm/engine/test/api/form/start.form.json
engine/src/test/resources/org/camunda/bpm/engine/test/api/form/task.form.json

* allows form keys starting with `camunda-forms:`
* distinguishes the form's content type in the REST API
related to CAM-13075

feat(engine+rest): serve camunda-forms form keys

---

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml

NOT IN (SELECT ...) does not perform well on PostgreSQL. It uses a plain sub-plan which has a bad performance. See https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_NOT_IN
related to CAM-12938

fix(engine): improve bad performing sql query for historic task query

---

engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/report/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/{id}/deployed-start-form/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/deployed-form/get.ftl

* adds a macro for multiple content types per response
* uses the new macro for endpoints with multiple possible types* adds the second media type return value manually as
extending the macro for this one-time use is overly complex
related to CAM-13106

fix(openapi): enable multiple return types in responses

---

engine/src/main/java/org/camunda/bpm/engine/history/HistoricTaskInstanceQuery.java
engine/src/main/java/org/camunda/bpm/engine/impl/HistoricTaskInstanceQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/json/JsonTaskQueryConverter.java
engine/src/main/java/org/camunda/bpm/engine/task/TaskQuery.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterTaskQueryTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryExpressionTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryOrTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/HistoricTaskInstanceQueryOrTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/HistoricTaskInstanceQueryTest.java

* adds query option to filter for (historic) tasks that do not have a due date
* adds query option to JSON task query converter for task filters
related to CAM-13153

feat(engine): add withoutDueDate filter for tasks

---

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/task-query-params.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskQueryDto.ftl
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceQueryDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceQueryTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricTaskInstanceRestServiceQueryTest.java

* adds query option to filter for (historic) tasks that do not have a due date
* adds query option to task query converter for task filters
related to CAM-13154

feat(engine-rest): add withoutDueDate filter for tasks

---

engine/src/main/java/org/camunda/bpm/engine/history/HistoricTaskInstanceQuery.java
engine/src/main/java/org/camunda/bpm/engine/impl/HistoricTaskInstanceQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/QueryOperator.java
engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/task/TaskQuery.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Commons.xml
engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterTaskQueryTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryOrTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/HistoricTaskInstanceQueryTest.java

* adds query option to filter for (historic) tasks that do not have a variable
with a value like the given one
* adds query option to JSON task query converter for the same in task filters
related to CAM-13172

feat(engine): add valueNotLike filter for task variables

---

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java

* returns the withoutDueDate query option for task queries
in filters only when enabled
related to CAM-13154

fix(engine-rest): return withoutDueDate option when enabled

---

engine/src/main/java/org/camunda/bpm/engine/test/ProcessEngineRule.java

Document that deployments have to be made known to the procesEnginRule to be cleaned up

Document cleanup behaviour for not annotation deployments

---

engine/pom.xml
engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryLogger.java
engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/EngineUtilLogger.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/ParseUtil.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/ProductPropertiesUtil.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/PropertiesUtil.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/StringUtil.java
engine/src/main/resources/org/camunda/bpm/engine/product-info.properties
engine/src/test/java/org/camunda/bpm/engine/impl/util/PropertiesUtilTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/ProcessEngineDetailsTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/db/SchemaLogEnsureSqlScriptTest.java
engine/src/test/java/org/camunda/bpm/engine/test/util/TestconfigProperties.java

* Validate telemetry data before sending. Product version, name, and edition must not be null or empty. Telemetry installation id must be a
valid UUIDv4 String.
* Store the product version in a properties file for use-cases where the manifest file is not available (e.g. during testing).
Related to CAM-13018

CAM-13018: fix(engine): validate telemetry data

---

qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/telemetry/TelemetryConnectPluginTest.java

* Provide a valid UUIDv4 installation id for the  test in the Engine-IT tests;
Related to CAM-13018

CAM-13018: fix(qa): adjust test installation id

---

engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyEndTest.java

chore(engine): exclude flaky test on MariaDB and CRDB

---

engine/src/main/java/org/camunda/bpm/engine/ExternalTaskService.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java
engine/src/main/java/org/camunda/bpm/engine/impl/externaltask/ExternalTaskLogger.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExternalTaskEntity.java
engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.externalTaskWithNestedErrorEventDefinitionVariableExpression.bpmn20.xml

* continues the default behavior of `ExternalTask#failed` when
the evaluation of an error event definition fails due
to the expression evaluation
related to CAM-13305

feat(engine): improve ext task handleFailure robustness

---

qa/test-db-rolling-update/test-old-engine/src/test/java/org/camunda/bpm/qa/rolling/update/variable/EmptyStringVariableTest.java

* removes Oracle specifics from the empty string variable test
since it behaves the same now on all DBs with 7.15 being the old engine
related to CAM-13378

chore(qa): adjust Oracle empty string test for 7.16

---

engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringExpressionManager.java

I had to create a SpringExpressionManager Bean and found it very confusing, that the constructor has two arguments that are nullable and change semantics if they are  ...  so at least for the "regular" use case of adding all beans of the spring context to the Camunda expression management, I'd prefer to just pass the applicationContext.

add additional constructor to SpringExpressionManager

---

engine/src/main/java/org/camunda/bpm/engine/impl/migration/instance/MigratingActivityInstance.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/migration/MigrationEventSubProcessTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/migration/MigrationUserTaskTest.java

A scope user task (with attached boundary event) which was migrated to a non-scope user task did not show up after the migration when querying for activity instance statistics by process definition id (like we do in Cockpit on process definition runtime view). This was caused by not setting the `PvmExecutionImpl#isActive` flag of the parent execution to the value of the to be removed child execution.
related to CAM-13354

fix(engine): fix after migration, user task is not active anymore

---

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/authorization-query-params.ftl
engine-rest/engine-rest-openapi/src/main/templates/main.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/authorization/AuthorizationCheckResultDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/authorization/AuthorizationCreateDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/authorization/AuthorizationDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/authorization/AuthorizationUpdateDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/authorization/check/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/authorization/count/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/authorization/create/post.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/authorization/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/authorization/options.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/authorization/{id}/delete.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/authorization/{id}/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/authorization/{id}/options.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/authorization/{id}/put.ftl

* The `OPTIONS /authorization` and `OPTIONS /authorization/{id}` endpoints are documented in a single page. I created two separate files for them. They both contain a comment to notify devs to also update the other one.
* The `PUT /authorization/{id}` endpoint uses a subset of the `AuthorizationDto` properties. I decided to create a separate `AuthorizationUpdateDto` file for this purpose. This would prevent confusion about what properties are available for update. I also added a comment in the `AuthorizationDto` file to also update the `AuthorizationUpdateDto` if any changes are made. Other options that I considered were:
* Create a parent FTL file with the `AuthorizationUpdateDto` properties, and extend the `AuthorizationDto` from it (I could also refactor the Java classes as well). …

CAM-11523: feat(openapi): add authorization endpoints

---

engine/src/main/java/org/camunda/bpm/engine/runtime/EventSubscriptionQuery.java

The correct `EventType` for Compensation events is `compensate`. (See https://github.com/camunda/camunda-bpm-platform/blob/master/engine/src/main/java/org/camunda/bpm/engine/impl/event/EventType.java#L32)
Related to CAM-13428

CAM-13428: chore(engine): fix eventType filter javadoc

---

engine/src/main/java/org/camunda/bpm/engine/impl/batch/variables/BatchSetVariablesHandler.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractSetVariableCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetExecutionVariablesCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/core/CoreLogger.java
engine/src/main/java/org/camunda/bpm/engine/impl/core/variable/VariableUtil.java
engine/src/main/java/org/camunda/bpm/engine/impl/core/variable/scope/AbstractVariableScope.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/VariableInstanceEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/util/TypedValueField.java
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/migration/MigrationContextSwitchClassesTest.java
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/jobexecutor/SetVariablesAsyncTest.java
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/jobexecutor/classes/MyPojo.java
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/util/AbstractFoxPlatformIntegrationTest.java

If a class is only present in a process application, the object variable cannot be deserialized in the job execution handler.
related to CAM-13435

fix(engine): fix set variables batch operation classloading bug

---

engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java
engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/SequentialJobAcquisitionRunnable.java
engine/src/main/java/org/camunda/bpm/engine/impl/util/ClassLoaderUtil.java
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/classloading/jobexecution/ClassloadingByJobPriorityTest.java
qa/integration-tests-engine/src/test/resources-tomcat/org/camunda/bpm/integrationtest/functional/classloading/jobexecution/engineWithAcquireJobsByPriority.xml
qa/integration-tests-engine/src/test/resources-wildfly/org/camunda/bpm/integrationtest/functional/classloading/jobexecution/engineWithAcquireJobsByPriority.xml

* On WildFly 12+, whem `jobExecutorAcquireByPriority` is set to true,
the wrong classloader is used, and job acquisition fails. This commit
fixes this issue by explicitly switching to the ProcessEngine
classloader.
Related to CAM-9913

CAM-9913: fix(engine): use correct classloader with priority job acquisition

---

webapps/package-lock.json
webapps/package.json

Was introduced when we still used `husky`.
related to CAM-13493
⚠️ Regenerate `package-lock.json` before the merge.

chore(webapps): remove lint-staged package

---

engine/src/main/java/org/camunda/bpm/application/impl/ProcessApplicationScriptEnvironment.java
engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/scripting/engine/DefaultScriptEngineResolver.java
engine/src/main/java/org/camunda/bpm/engine/impl/scripting/engine/ScriptEngineResolver.java
engine/src/main/java/org/camunda/bpm/engine/impl/scripting/engine/ScriptingEngines.java
engine/src/main/java/org/camunda/bpm/engine/impl/scripting/env/ScriptingEnvironment.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/scripttask/ScriptTaskGraalJsTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/scripting/AbstractScriptEnvironmentTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/scripting/EnvScriptResolutionTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/scripting/ScriptEngineNameJavaScriptTest.java
pom.xml
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/deployment/war/beans/GroovyProcessEnginePlugin.java
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/scriptengine/AbstractScriptEngineSupportTest.java
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/scriptengine/GroovyScriptEngineSupportTest.java
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/scriptengine/JavascriptScriptEngineSupportGraalJsTest.java
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/scriptengine/JavascriptScriptEngineSupportNashornTest.java
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/scriptengine/JavascriptScriptEngineSupportTest.java
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/scriptengine/PythonScriptEngineSupportTest.java
qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/scriptengine/RubyScriptEngineSupportTest.java

* bumps Spin to latest snapshot version
* adds engine configuration option for script engine resolver
* provides a default resolver
* resolves environment scripts for script engine language as a fallback
if none are found for the script's language itself (e.g. looks for
'ecmascript' environment scripts for 'graal.js' script language)
* adds Spin scripting QA tests
related to CAM-13517

chore(engine): enable custom script engine resolution

---

distro/jbossas7/webapp-standalone/pom.xml
distro/tomcat/webapp-standalone/pom.xml

* adds commons-dbcp as compile dependency to standalone webapps
since they reference `org.apache.commons.dbcp.BasicDataSource`
in the `applicationContext.xml`
related to CAM-13674

chore(distro): add commons-dbcp to standalone webapps

---

engine/src/test/java/org/camunda/bpm/engine/test/bpmn/scripttask/ScriptTaskGraalJsTest.java

* adjusts the `ScriptTaskGraalJsTest` to account for Spin environment
scripts being executed before the actual test script which can lead
to different error messages due to the Spin script trying to access
a Java function
related to CAM-13517

chore(test): adjust script test to consider Spin env script

---

engine/src/main/java/org/camunda/bpm/engine/impl/calendar/DateTimeUtil.java

* removes an unused import from `joda-time` that additionally causes
WLS compat tests to fail due the class referenced by this unused import
not being present on joda-time 1.2.1 (which is introduced by the profiles
for this compat test)
related to CAM-13694

chore(engine): remove unused import from joda-time

---

spring-boot-starter/starter/pom.xml

- it is not needed
related to CAM-13771

CAM-13771: remove spring-boot-loader-tools dependency

---

parent/pom.xml
pom.xml

* Version 2.9.1 of the maven-javadoc-plugin has a bug when running on
JDK 11. To run releases on JDK 11, version 3.0.1 must be used, where
the plugin is fixed.
Related to CAM-13763

CAM-13763: chore(maven): bump javadoc plugin version

---

quarkus-extension/engine/deployment/src/main/resources/application.properties
quarkus-extension/engine/qa/src/test/java/org/camunda/bpm/engine/cdi/test/interceptor/CompleteTaskInterceptor.java
quarkus-extension/engine/qa/src/test/java/org/camunda/bpm/engine/cdi/test/interceptor/StartProcessInterceptor.java

chore(quarkus-extension): disable engine-cdi interceptors by default

---

engine-cdi/src/main/java/org/camunda/bpm/engine/cdi/annotation/BusinessProcessScoped.java

A `BusinessProcessScoped` bean instance must be `Serializable`.
related to CAM-13744

chore(engine-cdi): fix javadocs of BusinessProcessScoped annotation

---

distro/sql-script/pom.xml
distro/sql-script/src/test/java/org/camunda/bpm/sql/test/SqlScriptTest.java
distro/sql-script/src/test/resources/properties-from-pom.properties

* adds a test for comparing a Liquibase changelog-based database
installation with an installation by current create scripts for
equality with regards to the resulting database schema
related to CAM-13782

chore(sql-script): test equality of Liquibase installation

---

engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml

* Adds a SQL Server-specific database hint to use loop joins when
deleting from the byte array table to prevent full table scans
for foreign key constraint checks on database instances with a
small load. This will lead to less locked rows and therefore also
a much lower possibility of running into deadlocks. Loop joins
will be used automatically on SQL Server for instances with
higher loads.
related to CAM-13683

fix(engine): prevent deadlock on SQL Server in cleanup

---

.gitignore
engine/src/main/java/org/camunda/bpm/container/impl/metadata/PropertyHelper.java
engine/src/test/java/org/camunda/bpm/container/impl/metadata/PropertyHelperTest.java
quarkus-extension/engine/deployment/src/main/java/org/camunda/bpm/quarkus/engine/extension/deployment/impl/CamundaEngineProcessor.java
quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/CamundaEngineConfigTest.java
quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/ConfigurableProcessEngineTest.java
quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/ManagedJobExecutorTest.java
quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/helper/ProcessEngineAwareExtension.java
quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/id/ConfigureDbIdGeneratorTest.java
quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/persistence/conf/ChooseDatasourceConfigurationTest.java
quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/persistence/conf/ChooseDefaultDatasourceConfigurationTest.java
quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/persistence/conf/ChooseNotExistingDatasourceConfigurationTest.java
quarkus-extension/engine/deployment/src/test/resources/job-executor-application.properties
quarkus-extension/engine/qa/src/test/java/org/camunda/bpm/engine/cdi/test/CdiProcessEngineTestCase.java
quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/CamundaEngineConfig.java
quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/CamundaJobExecutorConfig.java
quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/QuarkusProcessEngineConfiguration.java
quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/CamundaEngineConfig.java
quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/CamundaEngineRecorder.java
quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/CamundaJobExecutorConfig.java
quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/ManagedJobExecutor.java

CAM-13811: feat(quarkus): use a separate camunda thread pool

---

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java

Close prepared statement that identifies CockroachDB as used database.
related to CAM-13817

fix(engine): fix resource leak when bootstrapping the engine

---

quarkus-extension/engine/deployment/src/main/java/org/camunda/bpm/quarkus/engine/extension/deployment/impl/CamundaEngineProcessor.java
quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/deployment/ProcessEngineMultipleDeploymentTest.java
quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/deployment/ProcessEngineSingleDeploymentTest.java
quarkus-extension/engine/deployment/src/test/resources/org/camunda/bpm/quarkus/engine/test/deployment/simpleServiceTaskProcess.bpmn
quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/event/CamundaEngineStartupEvent.java
quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/CamundaEngineRecorder.java
quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/ProcessEngineStartEvent.java

* Define a ProcessEngineStartEvent. This event is fired after the process engine is bootstrapped. It can be used to perform process engine deployments.
Related to CAM-13631

CAM-13631: feat(quarkus): add process engine start event

---

engine/src/main/java/org/camunda/bpm/engine/impl/json/JsonTaskQueryConverter.java
engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterTaskQueryTest.java

* initializes OR queries in task queries upon deserialization from JSON
to flag them as OR queries before query options are set; options that
rely on this flag can be set correctly this way
related to CAM-13572

fix(engine): correct OR task query JSON conversion

---

distro/run/pom.xml
engine-rest/assembly/assembly-war-was9.xml
engine-rest/assembly/assembly-war-wls.xml
engine-rest/assembly/pom.xml
engine-rest/engine-rest-jaxrs2/pom.xml
engine-rest/engine-rest/pom.xml
parent/pom.xml

* bumps Jersey to 2.34 in REST API and web apps artifacts for WLS and WAS9
* bumps Jersey to 2.34 in Run manually as Spring Boot 2.5.x does not provide
this update yet
* adds explicit HK2 injection framework dependency for REST API on WAS9 & WLS
due to Jersey version bump above 2.26 (no HK2 included by default anymore)
related to CAM-13717

fix(engine): bump Jersey to 2.34

---

webapps/ui/cockpit/client/scripts/components/callActivityOverlays/callActivityOverlay.js

* remove tooltips when clicking on call activity navigation. These tooltips might otherwise block overlays if they are only hidden.
Related to CAM-13887

fix(cockpit): remove hidden blocking tooltips

---

webapps/camunda-bpm-sdk-js/lib/api-client/resources/process-instance.js

feat(sdk-js): add correlate message batch operation

---

distro/run/distro/assembly.xml
distro/tomcat/distro/assembly.xml
distro/wildfly/distro/assembly.xml

* removes the `META-INF` folder from the `configuration` folder in the
final distribution artifacts
related to CAM-13961

chore(run): remove META-INF folder from artifact

---

Jenkinsfile
internal-dependencies/pom.xml

- this pulled in SLF4J 2.0.0-alpha if built with Java 11 (not with Java 8)
- Our libraries are built and tested with SLF4J 1.7 so we should use that
related to CAM-13962

CAM-13962: exclude Hikari's SLF4J from Jboss standalone webapp

---

engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/BreakingScalaFeelBehaviorTest.java
pom.xml

this fixes an issue with unary-test comparison not being evaluated
without braces
Related to CAM-11269

chore(feel): bump feel scala version

---

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/get.ftl
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java
engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstanceQuery.java
engine/src/main/java/org/camunda/bpm/engine/impl/AbstractVariableQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/ProcessInstanceQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/QueryVariableValue.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceQueryOrTest.java
engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java

* Adds `processInstanceBusinessKeyIn` criterion to `HistoricProcessInstanceQuery` to select historic process instances whose business key is in the given set.
* Reduces SQL complexity for variable value criteria by... 
* `LEFT JOIN` only for distinct variable names
* removing condition duplicates
related to CAM-14107

feat(engine): add businessKeyIn criterion to hist proc inst query 

---

engine/src/main/java/org/camunda/bpm/engine/impl/tree/ActivityExecutionHierarchyWalker.java

This commit fixes little typo in class `org.camunda.bpm.engine.impl.tree.ActivityExecutionHierarchyWalker`. We change argument name `tupel` to `tuple` and method `createTupel` to `createTuple`. It seems that this fix does not break the compatibility, because method `createTuple` is used solely in ActivityExecutionHierarchyWalker and it is not mentioned in tests.

fix: fix typo in argument and method name (tupel -> tuple)

---

engine-rest/engine-rest/pom.xml
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/mapper/JacksonConfigurator.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/mapper/Java8DateTimePojo.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/mapper/Java8DateTimeTest.java

* adds Jackson JSR-310 dependency to REST API
* adds JavaTimeModule to object mapper in the REST API
related to CAM-13937

fix(engine-rest): handle Java 8 Time objects

---

webapps/camunda-commons-ui/lib/widgets/bpmn-viewer/cam-widget-bpmn-viewer.js
webapps/camunda-commons-ui/lib/widgets/bpmn-viewer/cam-widget-bpmn-viewer.less
webapps/ui/cockpit/client/scripts/directives/processDiagram.html
webapps/ui/cockpit/client/scripts/directives/processDiagram.js
webapps/ui/cockpit/client/scripts/pages/process-definition.html
webapps/ui/cockpit/client/scripts/pages/process-instance.html
webapps/ui/cockpit/client/scripts/pages/processDefinition.js
webapps/ui/cockpit/client/scripts/pages/processInstance.js

related to CAM-14099
based on https://github.com/camunda/camunda-bpm-platform/pull/1655
You might wonder "why are we wrapping the callbacks in an Object instead of passing it directly?" - and you would be right.
AngularJS defeated me and I could not figure it out. When passing the function directly, it was called, but the arguments were lost along the way. I have no Idea what AngularJS is doing and at this point, I just wrapped it to get a behavior I could understand

feat(selection): limit selection to elements on current plane

---

qa/test-db-instance-migration/test-migration/src/test/java/org/camunda/bpm/qa/upgrade/scenarios7130/restart/RestartProcessIntanceWithInitialVariablesTest.java

The `isInitial` flag for historical details of set variables is always set to `true` during the start phase.
related to CAM-14007

test(qa/migration): fix assertions of hist details `#isInitial` flags

---

spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/CookieNameIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteCustomValueIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteDisabledIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteEnabledIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteOptionLaxIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteOptionStrictIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SecureDisabledIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SecureEnabledIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/headersec/it/properties/HttpHeaderSecurityAbsenceIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/headersec/it/properties/HttpHeaderSecurityPresenceIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/headersec/it/properties/HttpHeaderSecurityValueIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/CookieNameIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SameSiteCustomValueIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SameSiteDisabledIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SameSiteEnabledIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SameSiteOptionLaxIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SameSiteOptionStrictIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SecureDisabledIT.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SecureEnabledIT.java

* Uses `@DirtiesContext` for ITs that use a specific configuration
that is never reused. This way, the cache and therefore also the
memory footprint are kept smaller
related to CAM-14143

chore(spring-boot-starter): disable cache for specific ITs

---

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/GetFormKeyCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/form/FormDefinition.java
engine/src/main/java/org/camunda/bpm/engine/impl/form/handler/DefaultFormHandler.java
engine/src/main/java/org/camunda/bpm/engine/impl/form/handler/DefaultStartFormHandler.java
engine/src/main/java/org/camunda/bpm/engine/impl/form/handler/DefaultTaskFormHandler.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ProcessDefinitionEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/task/TaskDefinition.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/start/StartEventCamundaFormDefinitionParseTest.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/usertask/UserTaskCamundaFormDefinitionParseTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/deploy/BPMNParseListenerTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/deploy/DelegatingBpmnParseListener.java
engine/src/test/resources/org/camunda/bpm/engine/test/standalone/deploy/bpmn.parse.listener.camunda.cfg.xml

- introduces a new FormDefinition pojo that contains the form
related configuration of a task or start event
- removes the duplicated parsing logic in BpmnParse and the task form
handler
related to CAM-14153

CAM-14153: let parse listeners modify form key via task definition

---

distro/run/assembly/assembly.xml
distro/run/assembly/pom.xml
distro/run/pom.xml
distro/run/qa/runtime/pom.xml

* Make the Groovy scripting engine available by default in Camunda Run.
Related to CAM-11913

CAM-11913: feat(run): add groovy lib to run distro

---

distro/run/core/pom.xml

* Include the Camunda Connect process engine plugin to Camunda Run by default.
Related to CAM-11837

CAM-11837: feat(run): include the connect plugin by default

---

engine-plugins/spin-plugin/src/main/java/org/camunda/spin/plugin/impl/SpinConfiguration.java
engine-plugins/spin-plugin/src/main/java/org/camunda/spin/plugin/impl/SpinProcessEnginePlugin.java
engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/impl/SpinProcessEnginePluginConfigurationTest.java
engine-plugins/spin-plugin/src/test/resources/custom.camunda.cfg.xml
pom.xml

* Add configuration options to the Spin process engine plugin. With
these options, users can enable/disable safe xml processing, if the
XML dataformat is used.
Related to CAM-14011, CAM-14141
:warning: The CI will fail until the related Spin PR is merged.

CAM-14141: fix(spin): add safe xml processing

---

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TableDataManager.java

Get rid of duplicate code.
TableDataManager
Duplicate code:
persistentObjectToTableNameMap.put(FilterEntity.class, "ACT_RU_FILTER");
Duplicate map key :
persistentObjectToTableNameMap.put(HistoricVariableInstanceEntity.class, "ACT_HI_DETAIL");

chore(engine): get rid of duplicate code

---

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/DecisionDefinition.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/DecisionRequirementsDefinition.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/EventSubscription.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Execution.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/ExternalTask.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricActivityInstance.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDecisionInstance.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDetail.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricExternalTaskLog.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIdentityLinkLog.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricJobLog.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricVariableInstance.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/JobDefinition.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/ProcessDefinition.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Statistics.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/UserOperationLogEntry.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml
webapps/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/incident.xml
webapps/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/processDefinition.xml
webapps/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/processInstance.xml

* replaces the IN construct on MySQL by OR used in the queries
when including authorization checks
related to CAM-14092

fix(engine): replace IN by OR for MySQL authorization joins

---

distro/run/assembly/resources/production.yml
distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunConfiguration.java
distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunAdministratorAuthorizationProperties.java
distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunCorsProperty.java
distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunProperties.java
distro/run/core/src/test/java/org/camunda/bpm/run/test/config/identity/AdminAuthorizationConfigurationTest.java
distro/run/core/src/test/resources/application-test-admin-auth-enabled.yml

* Add the Administrator Authorization Plugin to Camunda Run by default.
* Add a template LDAP configuration in the production.yml config file.
Related to CAM-13447

CAM-13447: feat(run): add admin authorization plugin

---

engine-plugins/connect-plugin/src/main/java/org/camunda/connect/plugin/impl/ConnectorParseListener.java
engine-plugins/connect-plugin/src/test/java/org/camunda/connect/plugin/ConnectProcessEnginePluginTest.java
engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java
engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskSupportTest.java
engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskSupportTest.businessRuleTask.bpmn20.xml
engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskSupportTest.messageEndEvent.bpmn20.xml
engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskSupportTest.messageIntermediateEvent.bpmn20.xml
engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskSupportTest.sendTask.bpmn20.xml

- fixes the case for intermediate/end message events, business rule tasks,
send tasks that are implemented as external tasks
- restructures the code how service-task-like activities are parsed
and handed to parse listeners; avoids that we create a 'dummy' activity
that also goes to parse listeners that remains unused; this comes at the cost
of some duplicated code, but I think my solution has the better tradeoff
than hackfixing this in the current solution
related to CAM-14308

CAM-14308: make extension properties available for all external tasks

---

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/behavior/BpmnActivityBehavior.java
engine/src/main/java/org/camunda/bpm/engine/impl/pvm/delegate/ActivityExecution.java
engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/gateway/InclusiveGatewayTest.java
engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/gateway/InclusiveGatewayTest.AsyncConcurrentExecutions.ParallelInclusiveGateway.bpmn
qa/test-db-instance-migration/test-fixture-716/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java
qa/test-db-instance-migration/test-fixture-716/src/main/java/org/camunda/bpm/qa/upgrade/pvm/AsyncJoinScenario.java
qa/test-db-instance-migration/test-fixture-716/src/main/resources/org/camunda/bpm/qa/upgrade/pvm/asyncInclusiveGateway.bpmn20.xml
qa/test-db-instance-migration/test-fixture-716/src/main/resources/org/camunda/bpm/qa/upgrade/pvm/asyncParallelGateway.bpmn20.xml
qa/test-db-instance-migration/test-migration/src/test/java/org/camunda/bpm/qa/upgrade/scenarios7130/restart/RestartProcessIntanceWithInitialVariablesTest.java
qa/test-db-instance-migration/test-migration/src/test/java/org/camunda/bpm/qa/upgrade/scenarios7160/externaltask/ExternalTaskFailureLogTest.java
qa/test-db-instance-migration/test-migration/src/test/java/org/camunda/bpm/qa/upgrade/scenarios7170/pvm/AsyncJoinTest.java
qa/test-db-instance-migration/test-migration/src/test/java/org/camunda/bpm/qa/upgrade/scenarios730/boundary/NonInterruptingBoundaryEventScenarioTest.java
qa/test-db-instance-migration/test-migration/src/test/java/org/camunda/bpm/qa/upgrade/scenarios780/CreateProcessInstanceWithJsonVariablesTest.java
qa/test-db-instance-migration/test-migration/src/test/java/org/camunda/bpm/qa/upgrade/scenarios790/CreateProcessInstanceWithJsonVariablesTest.java
qa/test-db-instance-migration/test-migration/src/test/java/org/camunda/bpm/qa/upgrade/util/ActivityInstanceAssert.java

Ensures that executions that are joined in a parallel or inclusive gateway
are ended synchronously before executing the next logical operation,
e.g. taking the next transition. This ensures the order of operations at
join gateways, even if a gateway is marked as `async-after`. Otherwise,
executions can get stuck unnecessarily at another inclusive join.
related to CAM-14116

fix(engine): end joined executions synchronously

---

examples/invoice/src/main/resources/reviewInvoice.bpmn

Sometimes it is helpful to show the removal times in a chain of subprocesses.
This missing detail should be added to the codebase for further references.

Add the removal time for the subprocess of the invoice example

---

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/deploy/BPMNParseListenerTest.java

- set tenantId in ProcessDefinitionEntity before calling BpmnParseListener
related to CAM-14171

fix(engine): set tenantId for BpmnParseListener

---

engine/src/test/java/org/camunda/bpm/engine/test/api/variables/JavaSerializationTest.java
typed-values/src/main/java/org/camunda/bpm/engine/variable/Variables.java
typed-values/src/test/java/org/camunda/bpm/engine/test/api/variable/VariableApiTest.java

* introduces `isTransient` method to `TypedValueBuilder` interface and its
implementation classes
* preserves the transient flag of builders in `Variables.untypedValue` method
CAM-14189

fix(typed-values): preserve transient flag for builders

---

webapps/pom.xml
webapps/src/test/java/org/camunda/bpm/webapp/impl/security/auth/ContainerAuthenticationFilterTest.java
webapps/src/test/java/org/camunda/bpm/webapp/impl/security/filter/csrf/CsrfPreventionFilterTest.java

- remove powermock
- update mockito to v4.3.1 & add mockito-inline for static tests
- fix deprecated mockito apis
- migrate tests from powermock to mockito
related to CAM-14389

chore(engine): webapps jdk17 support

---

engine-plugins/pom.xml
engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/variables/HistoricVariableJsonSerializationWithValidationTest.java
engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/variables/JsonSerializationWithValidationOnMultipleEnginesTest.java
pom.xml

- update mockito to v4.3.1
- fix deprecated mockito apis
- update jaxb-impl to v2.3.6
- use latest camunda-spin
related to CAM-14365

chore(engine): camunda-engine-plugin-spin jdk17 support

---

distro/jboss/webapp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml

Excludes `resteasy-jackson2-provider` and `jackson-datatype-jsr310` system modules to ensure that the libraries local to the deployment are used.
related to CAM-14419

fix(webapp/wildfly): exclude system modules for export feature

---

qa/test-db-rolling-update/create-new-engine/pom.xml
qa/test-db-rolling-update/create-old-engine/pom.xml
qa/test-db-rolling-update/test-old-engine/pom.xml
qa/test-old-engine/pom.xml

- were disabled during 7.17 development due to incompatibility
of H2 1.4 and 2.0
related to CAM-14434

CAM-14434: enable rolling-update and old-engine tests for h2

---

.ci/daily/Jenkinsfile

* Disable Docker GHA trigger stage due to GitHub API issues.
* Add a timeout option as an optimization so there are no infinite retried by the GHA invocation script.
Related to CAMTEAM-235

CAMTEAM-235: chore(ci): disable docker gha trigger stage

---

distro/run/assembly/resources/run.sh

* Fix issue where the run.sh couldn't create a run.pid file if there was whitespace on the path of the Camunda Run directory.
Related to CAM-14439

CAM-14439: fix(run): run.sh script works with whitespaces

---

distro/run/modules/swaggerui/ui/package-lock.json
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDetail.xml
engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricDetailQueryTest.java

* Add missing SQL AND operator when filtering by userOperationId and another parameter in the HistoricDetail query.
Related to CAM-14497

CAM-14497: fix(engine): add missing and sql operator

---

engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/comment/get.ftl
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/ProcessInstanceCommentResource.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/ProcessInstanceResource.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/ProcessInstanceCommentResourceImpl.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/ProcessInstanceResourceImpl.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java

This PR adds support for getting all process instance (tasks) comments from the rest api. 
This functionality is already present in the engine, but it is not exposed to the rest api. Comments can be retrieved only for specific tasks.
The relevant discussion in the forum can be found [here](https://forum.camunda.org/t/get-list-of-comments-for-a-process-instance/10772/7). 
I was not sure whether to use `/comment` or `/comments` for the endpoint. Comments in tasks are  using singular while variables in process instances use plural.

CAM-14446: feat(engine-rest): Add process instance comments rest api

---

Jenkinsfile
webapps/README.md
webapps/camunda-commons-ui/grunt/tasks/ensureLibs.js
webapps/camunda-commons-ui/index.js
webapps/package-lock.json
webapps/package.json
webapps/pom.xml
webapps/scripts/xlts.js

chore(webapps): use angularjs from xlts.dev

---

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CommandLogger.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeployCmd.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/deployment/BpmnDeploymentTest.java

bugfix: Fix query used for resolving duplicates for deployments when name is not provided
related to CAM-14536

[CAM-14536] Allow querying for last deployment when name for deployment not provided

---

engine/src/test/java/org/camunda/bpm/engine/test/bpmn/deployment/BpmnDeploymentTest.java

* The enableDuplicateFiltering flag was incorrectly refactored to true in most of the tests.
* In two new tests, the new deployment wasn't removed after the test completed.
related to CAM-14536
This PR reverts some changes of #1868

CAM-14536: fix(engine): correct flag in bpmn deployment tests

---

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Deployment.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Resource.xml
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/deployment/BpmnDeploymentTest.java

* provides jdbc type explicitly for potential `null`-value parameters
* adds test case to ensure duplicate filtering on null-name deployments
does not work
* uses automatic resource cleanup in BpmnDeploymentTest
related to CAM-14614

chore(engine): allow querying deployments w/o name

---

engine-plugins/identity-ldap/src/main/java/org/camunda/bpm/identity/impl/ldap/LdapIdentityProviderSession.java

The [`LdapIdentityProviderSession.checkPassword`](https://github.com/camunda/camunda-bpm-platform/blob/master/engine-plugins/identity-ldap/src/main/java/org/camunda/bpm/identity/impl/ldap/LdapIdentityProviderSession.java#L310) opens two LDAP-Connections: 
* One for [finding the user](https://github.com/camunda/camunda-bpm-platform/blob/master/engine-plugins/identity-ldap/src/main/java/org/camunda/bpm/identity/impl/ldap/LdapIdentityProviderSession.java#L332) and
* one for [validating its password](https://github.com/camunda/camunda-bpm-platform/blob/master/engine-plugins/identity-ldap/src/main/java/org/camunda/bpm/identity/impl/ldap/LdapIdentityProviderSession.java#L341).
The first one gets closed after the user is fetched. The second one, validating the user's password, does not get …

Closing ldap connection after password validation during checkPassword

---

distro/jboss/webapp-standalone/pom.xml
distro/run/assembly/assembly.xml
distro/run/assembly/pom.xml
distro/tomcat/assembly/assembly.xml
distro/tomcat/assembly/pom.xml
distro/tomcat/webapp-standalone/pom.xml
distro/wildfly/assembly/assembly.xml
distro/wildfly/assembly/pom.xml
distro/wildfly/modules/pom.xml
distro/wildfly/modules/src/main/modules/org/codehaus/groovy/groovy-all/main/module.xml
parent/pom.xml

* Groovy 2.5.16 is incompatible with JDK 17. Downgrade to Groovy 2.4.21 until support for JDK 17 is added to Groovy 2.5.x.
Related to CAM-14302

CAM-14302: chore(engine): downgrade groovy to 2.4.21

---

engine/src/main/java/org/camunda/bpm/engine/impl/core/variable/scope/AbstractVariableScope.java
engine/src/main/java/org/camunda/bpm/engine/impl/core/variable/scope/VariableStore.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/TransientVariableTest.java

* Prevents changing a variable's state of the `transient` attribute
to prevent unexpected variable persistence states through a "remove
and set" chain of commands. This makes the variable API core consistent
in that regard.
related to CAM-14321

fix(engine): prevent change of variable transience

---

engine/pom.xml
engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/camunda-changelog.xml
spring-boot-starter/starter-qa/integration-test-liquibase/pom.xml
spring-boot-starter/starter-qa/integration-test-liquibase/src/test/java/org/camunda/bpm/springboot/project/qa/liquibase/Application.java
spring-boot-starter/starter-qa/integration-test-liquibase/src/test/java/org/camunda/bpm/springboot/project/qa/liquibase/LiquibaseApplicationIT.java
spring-boot-starter/starter-qa/integration-test-liquibase/src/test/resources/application.properties
spring-boot-starter/starter-qa/integration-test-liquibase/src/test/resources/logback-test.xml
spring-boot-starter/starter-qa/pom.xml

* Copies upgrade scripts relevant to Liquibase into liquibase directory
on engine core compile.
* Adjusts changesets to the new location of the upgrade scripts.
* Adds a Spring Boot Starter IT that installs the DB using our Liquibase
changelog from a JAR.
related to [CAM-14629](https://jira.camunda.com/browse/CAM-14629)

fix(engine): make Liquibase work from JAR

---

engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/metrics/JobExecutorMetricsTest.java

* accounts for the case that more job errors can occur on CRDB
but doesn't enforce it since this doesn't always happen
related to CAM-13728

chore(engine): stabilize JobExecutorMetricsTest on CRDB

---

engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java

* Fixes the start time of the process instance and the query date for
"startDateOn" to be equal. Otherwise, the milliseconds between the
instance start and the query date can lead to an overflow to the next
second. This will break MySQL's seconds precision for datetime columns
and yield an unexpected instance in the test.
related to CAM-13733

chore(engine): stabilize HistoricProcessInstanceTest

---

engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/SequentialJobAcquisitionTest.java

* Waits for job execution runnables to finish first. Otherwise, they can
still set the guard to `true` after finishing the actual job execution.
Timing-wise, this can interfere with the test unnecessarily.
related to CAM-13890

chore(engine): stabilize SequentialJobAcquisitionTest

---

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java
engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/operation/PvmAtomicOperationDeleteCascadeFireActivityEnd.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/BoundaryEventInputOutputTest.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/gateway/EventBasedGatewayInputOutputTest.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/iomapping/VariableLogDelegate.java

* when the engine config flag skipOutputMappingOnCanceledActivities
is used, it should stop applying for any IO mappings performed
after the cancellation (e.g. tasks following a boundary event
or event-based gateway)
related to CAM-14456

CAM-14456: avoid propagation of skipIoMappings after cancellation

---

engine/src/main/java/org/camunda/bpm/engine/impl/util/ExceptionUtil.java
engine/src/test/java/org/camunda/bpm/engine/test/concurrency/BuiltinExceptionCodeForeignKeyConstraintViolationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/errorcode/ExceptionBuiltinCodesTest.java

Previously, the following foreign key constraint violations weren't handled for DB2:
* A non-null update of a foreign key in a child table must reference an existing primary key in the parent table.
* When a foreign key reference exists in the child table, the respective row in the parent table cannot be deleted.
related to CAM-14752

fix(engine): handle foreign key constraint violations on db2

---

engine-cdi/compatibility-test-weld2/pom.xml
engine-cdi/pom.xml

* As part of adding support for WebSphere Liberty, we need to ensure that there is test coverage for the CDI implementations that Liberty provides and Camunda supports. Liberty provides support for CDI 1.2 through Weld 2.4.8.Final.
Related to CAM-14757

CAM-14757: feat(qa): add test coverage for weld 2.4

---

database/pom.xml
qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/AbstractWebappUiIntegrationTest.java

* Add database configuration filenames for WAS Liberty in the DB profiles for H2 and PostgreSQL.
* Optimize ChromeDriver configuration. Add additional flags that make ChromeDriver more efficient in k8s/Jenkins environments. The previous configuration failed with OOM errors on WAS Liberty.
Related to CAM-14741, CAM-14756

CAM-14756: feat(qa): adjust IT tests to better support was liberty

---

engine/src/main/java/org/camunda/bpm/engine/impl/calendar/DurationHelper.java
engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/TimerDeclarationImpl.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/BoundaryTimerNonInterruptingEventTest.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
engine/src/test/java/org/camunda/bpm/engine/test/standalone/calendar/DurationHelperTest.java
engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.testFixedDateWithRepeatStartTimerEvent.bpmn20.xml

* Repeats cycles with start date one time less than defined in R
since the start date is the first repeat already.
* Uses the due date of the first timer as start date of the follow-up
repeats because that is the actual start date of the cycle.
related to CAM-14772

fix(engine): handle cycles with start date correctly

---

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/GetIdentityLinksForTaskCmd.java
engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskIdentityLinksTest.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/tasklistener/util/GetIdentityLinksTaskListener.java

fix(engine): return copied list in #getIdentityLinksForTask()

---

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/mappings.xml

This performance optimization looks so simple but it actually makes the bootstrapping of the process engine quite a bit faster: about 0,5 secs on my Macbook Pro M1. Every slower hardware (that should be a lot of systems) will profit even more. Please measure yourself and post the results.
It will also help in test suites which bootstrap the process engine multiple times (e.g. integration tests with `@DirtiesContext` in Spring Boot ) and even more in matrix builds.
The order of the mappings is crucial because mappings should be ordered so that cross-references can always be resolved by previously loaded mappings. Otherwise a BuilderException is thrown and the mapping is parsed again later.
It is actually possible to order the mappings in a way that the BuilderException is not thrown at …

[2835] chore(engine): Reorder mappings to improve loading times

---

engine-rest/engine-rest-openapi/src/main/templates/main.ftl
engine-rest/engine-rest-openapi/src/test/java/org/camunda/bpm/engine/rest/openapi/client/BasicAuthenticationTest.java

The generated ApiClient now supports BasicAuth.
See also: https://github.com/camunda-community-hub/camunda-platform-7-rest-client-java/issues/36#issuecomment-1261080124

fix(engine-rest-openapi): basic-auth-support

---

webapps/camunda-commons-ui/grunt/tasks/ensureLibs.js

On Windows, absolute file paths use backslashes instead of forward slashes. This makes the regular expressions fail to determine the npm packages from the file paths.
related to #2824

[#2824]: fix(webapps): make adding missing license headers work on windows

---

engine-plugins/identity-ldap/src/main/java/org/camunda/bpm/identity/impl/ldap/LdapConfiguration.java
engine-plugins/identity-ldap/src/main/java/org/camunda/bpm/identity/impl/ldap/LdapIdentityProviderSession.java
engine-plugins/identity-ldap/src/main/java/org/camunda/bpm/identity/impl/ldap/LdapUserQueryImpl.java
engine-plugins/identity-ldap/src/test/java/org/camunda/bpm/identity/impl/ldap/LdapDisableAuthorizationCheckTest.java
engine-plugins/identity-ldap/src/test/java/org/camunda/bpm/identity/impl/ldap/LdapGroupLargeQueryTest.java
engine-plugins/identity-ldap/src/test/java/org/camunda/bpm/identity/impl/ldap/LdapGroupQueryTest.java
engine-plugins/identity-ldap/src/test/java/org/camunda/bpm/identity/impl/ldap/LdapTestEnvironment.java
engine-plugins/identity-ldap/src/test/java/org/camunda/bpm/identity/impl/ldap/LdapTestUtilities.java
engine-plugins/identity-ldap/src/test/java/org/camunda/bpm/identity/impl/ldap/LdapUserLargeQueryTest.java
engine-plugins/identity-ldap/src/test/java/org/camunda/bpm/identity/impl/ldap/LdapUserQueryTest.java
engine-plugins/identity-ldap/src/test/resources/camunda.ldap.pages.cfg.xml

* Implements LDAPv3 Control for paged-results as defined in RFC 2696 [1].
* Pagination is disabled by default.
* Enable pagination by defining a `pageSize` in your plugin configuration.
[1] http://www.ietf.org/rfc/rfc2696.txt
related to camunda/camunda-bpm-platform#2799

feat(ldap-plugin): add support for pagination

---

.github/workflows/extract-issue-links.yml

Fixes the failed workflow run: https://github.com/camunda/camunda-bpm-platform/actions/runs/3480233918/jobs/5819763303
related to CAMTEAM-280

CAMTEAM-280: import correct secret from vault

---

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobExecutorLogger.java
engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobManager.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/BatchJobPriorityRangeTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsForPriorityRangeTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorFollowUpTest.java
engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorPriorityRangeConfigurationTest.java

fix(engine): use primitive type for job priority range config properties

---

webapps/camunda-commons-ui/grunt/tasks/ensureLibs.js

related to #2966
<details><summary>Diff CE deps.js</summary>
```diff
30c30
< @license didi@5.2.1
---
> @license didi@8.0.2
548c548
< @license moddle-xml@8.0.8
---
> @license moddle-xml@9.0.5
637c637
< @license diagram-js@8.8.0
---
> @license diagram-js@4.0.3
660a661,685
> @license didi@4.0.0
> The MIT License
> 
> Copyright (C) 2013 Vojta Jína.
> Copyright (C) 2015-present Nico Rehwaldt.
> 
> Permission is hereby granted, free of charge, to any person obtaining a copy of
> this software and associated documentation files (the "Software"), to deal in
> the Software without restriction, including without limitation the rights to
> use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
> of the Software, and to permit persons to whom the Software is furnished to do
> …
```

fix(webapps): respect license headers of different package versions

---

engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java

Remove unnecessary types and add required ones to avoid compilation errors with JDK 17+.
fixes #3057

chore(rest): improve types in filter test

---

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/SignalRestServiceImpl.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/SignalRestServiceTest.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SignalEventReceivedCmd.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/signal/SignalEventReceivedBuilderTest.java

- when execution is not found or execution is not expecting this signal, then it now throws NotFoundException instead of ProcessEngineException so that callers can handle these cases explicitly
related to camunda/camunda-bpm-platform#2949

2949: change exception type when signalling single execution

---

engine/src/main/java/org/camunda/bpm/engine/impl/identity/db/DbIdentityServiceProvider.java
engine/src/test/java/org/camunda/bpm/engine/test/api/identity/IdentityServiceAuthorizationsTest.java

* Remove the check for CREATE permission on resources USER, GROUP, and TENANT
when creating the transient objects. The `saveXYZ` methods still check this
permission when persisting the objects. The `newXYZ` methods are used by
other components (e.g. the REST API) to create transient objects, e.g. for
password policy checks. This must not require CREATE permissions as users
might otherwise not be able to modify their own passwords.
fixes #2762

fix(engine): remove permission for transient user creation

---

qa/test-db-upgrade/pom.xml
qa/test-old-engine/pom.xml

- Excludes the Jakarta tests in JDKs below 11 in `upgrade-db` and `old-engine`.
- Adds the Jakarta Transaction API on JDKs 11+ and also runs the Jakarta tests.
- The adjustments in `old-engine` become necessary with 7.20, when 7.19 becomes the old engine and brings along Jakarta tests. We could leave this out right now, technically. But it shouldn't create any harm, so I opted for already adjusting this so we're good for 7.20 already as well.

test(qa): execute Jakarta test classes on JDK 11+

---

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/deployer/BpmnDeployer.java
engine/src/test/java/org/camunda/bpm/engine/test/api/cfg/DeploymentCacheCfgTest.java

avoid creation during re-caching of processes
Related to camunda/camunda-bpm-platform#3120

fix(engine): add candidate starter identity links only for new deployments

---

distro/wildfly/modules/src/main/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml
distro/wildfly26/modules/src/main/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml
qa/wildfly-runtime/src/main/common/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml
qa/wildfly26-runtime/src/main/common/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml

* Removes the `org.jboss.as.web` module dependency from the Camunda WildFly subsystem since we only need `org.jboss.as.web-common`

chore(distro/wildfly): remove JBoss Web dependency

---

settings/intellij-idea/formatter.xml

This commit fixes optimizing imports (manually or automatically) using IntelliJ in the right order
related to: #3310

style(settings): Adjust IntelliJ formatter.xml to Make Static Imports Precede Imports

---

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/telemetry/TelemetryDataDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/telemetry/TelemetryInternalsDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/telemetry/TelemetryProductDto.ftl

- The following DTOs do not contain entries with dynamic keys but have additionalProperties=true: TelemetryProductDto TelemetryLicenseKeyDto AbstractVendorVersionInformationDto
related to: camunda/camunda-bpm-platform#3186

fix(rest): Remove additionalProperties from Unnecessary Responses

---

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/HandleExternalTaskCmd.java
engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.shouldThrowProcessEngineExceptionWhenOtherResourceIsNotFound.bpmn20.xml

prevent throwing NotFoundExceptions for other resources instead throw a ProcessEngineException
https://github.com/camunda/camunda-bpm-platform/issues/3138

fix(engine): adjust exception handling in external tasks

---

webapps/frontend/.prettierrc

* Prettier respects the `.editorconfig` file in the `camunda/camunda-bpm-release-scripts`.
* `.editorconfig` can be overridden via `.prettierrc`.
related to camunda/camunda-bpm-platform#2748

chore(webapps): prettier overrides editorconfig

---

quarkus-extension/engine/runtime/pom.xml
quarkus-extension/engine/runtime/src/main/resources/META-INF/quarkus-extension.properties
quarkus-extension/engine/runtime/src/main/resources/META-INF/quarkus-extension.yaml

- This plugin is needed to fill the missing parts in the extension descriptor

fix(quarkus): Invoke the `quarkus-extension-maven-plugin`

---

parent/pom.xml

* Bumps Spring Boot patch level to 2.7.12 and Tomcat patch level to 9.0.75 to be consistent in versions and up to date.
related to https://github.com/camunda/camunda-bpm-platform/issues/3301

chore(parent): bump Spring Boot and Tomcat versions

---

webapps/assembly/pom.xml
webapps/frontend/webpack.dev.js

related to camunda/camunda-bpm-platform#3448

chore(webpack): correct dev server proxy mapping

---

engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/SetTaskPropertyAuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancySetTaskPropertyTest.java

This fix enforces the tests of MultiTenancySetTaskPropertyTest, SetTaskPropertyAuthorizationTest to always choose dates with zero ms precision to avoid issues with MySQL TIMESTAMP or DATETIME types getting rounded.
Related to: #3477, #3154

fix(engine): Fix SetProperty & Multi-tenancy Problem with MySQL ms Precision

---

webapps/assembly/src/test/java/org/camunda/bpm/webapp/impl/util/HeaderRule.java

* Retries a failed test server start in case the port is still bound.
The start will be retried 3 times at maximum. There will be a backoff
of half a second between retries.
related to https://github.com/camunda/camunda-bpm-platform/issues/2598

chore(webapps): retry test server start when port bound

---

engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/spi/transform/DmnElementTransformHandler.java
engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/dmn/configuration/DmnEngineConfigurationBuilder.java
engine/src/main/java/org/camunda/bpm/engine/impl/dmn/transformer/DecisionDefinitionHandler.java
engine/src/test/java/org/camunda/bpm/engine/test/dmn/deployment/DecisionDefinitionTest.java

* Fix DecisionDefinitionHandler to be stateless
**historyTimeToLive** was shared between different ProcessEngineConfiguration among different unit-tests that use the same field because DefaultElementTransformHandlerRegistry has a static **handlers** map field that stored the handlers per type.
That map is shared across different ProcessEngineConfigurations. In order for this to work, all handlers need to stateless...
The fix fetches processTimeToLive from Context during the parsing time of decision instead.
Related to: #2496

fix(engine): Fix Broken Tests

---

engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/signal/SignalEventConcurrencyTest.java

* Prevents the SignalEventConcurrencyTest from running into unexpected concurrent execution of threads.
related to https://github.com/camunda/camunda-bpm-platform/issues/2904

test(engine): stabilize SignalEventConcurrencyTest

---

distro/run/modules/swaggerui/pom.xml
distro/run/modules/swaggerui/ui/.gitignore
distro/run/modules/swaggerui/ui/package-lock.json
distro/run/modules/swaggerui/ui/package.json
distro/run/modules/swaggerui/ui/tasks/license.js
distro/run/modules/swaggerui/ui/tasks/licenses/LICENSE_format
distro/run/modules/swaggerui/ui/tasks/licenses/LICENSE_toggle-selection
distro/run/modules/swaggerui/ui/webpack.config.js
engine-rest/docs/.gitignore
engine-rest/docs/package-lock.json
engine-rest/docs/pom.xml
parent/pom.xml
webapps/pom.xml

- use frontend-maven-plugin
related to #3200

chore(swaggerui): bump version

---

engine-rest/engine-rest-jakarta/src/test/java-resteasy/org/camunda/bpm/engine/rest/util/container/ResteasySpecifics.java
engine-rest/engine-rest-jakarta/src/test/java-resteasy/org/camunda/bpm/engine/rest/util/container/ResteasyUndertowServerBootstrap.java
engine-rest/engine-rest/src/test/java-jersey2/org/camunda/bpm/engine/rest/util/container/JerseyServerBootstrap.java
engine-rest/engine-rest/src/test/java-resteasy/org/camunda/bpm/engine/rest/util/container/ResteasyServerBootstrap.java
engine-rest/engine-rest/src/test/java-resteasy/org/camunda/bpm/engine/rest/util/container/ResteasyTomcatServerBootstrap.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/util/container/AbstractServerBootstrap.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/util/container/EmbeddedServerBootstrap.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/util/container/TomcatServerBootstrap.java

* Supports retrying server startups when the address is still bound. Occasionally, the OS can take more time to release the port physically after we stop our test server instance. Before we start it again for the next test class, we might have to wait and retry.
related to https://github.com/camunda/camunda-bpm-platform/issues/3535

test(engine-rest): retry server start when port still bound

---

engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/AuthorizationRevokeModeAlwaysTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/AuthorizationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/SetTaskPropertyAuthorizationTest.java
webapps/assembly/src/test/java/org/camunda/bpm/cockpit/plugin/base/authorization/AuthorizationTest.java

* Removes repeated authorization test cases (~1600) for revoke mode ALWAYS. Instead, ensures that mode ALWAYS leads equivalent queries compared to when AUTO mode triggers. The latter is well-tested, ensuring ALWAYS works as well.
related to https://github.com/camunda/camunda-bpm-platform/issues/3530

test(engine+webapps): simplify revoke ALWAYS tests

---

engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/DefaultDmnEngineConfiguration.java
engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/evaluation/ExpressionEvaluationHandler.java
engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/transform/DmnExpressionTransformHelper.java
model-api/dmn-model/src/main/java/org/camunda/bpm/model/dmn/Dmn.java
model-api/dmn-model/src/main/java/org/camunda/bpm/model/dmn/impl/DmnModelConstants.java
model-api/dmn-model/src/main/java/org/camunda/bpm/model/dmn/impl/DmnParser.java
model-api/dmn-model/src/main/resources/org/camunda/bpm/model/dmn/schema/DMN14.xsd
model-api/dmn-model/src/main/resources/org/camunda/bpm/model/dmn/schema/DMN15.xsd
model-api/dmn-model/src/main/resources/org/camunda/bpm/model/dmn/schema/DMNDI15.xsd
model-api/dmn-model/src/test/java/org/camunda/bpm/model/dmn/ExampleCompatibilityTest.java
model-api/dmn-model/src/test/resources/org/camunda/bpm/model/dmn/Example-DMN-1.4.dmn
model-api/dmn-model/src/test/resources/org/camunda/bpm/model/dmn/Example-DMN-1.5.dmn

- Add the DMN and FEEL 1.4 + 1.5 namespaces to the model API.
- Add the DMN 1.4 + 1.5 XSD schemas. Note that there is only a DMN-DI schema for version 1.5 because version 1.4 uses the DMN-DI of version 1.3. 
- Keep the DMN 1.3. namespace as the default/latest version until the Camunda Modeler supports the new namespace (see [here](https://github.com/camunda/product-hub/issues/1041)). Otherwise, we would create new DMNs for version 1.5. 
It is safe to introduce DMN 1.5 already, even if the standard is not published yet. Currently, it is in public beta and in the OMG review process. At this stage, it is unlikely that the namespaces would change.   
related to #2665, #3598

feat: Support new DMN 1.4 and 1.5 namespaces & schema

---

engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringTransactionInterceptor.java

related to camunda/camunda-bpm-platform#3712
I’ve encountered a bug in the implementation of org.camunda.bpm.engine.spring.SpringTransactionInterceptor
My Delegate code results in a Rollback Exception. The Interceptor, in an attempt to handle commit retry for CockroachDB casts RollbackException to the SQLException. We use Spring Data JPA (Hibernate) on our end to communicate with DB
I didn’t find any mention of such behaviour from this class
Spring Boot: 2.7.10
Camunda Version: 7.19.0
DBMS: PostgreSQL
Without digging depper I can understand that the matter can be fixed with a single `instanceof`
My changes changes are covered in this PR. I found it more productive to submit PR, because my topic on the forum (https://forum.camunda.io/t/java-lang-classcastexception-class-javax-persistence-ro …

fix(spring): Fix Unchecked cast to the SQLException

---

examples/invoice/src/main/resources/invoiceBusinessDecisions.dmn

* This commit adds a HTTL value on invoiceBusinessDecisions.dmn file used by camunda-run to prevent the exception thrown at application startup since the new default of enforceHistoryTimeToLive now is true.
Related to: #2994

chore(engine): Add HistoryTimeToLive to Invoice Example

---

webapps/frontend/ui/admin/client/scripts/camunda-admin-bootstrap.js
webapps/frontend/ui/cockpit/client/scripts/camunda-cockpit-bootstrap.js
webapps/frontend/ui/common/scripts/services/plugins/loadPlugins.js
webapps/frontend/ui/tasklist/client/scripts/camunda-tasklist-bootstrap.js
webapps/frontend/ui/welcome/client/scripts/camunda-welcome-bootstrap.js

related to camunda/camunda-bpm-platform#3701

fix(webapps): correct loading path of legacy `requireJs` plugins

---

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/HistoryTimeToLiveDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/decision-definition/key/{key}/tenant-id/{tenant-id}/history-time-to-live/put.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/key/{key}/history-time-to-live/put.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/{id}/history-time-to-live/put.ftl

Remove explicit `null` mention in **HistoryTimeToLiveDto**
Doc **Endpoints** Adjusted:
updateHistoryTimeToLiveByDecisionDefinitionKeyAndTenant
updateHistoryTimeToLiveByProcessDefinitionKey
updateHistoryTimeToLiveByProcessDefinitionId
Related to: #2994

docs(engine): Adjust Docs for HistoryTimeToLive Update Actions

---

webapps/frontend/ui/admin/client/scripts/pages/generic-confirmation.html
webapps/frontend/ui/admin/client/scripts/pages/groupEdit.js
webapps/frontend/ui/admin/client/scripts/pages/tenantEdit.js
webapps/frontend/ui/admin/client/scripts/pages/userEdit.js

related to camunda/camunda-bpm-platform#3735

fix(admin): show error on user deletion

---

bom/pom.xml

fix camunda-engine-rest-core (-jakarta) dependencies.

---

webapps/frontend/ui/admin/client/scripts/camunda-admin-bootstrap.js
webapps/frontend/ui/cockpit/client/scripts/camunda-cockpit-bootstrap.js
webapps/frontend/ui/tasklist/client/scripts/camunda-tasklist-bootstrap.js
webapps/frontend/ui/welcome/client/scripts/camunda-welcome-bootstrap.js

related to camunda/camunda-bpm-platform#3796

fix(webapps): clear requirejs globals after bootstrapping

---

engine/src/main/java/org/camunda/bpm/engine/impl/util/ExceptionUtil.java

I can't describe the exact situation an NPE happened for me here, but it does happen at least on some databases that `SQLState` is `null`. As can be seen from the source code, `toUpperCase()` call is actually pointless in this function and is never important, so its only practical consequence was causing an NPE in certain situations.
related to https://github.com/camunda/camunda-bpm-platform/issues/3818

Avoid NPE in ExceptionUtil.checkVariableIntegrityViolation()

---

engine/src/main/java/org/camunda/bpm/engine/impl/util/ExceptionUtil.java
engine/src/test/java/org/camunda/bpm/engine/impl/util/ExceptionUtilTest.java

This commit
1) plugs _potential_ (I haven't observed them in reality) causes for NPEs in `ExceptionUtil`, similar to those in 660e7f1298;
2) adds several tests for the plugged methods that assert no NPEs and each check one (mocked) parameter set that causes the tested method to return true.
This was tentatively agreed on in #3818.

avoid more potential NPE in ExceptionUtil

---

distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigAllowCredentialsTest.java
distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigAllowedHeadersTest.java
distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationEnabledAllowedOriginConfiguredTest.java
distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationEnabledWildcardTest.java
distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationExposedHeadersTest.java
distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationPreflightMaxAgeTest.java
distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsWithChangedContextPathTest.java
parent/pom.xml

https://github.com/camunda/camunda-bpm-platform/issues/3724

chore(deps): update tomcat to 9.0.82 (run 10.0.15); spring boot 3.1.5

---

spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappInitializer.java
spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/filter/AppendTrailingSlashFilter.java
spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/filter/MapTrailingSlashFilter.java
spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/apppath/RequestTrailingSlashIT.java

Related to https://github.com/camunda/camunda-bpm-platform/issues/3889

chore(spring-boot-webapp): introduce filter to make URLs without trailing slashes work

---

spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/configuration/impl/custom/CreateAdminUserConfiguration.java
spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/util/SpringBootProcessEngineLogger.java
spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/configuration/impl/custom/CreateAdminUserConfigurationTest.java

Logs admin user on `DEBUG`.
related to camunda/camunda-bpm-platform#3956

fix(spring-boot): avoid logging admin user on `INFO`

---

quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/ManagedJobExecutorTest.java

Related-to: https://github.com/camunda/camunda-bpm-platform/issues/3940

chore(quarkus-extesion/engine): Fix Flaky Quarkus Test

---

clients/java/client/pom.xml
clients/java/client/src/it/java/org/camunda/bpm/client/rule/EngineRule.java
clients/java/client/src/main/java/org/camunda/bpm/client/impl/EngineClientLogger.java
clients/java/client/src/main/java/org/camunda/bpm/client/impl/RequestExecutor.java
clients/java/client/src/main/java/org/camunda/bpm/client/interceptor/auth/BasicAuthProvider.java
clients/java/client/src/main/java/org/camunda/bpm/client/interceptor/impl/RequestInterceptorHandler.java
clients/java/client/src/main/java/org/camunda/bpm/client/variable/impl/mapper/ByteArrayValueMapper.java
clients/java/client/src/main/java/org/camunda/bpm/client/variable/impl/mapper/FileValueMapper.java

related to camunda/camunda-bpm-platform#3945

feat(client/java): upgrade Apache HttpClient to 5

---

clients/java/client/src/main/java/org/camunda/bpm/client/topic/impl/dto/FetchAndLockRequestDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/FetchExternalTasksDto.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskRestServiceInteractionTest.java

Description: This commit renames the `sortings` parameter of the FetchAndLock API to `sorting` to match the existing convention of other similar APIs that involve sorting.
Related-to: #4018, #3896

chore(engine-rest, clients): Change sorting param

---

parent/pom.xml

https://github.com/camunda/camunda-bpm-platform/issues/3996

chore(parent): increase wait for spring-boot-maven-plugin

---

qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/util/AbstractFoxPlatformIntegrationTest.java

Description: Increase max wait-time of all Jobs to finish of class `AbstractFoxPlatformIntegrationTest` from 12 to 20 seconds
Reason: Fix flaky tests which might have spawned jobs that take longer to finish in various Jenkins executions
Context: Wildfly Flakiness
Related-to: #3995

chore(integration-tests-engine): Increase Max Job Wait Timeout

---

.ci/config/stage-types.yaml

Excluding webapps modules is not needed for JDK 11+ stages. It was added by mistake from previous jobs/stages.

chore(ci): include webapps in platform stages

---

engine/src/main/java/org/camunda/bpm/engine/impl/HistoryTimeToLiveParser.java
engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ConfigurationLogger.java
engine/src/test/java/org/camunda/bpm/engine/test/api/repository/HistoryTimeToLiveDeploymentTest.java
engine/src/test/resources/org/camunda/bpm/engine/test/api/repository/case_with_365_httl.cmmn
engine/src/test/resources/org/camunda/bpm/engine/test/api/repository/decision_with_365_httl.dmn

https://github.com/camunda/camunda-bpm-platform/issues/4031
```[tasklist]
```

chore(engine): adjust TTL warnings

---

database/pom.xml

We have been alerted a critical vulnerability in prostgres driver version 42.5.4 from Github hence bumping it up to 42.5.5 
Advisory :
https://github.com/advisories/GHSA-xfg6-62px-cxc2
https://nvd.nist.gov/vuln/detail/CVE-2024-1597
related to https://github.com/camunda/camunda-bpm-platform/issues/4127

chore(deps): bump up postgresql driver

---

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ActivityCancellationCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/gateway/ParallelGatewayTest.java

Related to https://github.com/camunda/camunda-bpm-platform/issues/3916

fix(engine): fire end event when inactive exec is canceled externally

---

.ci/config/stage-types.yaml
engine-rest/engine-rest/pom.xml

engine-rest-unit-jersey-2
engine-rest-unit-resteasy
engine-rest-unit-compatibility-wildfly
Related-to: https://github.com/camunda/team-automation-platform/issues/114

chore(.ci/config): Add jdk-11-latest to engine-rest unit tests

---

engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/BreakingScalaFeelBehaviorTest.java
engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/FeelBehavior.java
engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/JuelFeelBehaviorTest.java
engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/ScalaFeelBehaviorTest.java
engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/CustomFunctionTest.java
pom.xml

Notable points of this change:
**Changes in feel-scala:**
- `1.6.2` **legacy behaviour**: when disabling the var-args evaluation and a given function with arguments that do not exist throws an Exception
- `1.7.5` **new behaviour**: The above returns successfully and the answer contains suppressed failures.
- `FeelEngine#evalExpression` are deprecated and changed to the new `FeelEngineApi#evaluateExpression`. They also contain breaking changes in behaviour.
**Change Reason:**
- Adapt the behaviour of ScalaFeelEngine appropriately so that the legacy behaviour of `ScalaFeelEngine` is retained.
**Breaking change:**
- `FeelExceptions` with "no function found" messages now start with a capital letter.
- This is accepted as a small change to make the proxy code as simple as possible
Related-to: …

chore(project): Upgrade to feel-engine 1.7.5

---

webapps/frontend/camunda-commons-ui/lib/widgets/variables-table/cam-widget-variables-table.html
webapps/frontend/camunda-commons-ui/lib/widgets/variables-table/cam-widget-variables-table.js

related to camunda/camunda-bpm-platform#4190

fix(webapps): fix copy variable value not type string

---

distro/license-book/src/main/resources/license-book.txt

related to camunda/camunda-bpm-platform#3830

chore(license-book): update license book for 7.21.0

---

clients/java/client/src/test/java/org/camunda/bpm/client/variable/DateValueMapperTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoryCleanupRestServiceInteractionTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyEndTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyStartTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeInChunksTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeNonHierarchicalTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/helper/BatchSetRemovalTimeRule.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/AbstractHistoryCleanupSchedulerTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupRemovalTimeTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerAttachmentsTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerAuthorizationsTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerBatchesTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerDecisionsTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerProcessInstancesTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerTaskInstancesTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerTaskMetricsTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerVariableInstancesTest.java
engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
engine/src/test/java/org/camunda/bpm/engine/test/concurrency/CompetingHistoryCleanupAcquisitionTest.java
engine/src/test/java/org/camunda/bpm/engine/test/history/useroperationlog/UserOperationLogAnnotationTest.java
engine/src/test/java/org/camunda/bpm/engine/test/util/ClockTestUtil.java
webapps/assembly/src/test/java/org/camunda/bpm/admin/plugin/base/MetricsRestServiceTest.java

The bug is they used Epoch millisecond based on CET instead of UTC timezone. There are other places that its being used but aren't affecting tests. I just fixed the failed ones. I used GregorianCalendar Calendar instead of Julian since its widely used to create Date and also I think its more readable than that putting an Epoch millisecond.
_The fix should work on any timezone that the tests are being run_
Example to run engine (other modules can be run the same way) tests in a specific timezone from a root folder:
**mvn clean install -pl engine Duser.timezone=UTC
mvn clean install -pl engine -Duser.timezone=MST**
-Duser.timezone --> sets VM time which takes precedence over OS time.
https://github.com/camunda/camunda-bpm-platform/issues/2604

fix(engine/webapps/engine-rest/clients): tests fails when build runs on UTC timezone

---

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricDecisionInstanceDto.ftl

- fixed typo in /history/decision-instance response
related to #3710

fix(engine-rest): typo fix. related to #3710

---

engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml

Related to https://github.com/camunda/camunda-bpm-platform/issues/4067

fix(db2): Reduce batch execution time by filtering out queried byte arrays

---

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/message/MessageCorrelationResultDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/message/MessageCorrelationResultWithVariableDto.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/MessageRestServiceTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java

fix(engine-rest): /messages. Return result based on resultType

---

parent/pom.xml

Related to https://github.com/camunda/camunda-bpm-platform/issues/4186

feat(project): add support for spring boot 3.3

---

model-api/xml-model/src/main/java/org/camunda/bpm/model/xml/impl/validation/ModelValidationResultsImpl.java
model-api/xml-model/src/main/java/org/camunda/bpm/model/xml/validation/ValidationResultFormatter.java
model-api/xml-model/src/main/java/org/camunda/bpm/model/xml/validation/ValidationResults.java
model-api/xml-model/src/test/java/org/camunda/bpm/model/xml/validation/ModelValidationTest.java
model-api/xml-model/src/test/java/org/camunda/bpm/model/xml/validation/TestResultFormatter.java

- Added two new methods to the ValidationResultFormatter:
- one to format and print the suffix
- and another to return the expected size of this suffix
- Created empty default implementation for both methods not to break backwards-compatibility
- Updated the `write` implementation to use the new formatter methods
- Implemented the new methods in the TestResultFormatter and updated the test
--- 
Extend ValidationResults to allow write results until a max size
- Added a new `ValidationResults.write` method that accepts a `maxSize`
- keeps writing results to the writer as usual while comparing the size of the writer to the maxSize after every append
- keeps track of the length of the writer after every append
- if the size of the writer exceeds the max size, it resets the writer to the …

feat: Extend `ValidationResults` to allow write results until a max size

---

webapps/frontend/camunda-commons-ui/lib/widgets/search/cam-widget-search.js
webapps/frontend/public/app/admin/locales/en.json
webapps/frontend/public/app/cockpit/locales/en.json
webapps/frontend/public/app/tasklist/locales/en.json
webapps/frontend/public/app/welcome/locales/en.json
webapps/frontend/ui/cockpit/client/scripts/batches/config/batch-search-config.json
webapps/frontend/ui/cockpit/plugins/base/app/views/processDefinition/process-instance-search-config.json
webapps/frontend/ui/cockpit/plugins/base/app/views/processInstance/variable-instances-tab-search-config.json
webapps/frontend/ui/cockpit/plugins/base/app/views/processesDashboard/process-definition-search-config.json
webapps/frontend/ui/cockpit/plugins/decisionList/app/views/decisionDefinition/decision-instance-search-config.json
webapps/frontend/ui/common/scripts/services/locales.js
webapps/frontend/ui/tasklist/client/scripts/task/directives/cam-tasklist-task-meta.js
webapps/frontend/ui/tasklist/client/scripts/task/directives/cam-tasklist-task.js
webapps/frontend/ui/tasklist/client/scripts/tasklist/plugins/cam-tasklist-search-plugin-config.json

related to camunda/camunda-bpm-platform#4351

fix(webapps): add translation handler

---

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/VariableInstanceEntity.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/VariableInstanceTest.java

**Problem Description:** During Set Variable and Read Variable operations, the following partial ORM operations can occur in a problematic sequence:
- Thread A reads an Object Variable, thus associated with a byte array value
- Thread B reads the same Object Variable and updates its value to the db
- Now Thread A has a leaking byte array reference that is null
**Solution:** Instead of deleting an updating the byte array value, during the update, the deletion is simply skipped.
The fix was verified with the customer.
The above behaviour introduces leftover byte-array state on type change. Thus, only during a type change, the byte-array is deleted.
**Unit-tests:** This commit introduces unit tests that verify the correct state of the variables on type change.
**Limitations Accepted:** The …

fix(engine): Skip ByteArray Deletion when Updating Var

---

internal-dependencies/pom.xml

As per online discussion with Github users @venetrius and @tasso94 involved with this camunda project, removing an dependency that is no longer used in the project

Removing obsolete dependency, org.json:json, that is no longer used in the project

---

parent/pom.xml

Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4299

chore(parent): Bump Graalvm to Version 21.3.11

---

engine-plugins/identity-ldap/src/main/java/org/camunda/bpm/identity/impl/ldap/LdapIdentityProviderSession.java

thrown error only if id is null, do nothing if authorization is missing
https://github.com/camunda/camunda-bpm-platform/issues/4293

fix(identity/ldap): adjust ldap error handling

---

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricActivityInstance.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricCaseActivityInstance.xml
engine/src/test/java/org/camunda/bpm/engine/test/persistence/DatabaseNamingConsistencyTest.java
webapps/assembly/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/processDefinition.xml
webapps/assembly/src/test/java/org/camunda/bpm/webapp/impl/engine/WebappsDatabaseNamingConsistencyTest.java

Related to https://github.com/camunda/camunda-bpm-platform/issues/4525

chore(db): use uppercase DB property names

---

qa/test-old-engine/pom.xml
quarkus-extension/README.md
quarkus-extension/engine/deployment/src/test/resources/org/camunda/bpm/quarkus/engine/test/config/mixed-application.properties
quarkus-extension/engine/deployment/src/test/resources/org/camunda/bpm/quarkus/engine/test/config/process-engine-config-application.properties

+ exclude telemetry test in `old-engine` setup as telemetry feature is removed in newer versions; during rolling update users run old engine and data with new schema, so the test is not relevant for the scenario
fixes `quarkus-UNIT` in CE main and `old-engine` in CE daily/sidetrack
https://github.com/camunda/camunda-bpm-platform/issues/4483

remove(tests): remove telemetry configuration property 

---

.ci/config/stage-types.yaml

related to https://github.com/camunda/camunda-bpm-platform/issues/4451

fix(ci): skip starter-security module for jdk11 stages

---

distro/run/pom.xml

Moving the `modules/oauth2` from `distro-ce` to `distro` since it should be available in both builds ce and ee.
https://github.com/camunda/camunda-bpm-platform/issues/4451
fixes failure in [7.22-TEST-RELEASE-build-camunda-bpm-EE-tags](https://release.cambpm.camunda.cloud/job/7.22/job/7.22-TEST-RELEASE-build-camunda-bpm-EE-tags/)
Profiles used in release:
- ce - `-Pdistro,distro-ce,distro-wildfly,distro-webjar,release-community`
- ee - `-Pdistro,distro-wildfly,distro-webjar,distro-starter`

fix(modules): oauth2 module should be available for ce and ee

---

spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/CamundaSpringSecurityOAuth2AutoConfiguration.java
spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/OAuth2Properties.java
spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/OAuth2GrantedAuthoritiesMapper.java
spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/OAuth2IdentityProvider.java
spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/OAuth2IdentityProviderFactory.java
spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/OAuth2IdentityProviderPlugin.java

related to https://github.com/camunda/camunda-bpm-platform/issues/4453

feat(run): add oauth2 identity provider

---

clients/java/client/src/main/java/org/camunda/bpm/client/impl/EngineClient.java
clients/java/client/src/main/java/org/camunda/bpm/client/task/impl/ExternalTaskImpl.java
clients/java/client/src/main/java/org/camunda/bpm/client/variable/impl/value/DeferredFileValueImpl.java
clients/java/client/src/main/java/org/camunda/bpm/client/variable/value/DeferredFileValue.java

fix(client): load local file variable

---

.ci/config/matrices.yaml
.ci/config/stage-types.yaml
.ci/daily/Jenkinsfile
Jenkinsfile
parent/pom.xml

Related to https://github.com/camunda/team-automation-platform/issues/52

chore(ci): introduce declarative pod specs

---

spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/CamundaSpringSecurityOAuth2AutoConfiguration.java
spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/AuthorizeTokenFilter.java

related to https://github.com/camunda/camunda-bpm-platform/issues/4585

feat(oauth2): revalidate access tokens

---

.ci/daily/Jenkinsfile

related to camunda/team-automation-platform#52

chore(ci): migrate distro-maven and public-nexus stages

---

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/task-query-params.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskQueryDto.ftl
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceQueryTest.java
engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/json/JsonTaskQueryConverter.java
engine/src/main/java/org/camunda/bpm/engine/task/TaskQuery.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterTaskQueryTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java

feat(engine/engine-rest): like-queries for candidate groups

---

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/ModificationDto.ftl
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/ModificationDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ModificationRestServiceImpl.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ModificationRestServiceInteractionTest.java
engine/src/main/java/org/camunda/bpm/engine/impl/ModificationBuilderImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractModificationCmd.java
engine/src/main/java/org/camunda/bpm/engine/runtime/ModificationBuilder.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ModificationExecutionAsyncTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ModificationExecutionSyncTest.java
engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.syncAfterOneTaskProcess.bpmn20.xml

related to: https://github.com/camunda/camunda-bpm-platform/issues/4620

4620 add historic process instance query to execute modification async

---

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java
engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstanceQuery.java
engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java
engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/failingProcessAfterUserTaskCreateOneIncident.bpmn20.xml

4587 add incident id in filter to historic process instance query

---

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java
engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstanceQuery.java
engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java
engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.failingSubprocessWithAsyncBeforeTask.bpmn20.xml
engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.subprocessWithAsyncBeforeTask.bpmn20.xml
engine/src/test/resources/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.testHistoricProcessInstanceQueryActivityIdInWithIncident.bpmn

feature(engine): add activityIdIn filter to HistoricProcessInstanceQuery

---

clients/java/client/src/it/java/org/camunda/bpm/client/variable/FileSerializationIT.java
clients/java/client/src/main/java/org/camunda/bpm/client/task/impl/ExternalTaskImpl.java
clients/java/client/src/main/java/org/camunda/bpm/client/variable/impl/TypedValues.java
clients/java/client/src/main/java/org/camunda/bpm/client/variable/impl/VariableValue.java
clients/java/client/src/main/java/org/camunda/bpm/client/variable/impl/value/DeferredFileValueImpl.java
clients/java/client/src/main/java/org/camunda/bpm/client/variable/value/DeferredFileValue.java
clients/java/client/src/test/java/org/camunda/bpm/client/task/ExternalTaskImplTest.java

fix(client) don't expose executionId to public API

---

parent/pom.xml

Related to https://github.com/camunda/camunda-bpm-platform/issues/4551

chore(spring-boot): Bump Spring Boot version to 3.3.5

---

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl
engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstanceQuery.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java

related to camunda/camunda-bpm-platform#4757

fix(engine): allow querying for hist pis by async activities

---

Jenkinsfile
webapps/README.md
webapps/frontend/package.json
webapps/frontend/scripts/xlts.js
webapps/pom.xml

chore(webapps): use HeroDev libraries

---

pom.xml

Related to https://github.com/camunda/camunda-bpm-platform/issues/4530

chore(dmn): bump feel scala version to 1.18.1

---

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceDto.ftl
engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskDto.ftl

Related to https://github.com/camunda/camunda-bpm-platform/issues/4683
Hints for review:
Adds taskState in the response schema of:
- Task 
- Get List
- Get List (POST)
- Get
- Historic Task Instance 
- Get Tasks (Historic)
- Get Tasks (Historic) (POST) 
Examples already have it.

openapi(tasks): include task state in response specification

---

engine/src/main/java/org/camunda/bpm/engine/impl/batch/variables/BatchSetVariablesHandler.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractVariableCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetExecutionVariablesCmd.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/SetVariablesBatchTest.java
engine/src/test/java/org/camunda/bpm/engine/test/history/JobEntityAndJobLogBatchIdTest.java
engine/src/test/java/org/camunda/bpm/engine/test/util/ExecutableProcessUtil.java

Related to https://github.com/camunda/camunda-bpm-platform/issues/4795

feat(engine): don't fail on change variables async when process instance does not exist 

---

spin/dataformat-xml-dom/src/test/java/org/camunda/spin/xml/XmlTestUtil.java
spin/dataformat-xml-dom/src/test/java/org/camunda/spin/xml/dom/XmlDomMapJavaToXmlScriptTest.java
spin/dataformat-xml-dom/src/test/java/org/camunda/spin/xml/dom/XmlDomMapJavaToXmlTest.java

Related to: https://github.com/camunda/camunda-bpm-platform/issues/4606

fix(spin) time zone unit tests fail when run it in non CET timezone in spin module

---

engine-rest/engine-rest-openapi/README.md
engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/errorDetails/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/history/external-task-log/{id}/error-details/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/history/job-log/{id}/stacktrace/get.ftl
engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/stacktrace/get.ftl

related to #3298
Adds missing schema declarations for:
- `/job/aJobId/stacktrace`
- `history/job-log/someId/stacktrace`
I noticed that there was no attribute for the response macro to add this declaration for string responses, instead of defaulting to the "manual" approach I adjusted the macro to add a `contenctDesc` field as that seemed cleaner to me - let me know if there is a reason not to have this added there though and we can instead rewrite the above without using the macros.
While I was there I also noticed it was missing for `history/external-task-log/someId/error-details` so this adds it for that too. Also adjusts the equivalent in `external-task/someId/errorDetails` just for consistency.

fix(openApi): add missing schema declarations

---

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/ExceptionHandlerHelper.java

While implementing custom exception handling for my Camunda REST API, I used the `ExceptionHandlerHelper` class from the `engine-rest` module to ensure that the behavior of error handling is consistent with the built-in Camunda REST API error handling. The custom exception handler code is as follows:
```java
@ControllerAdvice
public class CustomExceptionHandler extends ResponseEntityExceptionHandler {
protected static final ExceptionLogger LOGGER = ExceptionLogger.REST_LOGGER;
private static final ExceptionHandlerHelper DELEGATE = ExceptionHandlerHelper.getInstance();
@ExceptionHandler
public ResponseEntity<Object> handleAnyException(Throwable ex, NativeWebRequest request) {
ExceptionDto exceptionDto = DELEGATE.fromException(ex);
return handleExceptionInternal((Exception) ex, …
```

refactor(engine-rest): Ensure Proper Exception Code Assignment in ExceptionHandlerHelper

---

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/scripting/engine/CamundaScriptEngineManager.java
engine/src/main/java/org/camunda/bpm/engine/impl/scripting/engine/CustomScriptEngineManager.java
parent/pom.xml

**Notes**
- Bumps icu:icu4j to version 71.1
**Introduces**:
CustomScriptEngineManager - Class that allows to parameterise behaviour needed for a given JS engine: a) After the engines are detected from the classpath b) Before the engines are created
**GraalVM Warnings**
The commit sets the System property to disable the respective warnings introduced by bumping GraalVM to version 21.3.10.
- The system property is always set when a GraalJS script engine is found on the classpath
- The above applies by default to all distros
**Related-to**: https://github.com/camunda/camunda-bpm-platform/issues/4299

chore(engine,parent): Bump GraalVM to 21.3.12

---

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractInstantiationCmd.java
engine/src/main/java/org/camunda/bpm/engine/impl/json/ModificationCmdJsonConverter.java
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/SingleProcessInstanceModificationAsyncTest.java
engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.loop.bpmn

related to #4507
[Suggesting](https://github.com/camunda/camunda-bpm-platform/pull/4829#discussion_r1867865183) a follow up to investigate whether a similar fix is required for TransitionInstantiationCmd (and implement if so)

fix(asyncInstanceModification): respect ancestor during startBefore/after cmd execution

---

spring-boot-starter/starter-security/pom.xml
spring-boot-starter/starter-security/src/test/java/org/camunda/bpm/spring/boot/starter/security/SampleApplication.java
spring-boot-starter/starter-security/src/test/java/org/camunda/bpm/spring/boot/starter/security/oauth2/AbstractSpringSecurityIT.java
spring-boot-starter/starter-security/src/test/java/org/camunda/bpm/spring/boot/starter/security/oauth2/CamundaBpmSampleApplicationIT.java
spring-boot-starter/starter-security/src/test/java/org/camunda/bpm/spring/boot/starter/security/oauth2/CamundaBpmSecurityAutoConfigOauth2ApplicationIT.java
spring-boot-starter/starter-security/src/test/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/CamundaIdentityProviderIT.java
spring-boot-starter/starter-security/src/test/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/OAuth2GrantedAuthoritiesMapperIT.java
spring-boot-starter/starter-security/src/test/resources/oauth2-mock.properties

related to https://github.com/camunda/camunda-bpm-platform/issues/4567

tests(starter): add tests for oauth2 and identity provider

---

spin/dataformat-json-jackson/src/main/java/org/camunda/spin/impl/json/jackson/format/JacksonJsonDataFormat.java
spin/dataformat-json-jackson/src/test/java/org/camunda/spin/json/JsonTestConstants.java
spin/dataformat-json-jackson/src/test/java/org/camunda/spin/json/mapping/OrderDetails.java
spin/dataformat-json-jackson/src/test/java/org/camunda/spin/json/tree/JsonTreeJsonPathScriptTest.java
spin/dataformat-json-jackson/src/test/java/org/camunda/spin/json/tree/JsonTreeReadPropertyScriptTest.java
spin/dataformat-json-jackson/src/test/resources/org/camunda/spin/groovy/json/tree/JsonTreeJsonPathGroovyTest.shouldGetNumberFromJsonPath.groovy
spin/dataformat-json-jackson/src/test/resources/org/camunda/spin/groovy/json/tree/JsonTreeMapObjectToJsonGroovyTest.shouldMapDictionary.groovy
spin/dataformat-json-jackson/src/test/resources/org/camunda/spin/javascript/json/tree/JsonTreeJsonPathJavascriptTest.shouldGetNumberFromJsonPath.js
spin/dataformat-json-jackson/src/test/resources/org/camunda/spin/javascript/nashorn/json/tree/JsonTreeJsonPathJavascriptTest.shouldGetNumberFromJsonPath.js
spin/dataformat-json-jackson/src/test/resources/org/camunda/spin/json/example.json
spin/dataformat-json-jackson/src/test/resources/org/camunda/spin/python/json/tree/JsonTreeJsonPathPythonTest.shouldGetNumberFromJsonPath.py
spin/dataformat-json-jackson/src/test/resources/org/camunda/spin/python/json/tree/JsonTreeMapObjectToJsonPythonTest.shouldMapDictionary.py
spin/dataformat-json-jackson/src/test/resources/org/camunda/spin/ruby/json/tree/JsonTreeJsonPathRubyTest.shouldGetNumberFromJsonPath.rb
spin/dataformat-json-jackson/src/test/resources/org/camunda/spin/ruby/json/tree/JsonTreeMapObjectToJsonRubyTest.shouldMapDictionary.rb

Related to https://github.com/camunda/camunda-bpm-platform/issues/2575

fix(spin): make jsonPath use Double nodes as default number type

---

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml
engine/src/test/java/org/camunda/bpm/engine/test/api/optimize/GetCompletedHistoricTaskInstancesForOptimizeTest.java
engine/src/test/java/org/camunda/bpm/engine/test/api/optimize/GetRunningHistoricTaskInstancesForOptimizeTest.java

related to [OPT#4735](https://github.com/camunda/camunda-bpm-platform/issues/4735)
Excludes standallone usertasks from optimize exports.

chore(optimize): exclude standalone tasks from optimize queries

---

distro/run/core/src/test/java/org/camunda/bpm/run/test/config/https/HttpsConfigurationEnabledTest.java
distro/run/core/src/test/resources/application-test-https-enabled.yml
engine-rest/engine-rest-jakarta/pom.xml
parent/pom.xml

Related to https://github.com/camunda/camunda-bpm-platform/issues/4657

chore(pom): add support for Spring Boot 3.4.1

---

parent/pom.xml

Related to: camunda/camunda-bpm-platform/issues/4883

chore (parent): Bump Tomcat versions to 9.0.98 and 10.1.34 (#4883)

---

parent/pom.xml

fixes red CI
#4049
follow up of https://github.com/camunda/camunda-bpm-platform/pull/4847

revert(deps): revert accidental bump of a library

---

clients/java/client/src/it/java/org/camunda/bpm/client/client/ClientIT.java
clients/java/client/src/main/java/org/camunda/bpm/client/ExternalTaskClientBuilder.java
clients/java/client/src/main/java/org/camunda/bpm/client/UrlResolver.java
clients/java/client/src/main/java/org/camunda/bpm/client/impl/EngineClient.java
clients/java/client/src/main/java/org/camunda/bpm/client/impl/ExternalTaskClientBuilderImpl.java
clients/java/client/src/main/java/org/camunda/bpm/client/impl/PermanentUrlResolver.java
clients/java/client/src/test/java/org/camunda/bpm/client/impl/ExternalTaskClientBuilderImplTest.java

Implement lat PR comments from[ community PR.](https://github.com/camunda/camunda-bpm-platform/pull/4546)
Requires additional team review.
related to https://github.com/camunda/camunda-bpm-platform/issues/4888

feat(baseUrl): add UrlResolver

---

engine-rest/assembly-jakarta/src/main/runtime/tomcat/webapp/WEB-INF/web.xml
engine-rest/assembly-jakarta/src/main/runtime/wildfly/webapp/WEB-INF/web.xml
engine-rest/assembly/src/main/runtime/jbossas7/webapp/WEB-INF/web.xml
engine-rest/assembly/src/main/runtime/tomcat/webapp/WEB-INF/web.xml
engine-rest/assembly/src/main/runtime/was/webapp/WEB-INF/web.xml
engine-rest/assembly/src/main/runtime/wildfly/webapp/WEB-INF/web.xml
engine-rest/assembly/src/main/runtime/wls/webapp/WEB-INF/web.xml
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/FetchAndLockHandlerImpl.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/impl/FetchAndLockHandlerTest.java

Related to https://github.com/camunda/camunda-bpm-platform/issues/4885

feat(rest): make LockAndFetchHandler blocking queue's capacity configurable

---

Jenkinsfile
distro/wildfly/assembly/src/wildfly/standalone-full.xml
distro/wildfly/assembly/src/wildfly/standalone.xml
parent/pom.xml
qa/integration-tests-webapps/pom.xml
qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml
qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml
qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml

related to https://github.com/camunda/camunda-bpm-platform/issues/4655
Adds support for wildfly 35
Keeping track of license check in [this doc](https://docs.google.com/document/d/1s8_6fLdjl3j0B5WQEav2orGcwz4uUs-MIuah4YqBtxs/edit?tab=t.0)
For manual testing setup, [this](https://docs.camunda.org/manual/develop/installation/full/jboss/manual/#setup) guide was used.
Follow up: https://github.com/camunda/team-automation-platform/issues/282

deps(wildfly): upgrade to wildfly 35

---

webapps/assembly/src/main/java/org/camunda/bpm/webapp/impl/security/auth/UserAuthenticationResource.java
webapps/assembly/src/test/java/org/camunda/bpm/webapp/impl/security/auth/UserAuthenticationResourceTest.java

Related to https://github.com/camunda/camunda-bpm-platform/issues/3739

fix(webapp): Handle null authentication as unauthorized

---

webapps/frontend/ui/tasklist/client/scripts/controller/cam-tasklist-view-ctrl.js
webapps/frontend/ui/tasklist/client/scripts/tasklist/directives/cam-tasklist-tasks.js

related to: camunda/camunda-bpm-platform/issues/4793

fix(webapps/tasklist): render task if no filter exists

---

engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstanceQuery.java
engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java
engine/src/test/resources/org/camunda/bpm/engine/test/api/history/testInstancesWithJobsRetrying.bpmn20.xml
engine/src/test/resources/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceTest.testGetJobExceptionStacktrace.bpmn20.xml

feat(queryAPI): add filter for instances with jobs retrying in java API

---

Jenkinsfile

Related to https://github.com/camunda/team-automation-platform/issues/87

chore(CI): archive Tomcat server log for flaky test investigation

---

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java

related to https://github.com/camunda/camunda-bpm-platform/issues/4905
Adds the `withJobsRetrying` query parameter to openAPI definition as well as `HistoricProcessInstanceQueryDto` for use by cockpit instance search. See ticket for more details.

feat(restAPI): add withJobsRetrying to rest and openAPI

---

.ci/config/stage-types.yaml

[#4869](https://github.com/camunda/camunda-bpm-platform/issues/4869)

fix(ci): exclude jakarta module from jdk 11 stages

---

parent/pom.xml
quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/persistence/conf/ChooseNotExistingDatasourceConfigurationTest.java
quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/persistence/conf/NoDefaultDatasourceConfigurationTest.java

related to #4870
License check [here](https://docs.google.com/spreadsheets/d/1EDSQm4OMJWiYg9hmHZmsCq0dWTy8SpGYSolWnozjagQ/edit?gid=0#gid=0)

chore(dependencies): update Quarkus to 3.19 

---

parent/pom.xml

related to #4870
License check for 3.20 done [here](https://docs.google.com/spreadsheets/d/1EDSQm4OMJWiYg9hmHZmsCq0dWTy8SpGYSolWnozjagQ/edit?gid=1870671348#gid=1870671348)
- except for`jna`, none of the licenses changed
- for `jna`, one of jna's licenses is on the Go list

chore(deps): bump quarkus to 3.20.0

---

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl
engine-rest/engine-rest-openapi/src/main/templates/lib/commons/process-instance-query-params.ftl
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceQueryDto.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceQueryTest.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java
engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstanceQuery.java
engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/impl/ProcessInstanceQueryImpl.java
engine/src/main/java/org/camunda/bpm/engine/runtime/ProcessInstanceQuery.java
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Execution.xml
engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceQueryTest.java
engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java

For the /process-instance & history/process-instance APIs, Have implemented the root-process-instance filters to get the Process instances related to the provided root-process-instance.
Git Issue: https://github.com/camunda/camunda-bpm-platform/issues/2582

Implement filteration by rootProcessInstanceId for Process Instances and History Process instances endpoints #2582

---

clients/java/client/src/main/java/org/camunda/bpm/client/impl/ExternalTaskClientBuilderImpl.java
clients/java/client/src/test/java/org/camunda/bpm/client/impl/ExternalTaskClientBuilderImplTest.java

Related to https://github.com/camunda/camunda-bpm-platform/issues/5112

fix(xtac): initialize url resolver with null base url

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/subtask.md
.github/ISSUE_TEMPLATE/task.md

Related to https://github.com/camunda/team-automation-platform/issues/344
Removes deprecated tasklists from git issue templates

fix(git): update templates to remove tasklists

---

spring-boot-starter/starter-rest/pom.xml
spring-boot-starter/starter-rest/src/main/java/org/camunda/bpm/spring/boot/starter/rest/CamundaBpmRestInitializer.java
spring-boot-starter/starter-rest/src/main/java/org/camunda/bpm/spring/boot/starter/rest/CamundaBpmRestJerseyAutoConfiguration.java
spring-boot-starter/starter-rest/src/test/java/org/camunda/bpm/spring/boot/starter/rest/config/fetchandlock/FetchAndLockHandlerConfigureQueueCapacityIT.java
spring-boot-starter/starter-rest/src/test/java/org/camunda/bpm/spring/boot/starter/rest/config/fetchandlock/FetchAndLockHandlerConfigureUniqueWorkerRequestFalseIT.java
spring-boot-starter/starter-rest/src/test/java/org/camunda/bpm/spring/boot/starter/rest/config/fetchandlock/FetchAndLockHandlerConfigureUniqueWorkerRequestTrueIT.java
spring-boot-starter/starter-rest/src/test/java/org/camunda/bpm/spring/boot/starter/rest/config/fetchandlock/FetchAndLockHandlerDefaultConfigIT.java
spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/property/CamundaBpmProperties.java
spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/property/FetchAndLockProperties.java
spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/property/RestApiProperty.java
spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/property/ParsePropertiesHelper.java
spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/property/RestApiPropertyDefaultsTest.java
spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/property/RestApiPropertyTest.java

Exposes the following configurations:
* `camunda.bpm.rest-api.fetch-and-lock.queue-capacity`
* `camunda.bpm.rest-api.fetch-and-lock.unique-worker-request`
related to camunda/camunda-bpm-platform#5140

chore(spring-boot/rest): expose `FetchAndLockHandler` configurations

---

internal-dependencies/pom.xml
parent/pom.xml
spin/pom.xml

related to camunda/camunda-bpm-platform#5119

chore(deps): bump `json-smart` to 2.5.2
