spring-boot-starter/starter-client/README.md
=> docs(spring-boot-starter-client): fixed typo in @Configuration

.ci/config/stage-types.yaml, Jenkinsfile, distro/jbossas7/subsystem/pom.xml, parent/pom.xml, pom.xml, quarkus-extension/README.md, quarkus-extension/engine/README.md, quarkus-extension/engine/deployment/pom.xml, quarkus-extension/engine/deployment/src/main/java/org/camunda/bpm/quarkus/engine/extension/deployment/impl/CamundaEngineProcessor.java, quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/UnitTest.java, quarkus-extension/engine/pom.xml, quarkus-extension/engine/runtime/pom.xml, quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/CamundaEngineRecorder.java, quarkus-extension/engine/runtime/src/main/resources/META-INF/quarkus-extension.properties, quarkus-extension/engine/runtime/src/main/resources/META-INF/quarkus-extension.yaml, quarkus-extension/pom.xml, webapps/pom.xml, webapps/src/test/java/org/camunda/bpm/webapp/impl/security/auth/ContainerAuthenticationFilterTest.java
=> chore(quarkus-extension): add initial project structure

quarkus-extension/engine/deployment/src/main/java/org/camunda/bpm/quarkus/engine/extension/deployment/impl/CamundaEngineProcessor.java, quarkus-extension/engine/deployment/src/main/java/org/camunda/bpm/quarkus/engine/extension/deployment/impl/ProcessEngineConfigurationBuildItem.java, quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/ConfigurableProcessEngineTest.java, quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/CamundaEngineRecorder.java
Related to CAM-13724
:warning: The branch should be rebased on master before merging
=> CAM-13724: programmatic engine configuration in Quarkus

engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/metrics/TaskMetricsTest.java
=> test(engine): use java 8 method signature

settings/intellij-idea/formatter.xml
=> chore(settings): create intellij idea formatter file

engine-rest/engine-rest-openapi/src/main/templates/paths/incident/count/get.ftl
=> fix(open-api): correct response of incident count

parent/pom.xml
=> chore(deps): bump quarkus to 2.1.0.Final

quarkus-extension/engine/deployment/src/main/resources/application.properties
=> chore(quarkus-extension): remove auto-inject-fields configuration

quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/lookup/ProgrammaticBeanLookupTest.java
=> test(quarkus-extension): add jira ticket for copied ProgrammaticBeanLookupTest

quarkus-extension/engine/qa/src/test/java/org/camunda/bpm/engine/cdi/test/CdiProcessEngineTestCase.java
=> test(quarkus-extension/qa): destroy beans after test

quarkus-extension/engine/runtime/src/main/resources/META-INF/quarkus-extension.yaml
=> fix(quarkus-extension): add artifact coords to quarkus-extension.yaml

webapps/camunda-bpm-sdk-js/lib/forms/camunda-form.js
=> fix(tasklist): skip storing input value of type file

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java
=> fix(engine): fix task criteria without candidate groups and users

engine-rest/engine-rest-openapi/src/main/templates/paths/incident/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/incident/get.ftl
=> fix(openapi): fix issues with incident resource

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/CalledProcessDefinitionDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/{id}/static-called-process-definitions/get.ftl
Related to CAM-12180
Related to CAM-13690
=> chore(open-api): add static-called-process-definitions

quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/id/ConfigureDbIdGeneratorTest.java, quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/id/DefaultIdGeneratorTest.java, quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/QuarkusProcessEngineConfiguration.java
=> chore(quarkus-extension): make strong id generator default

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/CamundaFormRef.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/get.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/hal/task/HalTask.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessDefinitionRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockTaskBuilder.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/task/TaskQueryTest.shouldContainCamundaFormRefIfInitialized.bpmn
=> feat(forms): include camFormRef in TaskQuery API

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/form/deployer/CamundaFormDefinitionDeployer.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/CamundaFormDefinitionStrictParseTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/CamundaFormDefinitionStrictParseTest.anyForm.form
=> chore(forms): make strict forms parsing configurable

bom/pom.xml
=> chore(bom): add quarkus engine extension

engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/AbstractRestServiceTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricCaseActivityStatisticsRestServiceQueryTest.java
=> CAM-13547: recreate engine mock before every test 

.ci/config/matrices.yaml, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> CAM-13625: add azure db support to ci

engine-rest/engine-rest-openapi/pom.xml
=> chore(openapi): skip test-compile phase and client generation 

parent/pom.xml
=> chore(quarkus-extension): bump version to 2.1.2.Final

quarkus-extension/engine/pom.xml, quarkus-extension/engine/qa/pom.xml
=> test(quarkus-extension): increase heap space of surefire

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/task-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/commons/variable-instance-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDefinitionsSuspensionStateDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/schema/log/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/user/{id}/credentials/put.ftl
=> fix(open-api): fix minor errors

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/AnyValue.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/ConditionQueryParameterDto.ftl
Related to CAM-13468
Related to CAM-13469
=> fix(openapi): add AnyValue type for ConditionalQueryParameterDto

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SchemaLogQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricActivityInstanceQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricDetailQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricExternalTaskLogQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricVariableInstanceQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/batch/HistoricBatchQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/GroupQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/EventSubscriptionQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ExecutionQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDefinitionQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/VariableInstanceQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExternalTaskQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskQueryDto.ftl
=> chore(openapi): make sorting prop nullable

engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.cockroachdb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.db2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.h2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mariadb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mssql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mysql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.oracle.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.postgres.create.engine.sql
* adds table ACT_RE_CAMFORMDEF to baseline scripts
related to CAM-13828
=> chore(engine): add missing table to Liquibase baseline

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
=> fix(qa): revert builder pattern on ProcessEngineConfigurationImpl setter

engine/src/main/java/org/camunda/bpm/engine/impl/test/TestHelper.java, engine/src/main/java/org/camunda/bpm/engine/test/ProcessEngineRule.java
This problem was introduced with CAM-13632.
related to CAM-13854
=> test(engine): fix failing history level tests

engine-spring/compatibility-test-spring4/pom.xml, engine-spring/core/pom.xml, engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringProcessEngineConfiguration.java, engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/AbstractScriptTaskTest.java, engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/ScriptTaskLimitedBeansTest.java, engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/ScriptTaskNoBeansTest.java, engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/TestbeanNoName.java, engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/scripttask/ScriptTaskLimitedBeansTest-applicationContext.xml, engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/scripttask/ScriptTaskNoBeansTest-applicationContext.xml, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
* does not provide Spring beans in scripts when custom beans are defined
related to CAM-12958
=> fix(engine-spring): respect custom beans in scripts

webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form.js
=> feat(forms): support form versioning in tasklist

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/GetStaticCalledProcessDefinitionCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/api/repository/RepositoryServiceTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/repository/nested-call-activities.bpmn
Related to CAM-13844
Related to CAM-12180
=> fix(engine): include nested call activities in getStaticCalledProcessDefinitions

webapps/src/main/runtime/develop/java/org/camunda/bpm/pa/DevProcessApplication.java, webapps/src/main/runtime/develop/resources/pa5/call-activities-with-references.bpmn, webapps/ui/cockpit/client/scripts/components/callActivityOverlays/callActivityOverlay.js, webapps/ui/cockpit/client/scripts/components/callActivityOverlays/definition/index.js, webapps/ui/cockpit/client/scripts/components/callActivityOverlays/instance/index.js
=> feat(cockpit): navigate running dynamic call activities in definition view

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobExecutor.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobExecutorLogger.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupJobDeclaration.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/history/HistoryCleanupJobPriorityTest.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/AbstractJobExecutorAcquireJobsTest.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/BatchJobPriorityRangeTest.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/ControllableCommandContext.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/HistoryCleanupJobPriorityRangeTest.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsByPriorityTest.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsForPriorityRangeTest.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorFollowUpTest.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorPriorityRangeConfigurationTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsForPriorityRangeTest.jobPrioProcess.bpmn20.xml
=> feat(engine): support priority range for job executor

parent/pom.xml, pom.xml
=> CAM-13874: update template engine versions to 2.1.0

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/ConditionQueryParameterDto.ftl
=> chore(openapi): add notLike to ConditionalQueryParameterDto

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/VariableValueDto.ftl
=> fix(open-api): change type of variable value to AnyType

webapps/package-lock.json, webapps/package.json, webapps/ui/cockpit/client/scripts/repository/resource/directives/cam-cockpit-form.js, webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form-camunda.js
related to CAM-13719, CAM-13333
=> chore(deps): update to form-js@0.4.1

distro/run/core/pom.xml, parent/pom.xml, spring-boot-starter/starter/pom.xml
=> CAM-13812: update Tomcat to 9.0.52

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/batch/CorrelationMessageAsyncDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/message-async/post.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/ProcessInstanceRestService.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/batch/CorrelationMessageAsyncDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ProcessInstanceRestServiceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java
* adds REST API endpoint to correlate message to process instances async
* adds OpenAPI description for the endpoint
related to CAM-13864
=> feat(rest): add message correlation batch endpoint

.ci/daily/Jenkinsfile, parent/pom.xml, pom.xml
Related to CAM-13784
:warning: The shared lib reference should be removed before merging.
=> CAM-13784: feat(ci): add javadoc staging stage

webapps/camunda-commons-ui/lib/widgets/dmn-viewer/cam-widget-dmn-viewer.js
=> fix(cockpit): skip loading plugins for not yet intialized tables

webapps/package-lock.json, webapps/package.json, webapps/ui/cockpit/grunt/config/copy.js
=> fix(webapps): add direct dependency to dmn-font

distro/license-book/src/main/resources/license-book.txt
=> CAM-13899: update license book to 7.16.0

webapps/package-lock.json, webapps/package.json
=> fix(webapps): replace `git://` protocol in `package.json`

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
=> chore(ci): use global logger's level

clients/java/client/src/main/java/org/camunda/bpm/client/backoff/ErrorAwareBackoffStrategy.java, clients/java/client/src/main/java/org/camunda/bpm/client/backoff/ExponentialErrorBackoffStrategy.java, clients/java/client/src/main/java/org/camunda/bpm/client/exception/FetchAndLockException.java, clients/java/client/src/main/java/org/camunda/bpm/client/topic/impl/TopicSubscriptionManager.java, clients/java/client/src/main/java/org/camunda/bpm/client/topic/impl/TopicSubscriptionManagerLogger.java, clients/java/client/src/main/java/org/camunda/bpm/client/topic/impl/dto/FetchAndLockResponseDto.java, clients/java/client/src/test/java/org/camunda/bpm/client/backoff/ExponentialErrorBackoffStrategyTest.java
- Added error aware backoff strategy interface
- Implemented exponential error backoff strategy
- Modified TopicSubscriptionManager to run error aware backoff strategies
related to CAM-12816
=> CAM-12816 feat(client): Error backoff strategy

webapps/ui/tasklist/client/scripts/services/cam-tasklist-assign-notification.js, webapps/ui/tasklist/client/scripts/tasklist/directives/cam-tasklist-tasks.js
=> fix(tasklist): fix task link in assignee notification panel

webapps/camunda-commons-ui/lib/services/index.js
=> fix(webapp): fix initial page load error without trailing slash

webapps/camunda-commons-ui/lib/widgets/dmn-viewer/cam-widget-dmn-viewer.less
=> fix(dmn-ui): fix table cell overlap with long words

webapps/camunda-commons-ui/lib/widgets/bpmn-viewer/cam-widget-bpmn-viewer.js, webapps/camunda-commons-ui/lib/widgets/bpmn-viewer/cam-widget-bpmn-viewer.less, webapps/package-lock.json, webapps/package.json
This PR updates to the preview version of bpmn-js and adjusts basic style and behavior to Cockpit.
The Scope is to allow import and display of these processes. Specific behavior and changes (selection/heatmap/...) will be handled separately, see [parent issue](https://jira.camunda.com/browse/CAM-13112) for this. 
related to CAM-14095
=> feat: import multi-plane diagrams

webapps/ui/cockpit/plugins/base/app/views/common/diagramPlugins/instanceCount.js, webapps/ui/cockpit/plugins/base/app/views/processDefinition/diagramPlugins/instanceCount.js, webapps/ui/cockpit/plugins/base/app/views/processInstance/diagramPlugins/instanceCount.js
related to CAM-14097
based on #1655
=> feat(processDefinition): show Badge on collapsed Shape

webapps/camunda-commons-ui/lib/widgets/bpmn-viewer/cam-widget-bpmn-viewer.js, webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task.js, webapps/ui/tasklist/client/scripts/task/plugins/detail/cam-tasklist-task-detail-diagram-plugin.js
based on #1655
related to CAM-14102
=> feat(tasklist): open correct plane

webapps/ui/admin/client/scripts/config.js, webapps/ui/admin/client/scripts/pages/execution-metrics.html, webapps/ui/admin/client/scripts/pages/execution-metrics.js, webapps/ui/common/scripts/services/cam-configuration.js
- display unique metrics by default
- add config flag for old behaviour with checkbox
related to CAM-13640
=> feat(admin): make execution metrics dialog easier to use

engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/SpringProcessEngineInitializationTest.java, engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/configuration/SpringProcessEngineInitializationTest.java, engine-spring/core/src/test/resources/activiti-context.xml, engine/src/main/java/org/camunda/bpm/engine/ProcessEngines.java
fix ClassNotFoundException in ProcessEngines.initProcessEngineFromSpringResource:136
related to CAM-14030
=> [CAM-14030] fix(engine): fix ClassNotFoundException in ProcessEngines

webapps/camunda-commons-ui/lib/widgets/search/cam-widget-search.js
=> chore(webapps): add support for `IN` operator to cam-widget-search

engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/ExampleConfiguration.java, engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/configuration/SpringProcessEngineInitializationTest.java, engine-spring/core/src/test/resources/activiti-context.xml
=> chore(engine-spring): close all test process engines

webapps/camunda-commons-ui/lib/widgets/inline-field/cam-widget-inline-field.html, webapps/camunda-commons-ui/lib/widgets/inline-field/cam-widget-inline-field.js, webapps/camunda-commons-ui/lib/widgets/inline-field/cam-widget-inline-field.less, webapps/camunda-commons-ui/lib/widgets/inline-field/dialog/controller.js, webapps/camunda-commons-ui/lib/widgets/inline-field/dialog/template.html, webapps/camunda-commons-ui/lib/widgets/search-pill/cam-widget-search-pill.html, webapps/ui/tasklist/client/scripts/tasklist/plugins/cam-tasklist-search-plugin-config.json, webapps/ui/tasklist/client/scripts/tasklist/plugins/cam-tasklist-search-plugin.js
⚠️ Merge https://github.com/camunda/camunda-bpm-platform/pull/1680 first and change base branch.
related to CAM-14123
=> feat(webapps/commons): search pill dialog for in criterion value

engine-plugins/spin-plugin/src/main/java/org/camunda/spin/plugin/impl/JsonValueSerializer.java, engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/variables/JsonValueTest.java
=> fix(spin-plugin): make accessing `null` variable `null` safe

parent/pom.xml, spring-boot-starter/pom.xml, spring-boot-starter/starter-client/spring-boot/pom.xml, spring-boot-starter/starter-client/spring-boot/src/test/java/org/camunda/bpm/client/spring/boot/starter/client/BasicAuthAndInterceptorConfigurationTest.java, spring-boot-starter/starter-client/spring-boot/src/test/java/org/camunda/bpm/client/spring/boot/starter/client/BasicAuthConfigurationTest.java, spring-boot-starter/starter-client/spring/pom.xml, spring-boot-starter/starter-client/spring/src/test/java/org/camunda/bpm/client/spring/ConfigurationTest.java, spring-boot-starter/starter-client/spring/src/test/java/org/camunda/bpm/client/spring/DefaultConfigurationTest.java, spring-boot-starter/starter-client/spring/src/test/java/org/camunda/bpm/client/spring/MockedTest.java, spring-boot-starter/starter-client/spring/src/test/java/org/camunda/bpm/client/spring/subscription/AutoOpenTrueTest.java, spring-boot-starter/starter-client/spring/src/test/java/org/camunda/bpm/client/spring/subscription/SubscriptionTest.java, spring-boot-starter/starter-webapp-core/pom.xml, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/LazyDelegateFilterTest.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/LazyInitRegistrationTest.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/configuration/impl/DefaultDatasourceConfigurationTest.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/configuration/impl/DefaultHistoryConfigurationTest.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/configuration/impl/DefaultHistoryLevelAutoHandlingConfigurationTest.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/event/JobExecutorStartingEventListenerTest.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/event/ProcessApplicationEventPublisherTest.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/jdbc/HistoryLevelDeterminatorJdbcTemplateImplTest.java
=> feat(parent): bump Spring Boot to 2.6.1

distro/run/pom.xml
=> chore(run): bump Log4J to 2.15.0

distro/run/pom.xml, parent/pom.xml, spring-boot-starter/pom.xml, spring-boot-starter/starter-webapp-core/pom.xml
=> chore(run&spring-boot): bump logback to 1.2.8

distro/run/pom.xml, spring-boot-starter/pom.xml
=> chore(run&spring-boot): bump log4j to 2.16.0

distro/run/pom.xml, spring-boot-starter/pom.xml
=> chore(run&spring-boot): bump logback to 1.2.9

distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunRestConfiguration.java, distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunCorsProperty.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigAllowCredentialsTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigAllowedHeadersTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigDecorateRequestTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationExposedHeadersTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationPreflightMaxAgeTest.java
* Add additional configuration properties to the CORS filter.
Related to CAM-11900
=> CAM-11900: feat(run): expand cors filter

webapps/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/processInstance.xml
=> fix(webapps): join history only when needed

parent/pom.xml
=> chore(parent): provide maximum heap size for failsafe

distro/run/pom.xml, spring-boot-starter/pom.xml
=> chore(run&spring-boot): bump log4j to 2.17.1

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/CommentEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/api/encoding/ProcessEngineCharacterEncodingTest.java
=> chore(engine): ensure task comment uses configured character encoding

engine-rest/engine-rest-openapi/pom.xml, parent/pom.xml
=> chore(engine): bump gson to 2.8.9

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/DeploymentRestService.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/DeploymentRestServiceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessEngineRestServiceTest.java
- add rest endpoint to fetch registered deployments
related to CAM-14280
=> feat(rest): registered deployments rest api

distro/run/core/pom.xml, distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunLdapProperties.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigDecorateRequestTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/identity/LdapConfigurationTest.java, spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/property/AdminUserProperty.java
=> CAM-14284: do not log LDAP connection properties

webapps/package-lock.json, webapps/package.json
=> deps: bump to form-js@0.6.0

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/telemetry/InternalsDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TelemetryRestServiceTest.java, engine/src/main/java/org/camunda/bpm/engine/telemetry/Internals.java
=> CAM-14310: avoid NPE when getting telemetry data without license

distro/h2-webapp/src/main/webapp/WEB-INF/web.xml
=> CAM-14285: disable remote access to h2 console

engine/src/main/java/org/camunda/bpm/engine/authorization/Authorization.java
=> Fix a typo in javadoc

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceTest.java
=> CAM-14345: test/fix multi instance with inner async after

webapps/ui/cockpit/plugins/base/app/views/processInstance/job-retry-bulk-dialog.html, webapps/ui/cockpit/plugins/base/app/views/processInstance/jobRetryBulkDialog.js
=> fix(cockpit): fix checkbox in job retry dialog.

CONTRIBUTING.md
Related to [CAMTEAM-223](https://jira.camunda.com/browse/CAMTEAM-223)
=> CAMTEAM-223:  commit msg best practice

distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunConfiguration.java, distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunProcessEnginePluginProperty.java, distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunProperties.java, distro/run/core/src/main/java/org/camunda/bpm/run/utils/CamundaBpmRunLogger.java, distro/run/core/src/main/java/org/camunda/bpm/run/utils/CamundaBpmRunProcessEnginePluginHelper.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/plugins/CamundaBpmRunProcessEnginePluginsHelperTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/plugins/CamundaRunProcessEnginePluginsRegistrationTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/plugins/ProcessEnginePluginsConfigurationOverrideTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/plugins/TestDefaultValuesPlugin.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/plugins/TestFalsePlugin.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/plugins/TestFirstPlugin.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/plugins/TestSecondPlugin.java, distro/run/core/src/test/resources/application-test-new-plugins.yml, distro/run/core/src/test/resources/application-test-plugins-config-override.yml, engine/src/main/java/org/camunda/bpm/container/impl/ContainerIntegrationLogger.java, engine/src/main/java/org/camunda/bpm/container/impl/deployment/StartProcessEngineStep.java, engine/src/main/java/org/camunda/bpm/engine/impl/util/ReflectUtil.java, spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/util/SpringBootProcessEngineLogger.java, spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/util/SpringBootStarterPropertyHelper.java
=> CAM-13338: register engine plugins in Run

qa/test-db-upgrade/pom.xml
=> chore(engine): update mockito version in qa db upgrade

parent/pom.xml
=> chore(spring): downgrade spring framework version

engine/src/main/java/org/camunda/bpm/engine/impl/form/engine/AbstractRenderFormDelegate.java, engine/src/main/java/org/camunda/bpm/engine/impl/form/engine/FormPropertyAdapter.java, engine/src/main/java/org/camunda/bpm/engine/impl/form/engine/HtmlFormEngine.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/form/HtmlFormEngineTest.testLegacyFormPropertySupportReadOnly.html, engine/src/test/resources/org/camunda/bpm/engine/test/api/form/HtmlFormEngineTest.testRenderDateField.html, webapps/camunda-bpm-sdk-js/lib/forms/controls/input-field-handler.js
- fix rendering of readonly boolean fields
- fix submitting readonly boolean fields
related to CAM-14185
=> fix(engine/tasklist): readonly boolean field cannot be submitted

distro/run/assembly/assembly.xml, distro/run/assembly/resources/run.bat, distro/run/assembly/resources/run.sh, distro/run/assembly/resources/shutdown.bat, distro/run/assembly/resources/shutdown.sh, distro/run/assembly/resources/start.bat, distro/run/assembly/resources/start.sh, distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/util/SpringBootManagedContainer.java
* Add Camunda Run shutdown shell script.
* Add Camunda Run shutdown bat script.
Related to CAM-14293
=> CAM-14293: feat(run): add shutdown scripts

webapps/camunda-commons-ui/lib/widgets/bpmn-viewer/cam-widget-bpmn-viewer.js, webapps/package-lock.json, webapps/package.json, webapps/ui/cockpit/client/scripts/directives/processDiagram.html, webapps/ui/cockpit/client/scripts/directives/processDiagram.js, webapps/ui/cockpit/client/scripts/pages/processDefinition.js, webapps/ui/cockpit/client/scripts/pages/processInstance.js, webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task.js
- planes are removed, it is all root elements now
related to CAM-14103
=> chore: update to bpmn-js@9

webapps/camunda-bpm-sdk-js/lib/angularjs/forms/index.js
=> fix(sdk-js): avoid making embedded form fields dirty

webapps/camunda-commons-ui/lib/pages/index.js
=> fix(webapps): avoid showing an error for `GET /camunda-welcome`

webapps/ui/admin/client/scripts/pages/authorizations.js
=> feat(admin): configure SYSTEM permissions for users

distro/run/modules/swaggerui/pom.xml
=> CAM-14396: let owasp plugin scan swaggerui package-lock.json

database/pom.xml
=> chore(build): update postgres driver version to 42.3.3

distro/run/assembly/resources/start.bat, distro/run/assembly/resources/start.sh, distro/webjar/pom.xml, spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/property/WebappProperty.java
* Add the camunda-welcome page to the camunda-webapp-webjar so that it is available to our Spring Boot Starter and Camunda Run.
Related to CAM-11911
=> CAM-11911: chore(run): add camunda-welcome to run

webapps/package-lock.json, webapps/ui/cockpit/client/scripts/camunda-cockpit-ui.js, webapps/ui/cockpit/client/scripts/pages/processes.less, webapps/ui/common/styles/pages/dashboard.less
⚠️ Rebase before merging with `origin/master`.
related to CAM-14398
=> chore(cockpit): whitelist `blob` protocol in `href` attr

.ci/daily/Jenkinsfile, Jenkinsfile, distro/run/core/src/test/java/org/camunda/bpm/run/test/TelemetryDataTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsAuthenticationTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/identity/AdminAuthorizationConfigurationTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/identity/AuthenticationWithChangedContextPathTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/identity/DemoUserConfigurationTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/config/identity/LdapConfigurationTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/plugins/CamundaRunProcessEnginePluginsRegistrationTest.java, distro/run/core/src/test/java/org/camunda/bpm/run/test/plugins/ProcessEnginePluginsConfigurationOverrideTest.java
* Increase heap size for Run - Core tests running on JDK8.
Related to CAM-14412
=> CAM-14412: chore(run): increase heap size for jdk8 tests

distro/tomcat/assembly/src/conf/server.xml, parent/pom.xml, qa/tomcat-runtime/src/main/conf/server.xml, webapps/pom.xml
=> CAM-14298: Update Tomcat to 9.0.58

engine-rest/engine-rest/pom.xml, internal-dependencies/pom.xml, parent/pom.xml, webapps/pom.xml
=> chore(webapps): move webapps to jax rs 2 api

engine/src/main/java/org/camunda/bpm/engine/authorization/BatchPermissions.java, engine/src/main/java/org/camunda/bpm/engine/authorization/HistoricProcessInstancePermissions.java, engine/src/main/java/org/camunda/bpm/engine/authorization/HistoricTaskPermissions.java, engine/src/main/java/org/camunda/bpm/engine/authorization/OptimizePermissions.java, engine/src/main/java/org/camunda/bpm/engine/authorization/Permissions.java, engine/src/main/java/org/camunda/bpm/engine/authorization/ProcessDefinitionPermissions.java, engine/src/main/java/org/camunda/bpm/engine/authorization/ProcessInstancePermissions.java, engine/src/main/java/org/camunda/bpm/engine/authorization/SystemPermissions.java, engine/src/main/java/org/camunda/bpm/engine/authorization/TaskPermissions.java, engine/src/main/java/org/camunda/bpm/engine/authorization/UserOperationLogCategoryPermissions.java
Other Permission classes might have to be fixed as well
related to CAM-14354
=> [CAM-14354] docs: fix wording in JavaDoc comment

engine-dmn/feel-scala/pom.xml, engine-dmn/pom.xml, engine-plugins/pom.xml, engine-rest/pom.xml, engine-spring/compatibility-test-spring4/pom.xml, engine/pom.xml, internal-dependencies/pom.xml, parent/pom.xml, qa/test-db-upgrade/pom.xml, webapps/pom.xml
- replace old mockito with new globally
- replace old jaxb with new globally
- replace PermSize jvm arg with MetaspaceSize
- skip test for spring4 compatibility starting of jdk16
related to CAM-14367
=> chore(engine): jdk17 cleanup

webapps/camunda-bpm-sdk-js/lib/api-client/resources/telemetry.js, webapps/camunda-commons-ui/lib/widgets/debug/cam-widget-debug.html, webapps/camunda-commons-ui/lib/widgets/debug/cam-widget-debug.js, webapps/ui/admin/client/scripts/pages/diagnostics.html, webapps/ui/admin/client/scripts/pages/diagnostics.js, webapps/ui/admin/client/scripts/pages/main.js
=> CAM-14068: request platform information via the Camunda Webapps

.ci/config/matrices.yaml, .ci/config/stage-types.yaml
=> chore(ci): jdk17 stages

webapps/package-lock.json, webapps/package.json
=> CAM-14431: update form-js to 0.7.0

clients/java/client/pom.xml, distro/wildfly/assembly/src/wildfly/standalone-full.xml, distro/wildfly/assembly/src/wildfly/standalone.xml, distro/wildfly/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/util/FixedObjectTypeAttributeDefinition.java, parent/pom.xml, qa/integration-tests-webapps/pom.xml, qa/integration-tests-webapps/shared-engine/pom.xml, qa/integration-tests-webapps/standalone-engine/pom.xml, qa/vanilla-runtimes/wildfly/pom.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml, qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
=> feat(distro/wildfly): add compatibility for widlfly 26

spring-boot-starter/starter-test/pom.xml, test-utils/assert/pom.xml, test-utils/junit5-extension/pom.xml
=> chore(test-utils/assert): manage `assertj` version by spring boot

.ci/daily/Jenkinsfile, Jenkinsfile
* Trigger the Camunda Docker repo GHA workflow from the Daily CE pipeline.
Related to CAMTEAM-231
=> CAMTEAM-231: feat(ci): trigger docker gha from pipeline

CONTRIBUTING.md, settings/maven/nexus-settings.xml, webapps/.npmrc, webapps/camunda-bpm-sdk-js/.npmrc, webapps/pom.xml
=> Change to the new artifactory domain

test-utils/junit5-extension/pom.xml, test-utils/junit5-extension/src/main/java/org/camunda/bpm/engine/test/junit5/ProcessEngineExtension.java, test-utils/junit5-extension/src/test/java/org/camunda/bpm/engine/test/junit5/ProcessEngineExtensionRequiredDatabaseTest.java, test-utils/junit5-extension/src/test/java/org/camunda/bpm/engine/test/junit5/ProcessEngineExtensionRequiredHistoryLevelAuditTest.java, test-utils/junit5-extension/src/test/java/org/camunda/bpm/engine/test/junit5/ProcessEngineExtensionSetTimeTest.java, test-utils/junit5-extension/src/test/java/org/camunda/bpm/engine/test/junit5/deployment/ProcessEngineExtensionManageDeploymentsTest.java, test-utils/junit5-extension/src/test/java/org/camunda/bpm/engine/test/junit5/deployment/ProcessEngineExtensionResourcesDeploymentTest.java, test-utils/junit5-extension/src/test/java/org/camunda/bpm/engine/test/junit5/registerExtension/RegisterNewProcessEngineTest.java
=> feat(junit5): make JUnit 5 extension feature equal to JUnit 4 rule

bom/pom.xml, pom.xml, test-utils/assert/core/pom.xml, test-utils/assert/pom.xml, test-utils/assert/qa/pom.xml, test-utils/assert/qa/src/test/java/org/camunda/bpm/engine/test/assertions/junit5/ProcessEngineExtensionCompatibilityTest.java, test-utils/assert/qa/src/test/resources/camunda.cfg.xml, test-utils/assert/qa/src/test/resources/simpleProcess.bpmn, test-utils/junit5-extension/src/main/java/org/camunda/bpm/engine/test/junit5/ProcessEngineExtension.java
=> chore(junit5/assert): add test for junit5 + assert

distro/license-book/src/main/resources/license-book.txt
=> CAM-14231: update license book to 7.17

database/pom.xml, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.cockroachdb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/camunda-changelog.xml, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/cockroachdb_engine_7.17_to_7.18.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.17_to_7.18.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.17_to_7.18.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.17_to_7.18.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.17_to_7.18.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.17_to_7.18.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.17_to_7.18.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.17_to_7.18.sql, qa/test-db-instance-migration/pom.xml, qa/test-db-instance-migration/test-fixture-718/pom.xml, qa/test-db-instance-migration/test-fixture-718/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java, qa/test-db-instance-migration/test-fixture-718/src/main/resources/camunda.cfg.xml, qa/test-db-rolling-update/create-new-engine/pom.xml, qa/test-db-rolling-update/create-old-engine/pom.xml, qa/test-db-rolling-update/rolling-update-util/pom.xml, qa/test-db-rolling-update/test-old-engine/pom.xml, qa/test-db-upgrade/pom.xml, qa/test-old-engine/pom.xml
=> chore(release): prepare codebase for 7.18 development

parent/pom.xml
* bumps Spring Boot to 2.6.6
* bumps Spring Framework to 5.2.20.RELEASE
related to CAM-14516
=> chore(parent): bump Spring versions

pom.xml
* bumps Spin to 1.14.1
* bumps Connect to 1.5.3
related to CAM-14106
=> chore(project): bump Spin and Connect versions

webapps/camunda-commons-ui/lib/widgets/debug/cam-widget-debug.html
=> CAM-14507: display copy option when the mouse is on the JSON telemetry data

engine/src/main/java/org/camunda/bpm/application/impl/ProcessApplicationLogger.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/behavior/BpmnBehaviorLogger.java, spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/util/SpringBootProcessEngineLogger.java
Consistency: Most log messages start the sentence with upper case,
so others should also.
=> Start all messages with upper case

engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/el/ExpressionEvaluationTest.java, engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/BreakingScalaFeelBehaviorTest.java, engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/el/ExpressionEvaluationTest.inputVariableName.dmn, engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/el/ExpressionEvaluationTest.overrideInputVariableName.dmn, engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/el/ExpressionEvaluationTest.variableContext.dmn, engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/el/ExpressionEvaluationTest.variableContextWithInputVariable.dmn, pom.xml
=> chore(engine-dmn): bump feel engine to version 1.14.2

engine/src/main/java/org/camunda/bpm/engine/impl/test/TestHelper.java, test-utils/junit5-extension/pom.xml, test-utils/junit5-extension/src/test/java/org/camunda/bpm/engine/test/junit5/deployment/EnsureDbCleanTest.java
=> CAM-14511: remove need for junit-vintage-engine

clients/java/client/pom.xml
=> chore(clients): bump HTTP client to 4.5.13 in XTaC

database/pom.xml
=> chore(database): bump MySQL connector to 8.0.28

.ci/config/matrices.yaml, .ci/config/stage-types.yaml, Jenkinsfile, database/pom.xml, engine/pom.xml, engine/src/test/java/org/camunda/bpm/engine/test/persistence/DatabaseFlushTest.java, qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/util/DeploymentHelper.java, qa/test-db-upgrade/pom.xml, qa/test-old-engine/pom.xml
- remove mariadb 10.2
- remove mariadb galera
- remove was85
- remove jdk 12,13,14,15
- remove postgres 9.6
related to CAM-14266
=> chore(ci): remove unsupported environments

parent/pom.xml
=> chore(database): bump Resteasy to 3.15.3.Final

parent/pom.xml, pom.xml
=> chore(deps): bump logback to version 1.2.11

webapps/ui/cockpit/client/scripts/pages/decision-instance.html
=> CAM-14149: display removal time for process and decision instances

webapps/package-lock.json, webapps/package.json
=> chore(deps): bump moment version

distro/jboss/webapp-standalone/pom.xml, distro/run/assembly/assembly.xml, distro/run/assembly/pom.xml, distro/run/modules/swaggerui/ui/package-lock.json, distro/run/pom.xml, distro/run/qa/runtime/pom.xml, distro/tomcat/assembly/assembly.xml, distro/tomcat/assembly/pom.xml, distro/tomcat/webapp-standalone/pom.xml, distro/wildfly/assembly/assembly.xml, distro/wildfly/assembly/pom.xml, distro/wildfly/modules/pom.xml, distro/wildfly/modules/src/main/modules/org/codehaus/groovy/groovy-all/main/module.xml, engine-dmn/engine/pom.xml, engine-plugins/connect-plugin/pom.xml, engine-plugins/spin-plugin/pom.xml, engine-rest/pom.xml, engine-spring/compatibility-test-spring4/pom.xml, engine-spring/core/pom.xml, engine/pom.xml, internal-dependencies/pom.xml, parent/pom.xml, qa/integration-tests-engine/pom.xml, qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/deployment/war/TestWarDeploymentWithProcessEnginePlugin.java, qa/test-db-instance-migration/test-fixture-710/pom.xml, qa/test-db-instance-migration/test-migration/pom.xml, qa/test-db-upgrade/pom.xml, qa/test-old-engine/pom.xml
=> CAM-14302: chore(engine): bump groovy to 2.5.16

parent/pom.xml, quarkus-extension/engine/deployment/pom.xml, quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/ManagedJobExecutorTest.java, quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineDefaultConfigTest.java, quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineProgrammaticAndConfigFileTest.java, quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/helper/ProcessEngineAwareExtension.java, quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/id/ConfigureDbIdGeneratorTest.java
=> chore(quarkus): support version 2.8.1

distro/run/modules/example/pom.xml, distro/run/modules/example/src/main/java/org/camunda/bpm/run/example/invoice/Application.java
=> fix(distro/run): let example serve `camunda-invoice` assets

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/identity/IdentityServiceAuthorizationsTest.java
=> fix(engine): fix tenant <-> group/user membership deletion

engine-cdi/core/src/main/java/org/camunda/bpm/engine/cdi/impl/event/CdiEventSupportBpmnParseListener.java, engine/src/main/java/org/camunda/bpm/application/impl/event/ProcessApplicationEventParseListener.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/AbstractBpmnParseListener.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParseListener.java, engine/src/main/java/org/camunda/bpm/engine/impl/history/parser/HistoryParseListener.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/deploy/BPMNParseListenerTest.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/deploy/DelegatingBpmnParseListener.java, engine/src/test/resources/org/camunda/bpm/engine/test/standalone/deploy/BPMNParseListenerTest.shouldInvokeParseIoMapping.bpmn20.xml
=> feat(engine): BpmnParseListener provides methods for I/O mappings

spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappInitializer.java, spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/filter/ResourceLoadingProcessEnginesFilter.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/redirect/ResourceLoadingProcessEnginesAppPathCamundaIndexRedirectTest.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/redirect/ResourceLoadingProcessEnginesAppPathCamundaTest.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/redirect/ResourceLoadingProcessEnginesAppPathRootIndexRedirectTest.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/redirect/ResourceLoadingProcessEnginesAppPathRootTest.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/util/HeaderRule.java, spring-boot-starter/starter-webapp-core/src/test/resources/static/index.html
=> fix(spring-boot): index-redirect=false should not redirect to Tasklist

pom.xml
=> chore(deps): bump spin to 1.16.0

distro/license-book/src/main/resources/license-book.txt
=> CAM-14617: update AngularJS libraries

README.md
=> CAM-14617: inform about and link to third-party dependency docs

distro/run/assembly/resources/production.yml, webapps/camunda-commons-ui/lib/auth/page/login.html, webapps/camunda-commons-ui/lib/auth/page/login.less, webapps/camunda-commons-ui/lib/widgets/footer/cam-widget-footer.html, webapps/camunda-commons-ui/lib/widgets/footer/cam-widget-footer.less, webapps/src/main/java/org/camunda/bpm/webapp/impl/engine/ProcessEnginesFilter.java, webapps/src/main/java/org/camunda/bpm/webapp/impl/security/filter/headersec/HttpHeaderSecurityFilter.java, webapps/src/main/java/org/camunda/bpm/webapp/impl/security/filter/headersec/provider/HeaderSecurityProvider.java, webapps/src/main/java/org/camunda/bpm/webapp/impl/security/filter/headersec/provider/impl/ContentSecurityPolicyProvider.java, webapps/src/test/java/org/camunda/bpm/webapp/impl/security/filter/headersec/ContentSecurityPolicyTest.java, webapps/ui/admin/client/scripts/index.html, webapps/ui/admin/client/styles/styles.less, webapps/ui/cockpit/client/scripts/directives/processDiagram.html, webapps/ui/cockpit/client/scripts/directives/processDiagram.less, webapps/ui/cockpit/client/scripts/directives/time-to-live/time-to-live.html, webapps/ui/cockpit/client/scripts/directives/time-to-live/time-to-live.less, webapps/ui/cockpit/client/scripts/index.html, webapps/ui/cockpit/client/styles/styles-components.less, webapps/ui/cockpit/client/styles/styles.less, webapps/ui/common/styles/app-splash.less, webapps/ui/tasklist/client/index.html, webapps/ui/tasklist/client/styles/styles.less, webapps/ui/welcome/client/scripts/index.html, webapps/ui/welcome/client/styles/styles.less
- define stricter content security policy
- generate and use nonce in index files
- extract inline styles
related to CAM-14139
=> feat(engine): stricter content security policy

distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/swaggerui/SwaggerUIGetRequestIT.java, distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/webapps/LoginIT.java, distro/run/qa/pom.xml, parent/pom.xml, qa/integration-tests-webapps/integration-tests/pom.xml, qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/LoginIT.java, qa/integration-tests-webapps/pom.xml, spring-boot-starter/starter-qa/integration-test-webapp/runtime/pom.xml
=> feat(spring-boot): support version 2.7.0

engine/src/main/java/org/camunda/bpm/engine/impl/javax/el/BeanELResolver.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/el/ExpressionManagerTest.java
=> fix(engine): fix problematic exception handling for Java 17

engine-cdi/core/pom.xml, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ContextLogger.java, pom.xml
=> feat(logging): add config property for bpmn stacktrace log level

engine/.clirr-jenkins-ignore.xml
* ignore superclass change in public API for MockExpressionManager
related to CAM-14530
=> chore(engine): add exception to clirr

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ProcessDataContext.java
=> feat(engine): add processDefinitionKey to logging mdc

qa/integration-tests-engine/pom.xml
- removes a code comment that contradicts the actual code
related to CAM-14711
=> CAM-14711: remove dead code

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ProcessDataContext.java
=> feat(engine): add activityName to logging mdc

engine-rest/engine-rest-openapi/src/main/templates/paths/metrics/get.ftl
=> chore(openapi): remove task worker metrics from interval

distro/sql-script/src/test/java/org/camunda/bpm/sql/test/SqlScriptTest.java
* Clean the database before executing the raw SQL scripts
related to CAM-14750
=> chore(engine): stabilize SqlScriptTest

engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ExceptionCodeInterceptor.java, engine/src/test/java/org/camunda/bpm/engine/test/errorcode/ExceptionBuiltinCodesTest.java, engine/src/test/java/org/camunda/bpm/engine/test/errorcode/conf/CustomErrorCodeProviderTest.java
=> fix(engine): skip writing log when code is already fallback code

webapps/camunda-commons-ui/lib/widgets/variables-table/cam-widget-variables-table.js, webapps/ui/cockpit/plugins/decisionList/app/views/decisionInstance/inputTable.js
=> CAM-14423: Cockpit Decision View shows date variables as invalid when they are not

webapps/camunda-commons-ui/lib/plugin/view.js, webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task.html, webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task.js
=> CAM-14696: Tasklist Plugin: method render does not get called on changing human task

engine/src/test/java/org/camunda/bpm/engine/test/persistence/SuppressSqlExceptionsTest.java
- fixes MultiInstanceTest, ProcessInstantiationAtActivitiesHistoryTest,
HistoricActivityInstanceTest
- root cause was that a previous test exchange the history level
but didn't fully restore the original one. See CAM-13862 for details
related to CAM-13862, CAM-13824
=> CAM-13862: fix unstable history tests in the assembly build

webapps/ui/cockpit/plugins/decisionList/app/views/decisionInstance/inputTable.js, webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task.js
=> chore(tasklist): fix eslint error breaking assembly build

database/pom.xml
=> CAM-14489: update h2 to 2.1.214

webapps/ui/cockpit/client/scripts/batches/components/batch.js, webapps/ui/cockpit/client/scripts/batches/controllers/view-ctrl.js, webapps/ui/cockpit/client/scripts/batches/templates/cam-cockpit-batch-view.html, webapps/ui/common/styles/app-splash.less
=> feat(batch): show username for in progress batches

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/signal/SignalEventConcurrencyTest.java, engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrencyTestHelper.java, engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/signal/SignalEventConcurrencyTest.testSignalWithCompletedExecution.bpmn20.xml
=> fix(engine): fix NPE with send signal to execution

webapps/ui/cockpit/client/scripts/batches/components/batch.js, webapps/ui/cockpit/client/scripts/batches/components/delete.js, webapps/ui/cockpit/client/scripts/batches/controllers/modal-ctrl.js, webapps/ui/cockpit/client/scripts/batches/controllers/view-ctrl.js, webapps/ui/cockpit/client/scripts/batches/templates/cam-cockpit-batch-view.html, webapps/ui/cockpit/client/scripts/batches/templates/delete-modal.html
=> feat(batch): delete historic batch entity feature

webapps/package-lock.json
=> fix(webapps): update commit hash of the translations repo

Jenkinsfile
=> fix(ci): change xlts.dev secrets vault path

engine/src/test/java/org/camunda/bpm/engine/test/errorcode/DeadlockTest.java
=> test(engine): fix flaky deadlock test on sql server

webapps/ui/common/styles/_three-cols-layout.less
=> CAM-14804: In Tasklist and Cockpit, update to Google Chrome v. 104 causes columns to change size

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/VariableInstanceConcurrentLocalInitializer.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstantiationAtActivitiesTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/concurrentExecutionVariable.bpmn20.xml, engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/concurrentExecutionVariableWithSubprocess.bpmn20.xml
=> CAM-14506: don't make variable concurrent on single execution 

engine/src/main/java/org/camunda/bpm/engine/impl/util/ExceptionUtil.java
=> fix(engine): make deadlock check null safe

engine/src/main/java/org/camunda/bpm/engine/impl/javax/el/BeanELResolver.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/el/ExpressionManagerTest.java
=> fix(engine): find method by resolving types from param vals in juel

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java, spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/CamundaEventingIT.java
=> chore(engine/springboot): fix historic task update events for related entities

clients/java/client/src/it/java/org/camunda/bpm/client/client/ClientIT.java, clients/java/client/src/it/java/org/camunda/bpm/client/rule/EngineRule.java, clients/java/client/src/it/java/org/camunda/bpm/client/util/RecordingExternalTaskHandler.java, clients/java/client/src/it/java/org/camunda/bpm/client/variable/pa/PaExceptionIT.java, clients/java/client/src/main/java/org/camunda/bpm/client/backoff/ErrorAwareBackoffStrategy.java, clients/java/client/src/main/java/org/camunda/bpm/client/backoff/ExponentialErrorBackoffStrategy.java, clients/java/client/src/main/java/org/camunda/bpm/client/exception/BadRequestException.java, clients/java/client/src/main/java/org/camunda/bpm/client/exception/EngineException.java, clients/java/client/src/main/java/org/camunda/bpm/client/exception/ExternalTaskClientException.java, clients/java/client/src/main/java/org/camunda/bpm/client/exception/NotAcquiredException.java, clients/java/client/src/main/java/org/camunda/bpm/client/exception/NotFoundException.java, clients/java/client/src/main/java/org/camunda/bpm/client/exception/NotResumedException.java, clients/java/client/src/main/java/org/camunda/bpm/client/exception/RestException.java, clients/java/client/src/main/java/org/camunda/bpm/client/exception/UnknownHttpErrorException.java, clients/java/client/src/main/java/org/camunda/bpm/client/impl/EngineClient.java, clients/java/client/src/main/java/org/camunda/bpm/client/impl/EngineClientException.java, clients/java/client/src/main/java/org/camunda/bpm/client/impl/EngineClientLogger.java, clients/java/client/src/main/java/org/camunda/bpm/client/impl/EngineRestExceptionDto.java, clients/java/client/src/main/java/org/camunda/bpm/client/impl/ExternalTaskClientLogger.java, clients/java/client/src/main/java/org/camunda/bpm/client/impl/RequestExecutor.java, clients/java/client/src/main/java/org/camunda/bpm/client/task/ExternalTaskService.java, clients/java/client/src/main/java/org/camunda/bpm/client/task/impl/ExternalTaskServiceImpl.java, clients/java/client/src/main/java/org/camunda/bpm/client/task/impl/dto/ExceptionResponseDto.java, clients/java/client/src/main/java/org/camunda/bpm/client/topic/impl/TopicSubscriptionManager.java, clients/java/client/src/main/java/org/camunda/bpm/client/topic/impl/TopicSubscriptionManagerLogger.java, clients/java/client/src/main/java/org/camunda/bpm/client/topic/impl/dto/FetchAndLockResponseDto.java, clients/java/client/src/main/java/org/camunda/bpm/client/variable/impl/value/DeferredFileValueImpl.java, clients/java/client/src/test/java/org/camunda/bpm/client/backoff/ExponentialErrorBackoffStrategyTest.java, clients/java/qa/engine-variable-test/src/main/java/org/camunda/qa/MyExecutionListener.java, clients/java/qa/engine-variable-test/src/main/resources/my-workflow.bpmn
=> feat(clients/java): expose exception error codes

.github/workflows/java-dependency-tree.yml
=> chore(github): use prefixed label to trigger bot

parent/pom.xml
=> CAM-14611: chore(parent): bump spring and spring-boot versions

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ProcessDataContext.java, engine/src/test/java/org/camunda/bpm/engine/test/logging/LogEngineNameDelegate.java, engine/src/test/java/org/camunda/bpm/engine/test/logging/ProcessDataLoggingContextMultipleEnginesTest.java, engine/src/test/java/org/camunda/bpm/engine/test/logging/ProcessDataLoggingContextTest.java
=> feat(engine): add engineName to MDC

webapps/grunt/tasks/license-header.js
=> chore(webapps): add license header to `lib/globalize.js`

webapps/ui/admin/client/scripts/camunda-admin-bootstrap.js, webapps/ui/cockpit/client/scripts/camunda-cockpit-bootstrap.js, webapps/ui/common/scripts/services/plugins/loadPlugins.js, webapps/ui/tasklist/client/scripts/camunda-tasklist-bootstrap.js, webapps/ui/welcome/client/scripts/camunda-welcome-bootstrap.js
=> fix(webapps): determine plugin path without traversal 

webapps/package.json
=> chore(webapps): bump xlts.dev angularjs

database/pom.xml
* Oracle 18
* DB2 10.5 / 11.1
related to CAM-14669
=> chore(database): cleanup `database/pom.xml` from retired envs

webapps/camunda-commons-ui/grunt/tasks/ensureLibs.js, webapps/package-lock.json, webapps/package.json, webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form-camunda.js
* Support for forms with multi-select components and checkboxes/dropdowns/radio buttons that are pre-populated with process data ("dynamic forms").
* Fill out multi-select components (taglist and checklist) with data from a process variable.
* Define the available select-options for select-type form components (checklist, radio, select, and taglist) with data from a process variable (pre-populated).
related to CAM-14886
=> feat(tasklist): add support for dynamic camunda forms

webapps/camunda-commons-ui/lib/widgets/selection-type/cam-widget-selection-type.html, webapps/camunda-commons-ui/lib/widgets/selection-type/cam-widget-selection-type.js, webapps/camunda-commons-ui/lib/widgets/selection-type/cam-widget-selection-type.less, webapps/ui/cockpit/client/en.json, webapps/ui/cockpit/client/styles/styles.less
=> feat(cockpit): improve safety of the migration operation

engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/signal/SignalEventConcurrencyTest.java
=> test(engine): exclude concurrency signal event test on cockroachdb

engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/FailedJobListener.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobExecutorLogger.java, engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentJobExecutorTest.java
=> fix(engine): skip FailedJobListener for timed out & already re-acquired jobs

distro/license-book/src/main/resources/license-book.txt
=> CAM-14539: update license book for 7.18

webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form-camunda.js
=> fix(tasklist): fix problem with start forms

database/pom.xml, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.cockroachdb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/camunda-changelog.xml, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/cockroachdb_engine_7.18_to_7.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.18_to_7.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.18_to_7.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.18_to_7.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.18_to_7.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.18_to_7.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.18_to_7.19.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.18_to_7.19.sql, qa/test-db-instance-migration/pom.xml, qa/test-db-instance-migration/test-fixture-719/pom.xml, qa/test-db-instance-migration/test-fixture-719/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java, qa/test-db-instance-migration/test-fixture-719/src/main/resources/camunda.cfg.xml, qa/test-db-rolling-update/create-new-engine/pom.xml, qa/test-db-rolling-update/create-old-engine/pom.xml, qa/test-db-rolling-update/rolling-update-util/pom.xml, qa/test-db-rolling-update/test-old-engine/pom.xml, qa/test-db-upgrade/pom.xml, qa/test-old-engine/pom.xml
=> chore(release): prepare codebase for 7.19 development

CONTRIBUTING.md, README.md
=> CAMTEAM-269: update to github issues and explain details

.ci/daily/Jenkinsfile
=> chore(ci): adjust staging folder for javadoc

.github/actions/common/dist/index.js, .github/actions/common/index.js, .github/actions/common/src/synchronize-label-colors.js, .github/actions/common/src/utils/collection-utils.js, .github/actions/synchronize-label-colors/action.yml, .github/actions/synchronize-label-colors/index.js, .github/workflows/sync-label-colors.yml
=> CAMTEAM-272: add workflow that synchronizes label colors

webapps/package-lock.json, webapps/package.json
=> chore(webapp): update jquery-ui to 1.13.2

engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireCleanupJobsTest.java
- test class name must end in Test
related to #2571
=> 2571: make surefire pick up history cleanup test

engine/src/main/java/org/camunda/bpm/engine/FilterService.java
=> chore(engine): fix a few typos

engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringBeansResolverFactory.java, spring-boot-starter/pom.xml, spring-boot-starter/starter-qa/integration-test-request-scope/pom.xml, spring-boot-starter/starter-qa/integration-test-request-scope/src/test/java/org/camunda/bpm/springboot/project/qa/simple/Application.java, spring-boot-starter/starter-qa/integration-test-request-scope/src/test/java/org/camunda/bpm/springboot/project/qa/simple/RequestScopeIT.java, spring-boot-starter/starter-qa/integration-test-request-scope/src/test/java/org/camunda/bpm/springboot/project/qa/simple/RequestScopedTestBean.java, spring-boot-starter/starter-qa/integration-test-request-scope/src/test/java/org/camunda/bpm/springboot/project/qa/simple/TestBean.java, spring-boot-starter/starter-qa/integration-test-request-scope/src/test/resources/application.properties, spring-boot-starter/starter-qa/integration-test-request-scope/src/test/resources/logback-test.xml, spring-boot-starter/starter-qa/pom.xml
=> fix(engine-spring): handle inactive scope for beans available in scripts

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/TaskCountByCandidateGroupResultDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/delete.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/report/candidate-group-count/get.ftl
=> chore(openapi): add missing endpoints

engine/src/main/java/org/camunda/bpm/engine/impl/javax/el/BeanELResolver.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/el/ExpressionManagerTest.java
=> fix(engine): fix bean method resolution with null param values 

webapps/package-lock.json, webapps/package.json
=> chore(webapp): update moment to 2.29.4

.github/ISSUE_TEMPLATE/config.yml
=> CAMTEAM-276: disable creating blank issues

.ci/daily/Jenkinsfile, engine-rest/docs/package-lock.json, engine-rest/docs/package.json, engine-rest/docs/pom.xml, engine-rest/docs/template.hbs, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/key/{key}/diagram/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/key/{key}/tenant-id/{tenant-id}/diagram/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/{id}/diagram/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/{varName}/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/variable-instance/{id}/data/get.ftl, engine-rest/pom.xml
=> [#2876]: Add CI to generate REST Docs from Open API definition

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
https://github.com/camunda/camunda-bpm-platform/issues/2856
=> [2856] chore(ci): switch to Maven 3.8

webapps/ui/admin/client/scripts/pages/execution-metrics.js
=> fix(admin): fix TypeError in metrics

.github/actions/common/dist/index.js, .github/actions/common/package-lock.json, .github/actions/common/package.json, .github/actions/common/src/extract-links.js, .github/workflows/add-issue-to-project.yml, .github/workflows/copy-issue.yml, .github/workflows/extract-issue-links.yml, .github/workflows/java-dependency-tree.yml, .github/workflows/sync-label-colors.yml
Also updates the dependencies of all workflows to avoid the recent deprecations of npm versions and set output functions
I tested the workflows (except dependency tree diff) in https://github.com/camunda/automation-platform-github-test1.
related to CAMTEAM-280
=> CAMTEAM-280: fix workflow for extracting JIRA links from issues

Jenkinsfile
=> chore(ci): exclude rest docs from wls-compatibility

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/telemetry/TelemetryInternalsDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/telemetry/data/get.ftl, engine-rest/engine-rest-openapi/src/test/java/org/camunda/bpm/engine/rest/openapi/client/ProcessInstanceTest.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/telemetry/InternalsDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TelemetryRestServiceTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/TelemetryConfigureCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/InternalsImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java, engine/src/main/java/org/camunda/bpm/engine/impl/util/ClockUtil.java, engine/src/main/java/org/camunda/bpm/engine/impl/util/JsonUtil.java, engine/src/main/java/org/camunda/bpm/engine/telemetry/Internals.java, engine/src/test/java/org/camunda/bpm/engine/impl/util/ClockUtilTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceGetTelemetryDataTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java, parent/pom.xml, qa/test-old-engine/pom.xml
=> chore(engine): add telemetry data collection time frame info

pom.xml
=> [2818] chore(deps): bump `feel-scala` engine to version `1.15.3`

webapps/camunda-commons-ui/vendor/dataDepend.js, webapps/camunda-commons-ui/vendor/jquery.js
=> test(karma): fix permanently

webapps/camunda-commons-ui/lib/analytics/index.js, webapps/camunda-commons-ui/lib/analytics/modal.html, webapps/ui/admin/client/scripts/pages/analytics.html, webapps/ui/admin/client/scripts/pages/analytics.js
=> fix(webapps): make telemetry setting toggleable again

parent/pom.xml
=> chore(distro): bump Tomcat to 9.0.69

database/pom.xml
=> chore(database): update postgresql jdbc driver 42.3.3 to 42.4.1

parent/pom.xml
Related to camunda/camunda-bpm-platform#2841
=> chore(deps): update spring boot to 2.7.6

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/task.md
Added a check mark along with the information for the Dev2QA handover.
=> Update templates with Dev2QA handover.

webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form-camunda.js
=> fix(tasklist): support option source static for camunda forms

engine-plugins/identity-ldap/src/main/java/org/camunda/bpm/identity/impl/ldap/LdapIdentityProviderSession.java, engine-plugins/identity-ldap/src/main/java/org/camunda/bpm/identity/impl/ldap/LdapUserQueryImpl.java, engine-plugins/identity-ldap/src/test/java/org/camunda/bpm/identity/impl/ldap/LdapEnableSortControlSupportTest.java
=> [3003]: Ldap sorting two directions

webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task-meta.html, webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task-meta.js, webapps/ui/tasklist/client/scripts/tasklist/directives/cam-tasklist-tasks.html, webapps/ui/tasklist/client/scripts/tasklist/directives/cam-tasklist-tasks.js
=> fix(webapp/tasklist): fix display of tasks with empty string assignee

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
Related to camunda/camunda-bpm-platform#3022
=> chore(ci): disable concurrent build executions

.ci/daily/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
https://github.com/camunda/camunda-bpm-platform/issues/3024
=> chore(ci): add withLabels to all stages

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/UserEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/api/identity/IdentityServiceTest.java
related to camunda/camunda-bpm-platform#2850
=> 2850: remove password and salt fields from user#toString

.ci/daily/Jenkinsfile
=> feat(docker): increase gha trigger timeout

.ci/daily/Jenkinsfile, .ci/main-trigger/Jenkinsfile, .ci/sidetrack/Jenkinsfile, Jenkinsfile
Related to camunda/camunda-bpm-platform#3061
=> chore(ci): add custom span attributes (OTEL) at the pipelines end

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobManager.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/BatchJobPriorityRangeTest.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/HistoryCleanupJobPriorityRangeTest.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsForPriorityRangeTest.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorPriorityRangeConfigurationTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsForPriorityRangeTest.jobPrioProcess.bpmn20.xml
=> fix(engine): allow negative job priorities and fix SQL

webapps/src/main/java/org/camunda/bpm/cockpit/plugin/resource/AbstractCockpitPluginResource.java, webapps/src/test/java/org/camunda/bpm/cockpit/plugin/base/tenantcheck/IncidentRestServiceTenantCheckTest.java, webapps/src/test/java/org/camunda/bpm/cockpit/plugin/base/tenantcheck/ProcessDefinitionResourceTenantCheckTest.java, webapps/src/test/java/org/camunda/bpm/cockpit/plugin/base/tenantcheck/ProcessInstanceResourceTenantCheckTest.java, webapps/src/test/java/org/camunda/bpm/cockpit/plugin/base/tenantcheck/ProcessInstanceRestServiceTenantCheckTest.java
=> fix(webapps): include admin groups & users in admin check

webapps/ui/cockpit/client/scripts/directives/time-to-live/time-to-live-dialog.html, webapps/ui/cockpit/client/scripts/directives/time-to-live/time-to-live-dialog.js
=> fix(webapp/cockpit): fix history ttl csp problem

engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsForPriorityRangeTest.java
=> chore(test): fix failing job prio tests for MSSQL and DB2

.ci/daily/Jenkinsfile
=> chore(ci): fetch the project version from the JOB_NAME

Jenkinsfile
=> chore(ci): add explicit check for default branch in assembly stage

.github/workflows/extract-issue-links.yml
=> CAMTEAM-291: publish translation notification on minor releases

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobDeclaration.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/migration/MigrateSuspendedInstanceTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/migration/MigrationTransitionInstancesTest.java
=> fix(engine): set job suspension state on migrate when PI is suspended

engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/migration/MigrationTransitionInstancesTest.java
=> chore(test): fix failing date comparison in mysql test

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/repository/impl/ProcessDefinitionResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessDefinitionRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/RepositoryService.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CreateMigrationPlanCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteHistoricVariableInstanceCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteHistoricVariableInstancesByProcessInstanceIdCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/deploy/cache/ProcessDefinitionCache.java, engine/src/test/java/org/camunda/bpm/engine/test/api/repository/RepositoryServiceTest.java
related to camunda/camunda-bpm-platform#3116
=> 3116: return 404 when process definition xml is not found

database/pom.xml, test-utils/testcontainers/pom.xml
to com.mysql:mysql-connector-j
Related to camunda/camunda-bpm-platform#2780
=> chore(deps): adjust mysql-connector-java dependency

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobRetriesDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/SetJobRetriesByProcessDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/SetJobRetriesDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job-definition/{id}/retries/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job/retries/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/retries/put.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/job-retries-historic-query-based/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/job-retries/post.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/RetriesDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/SetJobRetriesByProcessDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/SetJobRetriesDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/JobRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ProcessInstanceRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/management/JobDefinitionResourceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/JobResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobDefinitionRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
=> feat(engine): allow update duedate on set job retries (REST API)

engine/src/main/java/org/camunda/bpm/engine/management/SetJobRetriesByJobsAsyncBuilder.java, engine/src/main/java/org/camunda/bpm/engine/management/SetJobRetriesByProcessAsyncBuilder.java
=> chore(javadocs): fix javadocs for set job retries batch builders

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Statistics.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/TenantIdProviderTest.java
https://github.com/camunda/camunda-bpm-platform/issues/3127
=> fix(engine): add tenant check for activity statistics filters

webapps/camunda-bpm-sdk-js/lib/api-client/http-client.js, webapps/camunda-commons-ui/lib/services/HttpClient.js, webapps/camunda-commons-ui/lib/services/ifUnauthorizedForwardToWelcomeApp.js, webapps/camunda-commons-ui/lib/services/index.js
=> [3148]: fix(webapps): forward to welcome app if unauthorized

internal-dependencies/pom.xml, parent/pom.xml
related to camunda/camunda-bpm-platform#3180
=> chore(project): update commons-fileupload, tomcat, spring boot

engine/src/test/java/org/camunda/bpm/engine/test/bpmn/el/ExpressionManagerTest.java
related to camunda/camunda-bpm-platform#3195
=> chore(engine): make ExpressionManagerTest reset the mocks

distro/run/modules/swaggerui/pom.xml
=> chore(swaggerui): remove owasp dependency check config

engine-cdi/core/pom.xml, engine-cdi/jakarta/pom.xml, engine-cdi/pom.xml
=> chore(cdi): clean up Maven configuration

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobRetriesDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/SetJobRetriesByProcessDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/SetJobRetriesDto.ftl
=> fix(openapi): include duedate parameter for all job retries endpoints

parent/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/2788
=> chore(deps): update quarkus 2.x

engine-rest/engine-rest-jakarta/pom.xml
=> fix(engine-rest): fix jdk profile activation problem

webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task.js
related to camunda/camunda-bpm-platform#3164
=> fix(tasklist): changing task props don't re-render plugin

webapps/ui/cockpit/plugins/decisionList/app/views/decisionInstance/outputTable.js
related to camunda/camunda-bpm-platform#2866
=> fix(cockpit): fix display of date in dmn output table

engine/src/main/java/org/camunda/bpm/engine/impl/el/JuelExpressionManager.java, engine/src/test/java/org/camunda/bpm/engine/test/api/cfg/CustomExpressionManagerFunctionsTest.java
=> fix(engine): allow prefixed custom expression functions

settings/maven/nexus-settings.xml
https://github.com/camunda/camunda-bpm-platform/issues/3197
=> chore(settings): adjust nexus mirror

.ci/config/stage-types.yaml, CONTRIBUTING.md
=> fix(ci): fix webapps assembly exclusion

.ci/config/stage-types.yaml, webapps/assembly/pom.xml
=> fix(webapps): fix engine webapps stages and missing groupId

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/JobRestServiceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceInteractionTest.java
=> fix (bug fix): set objectMaper on JobQueryDto

Jenkinsfile, distro/wildfly/webapp/pom.xml
=> chore(distro/wildfly): use jakarta webapps & enable QA

.ci/config/stage-types.yaml, examples/invoice/pom.xml
=> fix(ci): fix stages containing assembly-jakarta

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, webapps/assembly-jakarta/pom.xml, webapps/assembly/pom.xml, webapps/assembly/src/main/java/org/camunda/bpm/admin/impl/web/SetupResource.java, webapps/assembly/src/main/java/org/camunda/bpm/webapp/impl/WebappLogger.java, webapps/assembly/src/main/java/org/camunda/bpm/webapp/impl/security/auth/AuthenticationUtil.java, webapps/assembly/src/main/java/org/camunda/bpm/webapp/impl/security/auth/Authentications.java, webapps/assembly/src/main/java/org/camunda/bpm/webapp/impl/security/auth/UserAuthenticationResource.java, webapps/assembly/src/test/java/org/camunda/bpm/webapp/impl/security/auth/UserAuthenticationResourceLoggingTest.java, webapps/assembly/src/test/java/org/camunda/bpm/webapp/impl/security/auth/UserAuthenticationResourceTest.java, webapps/assembly/src/test/resources/camunda-test-engine.cfg.xml, webapps/pom.xml
=> feat(logging): add webapps logging

webapps/frontend/package-lock.json, webapps/frontend/package.json
related to camunda/camunda-bpm-platform#2731
=> chore(webapps): bump form-js to 0.12.2

.ci/config/stage-types.yaml, .ci/daily/Jenkinsfile, webapps/assembly-jakarta/pom.xml, webapps/assembly/pom.xml
=> chore(webapps): enable jakarta unit tests

webapps/assembly/src/test/resources/logback-test.xml, webapps/assembly/src/test/resources/logging.properties
=> chore(webapps): introduce logback config file

webapps/assembly-jakarta/pom.xml, webapps/assembly/pom.xml, webapps/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/3278
=> fix(webapp): fix third party bom creation

distro/license-book/src/main/resources/license-book.txt
=> chore(license-book): update license book for 7.19.0

database/pom.xml, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.cockroachdb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/camunda-changelog.xml, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/cockroachdb_engine_7.19_to_7.20.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.19_to_7.20.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.19_to_7.20.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.19_to_7.20.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.19_to_7.20.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.19_to_7.20.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.19_to_7.20.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.19_to_7.20.sql, qa/test-db-instance-migration/pom.xml, qa/test-db-instance-migration/test-fixture-720/pom.xml, qa/test-db-instance-migration/test-fixture-720/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java, qa/test-db-instance-migration/test-fixture-720/src/main/resources/camunda.cfg.xml, qa/test-db-rolling-update/create-new-engine/pom.xml, qa/test-db-rolling-update/create-old-engine/pom.xml, qa/test-db-rolling-update/rolling-update-util/pom.xml, qa/test-db-rolling-update/test-old-engine/pom.xml, qa/test-db-upgrade/pom.xml, qa/test-old-engine/pom.xml
Related to #2942 
Related to #2903
=> 2942 prepare codebase next iteration

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/deployer/BpmnDeployer.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteProcessDefinitionsByIdsCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/api/repository/DeleteProcessDefinitionTest.java
=> fix(engine): Add TimerDeclarations when Restoring a ProcessDefinition after Deletion

distro/jboss/webapp-standalone/pom.xml, distro/tomcat/webapp-standalone/pom.xml, distro/wildfly/modules/pom.xml, distro/wildfly/modules/src/main/modules/net/minidev/accessors-smart/main/module.xml, distro/wildfly26/modules/pom.xml, distro/wildfly26/modules/src/main/modules/net/minidev/accessors-smart/main/module.xml, pom.xml
related to camunda/camunda-bpm-platform#3275
=> chore(project): update Spin to 1.19.1

parent/pom.xml
=> chore(parent): Bump resteasy version to 3.15.6

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/deployer/BpmnDeployer.java
=> fix(engine): improve speed of deploying message start event models

.github/ISSUE_TEMPLATE/alpha_release.md
related https://github.com/camunda/team-automation-platform/issues/21
=> chore(github): create alpha release issue template

.github/ISSUE_TEMPLATE/patch_release.md
related to https://github.com/camunda/team-automation-platform/issues/22
=> chore(github): create patch release issue template

parent/pom.xml
=> chore(spring): update spring framework and spring boot

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/deploy/DeploymentTest.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/deploy/SingleVariableListener.java
=> fix(engine): propagate skipCustomListeners in removeTasks

spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/apppath/ChangedAppPathIT.java
related to camunda/camunda-bpm-platform#2748
=> test(spring-boot): correcting frontend lib path

distro/run/modules/swaggerui/ui/webpack.config.js
related to camunda/camunda-bpm-platform#3386
=> chore(run/swaggerui): include prod deps only in license book

webapps/frontend/scripts/xlts.js
related to camunda/camunda-bpm-platform#2748
=> chore(webapps): fix xlts skip registry config

engine/.clirr-jenkins-ignore.xml
https://github.com/camunda/camunda-bpm-platform/issues/2980
=> chore(engine): allow changed JUEL-related members

spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappAutoConfiguration.java, spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappInitializer.java
related to camunda/camunda-bpm-platform#2748
=> fix(webapps): add resource handler for new assets directory

javaee/jobexecutor-ra/pom.xml, parent/pom.xml, pom.xml
of community users
related to 
https://github.com/camunda/camunda-bpm-platform/issues/3366
https://github.com/camunda/team-automation-platform/issues/24
=> chore(pom): add Camunda public artifactory repo for local builds

distro/webjar/pom.xml, webapps/assembly-jakarta/pom.xml, webapps/assembly/pom.xml, webapps/pom.xml
related camunda/camunda-bpm-platform#3402
=> fix(webapps): make `skipFrontendBuild` possible again

webapps/frontend/webpack.common.js, webapps/frontend/webpack.prod.js
related to camunda/camunda-bpm-platform#3400
=> chore(webapps): fix charset of scripts

webapps/frontend/ui/cockpit/client/scripts/components/variables/variable-upload-dialog.html, webapps/frontend/ui/cockpit/client/scripts/components/variables/variable-upload-dialog.js
=> fix(webapps/cockpit): fix variable file upload

distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/webapps/LoginIT.java, distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/webapps/PluginsRootResourceIT.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/PluginsRootResourceIT.java, webapps/assembly/src/main/java/org/camunda/bpm/webapp/plugin/resource/AbstractAppPluginRootResource.java, webapps/assembly/src/test/java/org/camunda/bpm/webapp/plugin/resource/AbstractAppPluginRootResourceTest.java
=> feat(webapps): explicit asset declaration for plugins

engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SubmitStartFormCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/StartProcessInstanceUserOperationLogTest.java, engine/src/test/java/org/camunda/bpm/engine/test/history/useroperationlog/UserOperationLogProcessInstanceTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/oneTaskProcessWithStartForm.bpmn20.xml
=> chore(history): create user op log for starting PI via form

qa/test-old-engine/pom.xml
related to https://github.com/camunda/camunda-bpm-platform/issues/3363
=> test(qa): increase maximum heap size for old engine tests

.ci/config/matrices.yaml, .ci/config/stage-types.yaml
related to https://github.com/camunda/camunda-bpm-platform/issues/3488
=> chore(ci): remove JDK8 CI stages

.ci/config/stage-types.yaml, Jenkinsfile, engine/.clirr-jenkins-ignore.xml, qa/test-db-instance-migration/test-fixture-719/pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/3447
=> 3447: adjust clirr and test fixture

webapps/frontend/ui/common/scripts/module/controllers/cam-pagination-search-integration.js
related to camunda/camunda-bpm-platform#3503
=> fix(cockpit): fix initial deployments page loading

engine/src/main/java/org/camunda/bpm/engine/TaskService.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractSetTaskPropertyCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetTaskDescriptionCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetTaskDueDateCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetTaskFollowUpDateCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskServiceTest.java
- Description
- DueDate
- FollowUpDate
Related to: #3491, #3154
=> chore(engine): Allow Null Values to TaskService Operations

engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/migration/batch/BatchMigrationTest.java, qa/test-old-engine/pom.xml
related to https://github.com/camunda/camunda-bpm-platform/issues/2605
=> test(engine): increase wait time on CRDB for batch test

webapps/frontend/camunda-bpm-sdk-js/lib/forms/type-util.js
related to camunda/camunda-bpm-platform#3501
=> fix(cockpit): fix `fast-xml-parser` usage

.ci/daily/Jenkinsfile
+ exclude 'engine-rest-openapi'
https://github.com/camunda/camunda-bpm-platform/issues/3441
=> fix(ci): run javadocs with JDK 17

engine/src/main/java/org/camunda/bpm/engine/impl/identity/db/DbIdentityServiceProvider.java, engine/src/test/java/org/camunda/bpm/engine/test/api/identity/IdentityServiceAuthorizationsTest.java
related to camunda/camunda-bpm-platform#3564
=> fix(engine): respect user when deleting auth for group memberships

pom.xml
related to camunda/camunda-bpm-platform#3572
=> chore(pom.xml): bump release parent

distro/run/qa/example-plugin/pom.xml, distro/run/qa/example-plugin/src/main/java/org/camunda/bpm/run/plugins/TestCockpitPlugin.java, distro/run/qa/example-plugin/src/main/java/org/camunda/bpm/run/plugins/TestCockpitResource.java, distro/run/qa/example-plugin/src/main/resources/META-INF/services/org.camunda.bpm.cockpit.plugin.spi.CockpitPlugin, distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/plugin/CockpitPluginAutoDeploymentIT.java, distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/util/SpringBootManagedContainer.java, distro/run/qa/pom.xml, distro/run/qa/runtime/pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/3411
=> chore(run): add test coverage for cockpit plugins

engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/DefaultDmnEngineConfiguration.java, engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/evaluation/DecisionTableEvaluationHandler.java, engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/api/ReturnBlankTableOutputAsNullTest.java, engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/api/ReturnBlankTableOutputAsNull.dmn, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/dmn/configuration/DmnEngineConfigurationBuilder.java, engine/src/test/java/org/camunda/bpm/engine/test/history/dmn/HistoricDecisionInstanceReturnBlankTableOutputAsNullTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/history/ReturnBlankTableOutputAsNull.dmn
=> fix(engine-dmn): allow to return blank table output as null 

.ci/config/stage-types.yaml
Related to https://github.com/camunda/camunda-bpm-platform/issues/3411
=> fix(run): exclude Run QA module from JDK 11 stages

webapps/frontend/package-lock.json, webapps/frontend/package.json
related to camunda/camunda-bpm-platform#3556
=> chore(webapps): update fast-xml-parser

engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrencyTestHelper.java
related to https://github.com/camunda/camunda-bpm-platform/issues/2904
=> test(engine): log unexpected exception in concurrent tests

.ci/config/matrices.yaml, database/pom.xml, qa/performance-tests-engine/README.md, settings/maven/nexus-settings.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/3243
=> chore(oracle): remove support for Oracle 12

Jenkinsfile
related to https://github.com/camunda/camunda-bpm-platform/issues/3620
=> chore(ci): remove engine plugins stage

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ConfigurationLogger.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
related to https://github.com/camunda/camunda-bpm-platform/issues/3563
=> fix(engine): fail on db metadata initialization errors

parent/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/3225
=> chore(parent): bump to snakeyaml 2.1

pom.xml
related to https://github.com/camunda/camunda-bpm-platform/issues/3633
=> chore(pom): bump Spin to 1.21.0

distro/run/modules/swaggerui/ui/package-lock.json, engine-rest/docs/package-lock.json, engine-rest/docs/package.json, webapps/frontend/package-lock.json
related to camunda/camunda-bpm-platform#3528
=> chore(webapps): update semver

distro/sql-script/src/test/java/org/camunda/bpm/sql/test/SqlScriptTest.java
* Uses direct comparison via existing snapshots to avoid creating databases
from those snapshots again.
* Introduces a second `Liquibase#dropAll` invocation to ensure all data is
cleaned up. A single invocation can leave data in the tables if the cleanup
takes too long or is interrupted. The method seems to silently ignore such
issues and progress as if successful.
related to https://github.com/camunda/camunda-bpm-platform/issues/3613
=> test(sql-script): stabilize cleanup and comparison

bom/pom.xml, distro/wildfly/modules/pom.xml, distro/wildfly/modules/src/main/modules/org/camunda/template-engines/camunda-template-engines-freemarker/main/module.xml, distro/wildfly26/modules/pom.xml, distro/wildfly26/modules/src/main/modules/org/camunda/template-engines/camunda-template-engines-freemarker/main/module.xml, pom.xml
related to camunda/camunda-bpm-platform#3695, camunda/camunda-bpm-platform#3696
=> chore(prj): move template engines to community hub

bom/pom.xml, pom.xml
related to camunda/camunda-bpm-platform#3697
=> chore(bom): remove xslt template engine

engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/TimerDeclarationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TimerEntity.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
https://github.com/camunda/camunda-bpm-platform/issues/2570
=> chore(engine): cover re-evaluate start timer cycle with date

webapps/frontend/ui/admin/client/scripts/index.html, webapps/frontend/ui/cockpit/client/scripts/index.html, webapps/frontend/ui/tasklist/client/index.html, webapps/frontend/ui/welcome/client/scripts/index.html, webapps/frontend/webpack.common.js, webapps/frontend/webpack.dev.js, webapps/frontend/webpack.prod.js
related to camunda/camunda-bpm-platform#3753
=> fix(webapps): load `user-styles.css` last

webapps/frontend/ui/admin/client/scripts/camunda-admin-bootstrap.js, webapps/frontend/ui/cockpit/client/scripts/camunda-cockpit-bootstrap.js, webapps/frontend/ui/tasklist/client/scripts/camunda-tasklist-bootstrap.js, webapps/frontend/ui/welcome/client/scripts/camunda-welcome-bootstrap.js
related to camunda/camunda-bpm-platform#3750
=> fix(webapps): make jQuery `$` variable globally available again

qa/test-old-engine/config/org/camunda/bpm/engine/test/concurrency/historycleanup.camunda.cfg.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/2994
=> fix(engine): Fix old-engine Config

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/ExceptionHandlerHelper.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/ExceptionLogger.java, engine/pom.xml, engine/src/main/java/org/camunda/bpm/engine/ProcessEnginePersistenceException.java, engine/src/main/java/org/camunda/bpm/engine/impl/util/ExceptionUtil.java, engine/src/test/java/org/camunda/bpm/engine/test/persistence/ConnectionPersistenceExceptionTest.java, engine/src/test/resources/database.properties
=> In the REST API, log persistence connection exceptions on log level ERROR

Jenkinsfile, parent/pom.xml, quarkus-extension/engine/deployment/src/main/java/org/camunda/bpm/quarkus/engine/extension/deployment/impl/CamundaEngineProcessor.java, quarkus-extension/engine/deployment/src/main/resources/application.properties, quarkus-extension/engine/qa/pom.xml, quarkus-extension/pom.xml
related to camunda/camunda-bpm-platform#3419
=> chore(quarkus): bump to latest version

engine/src/main/java/org/camunda/bpm/engine/management/ProcessDefinitionStatisticsQuery.java, webapps/assembly/src/main/java/org/camunda/bpm/cockpit/impl/plugin/base/dto/ProcessDefinitionStatisticsDto.java, webapps/assembly/src/main/java/org/camunda/bpm/cockpit/impl/plugin/base/dto/query/ProcessDefinitionStatisticsQueryDto.java, webapps/assembly/src/main/java/org/camunda/bpm/cockpit/impl/plugin/resources/ProcessDefinitionRestService.java, webapps/assembly/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/processDefinition.xml, webapps/assembly/src/test/java/org/camunda/bpm/cockpit/plugin/base/ProcessDefinitionRestServiceTest.java, webapps/assembly/src/test/java/org/camunda/bpm/cockpit/plugin/base/authorization/ProcessDefinitionRestServiceAuthorizationTest.java, webapps/assembly/src/test/java/org/camunda/bpm/cockpit/plugin/base/tenantcheck/ProcessDefinitionRestServiceTenantCheckTest.java
related to camunda/camunda-bpm-platform#3611
=> feat(engine): extend process definition statistics api & query

engine/src/main/java/org/camunda/bpm/engine/management/ProcessDefinitionStatisticsQuery.java, webapps/assembly/src/main/java/org/camunda/bpm/cockpit/impl/plugin/base/dto/ProcessDefinitionStatisticsDto.java, webapps/assembly/src/main/java/org/camunda/bpm/cockpit/impl/plugin/base/dto/query/ProcessDefinitionStatisticsQueryDto.java, webapps/assembly/src/main/java/org/camunda/bpm/cockpit/impl/plugin/resources/ProcessDefinitionRestService.java, webapps/assembly/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/processDefinition.xml, webapps/assembly/src/test/java/org/camunda/bpm/cockpit/plugin/base/ProcessDefinitionRestServiceTest.java, webapps/assembly/src/test/java/org/camunda/bpm/cockpit/plugin/base/authorization/ProcessDefinitionRestServiceAuthorizationTest.java, webapps/assembly/src/test/java/org/camunda/bpm/cockpit/plugin/base/tenantcheck/ProcessDefinitionRestServiceTenantCheckTest.java, webapps/frontend/public/app/cockpit/locales/de.json, webapps/frontend/public/app/cockpit/locales/en.json, webapps/frontend/ui/cockpit/client/scripts/directives/stateCircle.js, webapps/frontend/ui/cockpit/plugins/base/app/data/dashboard/processDefinitionStatisticsData.js, webapps/frontend/ui/cockpit/plugins/base/app/resources/processDefinition.js, webapps/frontend/ui/cockpit/plugins/base/app/views/processesDashboard/process-definition-search-config.json, webapps/frontend/ui/cockpit/plugins/base/app/views/processesDashboard/process-definitions.html, webapps/frontend/ui/cockpit/plugins/base/app/views/processesDashboard/process-definitions.js, webapps/frontend/ui/common/scripts/module/controllers/cam-pagination-search-integration.js
related to camunda/camunda-bpm-platform#3612
=> feat(webapps): improve process definition page

pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/3690
=> chore(deps): update feel-scala to 1.16.2

webapps/frontend/ui/cockpit/plugins/base/app/views/processesDashboard/process-definitions.js
related to camunda/camunda-bpm-platform#3612
=> fix(webapps): use new local storage key

distro/wildfly/subsystem/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/3584
=> chore(wildfly): exclude org.jboss.openjdk-orb:openjdk-orb

distro/license-book/src/main/resources/license-book.txt
=> chore(distro): update license book to 7.20.0

Jenkinsfile, quarkus-extension/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/3776
=> chore(ci): introduce quarkus tests profile

qa/test-db-instance-migration/test-fixture-721/pom.xml, qa/test-db-rolling-update/create-old-engine/src/main/resources/camunda.auth.cfg.xml, qa/test-db-rolling-update/create-old-engine/src/main/resources/camunda.cfg.xml, qa/test-old-engine/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/3346
=> fix(qa): fix qa setups after 7.20 release

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupHelper.java
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/3805
=> fix(engine): Fix historyCleanupDefaultNumberOfRetries

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricIncidentQueryTest.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/3763
=> fix(engine): add missing property check for historic incident

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricExternalTaskLogQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/batch/cleanable-batch-report/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/incident/count/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/incident/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/count/get.ftl
Related to https://github.com/camunda/camunda-bpm-platform/issues/3715
=> chore(openapi): fix pagination properties in various endpoints

.ci/config/matrices.yaml
Related to https://github.com/camunda/camunda-bpm-platform/issues/3744
=> chore(ci): add support for postgres 16

engine-rest/docs/package.json
https://github.com/camunda/camunda-bpm-platform/issues/3883
=> chore(rest/docs): make the build OS independent

engine/src/test/resources/org/camunda/bpm/engine/test/api/authorization/resource.authorization.provider.camunda.cfg.xml, qa/test-db-rolling-update/create-new-engine/src/main/resources/camunda.cfg.xml, qa/test-db-rolling-update/create-old-engine/src/main/resources/camunda.auth.cfg.xml, qa/test-db-rolling-update/create-old-engine/src/main/resources/camunda.cfg.xml, qa/test-db-rolling-update/test-old-engine/src/main/resources/camunda.auth.cfg.xml, qa/test-db-rolling-update/test-old-engine/src/main/resources/camunda.cfg.xml, qa/test-old-engine/config/camunda.cfg.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/2595
=> chore(qa): disable telemetry by default for all test setups

webapps/frontend/public/app/cockpit/locales/de.json, webapps/frontend/public/app/cockpit/locales/en.json
related to camunda/camunda-bpm-platform#3868
=> feat(cockpit): add additional heatmap period options

engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/BoundaryTimerNonInterruptingEventTest.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/3941
=> chore(test): fix brittle test

engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Statistics.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ProcessDefinitionStatisticsQueryTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/repository/ProcessDefinitionQueryTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/repository/three_.bpmn20.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/3891
=> fix(engine): add missing property to process definition statistics query

distro/run/modules/swaggerui/ui/package-lock.json, distro/run/modules/swaggerui/ui/package.json, distro/run/modules/swaggerui/ui/tasks/license.js
related to camunda/camunda-bpm-platform#3954
=> chore(swaggerui): bump dependencies to latest version

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/batch/DeleteProcessInstancesDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/delete-historic-query-based/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/delete/post.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/batch/DeleteProcessInstancesDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ProcessInstanceRestServiceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java, engine/src/main/java/org/camunda/bpm/engine/RuntimeService.java, engine/src/main/java/org/camunda/bpm/engine/impl/RuntimeServiceImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/batch/deletion/DeleteProcessInstanceBatchConfiguration.java, engine/src/main/java/org/camunda/bpm/engine/impl/batch/deletion/DeleteProcessInstanceBatchConfigurationJsonConverter.java, engine/src/main/java/org/camunda/bpm/engine/impl/batch/deletion/DeleteProcessInstancesJobHandler.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractDeleteProcessInstanceCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteProcessInstanceCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteProcessInstancesCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/batch/DeleteProcessInstanceBatchCmd.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceAsyncOperationsTest.java, engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceTest.java
=> feat(engine, engine-rest-open-api): Add SkipIoMapping Support

webapps/frontend/public/app/cockpit/locales/de.json, webapps/frontend/public/app/cockpit/locales/en.json
related to camunda/camunda-bpm-platform#3938
=> feat(cockpit): add translations for skipIoMappings flag

distro/run/assembly/resources/run.bat
https://github.com/camunda/camunda-bpm-platform/issues/3907
=> chore(run): adjust java check to use assigned JAVA_HOME

clients/java/client/pom.xml, clients/java/client/src/main/java/org/camunda/bpm/client/ExternalTaskClientBuilder.java, clients/java/client/src/main/java/org/camunda/bpm/client/impl/ExternalTaskClientBuilderImpl.java, clients/java/client/src/main/java/org/camunda/bpm/client/impl/RequestExecutor.java, clients/java/client/src/test/java/org/camunda/bpm/client/impl/ExternalTaskClientBuilderImplTest.java
related to camunda/camunda-bpm-platform#3944
=> feat(client/java): expose Apache HttpClientBuilder

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExternalTaskQueryDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/FetchExternalTasksDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/fetchAndLock/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/post.ftl
=> chore(engine-rest-openapi): Add createTime to Open API

distro/wildfly/modules/src/main/modules/org/joda/time/2.1/module.xml, distro/wildfly26/modules/src/main/modules/org/joda/time/2.1/module.xml, pom.xml
related to camunda/camunda-bpm-platform#3965
=> chore(dependency): update joda time

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/mapper/MultipartFormData.java
=> fix(engine): REST API endpoint should use UTF-8 charset

pom.xml
related to camunda/camunda-bpm-platform#3964
=> chore(dependency): update mybatis

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/deployer/BpmnDeployer.java, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricJobLogTest.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/2380
=> fix(engine): use correct job definition for job log

engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java, engine/src/main/java/org/camunda/bpm/engine/impl/task/TaskDefinition.java, engine/src/main/java/org/camunda/bpm/engine/impl/util/CollectionUtil.java, engine/src/test/java/org/camunda/bpm/engine/test/cmmn/handler/HumanTaskPlanItemHandlerTest.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/4042
=> chore(engine): improve task listener order enforcement

engine/pom.xml, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupSchedulerCmd.java, engine/src/test/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupSchedulerCmdTest.java
=> fix(engine): fix NPE in cleanup when metricsEnabled is false

webapps/assembly/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/processDefinition.xml, webapps/frontend/ui/cockpit/plugins/base/app/views/processesDashboard/process-definition-search-config.json
related to camunda/camunda-bpm-platform#4036
=> feat(cockpit): ease search for process definitions

webapps/frontend/package-lock.json
related to camunda/camunda-bpm-platform#3906
=> chore(webapps): bump frontend dependencies

engine/src/main/java/org/camunda/bpm/engine/impl/context/Context.java, engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandContextInterceptor.java, engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandInvocationContext.java, engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ProcessDataContext.java, engine/src/test/java/org/camunda/bpm/engine/test/logging/ProcessDataLoggingContextTest.java, engine/src/test/java/org/camunda/bpm/engine/test/logging/TestMdcFacade.java
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/2379
=> feat(engine): Add Support for External MDC Logging Properties Preservation

distro/wildfly/modules/src/main/modules/com/fasterxml/uuid/java-uuid-generator/main/module.xml, distro/wildfly26/modules/src/main/modules/com/fasterxml/uuid/java-uuid-generator/main/module.xml, pom.xml
related to camunda/camunda-bpm-platform#3913
=> chore(project): bump uuid generator version to 4.3.0

Jenkinsfile, engine-rest/engine-rest/pom.xml, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4077
=> fix(engine-rest): Adjust Mockito ArgumentMatchers

distro/wildfly/assembly/src/wildfly/standalone-full.xml, distro/wildfly/assembly/src/wildfly/standalone.conf, distro/wildfly/assembly/src/wildfly/standalone.conf.bat, distro/wildfly/assembly/src/wildfly/standalone.xml, parent/pom.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml, qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
https://github.com/camunda/camunda-bpm-platform/issues/4102
=> feat(distro): add WildFly 31 support

engine-rest/engine-rest-jakarta/pom.xml, parent/pom.xml, webapps/assembly-jakarta/pom.xml
related to https://github.com/camunda/camunda-bpm-platform/issues/3987
=> chore(spring): update spring framework

parent/pom.xml
related to https://github.com/camunda/camunda-bpm-platform/issues/3988
=> chore(spring-boot): update spring-boot

distro/run/pom.xml, parent/pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4066
=> chore(run): remove snakeyaml version override

parent/pom.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/3785
=> chore(parent): Upgrade Quarkus to 3.8.0

webapps/frontend/ui/cockpit/client/scripts/directives/time-to-live/time-to-live-dialog.js
related to: camunda/camunda-bpm-platform/issues/4097
=> feat(frontend): HTTL updated info message in CE edition

webapps/assembly/src/main/runtime/develop/resources/META-INF/processes.xml, webapps/assembly/src/main/runtime/develop/resources/pa3/complex-process.bpmn
related to: camunda/camunda-bpm-platform/issues/4120
=> fix(assembly): remove duplicate xmls element

webapps/frontend/package-lock.json, webapps/frontend/package.json, webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.html, webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.js, webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.less
related to camunda/camunda-bpm-platform#3980
=> feat(webapp): add metrics monthly chart

distro/wildfly/modules/pom.xml, distro/wildfly26/modules/pom.xml, pom.xml
=> chore(deps): Bump json-path to a version 2.9.0

webapps/frontend/ui/cockpit/client/scripts/directives/time-to-live/time-to-live-dialog.js
related to: camunda/camunda-bpm-platform/issues/4096
=> feat(frontend): Link to SET_REMOVAL_TIME batch should pre-set values

clients/java/client/pom.xml, clients/java/client/src/it/java/org/camunda/bpm/client/variable/XmlSerializable.java, clients/java/client/src/it/java/org/camunda/bpm/client/variable/XmlSerializables.java, clients/java/client/src/main/java/org/camunda/bpm/client/variable/impl/format/xml/DomXmlDataFormat.java, parent/pom.xml, spring-boot-starter/starter/pom.xml, webapps/assembly-jakarta/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/3829
=> use jakarta xml bind instead of javax for external task client

webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.html, webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.less
related to https://github.com/camunda/camunda-bpm-platform/issues/4162
=> fix(webapp): fix execution metrics less styles

distro/camunda-welcome/assets/css/welcome.css, distro/camunda-welcome/index.html, webapps/frontend/camunda-commons-ui/lib/widgets/header/cam-widget-header.html, webapps/frontend/camunda-commons-ui/lib/widgets/header/cam-widget-header.js, webapps/frontend/camunda-commons-ui/lib/widgets/header/cam-widget-header.less, webapps/frontend/public/app/admin/locales/en.json, webapps/frontend/public/app/cockpit/locales/en.json, webapps/frontend/public/app/tasklist/locales/en.json, webapps/frontend/public/app/welcome/locales/en.json, webapps/frontend/ui/admin/client/styles/styles.less, webapps/frontend/ui/cockpit/client/styles/ctn.less, webapps/frontend/ui/common/styles/_three-cols-layout.less, webapps/frontend/ui/welcome/client/styles/styles.less, webapps/frontend/webpack.common.js, webapps/frontend/webpack.dev.js, webapps/frontend/webpack.prod.js
related to https://github.com/camunda/camunda-bpm-platform/issues/4171
=> feat(webapp): add community edition end of life banner

.ci/config/matrices.yaml, .ci/config/stage-types.yaml, .ci/daily/Jenkinsfile, Jenkinsfile
=> chore(ci): Remove CockroachDB References

engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentTelemetryConfigurationTest.java
https://github.com/camunda/team-automation-platform/issues/126
=> fix(engine/tests): fix concurrent telemetry test with default value

distro/run/assembly/resources/run.bat
=> fix(distro/run): fix Camunda Run not launching using JDK with spaces in installation path

database/pom.xml, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.cockroachdb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/camunda-changelog.xml, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/cockroachdb_engine_7.21_to_7.22.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.21_to_7.22.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.21_to_7.22.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.21_to_7.22.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.21_to_7.22.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.21_to_7.22.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.21_to_7.22.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.21_to_7.22.sql, qa/test-db-instance-migration/pom.xml, qa/test-db-instance-migration/test-fixture-722/pom.xml, qa/test-db-instance-migration/test-fixture-722/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java, qa/test-db-instance-migration/test-fixture-722/src/main/resources/camunda.cfg.xml, qa/test-db-rolling-update/create-new-engine/pom.xml, qa/test-db-rolling-update/create-old-engine/pom.xml, qa/test-db-rolling-update/rolling-update-util/pom.xml, qa/test-db-rolling-update/test-old-engine/pom.xml, qa/test-old-engine/pom.xml
=> chore(project): Prepare Codebase for 7.22.0 Release

distro/wildfly/modules/src/main/modules/org/camunda/bpm/camunda-engine/main/module.xml, distro/wildfly/modules/src/main/modules/org/graalvm/js/js/main/module.xml, distro/wildfly/modules/src/main/modules/org/graalvm/regex/regex/main/module.xml, distro/wildfly/modules/src/main/modules/org/graalvm/truffle/truffle-api/main/module.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4188
=> fix(wildfly): updated graalVM modules

clients/java/client/src/it/java/org/camunda/bpm/client/task/ExternalTaskHandlerIT.java, clients/java/client/src/main/java/org/camunda/bpm/client/task/impl/dto/SetVariablesRequestDto.java
related to https://github.com/camunda/camunda-bpm-platform/issues/4243
=> fix(client): fix setVariables property

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/FetchExternalTasksDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskRestServiceInteractionTest.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/4051
=> fix(engine-rest): return bad request for invalid sorting option for fetch and lock

database/pom.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4172
=> chore(database): Update MySQL Connector to v8.3.0

webapps/frontend/package-lock.json, webapps/frontend/public/app/admin/locales/de.json, webapps/frontend/public/app/admin/locales/en.json, webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.html
related to https://github.com/camunda/camunda-bpm-platform/issues/4311
=> fix(webapp): add missing metrics translations

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-task-instance-query-params.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricTaskInstanceRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/history/HistoricTaskInstanceQuery.java, engine/src/main/java/org/camunda/bpm/engine/impl/HistoricTaskInstanceQueryImpl.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricTaskInstanceTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/history/multiprocess/rootProcess.bpmn, engine/src/test/resources/org/camunda/bpm/engine/test/api/history/multiprocess/secondLevelProcess.bpmn, engine/src/test/resources/org/camunda/bpm/engine/test/api/history/multiprocess/thirdLevelProcess.bpmn
Related to https://github.com/camunda/camunda-bpm-platform/issues/4314
=> feat(api): add filter on rootProcessInstanceId for historic task instances query

commons/typed-values/pom.xml
=> bugfix(commons): fix typed-values parent path

distro/run/modules/swaggerui/ui/package-lock.json, distro/run/modules/swaggerui/ui/package.json
related to https://github.com/camunda/camunda-bpm-platform/issues/4143
=> chore(swaggerui): bump dependencies

.ci/daily/Jenkinsfile
to be part of the stage and overall build result
https://github.com/camunda/team-automation-platform/issues/138
=> fix(ci): move publishDocs to runSteps

Jenkinsfile
https://github.com/camunda/team-automation-platform/issues/132
=> chore(ci): skipTests label

webapps/frontend/package-lock.json, webapps/frontend/package.json
related to https://github.com/camunda/camunda-bpm-platform/issues/4233
=> chore(webapp): bump form-js

parent/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/4145
=> deps(project): update to Spring 6.1.7 and 5.3.35

parent/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/4144
=> chore(deps): update to SB 3.2.6, SF 6.3.36, 6.1.8

freemarker-template-engine/pom.xml
=> fix(freemarker-template-engine): fix parent path in POM.xml

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/deployer/BpmnDeployer.java, engine/src/test/java/org/camunda/bpm/engine/test/concurrency/DeleteProcessDefinitionTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/repository/processWithStartSignalEvent.bpmn20.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/2460
=> fix(engine): remove orphan event subscriptions on process definition redeployment

.ci/config/matrices.yaml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4166
=> feat(ci): add support for sql server 2022

bom/camunda-only-bom/pom.xml, clients/java/client/pom.xml, commons/README.md, commons/bom/pom.xml, commons/pom.xml, engine-dmn/engine/pom.xml, engine-dmn/feel-api/pom.xml, engine-dmn/feel-juel/pom.xml, engine/pom.xml, spin/bom/pom.xml, spin/pom.xml
Related to: #4325
This PR has a few small changes: 
Commons - update scm tag
Commons - Update required Java version
Commons - Package typed-values with commons-bom
Commons - Use the platform defined version variable for Logback
Spin - update scm tag
=> chore(project): consolidate libs follow ups

freemarker-template-engine/pom.xml
=> chore(freemarker-template-engine): downgrade assertj-core

webapps/frontend/camunda-bpm-sdk-js/NOTICE, webapps/frontend/camunda-commons-ui/NOTICE
Related to https://github.com/camunda/camunda-bpm-platform/issues/4374
=> chore(webapps): remove not needed NOTICE files

engine/pom.xml
=> fix(engine): don't shade httpcomponents and commons-codec

.github/workflows/close-stale-issues.yml
https://github.com/camunda/team-automation-platform/issues/147
=> feat(workflow): add stale workflow

engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/deployer/BpmnDeployer.java, engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/EventSubscriptionManager.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/EventSubscription.xml, engine/src/test/java/org/camunda/bpm/engine/test/concurrency/DeleteProcessDefinitionTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/repository/processWithConditionalStartEvent.bpmn20.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4396
=> fix(engine): remove orphan subscription for conditional events on redeployment

engine/pom.xml
=> chore(engine): excluded shaded transitive dependencies

distro/tomcat/assembly/pom.xml
=> fix(distro): tomcat exclude connect-http-* libs

bom/camunda-only-bom/pom.xml, clients/java/client/pom.xml
=> chore(spin): exclude dataformat all shaded dependencies

.github/workflows/close-stale-issues.yml
fixing the correct yml file and tagging the main branch.
https://github.com/camunda/team-automation-platform/issues/147
=> fix(workflows): fix yml reference

qa/wildfly-runtime/src/main/common/modules/org/camunda/bpm/camunda-engine/main/module.xml, qa/wildfly-runtime/src/main/common/modules/org/camunda/bpm/qa/camunda-qa-ensure-clean-db/main/module.xml, qa/wildfly-runtime/src/main/common/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml, qa/wildfly-runtime/src/main/common/modules/org/jruby/jruby-complete/main/module.xml, qa/wildfly-runtime/src/main/common/modules/org/postgresql/postgresql/main/module.xml, qa/wildfly-runtime/src/main/common/modules/org/python/jython/main/module.xml
https://github.com/camunda/camunda-bpm-platform/issues/4424
=> chore(qa):  update deprecated javax module descriptor usages

parent/pom.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4331
=> chore(parent): Bump Tomcat to 9.0.89

internal-dependencies/pom.xml
related to https://github.com/camunda/camunda-bpm-platform/issues/4413
=> ISSUE-4413: Remove opensaml from internal-dependencies/pom.xml

engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/components/ProcessStartingBeanPostProcessorTest.java
Hi,
We found a typo in the logging messages.
It's an incremental commit but it can improve the quality of logging messages.
=> Fix typos in logging messages

qa/pom.xml
related to camunda/camunda-bpm-platform#2471
=> chore(qa): add `tomcat9-runtime` to distro profile

qa/tomcat-runtime/pom.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4434
=> chore(tomcat-runtime): Fix webapp-IT-tomcat-10-h2 failing tests

connect/http-client/src/main/java/org/camunda/connect/httpclient/impl/AbstractHttpConnector.java, connect/http-client/src/main/java/org/camunda/connect/httpclient/impl/HttpConnectorLogger.java, connect/http-client/src/test/java/org/camunda/connect/httpclient/HttpRequestTest.java, connect/http-client/src/test/java/org/camunda/connect/httpclient/HttpResponseTest.java
related to https://github.com/camunda/camunda-bpm-platform/issues/4241
=> feat(connect): add http connector response error handling

parent/pom.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4346
=> chore(parent): Bump Quarkus to Version 3.85

webapps/frontend/webpack.common.js
related to https://github.com/camunda/camunda-bpm-platform/issues/4404
=> fix(webapp): fix formjs date picker error

engine/pom.xml
Related-to: https://github.com/camunda/team-automation-platform/issues/163
=> chore(engine): Remove Unnecessary JBoss Artifacts

.ci/config/stage-types.yaml, CONTRIBUTING.md
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4467
=> chore(project): Remove Swagger References

webapps/frontend/package-lock.json, webapps/frontend/package.json
=> chore(webapps): bump requirejs to latest - 2.3.7

parent/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/4533
=> chore(deps): bump tomcat to versions 9.0.90 and 10.1.25

engine/src/main/java/org/camunda/bpm/engine/impl/scripting/engine/DefaultScriptEngineResolver.java, parent/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/4553
=> chore(deps): revert to graalvm 21.1.0

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-detail-query-params.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricDetailQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricDetailRestServiceQueryTest.java, engine/src/main/java/org/camunda/bpm/engine/history/HistoricDetailQuery.java, engine/src/main/java/org/camunda/bpm/engine/impl/HistoricDetailQueryImpl.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDetail.xml, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricDetailQueryTest.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/4504
=> feat(engine): Add variableNameLike filter to historic detail REST API

bom/camunda-only-bom/pom.xml, clients/java/client/pom.xml, distro/run/assembly/assembly.xml, distro/run/assembly/pom.xml, distro/run/assembly/resources/run.bat, distro/run/assembly/resources/run.sh, distro/run/modules/oauth2/pom.xml, distro/run/modules/oauth2/src/main/java/org/camunda/bpm/spring/boot/starter/security/CamundaBpmSpringSecurityDisableAutoConfiguration.java, distro/run/modules/oauth2/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, distro/run/pom.xml, distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/ComponentAvailabilityIT.java, parent/pom.xml, spring-boot-starter/pom.xml, spring-boot-starter/starter-security/pom.xml, spring-boot-starter/starter-security/src/test/java/my/own/custom/spring/boot/project/SampleApplication.java, spring-boot-starter/starter-security/src/test/java/my/own/custom/spring/boot/project/SamplePermitAllApplication.java, spring-boot-starter/starter-security/src/test/java/org/camunda/bpm/spring/boot/starter/security/CamundaBpmSampleApplicationTest.java, spring-boot-starter/starter-security/src/test/java/org/camunda/bpm/spring/boot/starter/security/CamundaBpmSamplePermitAllApplicationTest.java, spring-boot-starter/starter-security/src/test/resources/logback-test.xml
related to https://github.com/camunda/camunda-bpm-platform/issues/4451
=> feat(run): add spring security module

distro/tomcat/assembly/assembly.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4573
=> chore(distro/tomcat/assembly): Add Juel to distro/lib Folder

engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ConfigurationLogger.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/test/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationTest.java, engine/src/test/resources/camunda.cfg.skipIsolationLevelCheckEnabled.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4516
=> feat(engine): check transaction isolation level on init

webapps/frontend/public/app/cockpit/locales/de.json, webapps/frontend/public/app/cockpit/locales/en.json
=> feat(cockpit): add rootInstanceId filter to humanTask search

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/MultiFormDeploymentDto.ftl
Related to https://github.com/camunda/camunda-bpm-platform/issues/4312
=> fix(openapi): make description for POST /deployment/create more clear

parent/pom.xml
related to camunda/camunda-bpm-platform#4581
=> chore(deps): bump spring boot to 3.3.3

parent/pom.xml, quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineConfigFileTest.java, quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineConfigurationConfigTest.java, quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineJobExecutorConfigTest.java, quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineProgrammaticAndConfigFileTest.java, quarkus-extension/engine/deployment/src/test/resources/application.properties, quarkus-extension/engine/deployment/src/test/resources/org/camunda/bpm/quarkus/engine/test/config/job-executor-application.properties, quarkus-extension/engine/deployment/src/test/resources/org/camunda/bpm/quarkus/engine/test/config/mixed-application.properties, quarkus-extension/engine/deployment/src/test/resources/org/camunda/bpm/quarkus/engine/test/config/process-engine-config-application.properties, quarkus-extension/engine/qa/src/test/resources/application.properties, quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/CamundaEngineConfig.java, quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/CamundaJobExecutorConfig.java, quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/CamundaEngineRecorder.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/4163
=> chore(quarkus): Bump quarkus version to 3.14

database/pom.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4347
=> chore(database): Bump H2 to 2.2.222

engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/fetchAndLock/post.ftl
Related to https://github.com/camunda/camunda-bpm-platform/issues/4608
=> chore(docs): Fix sortOrder case in fetch and lock rest api example

webapps/frontend/package-lock.json, webapps/frontend/package.json
related to camunda/camunda-bpm-platform#4613
=> chore(webapps): bump webpack to the latest version 

parent/pom.xml
related to camunda/camunda-bpm-platform#4622
=> chore(deps): bump Tomcat to 10.1.29

.ci/config/stage-types.yaml
related to camunda/team-automation-platform#191
=> chore(ci): fix merge conflicts

.ci/daily/Jenkinsfile
related to camunda/team-automation-platform#52
=> chore(ci/daily): fix `stage-restapi-docs` by adding ssh

spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/OAuth2Properties.java, spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/AuthorizeTokenFilter.java, spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/SsoLogoutSuccessHandler.java
https://github.com/camunda/camunda-bpm-platform/issues/4455
=> feat(oauth2): improve logging with token name

spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/CamundaSpringSecurityOAuth2AutoConfiguration.java, spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/OAuth2Properties.java
https://github.com/camunda/camunda-bpm-platform/issues/4583
=> feat(oauth2): enable identity provider by default

engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/job-log/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/job-log/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/job-log/{id}/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/get.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/JobDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockJobBuilder.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceInteractionTest.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/4206
=> chore(rest): expose batch id for job and historic job log to REST API

engine/src/test/java/org/camunda/bpm/engine/test/history/JobEntityAndJobLogBatchIdTest.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/4206
=> fix(engine): Add missing HistoryLevel annotation to test

parent/pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4580
=> chore(quarkus): Bump quarkus version to 3.15

distro/license-book/src/main/resources/license-book.txt
related to camunda/camunda-bpm-platform#4249
=> chore(license-book): update license book for 7.22.0

webapps/frontend/public/app/admin/locales/de.json, webapps/frontend/public/app/cockpit/locales/de.json, webapps/frontend/public/app/tasklist/locales/de.json, webapps/frontend/public/app/welcome/locales/de.json
Related to https://github.com/camunda/camunda-bpm-platform/issues/4266
=> chore(release): update German translation

.ci/config/matrices.yaml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4130
=> chore(ci): remove postgresql_132 CI

engine-rest/docs/build.js
related to: camunda/team-automation-platform/issues/160
=> chore(rest-docs): include google tag manager

parent/pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4551
=> chore(engine): Bump Spring Framework

.github/workflows/codeql.yml
Related to https://github.com/camunda/team-automation-platform/issues/206
> [!warning] 
> Hints for review: This is for testing only. Not the final version of this file.
=> chore(workflows): enable github advanced security

webapps/frontend/public/app/cockpit/locales/de.json
Related to https://github.com/camunda/camunda-bpm-platform/issues/4682
=> fix(de.json): Add a missing space

engine-rest/engine-rest-openapi/src/main/templates/paths/metrics/get.ftl
https://github.com/camunda/camunda-bpm-platform/issues/4554
=> fix(openapi): fix incorrect schema for metrics param

internal-dependencies/pom.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4720
=> Bump to commons-io:2.17.0

webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.js
related to camunda/camunda-bpm-platform#4743
=> fix(admin): fix display of usage metrics > 12 months

.ci/config/stage-types.yaml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4165
=> chore(config): Add Podspec Execution to instance-migration

parent/pom.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4751
=> chore(parent): Bump Spring Libraries

parent/pom.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4751
=> chore(parent): Set Spring Version to 6.1.15

engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/components/jobexecutor/SpringJobExecutor.java, engine/src/main/java/org/camunda/bpm/container/impl/jmx/services/JmxManagedThreadPool.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobExecutor.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobExecutorLogger.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/RuntimeContainerJobExecutor.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/SequentialJobAcquisitionRunnable.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ThreadPoolJobExecutor.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/DelayDelegate.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobAcquisitionLoggingTest.java, engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutionLoggingTest.java, engine/src/test/resources/org/camunda/bpm/engine/test/jobexecutor/SimpleAsyncDelayProcess.bpmn20.xml
https://github.com/camunda/camunda-bpm-platform/issues/2666
=> Fidelity contributions 2666 job acquisition execution logging improvement

clients/java/client/pom.xml, clients/java/client/src/it/resources/integration-rules.properties
Related to https://github.com/camunda/team-automation-platform/issues/87
=> fix(flaky): change tomcat port for XTaC IT

engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/comment/get.ftl
related to https://github.com/camunda/camunda-bpm-platform/issues/2551
Fixes 
here: https://stage.docs.camunda.org/rest/camunda-bpm-platform/7.23-SNAPSHOT/#tag/Process-Instance-comment
=> chore(openapi): fix process instance comment tag

distro/run/core/src/test/java/org/camunda/bpm/run/test/config/https/HttpsConfigurationEnabledTest.java, distro/run/core/src/test/resources/application-test-https-enabled.yml, parent/pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4657
=> chore(pom): add support for Spring Boot 3.4.0

.github/workflows/set-version-labels.yml
related to: camunda/team-automation-platform/issues/189
=> feat(.github/workflows): add action for set version labels

README.md
Related to https://github.com/camunda/team-automation-platform/issues/228
=> chore(readme): Add information about EOL in contribution section

.github/workflows/set-version-labels.yml
Related-to: https://github.com/camunda/team-automation-platform/issues/189
=> chore(.github/workflows): Exclude Not Planned

webapps/assembly/src/main/java/org/camunda/bpm/webapp/impl/db/QuerySessionFactory.java, webapps/assembly/src/test/java/org/camunda/bpm/webapp/impl/db/QuerySessionFactoryTest.java, webapps/assembly/src/test/resources/camunda-skip-check.cfg.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4867
=> fix(webapps): add skipIsolationLevelCheck to configuration on webapp init

engine-rest/docs/package-lock.json, webapps/frontend/package-lock.json
Related to: camunda/camunda-bpm-platform/issues/4721
=> chore(webapps, engine-rest/docs): bump dompurify

pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/4902
=> chore(deps): bump to feel-scala 1.19.1

parent/pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4942
=> chore(distro): bump tomcat version to 10.1.36 and 9.0.100

engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java, engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
related to: /camunda/camunda-bpm-platform/issues/4896
=> fix(engine-rest): fix parsing processInstanceIdNotIn

webapps/frontend/public/app/cockpit/locales/de.json, webapps/frontend/public/app/cockpit/locales/en.json
related to: /camunda/camunda-bpm-platform/issues/4906
=> feat(webapps): localisation for instances with jobs retrying

webapps/frontend/public/app/cockpit/scripts/config.js, webapps/frontend/ui/cockpit/client/scripts/repository/deployments/plugins/actions/delete/modals/cam-cockpit-delete-deployment-modal-ctrl.js, webapps/frontend/ui/common/scripts/services/cam-configuration.js
Related to https://github.com/camunda/camunda-bpm-platform/issues/2479
=> feat(cockpit): Make default value for cascade flag configurable

webapps/frontend/camunda-commons-ui/lib/widgets/inline-field/dialog/controller.js
related to: camunda/camunda-bpm-platform/issues/4955
=> feat(webapps): auto format expanded edit field

qa/pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4869
=> chore(qa): Fix test release job

webapps/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/4287
=> chore(deps): update jetty to 9.4.57.v20241219

.ci/config/stage-types.yaml, .ci/sidetrack/Jenkinsfile, Jenkinsfile
fixes hanging stage due to wrong JDK.
https://github.com/camunda/camunda-bpm-platform/issues/4869
=> chore(ci): fix wildfly 26 stage to use JDK 11

spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappAutoConfiguration.java, spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/FaviconResourceResolver.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappAutoConfigurationIntegrationTest.java, spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/FaviconResourceResolverTest.java
related to: camunda/camunda-bpm-platform/issues/4930
=> fix(spring-boot-webapp): resolve favicon path

parent/pom.xml
related to #4901
License check [here](https://docs.google.com/spreadsheets/d/1jj4HpqB4fiB-2j22uUL5fxVaLXluBbJHp4x-a1_lzV0/edit?usp=sharing)
No manual regressin tests done as discussed on slack
=> chore(deps): bump spring 6 to newest patch

distro/camunda-welcome/index.html, webapps/frontend/public/app/admin/locales/de.json, webapps/frontend/public/app/admin/locales/en.json, webapps/frontend/public/app/cockpit/locales/de.json, webapps/frontend/public/app/cockpit/locales/en.json, webapps/frontend/public/app/tasklist/locales/de.json, webapps/frontend/public/app/tasklist/locales/en.json, webapps/frontend/public/app/welcome/locales/de.json, webapps/frontend/public/app/welcome/locales/en.json
related to camunda/camunda-bpm-platform#5029
=> chore(locales): change wording of the EOL banner

parent/pom.xml
related to https://github.com/camunda/camunda-bpm-platform/issues/4901
License check [here](https://docs.google.com/spreadsheets/d/1fO84_akGUpiIfz25xx_w2w_RlOpXarUtP1SWHUQ9aEs/edit?gid=0#gid=0)
No manual regression tests for this one
=> deps(springBoot): bump spring boot to 3.4.4

webapps/frontend/public/app/admin/locales/de.json, webapps/frontend/public/app/admin/locales/en.json, webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.html, webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.js
related to camunda/camunda-bpm-platform/issues/4415
=> task(webapp): execution metrics page, adjust month column

.snyk
Related to https://github.com/camunda/team-automation-platform/issues/318
=> chore(snyk): Add .snyk file

distro/license-book/src/main/resources/license-book.txt
related to camunda/camunda-bpm-platform#4684
=> chore(license-book): update license book for 7.23.0

distro/license-book/src/main/resources/license-book.txt
related to camunda/camunda-bpm-platform#4684
=> chore(license-book): update HeroDevs.com license

connect/pom.xml, database/pom.xml, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql, engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/camunda-changelog.xml, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.23_to_7.24.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.23_to_7.24.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.23_to_7.24.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.23_to_7.24.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.23_to_7.24.sql, engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.23_to_7.24.sql, qa/test-db-instance-migration/pom.xml, qa/test-db-instance-migration/test-fixture-723/pom.xml, qa/test-db-instance-migration/test-fixture-724/pom.xml, qa/test-db-instance-migration/test-fixture-724/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java, qa/test-db-instance-migration/test-fixture-724/src/main/resources/camunda.cfg.xml, qa/test-db-rolling-update/create-new-engine/pom.xml, qa/test-db-rolling-update/create-old-engine/pom.xml, qa/test-db-rolling-update/rolling-update-util/pom.xml, qa/test-db-rolling-update/test-old-engine/pom.xml, qa/test-old-engine/pom.xml, spin/pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4713
=> chore(release): prepare codebase for 7.24 development

.github/workflows/extract-issue-links.yml
related to: camunda/camunda-bpm-platform/issues/5070
=> chore(gha): remove devex from Notifications

pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/5072
=> fix(parent): Bump feel-scala version to 1.19.3

parent/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/5127
=> chore(deps): update to httpclient5 5.4.3 and SB 3.4.5

engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/{id}/delete.ftl
https://github.com/camunda/camunda-bpm-platform/issues/5116
=> chore(rest): fix deleteProcessDefinition description

engine/src/main/java/org/camunda/bpm/engine/ProcessEngineConfiguration.java, engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DefaultJobRetryCmd.java, engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobDeclaration.java, engine/src/test/java/org/camunda/bpm/engine/impl/jobexecutor/setInitialRetries/JobDeclarationRetriesTest.java, engine/src/test/java/org/camunda/bpm/engine/impl/jobexecutor/setInitialRetries/LegacyJobDeclarationRetriesTest.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/async/FoxJobRetryCmdTest.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/async/JobRetryCmdWithDefaultPropertyTest.java, engine/src/test/java/org/camunda/bpm/engine/test/bpmn/parse/RetryIntervalsConfigurationTest.java, engine/src/test/java/org/camunda/bpm/engine/test/history/useroperationlog/UserOperationLogQueryTest.java, engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/CustomHistoryLevelUserOperationLogTest.java
related to: https://github.com/camunda/camunda-bpm-platform/issues/2300
=> fix(engine): fix initial retry counter

parent/pom.xml
related to camunda/camunda-bpm-platform#5044
=> feat(spring-boot): add support for 3.5.0

.ci/config/stage-types.yaml, .ci/daily/Jenkinsfile, Jenkinsfile
Related to https://github.com/camunda/team-automation-platform/issues/338
=> chore(ci): add ci:all label

webapps/frontend/package-lock.json
related to camunda/camunda-bpm-platform#5121
=> chore(frontend): update all third-party libs

.github/renovate.json
related to camunda/camunda-bpm-platform#5214
=> chore(renovate): disable vulnerability alerts

parent/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/5216
=> chore(deps): update to latest tomcat

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/job-definition-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/commons/job-query-params.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/JobQueryDto.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java, engine/src/main/java/org/camunda/bpm/engine/impl/JobQueryImpl.java, engine/src/main/java/org/camunda/bpm/engine/runtime/JobQuery.java, engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml, engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/JobQueryTest.java, webapps/frontend/camunda-bpm-sdk-js/lib/api-client/resources/job.js
Related to: camunda/camunda-bpm-platform/issues/4470
=> feat(engine, engine-rest-core) Add a query criteria to retrieve all executing jobs

Jenkinsfile, webapps/assembly/src/main/runtime/develop/resources/META-INF/processes.xml, webapps/assembly/src/main/runtime/test/resources/META-INF/processes.xml, webapps/assembly/src/test/resources/camunda-test-engine.cfg.xml, webapps/assembly/src/test/resources/camunda.cfg.prefix.xml
related to https://github.com/camunda/camunda-bpm-platform/issues/4438
=> revert(webapps): unintended changes 

engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/CacheAwareHistoryEventProducer.java, engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoryEventDataTest.java, engine/src/test/java/org/camunda/bpm/engine/test/history/HistoryEventVerifier.java, engine/src/test/java/org/camunda/bpm/engine/test/history/TestEventHandler.java, engine/src/test/resources/org/camunda/bpm/engine/test/api/threeTasksProcess.bpmn20.xml
This merge request aims to enrich the information conveyed through events by adding process definition data such as version, name, and other relevant fields.
https://github.com/camunda/camunda-bpm-platform/issues/5291
=> feat(engine): adds process definition data to events

.github/renovate.json
=> chore(renovate): whitelist `commons-lang3` for automatic updates

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/task-query-params.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskWithAttachmentAndCommentDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskWithVariablesDto.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/post.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/get.ftl, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/TaskRestService.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskWithAttachmentAndCommentDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskWithVariablesDto.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/TaskRestServiceImpl.java, engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/impl/TaskResourceImpl.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
https://github.com/camunda/camunda-bpm-platform/issues/4487
=> Run CI for  fetch task variables

parent/pom.xml
related to: camunda/camunda-bpm-platform/issues/5297
=> chore(deps) bump spring & tomcat

distro/wildfly/assembly/src/wildfly/standalone-full.xml, distro/wildfly/assembly/src/wildfly/standalone.xml, distro/wildfly/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/deployment/processor/ModuleDependencyProcessor.java, distro/wildfly/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/extension/handler/EnhancedQueueExecutorService.java, distro/wildfly/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/extension/handler/JobExecutorAdd.java, distro/wildfly/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/service/MscExecutorService.java, distro/wildfly/subsystem/src/test/java/org/camunda/bpm/container/impl/jboss/test/JBossSubsystemXMLTest.java, parent/pom.xml, qa/integration-tests-webapps/pom.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml, qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
related to camunda/camunda-bpm-platform#5045
=> chore(distro): add support for WildFly 37

distro/camunda-welcome/index.html, webapps/frontend/public/app/admin/locales/de.json, webapps/frontend/public/app/admin/locales/en.json, webapps/frontend/public/app/cockpit/locales/de.json, webapps/frontend/public/app/cockpit/locales/en.json, webapps/frontend/public/app/tasklist/locales/de.json, webapps/frontend/public/app/tasklist/locales/en.json, webapps/frontend/public/app/welcome/locales/de.json, webapps/frontend/public/app/welcome/locales/en.json
related to camunda/camunda-bpm-platform#5356
=> chore(webapps): add tracking info to eol links

engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/5358
=> fix(db2): update to modern pagination for DB2

engine-rest/engine-rest-openapi/src/main/templates/paths/authorization/create/post.ftl
=> fix(openApi): add missing quotation marks

.github/ISSUE_TEMPLATE/bug_report.md
Added a section for workarounds in the bug report template.
=> chore(github): add workarounds section to bug report template

parent/pom.xml
related to camunda/camunda-bpm-platform#5043
=> chore(quarkus): support 3.27.0 LTS

distro/license-book/src/main/resources/license-book.txt
related to camunda/camunda-bpm-platform#5075
=> chore(license-book): update license book for 7.24.0
